export const policies = [
  {
    policyId: "P001",
    policyName: "Data Protection Policy",
    department: "IT",
    lastReviewedDate: "2024-12-15",
    nextReviewDate: "2025-12-15",
    owner: "Alice Mwangi",
    complianceTasksCompleted: 8,
    totalTasks: 10,
    status: "On Track",
    category: "Data Protection"
  },
  {
    policyId: "P002",
    policyName: "Employee Code of Conduct",
    department: "HR",
    lastReviewedDate: "2023-11-01",
    nextReviewDate: "2024-11-01",
    owner: "John Okello",
    complianceTasksCompleted: 5,
    totalTasks: 8,
    status: "At Risk",
    category: "HR"
  },
  {
    policyId: "P003",
    policyName: "Financial Reporting Policy",
    department: "Finance",
    lastReviewedDate: "2025-01-10",
    nextReviewDate: "2026-01-10",
    owner: "Grace Namaganda",
    complianceTasksCompleted: 12,
    totalTasks: 12,
    status: "On Track",
    category: "Financial"
  },
  {
    policyId: "P004",
    policyName: "IT Security Policy",
    department: "IT",
    lastReviewedDate: "2024-08-20",
    nextReviewDate: "2025-08-20",
    owner: "Mary Achieng",
    complianceTasksCompleted: 6,
    totalTasks: 10,
    status: "At Risk",
    category: "IT Security"
  },
  {
    policyId: "P005",
    policyName: "Workplace Safety Policy",
    department: "Operations",
    lastReviewedDate: "2025-02-15",
    nextReviewDate: "2026-02-15",
    owner: "Paul Nsubuga",
    complianceTasksCompleted: 4,
    totalTasks: 5,
    status: "On Track",
    category: "Safety"
  },
  {
    policyId: "P006",
    policyName: "Anti-Bribery Policy",
    department: "Legal",
    lastReviewedDate: "2024-10-01",
    nextReviewDate: "2025-10-01",
    owner: "Janet Kintu",
    complianceTasksCompleted: 3,
    totalTasks: 5,
    status: "At Risk",
    category: "Legal Compliance"
  },
  {
    policyId: "P007",
    policyName: "Vendor Management Policy",
    department: "Procurement",
    lastReviewedDate: "2023-09-15",
    nextReviewDate: "2024-09-15",
    owner: "David Ouma",
    complianceTasksCompleted: 7,
    totalTasks: 8,
    status: "On Track",
    category: "Vendor Management"
  },
  {
    policyId: "P008",
    policyName: "Record Retention Policy",
    department: "Finance",
    lastReviewedDate: "2025-03-01",
    nextReviewDate: "2026-03-01",
    owner: "Robert Lwanga",
    complianceTasksCompleted: 9,
    totalTasks: 10,
    status: "On Track",
    category: "Financial"
  },
  {
    policyId: "P009",
    policyName: "GDPR Policy",
    department: "Legal",
    lastReviewedDate: "2024-06-10",
    nextReviewDate: "2025-06-10",
    owner: "Christine Namatovu",
    complianceTasksCompleted: 5,
    totalTasks: 6,
    status: "At Risk",
    category: "Data Protection"
  },
  {
    policyId: "P010",
    policyName: "Health & Safety Policy",
    department: "Operations",
    lastReviewedDate: "2023-12-01",
    nextReviewDate: "2024-12-01",
    owner: "Diana Namusoke",
    complianceTasksCompleted: 3,
    totalTasks: 5,
    status: "At Risk",
    category: "Safety"
  },
  {
    policyId: "P011",
    policyName: "Financial Approval Policy",
    department: "Finance",
    lastReviewedDate: "2025-01-20",
    nextReviewDate: "2026-01-20",
    owner: "Naomi Kyaligonza",
    complianceTasksCompleted: 8,
    totalTasks: 8,
    status: "On Track",
    category: "Financial"
  },
  {
    policyId: "P012",
    policyName: "IT Access Control Policy",
    department: "IT",
    lastReviewedDate: "2024-07-15",
    nextReviewDate: "2025-07-15",
    owner: "Sandra Mbabazi",
    complianceTasksCompleted: 4,
    totalTasks: 6,
    status: "At Risk",
    category: "IT Security"
  },
  {
    policyId: "P013",
    policyName: "Media Licensing Policy",
    department: "Operations",
    lastReviewedDate: "2025-04-05",
    nextReviewDate: "2026-04-05",
    owner: "Henry Oryem",
    complianceTasksCompleted: 3,
    totalTasks: 3,
    status: "On Track",
    category: "Regulatory"
  },
  {
    policyId: "P014",
    policyName: "Employee Leave Policy",
    department: "HR",
    lastReviewedDate: "2023-11-15",
    nextReviewDate: "2024-11-15",
    owner: "James Kato",
    complianceTasksCompleted: 6,
    totalTasks: 7,
    status: "At Risk",
    category: "HR"
  },
  {
    policyId: "P015",
    policyName: "Data Retention Policy",
    department: "Legal",
    lastReviewedDate: "2025-03-10",
    nextReviewDate: "2026-03-10",
    owner: "Brian Odongo",
    complianceTasksCompleted: 5,
    totalTasks: 5,
    status: "On Track",
    category: "Data Protection"
  },
  {
    policyId: "P016",
    policyName: "Anti-Money Laundering Policy",
    department: "Finance",
    lastReviewedDate: "2024-09-05",
    nextReviewDate: "2025-09-05",
    owner: "Isaac Mugerwa",
    complianceTasksCompleted: 7,
    totalTasks: 10,
    status: "At Risk",
    category: "Financial"
  },
  {
    policyId: "P017",
    policyName: "Cybersecurity Policy",
    department: "IT",
    lastReviewedDate: "2025-02-01",
    nextReviewDate: "2026-02-01",
    owner: "Gloria Atwine",
    complianceTasksCompleted: 6,
    totalTasks: 7,
    status: "On Track",
    category: "IT Security"
  },
  {
    policyId: "P018",
    policyName: "Advertising Compliance Policy",
    department: "Editorial",
    lastReviewedDate: "2023-10-15",
    nextReviewDate: "2024-10-15",
    owner: "Charles Etukuri",
    complianceTasksCompleted: 4,
    totalTasks: 5,
    status: "At Risk",
    category: "Regulatory"
  },
  {
    policyId: "P019",
    policyName: "Whistleblower Policy",
    department: "Legal",
    lastReviewedDate: "2024-05-10",
    nextReviewDate: "2025-05-10",
    owner: "Caroline Nansubuga",
    complianceTasksCompleted: 2,
    totalTasks: 3,
    status: "At Risk",
    category: "Legal Compliance"
  },
  {
    policyId: "P020",
    policyName: "Contract Management Policy",
    department: "Legal",
    lastReviewedDate: "2025-01-25",
    nextReviewDate: "2026-01-25",
    owner: "Samuel Owor",
    complianceTasksCompleted: 7,
    totalTasks: 7,
    status: "On Track",
    category: "Legal Compliance"
  },
  {
    policyId: "P021",
    policyName: "Financial Reporting Manual",
    department: "Finance",
    lastReviewedDate: "2025-03-15",
    nextReviewDate: "2026-03-15",
    owner: "Naomi Kyaligonza",
    complianceTasksCompleted: 9,
    totalTasks: 10,
    status: "On Track",
    category: "Financial"
  },
  {
    policyId: "P022",
    policyName: "HR Recruitment Policy",
    department: "HR",
    lastReviewedDate: "2023-12-01",
    nextReviewDate: "2024-12-01",
    owner: "Lydia Nabukenya",
    complianceTasksCompleted: 5,
    totalTasks: 6,
    status: "At Risk",
    category: "HR"
  },
  {
    policyId: "P023",
    policyName: "IT Disaster Recovery Policy",
    department: "IT",
    lastReviewedDate: "2024-08-10",
    nextReviewDate: "2025-08-10",
    owner: "Angela Mirembe",
    complianceTasksCompleted: 3,
    totalTasks: 4,
    status: "At Risk",
    category: "IT Security"
  },
  {
    policyId: "P024",
    policyName: "Environmental Compliance Policy",
    department: "Operations",
    lastReviewedDate: "2025-02-20",
    nextReviewDate: "2026-02-20",
    owner: "Robert Ochieng",
    complianceTasksCompleted: 6,
    totalTasks: 6,
    status: "On Track",
    category: "Regulatory"
  },
  {
    policyId: "P025",
    policyName: "Procurement Compliance Policy",
    department: "Procurement",
    lastReviewedDate: "2024-11-05",
    nextReviewDate: "2025-11-05",
    owner: "Esther Kyomuhangi",
    complianceTasksCompleted: 7,
    totalTasks: 8,
    status: "On Track",
    category: "Vendor Management"
  },
  {
    policyId: "P026",
    policyName: "Workplace Diversity Policy",
    department: "HR",
    lastReviewedDate: "2023-09-20",
    nextReviewDate: "2024-09-20",
    owner: "James Kato",
    complianceTasksCompleted: 4,
    totalTasks: 5,
    status: "At Risk",
    category: "HR"
  },
  {
    policyId: "P027",
    policyName: "Internal Audit Policy",
    department: "Finance",
    lastReviewedDate: "2025-01-15",
    nextReviewDate: "2026-01-15",
    owner: "Grace Namaganda",
    complianceTasksCompleted: 8,
    totalTasks: 8,
    status: "On Track",
    category: "Financial"
  },
  {
    policyId: "P028",
    policyName: "Information Security Policy",
    department: "IT",
    lastReviewedDate: "2024-06-25",
    nextReviewDate: "2025-06-25",
    owner: "Sandra Mbabazi",
    complianceTasksCompleted: 5,
    totalTasks: 6,
    status: "At Risk",
    category: "IT Security"
  },
  {
    policyId: "P029",
    policyName: "Content Guidelines Policy",
    department: "Editorial",
    lastReviewedDate: "2025-03-05",
    nextReviewDate: "2026-03-05",
    owner: "Charles Etukuri",
    complianceTasksCompleted: 6,
    totalTasks: 6,
    status: "On Track",
    category: "Regulatory"
  },
  {
    policyId: "P030",
    policyName: "Regulatory Reporting Policy",
    department: "Legal",
    lastReviewedDate: "2025-01-05",
    nextReviewDate: "2026-01-05",
    owner: "Peter Mugisha",
    complianceTasksCompleted: 5,
    totalTasks: 5,
    status: "On Track",
    category: "Legal Compliance"
  }
];
