export const setupTimeData = [
  
  {
    jobId: "HS_004",
    machine: "Heidelberg Speedmaster",
    operator: "John Okello",
    operatorExperienceLevel: "Senior",
    service: "Newspaper Printing",
    setupDate: "2022-01-10",
    setupStartTime: "08:15:00",
    setupEndTime: "08:50:00",
    setupDurationMinutes: 35,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Tooling",
    jobPriority: "High",
    shift: "Morning",
    comments: "Smooth changeover"
  },
  {
    jobId: "GM_003",
    machine: "Goss Magnum",
    operator: "Grace Nanyonga",
    operatorExperienceLevel: "Intermediate",
    service: "Magazine Printing",
    setupDate: "2022-01-12",
    setupStartTime: "09:30:00",
    setupEndTime: "10:25:00",
    setupDurationMinutes: 55,
    expectedSetupDurationMinutes: 45,
    changeoverType: "Cleaning",
    jobPriority: "Medium",
    shift: "Morning",
    comments: "Extra cleaning required"
  },
  {
    jobId: "KL_003",
    machine: "Komori Lithrone",
    operator: "David Kato",
    operatorExperienceLevel: "Junior",
    service: "Business Card Printing",
    setupDate: "2022-01-15",
    setupStartTime: "14:00:00",
    setupEndTime: "14:30:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Afternoon",
    comments: "Learning curve"
  },
  {
    jobId: "HS_005",
    machine: "Heidelberg Speedmaster",
    operator: "Mary Namusoke",
    operatorExperienceLevel: "Intermediate",
    service: "Book Printing",
    setupDate: "2022-02-08",
    setupStartTime: "07:45:00",
    setupEndTime: "08:30:00",
    setupDurationMinutes: 45,
    expectedSetupDurationMinutes: 40,
    changeoverType: "Tooling",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_004",
    machine: "Goss Magnum",
    operator: "Sam Mubiru",
    operatorExperienceLevel: "Senior",
    service: "Weekly Newspaper",
    setupDate: "2022-02-14",
    setupStartTime: "13:15:00",
    setupEndTime: "13:45:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Afternoon",
    comments: "Efficient setup"
  },
  {
    jobId: "KL_004",
    machine: "Komori Lithrone",
    operator: "Peter Ssenoga",
    operatorExperienceLevel: "Intermediate",
    service: "Flyer Printing",
    setupDate: "2022-02-20",
    setupStartTime: "10:30:00",
    setupEndTime: "11:00:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Calibration",
    jobPriority: "Medium",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "HS_006",
    machine: "Heidelberg Speedmaster",
    operator: "Alice Nambi",
    operatorExperienceLevel: "Senior",
    service: "Magazine Printing",
    setupDate: "2022-03-05",
    setupStartTime: "08:00:00",
    setupEndTime: "08:35:00",
    setupDurationMinutes: 35,
    expectedSetupDurationMinutes: 40,
    changeoverType: "Tooling",
    jobPriority: "Medium",
    shift: "Morning",
    comments: "New operator performing well"
  },
  {
    jobId: "GM_005",
    machine: "Goss Magnum",
    operator: "Robert Ssali",
    operatorExperienceLevel: "Junior",
    service: "Poster Printing",
    setupDate: "2022-03-12",
    setupStartTime: "15:00:00",
    setupEndTime: "16:00:00",
    setupDurationMinutes: 60,
    expectedSetupDurationMinutes: 45,
    changeoverType: "Cleaning",
    jobPriority: "Low",
    shift: "Afternoon",
    comments: "Training session"
  },
  {
    jobId: "KL_005",
    machine: "Komori Lithrone",
    operator: "Sarah Kisakye",
    operatorExperienceLevel: "Intermediate",
    service: "Brochure Printing",
    setupDate: "2022-03-18",
    setupStartTime: "11:15:00",
    setupEndTime: "11:40:00",
    setupDurationMinutes: 25,
    expectedSetupDurationMinutes: 30,
    changeoverType: "Calibration",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "HS_007",
    machine: "Heidelberg Speedmaster",
    operator: "John Okello",
    operatorExperienceLevel: "Senior",
    service: "Newspaper Printing",
    setupDate: "2022-04-02",
    setupStartTime: "07:30:00",
    setupEndTime: "08:00:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_006",
    machine: "Goss Magnum",
    operator: "Grace Nanyonga",
    operatorExperienceLevel: "Intermediate",
    service: "Magazine Printing",
    setupDate: "2022-04-10",
    setupStartTime: "09:45:00",
    setupEndTime: "10:30:00",
    setupDurationMinutes: 45,
    expectedSetupDurationMinutes: 45,
    changeoverType: "Tooling",
    jobPriority: "Medium",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "KL_006",
    machine: "Komori Lithrone",
    operator: "David Kato",
    operatorExperienceLevel: "Junior",
    service: "Label Printing",
    setupDate: "2022-04-15",
    setupStartTime: "13:30:00",
    setupEndTime: "14:10:00",
    setupDurationMinutes: 40,
    expectedSetupDurationMinutes: 30,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Afternoon",
    comments: "Complex job setup"
  },
  {
    jobId: "HS_008",
    machine: "Heidelberg Speedmaster",
    operator: "Mary Namusoke",
    operatorExperienceLevel: "Intermediate",
    service: "Book Printing",
    setupDate: "2022-05-08",
    setupStartTime: "08:15:00",
    setupEndTime: "08:55:00",
    setupDurationMinutes: 40,
    expectedSetupDurationMinutes: 40,
    changeoverType: "Tooling",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_007",
    machine: "Goss Magnum",
    operator: "Sam Mubiru",
    operatorExperienceLevel: "Senior",
    service: "Weekly Newspaper",
    setupDate: "2022-05-20",
    setupStartTime: "12:30:00",
    setupEndTime: "13:05:00",
    setupDurationMinutes: 35,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Cleaning",
    jobPriority: "Medium",
    shift: "Afternoon",
    comments: ""
  },
  {
    jobId: "KL_007",
    machine: "Komori Lithrone",
    operator: "Peter Ssenoga",
    operatorExperienceLevel: "Intermediate",
    service: "Flyer Printing",
    setupDate: "2022-05-25",
    setupStartTime: "10:00:00",
    setupEndTime: "10:20:00",
    setupDurationMinutes: 20,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Morning",
    comments: "Quick setup"
  },
  {
    jobId: "HS_009",
    machine: "Heidelberg Speedmaster",
    operator: "Alice Nambi",
    operatorExperienceLevel: "Senior",
    service: "Catalog Printing",
    setupDate: "2022-06-12",
    setupStartTime: "07:45:00",
    setupEndTime: "08:25:00",
    setupDurationMinutes: 40,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Tooling",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_008",
    machine: "Goss Magnum",
    operator: "Robert Ssali",
    operatorExperienceLevel: "Junior",
    service: "Magazine Printing",
    setupDate: "2022-06-18",
    setupStartTime: "14:30:00",
    setupEndTime: "15:20:00",
    setupDurationMinutes: 50,
    expectedSetupDurationMinutes: 45,
    changeoverType: "Cleaning",
    jobPriority: "Medium",
    shift: "Afternoon",
    comments: "Improving skills"
  },
  {
    jobId: "KL_008",
    machine: "Komori Lithrone",
    operator: "Sarah Kisakye",
    operatorExperienceLevel: "Intermediate",
    service: "Business Card Printing",
    setupDate: "2022-06-28",
    setupStartTime: "11:30:00",
    setupEndTime: "12:00:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "HS_010",
    machine: "Heidelberg Speedmaster",
    operator: "John Okello",
    operatorExperienceLevel: "Senior",
    service: "Newspaper Printing",
    setupDate: "2022-07-05",
    setupStartTime: "08:00:00",
    setupEndTime: "08:30:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_009",
    machine: "Goss Magnum",
    operator: "Grace Nanyonga",
    operatorExperienceLevel: "Intermediate",
    service: "Weekly Newspaper",
    setupDate: "2022-07-15",
    setupStartTime: "09:15:00",
    setupEndTime: "10:00:00",
    setupDurationMinutes: 45,
    expectedSetupDurationMinutes: 40,
    changeoverType: "Tooling",
    jobPriority: "Medium",
    shift: "Morning",
    comments: ""
  },

 
  {
    jobId: "HS_011",
    machine: "Heidelberg Speedmaster",
    operator: "Mary Namusoke",
    operatorExperienceLevel: "Senior",
    service: "Book Printing",
    setupDate: "2023-01-08",
    setupStartTime: "08:00:00",
    setupEndTime: "08:35:00",
    setupDurationMinutes: 35,
    expectedSetupDurationMinutes: 40,
    changeoverType: "Tooling",
    jobPriority: "High",
    shift: "Morning",
    comments: "Promoted to Senior"
  },
  {
    jobId: "KL_009",
    machine: "Komori Lithrone",
    operator: "David Kato",
    operatorExperienceLevel: "Intermediate",
    service: "Poster Printing",
    setupDate: "2023-01-12",
    setupStartTime: "13:45:00",
    setupEndTime: "14:20:00",
    setupDurationMinutes: 35,
    expectedSetupDurationMinutes: 30,
    changeoverType: "Calibration",
    jobPriority: "Medium",
    shift: "Afternoon",
    comments: "Skill improvement"
  },
  {
    jobId: "GM_010",
    machine: "Goss Magnum",
    operator: "Sam Mubiru",
    operatorExperienceLevel: "Senior",
    service: "Magazine Printing",
    setupDate: "2023-01-20",
    setupStartTime: "12:15:00",
    setupEndTime: "12:45:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Afternoon",
    comments: ""
  },
  {
    jobId: "HS_012",
    machine: "Heidelberg Speedmaster",
    operator: "Alice Nambi",
    operatorExperienceLevel: "Senior",
    service: "Brochure Printing",
    setupDate: "2023-02-05",
    setupStartTime: "07:30:00",
    setupEndTime: "08:05:00",
    setupDurationMinutes: 35,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Tooling",
    jobPriority: "Medium",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "KL_010",
    machine: "Komori Lithrone",
    operator: "Peter Ssenoga",
    operatorExperienceLevel: "Senior",
    service: "Flyer Printing",
    setupDate: "2023-02-14",
    setupStartTime: "10:30:00",
    setupEndTime: "10:50:00",
    setupDurationMinutes: 20,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Morning",
    comments: "Promoted to Senior"
  },
  {
    jobId: "GM_011",
    machine: "Goss Magnum",
    operator: "Robert Ssali",
    operatorExperienceLevel: "Intermediate",
    service: "Weekly Newspaper",
    setupDate: "2023-02-22",
    setupStartTime: "15:00:00",
    setupEndTime: "15:45:00",
    setupDurationMinutes: 45,
    expectedSetupDurationMinutes: 40,
    changeoverType: "Cleaning",
    jobPriority: "Medium",
    shift: "Afternoon",
    comments: "Steady progress"
  },
  {
    jobId: "HS_013",
    machine: "Heidelberg Speedmaster",
    operator: "John Okello",
    operatorExperienceLevel: "Senior",
    service: "Newspaper Printing",
    setupDate: "2023-03-10",
    setupStartTime: "08:15:00",
    setupEndTime: "08:45:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "KL_011",
    machine: "Komori Lithrone",
    operator: "Sarah Kisakye",
    operatorExperienceLevel: "Senior",
    service: "Label Printing",
    setupDate: "2023-03-18",
    setupStartTime: "11:00:00",
    setupEndTime: "11:25:00",
    setupDurationMinutes: 25,
    expectedSetupDurationMinutes: 30,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Morning",
    comments: "Promoted to Senior"
  },
  {
    jobId: "GM_012",
    machine: "Goss Magnum",
    operator: "Grace Nanyonga",
    operatorExperienceLevel: "Senior",
    service: "Magazine Printing",
    setupDate: "2023-03-25",
    setupStartTime: "09:30:00",
    setupEndTime: "10:10:00",
    setupDurationMinutes: 40,
    expectedSetupDurationMinutes: 45,
    changeoverType: "Tooling",
    jobPriority: "High",
    shift: "Morning",
    comments: "Promoted to Senior"
  },
  {
    jobId: "HS_014",
    machine: "Heidelberg Speedmaster",
    operator: "Mary Namusoke",
    operatorExperienceLevel: "Senior",
    service: "Book Printing",
    setupDate: "2023-04-08",
    setupStartTime: "08:00:00",
    setupEndTime: "08:30:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Tooling",
    jobPriority: "Medium",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "KL_012",
    machine: "Komori Lithrone",
    operator: "James Mukasa",
    operatorExperienceLevel: "Junior",
    service: "Business Card Printing",
    setupDate: "2023-04-15",
    setupStartTime: "14:00:00",
    setupEndTime: "14:45:00",
    setupDurationMinutes: 45,
    expectedSetupDurationMinutes: 30,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Afternoon",
    comments: "New hire training"
  },
  {
    jobId: "GM_013",
    machine: "Goss Magnum",
    operator: "Sam Mubiru",
    operatorExperienceLevel: "Senior",
    service: "Weekly Newspaper",
    setupDate: "2023-04-28",
    setupStartTime: "12:45:00",
    setupEndTime: "13:15:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Afternoon",
    comments: ""
  },
  {
    jobId: "HS_015",
    machine: "Heidelberg Speedmaster",
    operator: "Alice Nambi",
    operatorExperienceLevel: "Senior",
    service: "Catalog Printing",
    setupDate: "2023-05-12",
    setupStartTime: "07:45:00",
    setupEndTime: "08:20:00",
    setupDurationMinutes: 35,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Tooling",
    jobPriority: "Medium",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "KL_013",
    machine: "Komori Lithrone",
    operator: "David Kato",
    operatorExperienceLevel: "Intermediate",
    service: "Flyer Printing",
    setupDate: "2023-05-20",
    setupStartTime: "10:15:00",
    setupEndTime: "10:45:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Calibration",
    jobPriority: "Medium",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_014",
    machine: "Goss Magnum",
    operator: "Robert Ssali",
    operatorExperienceLevel: "Intermediate",
    service: "Magazine Printing",
    setupDate: "2023-06-05",
    setupStartTime: "14:15:00",
    setupEndTime: "14:55:00",
    setupDurationMinutes: 40,
    expectedSetupDurationMinutes: 40,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Afternoon",
    comments: ""
  },
  {
    jobId: "HS_016",
    machine: "Heidelberg Speedmaster",
    operator: "John Okello",
    operatorExperienceLevel: "Senior",
    service: "Newspaper Printing",
    setupDate: "2023-06-18",
    setupStartTime: "08:00:00",
    setupEndTime: "08:25:00",
    setupDurationMinutes: 25,
    expectedSetupDurationMinutes: 30,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "KL_014",
    machine: "Komori Lithrone",
    operator: "Peter Ssenoga",
    operatorExperienceLevel: "Senior",
    service: "Poster Printing",
    setupDate: "2023-06-25",
    setupStartTime: "11:30:00",
    setupEndTime: "11:50:00",
    setupDurationMinutes: 20,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_015",
    machine: "Goss Magnum",
    operator: "Grace Nanyonga",
    operatorExperienceLevel: "Senior",
    service: "Weekly Newspaper",
    setupDate: "2023-07-08",
    setupStartTime: "09:00:00",
    setupEndTime: "09:35:00",
    setupDurationMinutes: 35,
    expectedSetupDurationMinutes: 40,
    changeoverType: "Tooling",
    jobPriority: "Medium",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "HS_017",
    machine: "Heidelberg Speedmaster",
    operator: "Mary Namusoke",
    operatorExperienceLevel: "Senior",
    service: "Book Printing",
    setupDate: "2023-07-20",
    setupStartTime: "08:15:00",
    setupEndTime: "08:45:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Tooling",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "KL_015",
    machine: "Komori Lithrone",
    operator: "Sarah Kisakye",
    operatorExperienceLevel: "Senior",
    service: "Brochure Printing",
    setupDate: "2023-08-05",
    setupStartTime: "10:45:00",
    setupEndTime: "11:10:00",
    setupDurationMinutes: 25,
    expectedSetupDurationMinutes: 30,
    changeoverType: "Calibration",
    jobPriority: "Medium",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_016",
    machine: "Goss Magnum",
    operator: "Sam Mubiru",
    operatorExperienceLevel: "Senior",
    service: "Magazine Printing",
    setupDate: "2023-08-15",
    setupStartTime: "13:00:00",
    setupEndTime: "13:30:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Afternoon",
    comments: ""
  },
  {
    jobId: "HS_018",
    machine: "Heidelberg Speedmaster",
    operator: "Alice Nambi",
    operatorExperienceLevel: "Senior",
    service: "Label Printing",
    setupDate: "2023-08-28",
    setupStartTime: "07:30:00",
    setupEndTime: "08:00:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Tooling",
    jobPriority: "Low",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "KL_016",
    machine: "Komori Lithrone",
    operator: "James Mukasa",
    operatorExperienceLevel: "Intermediate",
    service: "Flyer Printing",
    setupDate: "2023-09-10",
    setupStartTime: "14:30:00",
    setupEndTime: "15:05:00",
    setupDurationMinutes: 35,
    expectedSetupDurationMinutes: 30,
    changeoverType: "Calibration",
    jobPriority: "Medium",
    shift: "Afternoon",
    comments: "Skills developing"
  },

  // 2024 Records
  {
    jobId: "HS_019",
    machine: "Heidelberg Speedmaster",
    operator: "John Okello",
    operatorExperienceLevel: "Senior",
    service: "Newspaper Printing",
    setupDate: "2024-01-15",
    setupStartTime: "08:00:00",
    setupEndTime: "08:25:00",
    setupDurationMinutes: 25,
    expectedSetupDurationMinutes: 30,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_017",
    machine: "Goss Magnum",
    operator: "Robert Ssali",
    operatorExperienceLevel: "Senior",
    service: "Magazine Printing",
    setupDate: "2024-01-22",
    setupStartTime: "15:15:00",
    setupEndTime: "15:45:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Cleaning",
    jobPriority: "Medium",
    shift: "Afternoon",
    comments: "Promoted to Senior"
  },
  {
    jobId: "KL_017",
    machine: "Komori Lithrone",
    operator: "David Kato",
    operatorExperienceLevel: "Senior",
    service: "Business Card Printing",
    setupDate: "2024-02-05",
    setupStartTime: "10:00:00",
    setupEndTime: "10:20:00",
    setupDurationMinutes: 20,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Morning",
    comments: "Promoted to Senior"
  },
  {
    jobId: "HS_020",
    machine: "Heidelberg Speedmaster",
    operator: "Mary Namusoke",
    operatorExperienceLevel: "Senior",
    service: "Book Printing",
    setupDate: "2024-02-18",
    setupStartTime: "08:15:00",
    setupEndTime: "08:40:00",
    setupDurationMinutes: 25,
    expectedSetupDurationMinutes: 30,
    changeoverType: "Tooling",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_018",
    machine: "Goss Magnum",
    operator: "Grace Nanyonga",
    operatorExperienceLevel: "Senior",
    service: "Weekly Newspaper",
    setupDate: "2024-03-08",
    setupStartTime: "09:30:00",
    setupEndTime: "10:00:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Tooling",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "KL_018",
    machine: "Komori Lithrone",
    operator: "Peter Ssenoga",
    operatorExperienceLevel: "Senior",
    service: "Poster Printing",
    setupDate: "2024-03-20",
    setupStartTime: "11:15:00",
    setupEndTime: "11:35:00",
    setupDurationMinutes: 20,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Calibration",
    jobPriority: "Medium",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "HS_021",
    machine: "Heidelberg Speedmaster",
    operator: "Alice Nambi",
    operatorExperienceLevel: "Senior",
    service: "Catalog Printing",
    setupDate: "2024-04-12",
    setupStartTime: "07:45:00",
    setupEndTime: "08:15:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Tooling",
    jobPriority: "Medium",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_019",
    machine: "Goss Magnum",
    operator: "Sam Mubiru",
    operatorExperienceLevel: "Senior",
    service: "Magazine Printing",
    setupDate: "2024-04-25",
    setupStartTime: "12:30:00",
    setupEndTime: "13:00:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Afternoon",
    comments: ""
  },
  {
    jobId: "KL_019",
    machine: "Komori Lithrone",
    operator: "Sarah Kisakye",
    operatorExperienceLevel: "Senior",
    service: "Brochure Printing",
    setupDate: "2024-05-08",
    setupStartTime: "10:30:00",
    setupEndTime: "10:50:00",
    setupDurationMinutes: 20,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "HS_022",
    machine: "Heidelberg Speedmaster",
    operator: "John Okello",
    operatorExperienceLevel: "Senior",
    service: "Newspaper Printing",
    setupDate: "2024-05-18",
    setupStartTime: "08:00:00",
    setupEndTime: "08:20:00",
    setupDurationMinutes: 20,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_020",
    machine: "Goss Magnum",
    operator: "James Mukasa",
    operatorExperienceLevel: "Senior",
    service: "Weekly Newspaper",
    setupDate: "2024-06-05",
    setupStartTime: "14:00:00",
    setupEndTime: "14:30:00",
    setupDurationMinutes: 30,
    expectedSetupDurationMinutes: 35,
    changeoverType: "Cleaning",
    jobPriority: "Medium",
    shift: "Afternoon",
    comments: "Promoted to Senior"
  },
  {
    jobId: "KL_020",
    machine: "Komori Lithrone",
    operator: "David Kato",
    operatorExperienceLevel: "Senior",
    service: "Label Printing",
    setupDate: "2024-06-15",
    setupStartTime: "11:45:00",
    setupEndTime: "12:05:00",
    setupDurationMinutes: 20,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "HS_023",
    machine: "Heidelberg Speedmaster",
    operator: "Mary Namusoke",
    operatorExperienceLevel: "Senior",
    service: "Book Printing",
    setupDate: "2024-07-10",
    setupStartTime: "08:15:00",
    setupEndTime: "08:35:00",
    setupDurationMinutes: 20,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Tooling",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_021",
    machine: "Goss Magnum",
    operator: "Robert Ssali",
    operatorExperienceLevel: "Senior",
    service: "Magazine Printing",
    setupDate: "2024-07-22",
    setupStartTime: "15:30:00",
    setupEndTime: "15:55:00",
    setupDurationMinutes: 25,
    expectedSetupDurationMinutes: 30,
    changeoverType: "Cleaning",
    jobPriority: "Medium",
    shift: "Afternoon",
    comments: ""
  },
  {
    jobId: "KL_021",
    machine: "Komori Lithrone",
    operator: "Peter Ssenoga",
    operatorExperienceLevel: "Senior",
    service: "Flyer Printing",
    setupDate: "2024-08-08",
    setupStartTime: "10:15:00",
    setupEndTime: "10:30:00",
    setupDurationMinutes: 15,
    expectedSetupDurationMinutes: 20,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Morning",
    comments: "Exceptional performance"
  },
  {
    jobId: "HS_024",
    machine: "Heidelberg Speedmaster",
    operator: "Alice Nambi",
    operatorExperienceLevel: "Senior",
    service: "Business Card Printing",
    setupDate: "2024-08-20",
    setupStartTime: "07:30:00",
    setupEndTime: "07:50:00",
    setupDurationMinutes: 20,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Tooling",
    jobPriority: "Low",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_022",
    machine: "Goss Magnum",
    operator: "Grace Nanyonga",
    operatorExperienceLevel: "Senior",
    service: "Weekly Newspaper",
    setupDate: "2024-09-05",
    setupStartTime: "09:00:00",
    setupEndTime: "09:25:00",
    setupDurationMinutes: 25,
    expectedSetupDurationMinutes: 30,
    changeoverType: "Tooling",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "KL_022",
    machine: "Komori Lithrone",
    operator: "Sarah Kisakye",
    operatorExperienceLevel: "Senior",
    service: "Poster Printing",
    setupDate: "2024-09-18",
    setupStartTime: "11:00:00",
    setupEndTime: "11:20:00",
    setupDurationMinutes: 20,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Calibration",
    jobPriority: "Medium",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "HS_025",
    machine: "Heidelberg Speedmaster",
    operator: "John Okello",
    operatorExperienceLevel: "Senior",
    service: "Newspaper Printing",
    setupDate: "2024-10-08",
    setupStartTime: "08:00:00",
    setupEndTime: "08:18:00",
    setupDurationMinutes: 18,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_023",
    machine: "Goss Magnum",
    operator: "Sam Mubiru",
    operatorExperienceLevel: "Senior",
    service: "Magazine Printing",
    setupDate: "2024-10-22",
    setupStartTime: "12:45:00",
    setupEndTime: "13:10:00",
    setupDurationMinutes: 25,
    expectedSetupDurationMinutes: 30,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Afternoon",
    comments: ""
  },
  {
    jobId: "KL_023",
    machine: "Komori Lithrone",
    operator: "James Mukasa",
    operatorExperienceLevel: "Senior",
    service: "Brochure Printing",
    setupDate: "2024-11-10",
    setupStartTime: "14:15:00",
    setupEndTime: "14:35:00",
    setupDurationMinutes: 20,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Calibration",
    jobPriority: "Medium",
    shift: "Afternoon",
    comments: ""
  },
  {
    jobId: "HS_026",
    machine: "Heidelberg Speedmaster",
    operator: "Mary Namusoke",
    operatorExperienceLevel: "Senior",
    service: "Book Printing",
    setupDate: "2024-11-25",
    setupStartTime: "08:10:00",
    setupEndTime: "08:28:00",
    setupDurationMinutes: 18,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Tooling",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_024",
    machine: "Goss Magnum",
    operator: "Robert Ssali",
    operatorExperienceLevel: "Senior",
    service: "Weekly Newspaper",
    setupDate: "2024-12-08",
    setupStartTime: "15:00:00",
    setupEndTime: "15:22:00",
    setupDurationMinutes: 22,
    expectedSetupDurationMinutes: 28,
    changeoverType: "Cleaning",
    jobPriority: "Medium",
    shift: "Afternoon",
    comments: ""
  },

  
  {
    jobId: "HS_027",
    machine: "Heidelberg Speedmaster",
    operator: "David Kato",
    operatorExperienceLevel: "Senior",
    service: "Catalog Printing",
    setupDate: "2025-01-12",
    setupStartTime: "07:45:00",
    setupEndTime: "08:02:00",
    setupDurationMinutes: 17,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Tooling",
    jobPriority: "Medium",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "KL_024",
    machine: "Komori Lithrone",
    operator: "Peter Ssenoga",
    operatorExperienceLevel: "Senior",
    service: "Label Printing",
    setupDate: "2025-01-20",
    setupStartTime: "10:30:00",
    setupEndTime: "10:45:00",
    setupDurationMinutes: 15,
    expectedSetupDurationMinutes: 20,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_025",
    machine: "Goss Magnum",
    operator: "Grace Nanyonga",
    operatorExperienceLevel: "Senior",
    service: "Magazine Printing",
    setupDate: "2025-02-05",
    setupStartTime: "09:15:00",
    setupEndTime: "09:35:00",
    setupDurationMinutes: 20,
    expectedSetupDurationMinutes: 28,
    changeoverType: "Tooling",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "HS_028",
    machine: "Heidelberg Speedmaster",
    operator: "Alice Nambi",
    operatorExperienceLevel: "Senior",
    service: "Newspaper Printing",
    setupDate: "2025-02-18",
    setupStartTime: "08:00:00",
    setupEndTime: "08:15:00",
    setupDurationMinutes: 15,
    expectedSetupDurationMinutes: 22,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "KL_025",
    machine: "Komori Lithrone",
    operator: "Sarah Kisakye",
    operatorExperienceLevel: "Senior",
    service: "Business Card Printing",
    setupDate: "2025-03-08",
    setupStartTime: "11:30:00",
    setupEndTime: "11:43:00",
    setupDurationMinutes: 13,
    expectedSetupDurationMinutes: 20,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_026",
    machine: "Goss Magnum",
    operator: "Sam Mubiru",
    operatorExperienceLevel: "Senior",
    service: "Weekly Newspaper",
    setupDate: "2025-03-22",
    setupStartTime: "13:00:00",
    setupEndTime: "13:18:00",
    setupDurationMinutes: 18,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Cleaning",
    jobPriority: "Medium",
    shift: "Afternoon",
    comments: ""
  },
  {
    jobId: "HS_029",
    machine: "Heidelberg Speedmaster",
    operator: "John Okello",
    operatorExperienceLevel: "Senior",
    service: "Book Printing",
    setupDate: "2025-04-10",
    setupStartTime: "08:15:00",
    setupEndTime: "08:30:00",
    setupDurationMinutes: 15,
    expectedSetupDurationMinutes: 22,
    changeoverType: "Tooling",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "KL_026",
    machine: "Komori Lithrone",
    operator: "James Mukasa",
    operatorExperienceLevel: "Senior",
    service: "Flyer Printing",
    setupDate: "2025-04-25",
    setupStartTime: "14:00:00",
    setupEndTime: "14:15:00",
    setupDurationMinutes: 15,
    expectedSetupDurationMinutes: 20,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Afternoon",
    comments: ""
  },
  {
    jobId: "GM_027",
    machine: "Goss Magnum",
    operator: "Robert Ssali",
    operatorExperienceLevel: "Senior",
    service: "Magazine Printing",
    setupDate: "2025-05-12",
    setupStartTime: "15:30:00",
    setupEndTime: "15:47:00",
    setupDurationMinutes: 17,
    expectedSetupDurationMinutes: 25,
    changeoverType: "Cleaning",
    jobPriority: "Medium",
    shift: "Afternoon",
    comments: ""
  },
  {
    jobId: "HS_030",
    machine: "Heidelberg Speedmaster",
    operator: "Mary Namusoke",
    operatorExperienceLevel: "Senior",
    service: "Brochure Printing",
    setupDate: "2025-05-28",
    setupStartTime: "07:30:00",
    setupEndTime: "07:43:00",
    setupDurationMinutes: 13,
    expectedSetupDurationMinutes: 20,
    changeoverType: "Tooling",
    jobPriority: "Medium",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "KL_027",
    machine: "Komori Lithrone",
    operator: "David Kato",
    operatorExperienceLevel: "Senior",
    service: "Poster Printing",
    setupDate: "2025-06-15",
    setupStartTime: "10:45:00",
    setupEndTime: "11:00:00",
    setupDurationMinutes: 15,
    expectedSetupDurationMinutes: 20,
    changeoverType: "Calibration",
    jobPriority: "Medium",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_028",
    machine: "Goss Magnum",
    operator: "Grace Nanyonga",
    operatorExperienceLevel: "Senior",
    service: "Weekly Newspaper",
    setupDate: "2025-07-05",
    setupStartTime: "09:00:00",
    setupEndTime: "09:15:00",
    setupDurationMinutes: 15,
    expectedSetupDurationMinutes: 22,
    changeoverType: "Tooling",
    jobPriority: "High",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "HS_031",
    machine: "Heidelberg Speedmaster",
    operator: "Peter Ssenoga",
    operatorExperienceLevel: "Senior",
    service: "Label Printing",
    setupDate: "2025-07-20",
    setupStartTime: "08:00:00",
    setupEndTime: "08:12:00",
    setupDurationMinutes: 12,
    expectedSetupDurationMinutes: 18,
    changeoverType: "Cleaning",
    jobPriority: "Low",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "KL_028",
    machine: "Komori Lithrone",
    operator: "Alice Nambi",
    operatorExperienceLevel: "Senior",
    service: "Business Card Printing",
    setupDate: "2025-08-08",
    setupStartTime: "11:15:00",
    setupEndTime: "11:27:00",
    setupDurationMinutes: 12,
    expectedSetupDurationMinutes: 18,
    changeoverType: "Calibration",
    jobPriority: "Low",
    shift: "Morning",
    comments: ""
  },
  {
    jobId: "GM_029",
    machine: "Goss Magnum",
    operator: "Sam Mubiru",
    operatorExperienceLevel: "Senior",
    service: "Magazine Printing",
    setupDate: "2025-08-22",
    setupStartTime: "12:30:00",
    setupEndTime: "12:43:00",
    setupDurationMinutes: 13,
    expectedSetupDurationMinutes: 20,
    changeoverType: "Cleaning",
    jobPriority: "High",
    shift: "Afternoon",
    comments: ""
  }
];