export const journalistData = [
  {
    articleId: "ART001",
    authorId: "AUTH001",
    author: "Charles Etukuri",
    title: "Karuma bridge to be closed on March 10 for high tech repairs",
    category: "News",
    avgDuration: "00:18:05",
    bounceRate: 0,
    publishDate: "2025-02-28",
    shares: 150,
    likes: 420,
    views: 8000,
    clicks: 3100,
    platform: "Web",
    tags: ["infrastructure", "transport", "repairs"]
  },
  {
    articleId: "ART002",
    authorId: "AUTH002",
    author: "Martin",
    title: "Soroti man gets eight years for defiling teenage girl",
    category: "News",
    avgDuration: "00:00:00",
    bounceRate: 0,
    publishDate: "2025-02-27",
    shares: 90,
    likes: 300,
    views: 5600,
    clicks: 2100,
    platform: "Mobile",
    tags: ["crime", "soroti", "court"]
  },
  {
    articleId: "ART003",
    authorId: "AUTH003",
    author: "AFP",
    title: "Poisoning suspected in DR Congo mystery illness: WHO",
    category: "World",
    avgDuration: "00:18:24",
    bounceRate: 1,
    publishDate: "2025-02-25",
    shares: 200,
    likes: 500,
    views: 12000,
    clicks: 4400,
    platform: "Web",
    tags: ["world", "health", "WHO"]
  },
  {
    articleId: "ART004",
    authorId: "AUTH001",
    author: "Charles Etukuri",
    title: "Two killed as soda truck crashes near Lugogo Cricket Oval",
    category: "News",
    avgDuration: "00:00:00",
    bounceRate: 1,
    publishDate: "2025-02-26",
    shares: 110,
    likes: 280,
    views: 6400,
    clicks: 1900,
    platform: "Mobile",
    tags: ["accident", "lugogo", "breaking"]
  },
  {
    articleId: "ART005",
    authorId: "AUTH004",
    author: "Francis",
    title: "MIU fresh graduates urged to be openminded",
    category: "Education",
    avgDuration: "00:00:00",
    bounceRate: 0,
    publishDate: "2025-02-24",
    shares: 75,
    likes: 220,
    views: 4300,
    clicks: 1500,
    platform: "Web",
    tags: ["education", "graduates", "MIU"]
  },
  {
    articleId: "ART006",
    authorId: "AUTH005",
    author: "Isaac Nuwagaba",
    title: "Loss of sh25.5b US grant bites refugee education",
    category: "Education",
    avgDuration: "00:14:10",
    bounceRate: 0,
    publishDate: "2025-02-20",
    shares: 180,
    likes: 460,
    views: 7800,
    clicks: 2500,
    platform: "Mobile",
    tags: ["refugee", "education", "funding"]
  },
  {
    articleId: "ART007",
    authorId: "AUTH006",
    author: "Peter",
    title: "Bunyoro women urge govt on renewable energy",
    category: "Agric. & Environment",
    avgDuration: "00:00:00",
    bounceRate: 1,
    publishDate: "2025-02-19",
    shares: 95,
    likes: 240,
    views: 5000,
    clicks: 1600,
    platform: "Web",
    tags: ["bunyoro", "energy", "renewable"]
  },
  {
    articleId: "ART008",
    authorId: "AUTH007",
    author: "Godfrey Yusufu",
    title: "Bible verse of the 1st March, 2025",
    category: "News",
    avgDuration: "00:16:34",
    bounceRate: 0,
    publishDate: "2025-03-01",
    shares: 210,
    likes: 480,
    views: 9100,
    clicks: 3400,
    platform: "Mobile",
    tags: ["religion", "bible", "devotion"]
  },
  {
    articleId: "ART009",
    authorId: "AUTH003",
    author: "AFP",
    title: "Police probing 'suspicious' deaths of Hollywood giant Gene Hackman, wife",
    category: "Ent. & Lifestyle",
    avgDuration: "00:14:45",
    bounceRate: 0,
    publishDate: "2025-02-21",
    shares: 300,
    likes: 890,
    views: 15000,
    clicks: 5600,
    platform: "Web",
    tags: ["hollywood", "celebrity", "crime"]
  },
  {
    articleId: "ART010",
    authorId: "AUTH003",
    author: "AFP",
    title: "'You're gambling with WW3': Trump, Zelensky row in Oval Office",
    category: "World",
    avgDuration: "00:19:05",
    bounceRate: 1,
    publishDate: "2025-02-23",
    shares: 420,
    likes: 970,
    views: 17800,
    clicks: 6700,
    platform: "Web",
    tags: ["trump", "zelensky", "world"]
  },
  {
    articleId: "ART011",
    authorId: "AUTH002",
    author: "Martin",
    title: "Trial of Soroti gynaecologist Egwau fails to kick off",
    category: "News",
    avgDuration: "00:19:27",
    bounceRate: 0,
    publishDate: "2025-02-18",
    shares: 130,
    likes: 400,
    views: 7200,
    clicks: 2300,
    platform: "Mobile",
    tags: ["soroti", "trial", "health"]
  },
  {
    articleId: "ART012",
    authorId: "AUTH008",
    author: "Jeff Andrew",
    title: "Choose service delivery over new administrative units’ creation, govt told",
    category: "News",
    avgDuration: "00:00:00",
    bounceRate: 0,
    publishDate: "2025-02-22",
    shares: 90,
    likes: 250,
    views: 4600,
    clicks: 1700,
    platform: "Web",
    tags: ["government", "administrative", "service delivery"]
  },
  {
    articleId: "ART013",
    authorId: "AUTH009",
    author: "Farooq",
    title: "Ramadan: Muslims begin holy month on March 1",
    category: "News",
    avgDuration: "00:00:00",
    bounceRate: 0,
    publishDate: "2025-03-01",
    shares: 180,
    likes: 510,
    views: 8700,
    clicks: 3100,
    platform: "Mobile",
    tags: ["ramadan", "religion", "muslim"]
  },
  {
    articleId: "ART014",
    authorId: "AUTH010",
    author: "Vision Reporter",
    title: "KCCA urged to waive licence fees for Presidential Skilling graduates",
    category: "News",
    avgDuration: "00:00:00",
    bounceRate: 0,
    publishDate: "2025-02-17",
    shares: 70,
    likes: 210,
    views: 4000,
    clicks: 1300,
    platform: "Web",
    tags: ["kcca", "skilling", "graduates"]
  },
  {
    articleId: "ART015",
    authorId: "AUTH011",
    author: "Ali",
    title: "MTN MoMo launches virtual card",
    category: "Business",
    avgDuration: "00:29:20",
    bounceRate: 0,
    publishDate: "2025-02-16",
    shares: 250,
    likes: 780,
    views: 13500,
    clicks: 4900,
    platform: "Web",
    tags: ["momo", "virtual card", "business"]
  },
  {
    articleId: "ART016",
    authorId: "AUTH012",
    author: "Benjalina Namazzi",
    title: "As Ugandans feel the heat, COU launches Environmental Month",
    category: "Agric. & Environment",
    avgDuration: "00:15:36",
    bounceRate: 1,
    publishDate: "2025-02-15",
    shares: 210,
    likes: 560,
    views: 8800,
    clicks: 3000,
    platform: "Mobile",
    tags: ["environment", "COU", "climate"]
  },
  {
    articleId: "ART017",
    authorId: "AUTH003",
    author: "AFP",
    title: "Israel says killed Hezbollah militant in Lebanon strike",
    category: "World",
    avgDuration: "00:14:29",
    bounceRate: 0,
    publishDate: "2025-02-12",
    shares: 330,
    likes: 770,
    views: 14200,
    clicks: 5200,
    platform: "Web",
    tags: ["israel", "hezbollah", "world"]
  },
  {
    articleId: "ART018",
    authorId: "AUTH013",
    author: "Ranell Dickson",
    title: "Music out, books in: Govt orders musicians to exit schools",
    category: "Ent. & Lifestyle",
    avgDuration: "00:13:36",
    bounceRate: 0,
    publishDate: "2025-02-13",
    shares: 280,
    likes: 650,
    views: 11200,
    clicks: 3900,
    platform: "Mobile",
    tags: ["music", "schools", "policy"]
  },
  {
    articleId: "ART019",
    authorId: "AUTH010",
    author: "Vision Reporter",
    title: "Anxiety in Muslim community as Mufti Mubaje clocks 70 years",
    category: "News",
    avgDuration: "00:19:13",
    bounceRate: 1,
    publishDate: "2025-02-14",
    shares: 140,
    likes: 360,
    views: 6700,
    clicks: 2400,
    platform: "Web",
    tags: ["muslim", "mufti", "uganda"]
  },
  {
    articleId: "ART020",
    authorId: "AUTH003",
    author: "AFP",
    title: "UN authorizes evacuation of staff families from Burundi",
    category: "News",
    avgDuration: "00:00:00",
    bounceRate: 0,
    publishDate: "2025-02-11",
    shares: 175,
    likes: 420,
    views: 7500,
    clicks: 2800,
    platform: "Mobile",
    tags: ["UN", "burundi", "evacuation"]
  }
];
