// Raw meeting data (without attendanceRate hardcoding)
const rawMeetings = [
  {
    meetingId: "M001",
    meetingTitle: "Strategy Review",
    meetingDate: "2025-01-01",
    startTime: "09:30",
    endTime: "10:30",
    meetingStatus: "Held",
    department: "Executives",
    totalInvited: 10,
    attended: 9,
  },
  {
    meetingId: "M002",
    meetingTitle: "Q1 Financial Report",
    meetingDate: "2025-03-20",
    startTime: "10:30",
    endTime: "11:30",
    meetingStatus: "Held",
    department: "Finance",
    totalInvited: 20,
    attended: 17,
  },
  {
    meetingId: "M003",
    meetingTitle: "Disciplinary Meeting",
    meetingDate: "2025-09-11",
    startTime: "11:30",
    endTime: "12:30",
    meetingStatus: "Rescheduled",
    department: "HR",
    totalInvited: 10,
    attended: 8,
  },
  {
    meetingId: "M004",
    meetingTitle: "Product Launch Planning",
    meetingDate: "2025-04-05",
    startTime: "14:00",
    endTime: "15:30",
    meetingStatus: "Held",
    department: "Marketing",
    totalInvited: 20,
    attended: 19,
  },
  {
    meetingId: "M005",
    meetingTitle: "IT Infrastructure Update",
    meetingDate: "2025-03-10",
    startTime: "09:00",
    endTime: "10:00",
    meetingStatus: "Cancelled",
    department: "IT",
    totalInvited: 15,
    attended: 0,
  },
  {
    meetingId: "M006",
    meetingTitle: "Budget Alignment",
    meetingDate: "2025-02-20",
    startTime: "13:00",
    endTime: "14:00",
    meetingStatus: "Held",
    department: "Finance",
    totalInvited: 16,
    attended: 14,
  },
  {
    meetingId: "M007",
    meetingTitle: "Quarterly Performance Review",
    meetingDate: "2025-01-15",
    startTime: "10:00",
    endTime: "11:30",
    meetingStatus: "Held",
    department: "Executives",
    totalInvited: 12,
    attended: 11,
  },
  {
    meetingId: "M008",
    meetingTitle: "Team Building Discussion",
    meetingDate: "2025-04-12",
    startTime: "15:00",
    endTime: "16:00",
    meetingStatus: "Held",
    department: "HR",
    totalInvited: 15,
    attended: 13,
  },
  {
    meetingId: "M009",
    meetingTitle: "Sales Strategy Meeting",
    meetingDate: "2025-09-25",
    startTime: "11:00",
    endTime: "12:00",
    meetingStatus: "Rescheduled",
    department: "Sales",
    totalInvited: 10,
    attended: 8,
  },
  {
    meetingId: "M010",
    meetingTitle: "Customer Feedback Review",
    meetingDate: "2025-02-28",
    startTime: "09:30",
    endTime: "10:30",
    meetingStatus: "Held",
    department: "Support",
    totalInvited: 13,
    attended: 11,
  },
  {
    meetingId: "M011",
    meetingTitle: "Compliance Audit Discussion",
    meetingDate: "2025-01-20",
    startTime: "14:00",
    endTime: "15:00",
    meetingStatus: "Held",
    department: "Compliance",
    totalInvited: 10,
    attended: 9,
  },
  {
    meetingId: "M012",
    meetingTitle: "New Product Brainstorm",
    meetingDate: "2025-02-05",
    startTime: "10:30",
    endTime: "12:00",
    meetingStatus: "Held",
    department: "R&D",
    totalInvited: 15,
    attended: 14,
  },
  {
    meetingId: "M013",
    meetingTitle: "Operations Efficiency Review",
    meetingDate: "2025-03-15",
    startTime: "09:00",
    endTime: "10:30",
    meetingStatus: "Held",
    department: "Operations",
    totalInvited: 16,
    attended: 14,
  },
  {
    meetingId: "M014",
    meetingTitle: "Investor Relations Update",
    meetingDate: "2025-01-28",
    startTime: "13:00",
    endTime: "14:00",
    meetingStatus: "Rescheduled",
    department: "Finance",
    totalInvited: 11,
    attended: 9,
  },
  {
    meetingId: "M015",
    meetingTitle: "Marketing Campaign Planning",
    meetingDate: "2025-04-01",
    startTime: "11:00",
    endTime: "12:30",
    meetingStatus: "Held",
    department: "Marketing",
    totalInvited: 20,
    attended: 19,
  },
  {
    meetingId: "M016",
    meetingTitle: "Executive Q&A",
    meetingDate: "2025-03-08",
    startTime: "14:30",
    endTime: "15:30",
    meetingStatus: "Held",
    department: "Executives",
    totalInvited: 10,
    attended: 9,
  },
  {
    meetingId: "M017",
    meetingTitle: "Training Needs Assessment",
    meetingDate: "2025-02-18",
    startTime: "10:00",
    endTime: "11:30",
    meetingStatus: "Held",
    department: "HR",
    totalInvited: 13,
    attended: 11,
  },
  {
    meetingId: "M018",
    meetingTitle: "Supplier Review Meeting",
    meetingDate: "2025-03-12",
    startTime: "09:30",
    endTime: "10:30",
    meetingStatus: "Cancelled",
    department: "Procurement",
    totalInvited: 12,
    attended: 0,
  },
  {
    meetingId: "M019",
    meetingTitle: "Annual Strategy Kickoff",
    meetingDate: "2025-01-05",
    startTime: "08:30",
    endTime: "10:00",
    meetingStatus: "Held",
    department: "Executives",
    totalInvited: 12,
    attended: 11,
  },
  {
    meetingId: "M020",
    meetingTitle: "IT Security Briefing",
    meetingDate: "2025-04-10",
    startTime: "15:00",
    endTime: "16:00",
    meetingStatus: "Held",
    department: "IT",
    totalInvited: 15,
    attended: 13,
  },
];


const meetings = rawMeetings.map(m => ({
  ...m,
  attendanceRate:
    m.totalInvited > 0 ? `${Math.round((m.attended / m.totalInvited) * 100)}%` : "0%",
}));

export default meetings;
