export const meetingsDummy = [
  {
    meetingId: "M001",
    meetingTitle: "Strategy Review Q1",
    meetingDate: "2025-01-10",
    startTime: "09:00",
    endTime: "10:30",
    meetingStatus: "Held",
    department: "Administration",
    attendanceRate: "85%",
  },
  {
    meetingId: "M002",
    meetingTitle: "Budget Planning",
    meetingDate: "2025-02-14",
    startTime: "10:00",
    endTime: "11:00",
    meetingStatus: "Held",
    department: "Finance",
    attendanceRate: "90%",
  },
  {
    meetingId: "M003",
    meetingTitle: "Operations Review",
    meetingDate: "2025-03-05",
    startTime: "14:00",
    endTime: "15:30",
    meetingStatus: "Held",
    department: "Operations",
    attendanceRate: "75%",
  },
  {
    meetingId: "M004",
    meetingTitle: "Editorial Board Meeting",
    meetingDate: "2025-03-20",
    startTime: "11:00",
    endTime: "12:00",
    meetingStatus: "Rescheduled",
    department: "Editorial",
    attendanceRate: "60%",
  },
  {
    meetingId: "M005",
    meetingTitle: "IT Infrastructure Review",
    meetingDate: "2025-04-02",
    startTime: "09:30",
    endTime: "10:30",
    meetingStatus: "Held",
    department: "IT",
    attendanceRate: "100%",
  },
];
