const reports = [
  {
    date: "2025-01-06",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 91,
        records_checked: 15682,
        duplicates_found: 10,
        compliance_status: "Compliant",
        classified_datasets: 80,
        access_requests: 30,
        failed_access_attempts: 5,
        metadata_completeness: 81,
        last_audit: "2025-01-06",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 76,
        records_checked: 22186,
        duplicates_found: 25,
        compliance_status: "Compliant",
        classified_datasets: 87,
        access_requests: 22,
        failed_access_attempts: 3,
        metadata_completeness: 82,
        last_audit: "2025-01-06",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 95,
        records_checked: 20978,
        duplicates_found: 39,
        compliance_status: "Non-Compliant",
        classified_datasets: 80,
        access_requests: 30,
        failed_access_attempts: 2,
        metadata_completeness: 83,
        last_audit: "2025-01-06",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 93,
        records_checked: 18600,
        duplicates_found: 23,
        compliance_status: "Compliant",
        classified_datasets: 50,
        access_requests: 44,
        failed_access_attempts: 7,
        metadata_completeness: 91,
        last_audit: "2025-01-06",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 84,
        records_checked: 22269,
        duplicates_found: 32,
        compliance_status: "Compliant",
        classified_datasets: 68,
        access_requests: 39,
        failed_access_attempts: 3,
        metadata_completeness: 75,
        last_audit: "2025-01-06",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 92,
        records_checked: 15103,
        duplicates_found: 40,
        compliance_status: "Non-Compliant",
        classified_datasets: 88,
        access_requests: 49,
        failed_access_attempts: 1,
        metadata_completeness: 94,
        last_audit: "2025-01-06",
      },
    ],
  },
  {
    date: "2025-01-13",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 76,
        records_checked: 10516,
        duplicates_found: 48,
        compliance_status: "Compliant",
        classified_datasets: 74,
        access_requests: 51,
        failed_access_attempts: 3,
        metadata_completeness: 93,
        last_audit: "2025-01-13",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 83,
        records_checked: 18994,
        duplicates_found: 39,
        compliance_status: "Non-Compliant",
        classified_datasets: 83,
        access_requests: 38,
        failed_access_attempts: 2,
        metadata_completeness: 80,
        last_audit: "2025-01-13",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 91,
        records_checked: 23917,
        duplicates_found: 57,
        compliance_status: "Compliant",
        classified_datasets: 72,
        access_requests: 53,
        failed_access_attempts: 1,
        metadata_completeness: 94,
        last_audit: "2025-01-13",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 82,
        records_checked: 24481,
        duplicates_found: 18,
        compliance_status: "Compliant",
        classified_datasets: 79,
        access_requests: 27,
        failed_access_attempts: 4,
        metadata_completeness: 80,
        last_audit: "2025-01-13",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 93,
        records_checked: 16463,
        duplicates_found: 58,
        compliance_status: "Non-Compliant",
        classified_datasets: 80,
        access_requests: 40,
        failed_access_attempts: 3,
        metadata_completeness: 87,
        last_audit: "2025-01-13",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 80,
        records_checked: 13300,
        duplicates_found: 56,
        compliance_status: "Compliant",
        classified_datasets: 55,
        access_requests: 20,
        failed_access_attempts: 5,
        metadata_completeness: 74,
        last_audit: "2025-01-13",
      },
    ],
  },
  {
    date: "2025-01-20",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 77,
        records_checked: 14277,
        duplicates_found: 57,
        compliance_status: "Compliant",
        classified_datasets: 65,
        access_requests: 31,
        failed_access_attempts: 6,
        metadata_completeness: 89,
        last_audit: "2025-01-20",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 83,
        records_checked: 6970,
        duplicates_found: 35,
        compliance_status: "Non-Compliant",
        classified_datasets: 60,
        access_requests: 36,
        failed_access_attempts: 4,
        metadata_completeness: 91,
        last_audit: "2025-01-20",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 81,
        records_checked: 4276,
        duplicates_found: 44,
        compliance_status: "Compliant",
        classified_datasets: 57,
        access_requests: 46,
        failed_access_attempts: 3,
        metadata_completeness: 82,
        last_audit: "2025-01-20",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 77,
        records_checked: 21389,
        duplicates_found: 28,
        compliance_status: "Compliant",
        classified_datasets: 82,
        access_requests: 25,
        failed_access_attempts: 6,
        metadata_completeness: 80,
        last_audit: "2025-01-20",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 86,
        records_checked: 18785,
        duplicates_found: 51,
        compliance_status: "Compliant",
        classified_datasets: 67,
        access_requests: 48,
        failed_access_attempts: 4,
        metadata_completeness: 92,
        last_audit: "2025-01-20",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 90,
        records_checked: 9969,
        duplicates_found: 55,
        compliance_status: "Non-Compliant",
        classified_datasets: 52,
        access_requests: 55,
        failed_access_attempts: 6,
        metadata_completeness: 92,
        last_audit: "2025-01-20",
      },
    ],
  },
  {
    date: "2025-01-27",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 81,
        records_checked: 15097,
        duplicates_found: 21,
        compliance_status: "Non-Compliant",
        classified_datasets: 62,
        access_requests: 30,
        failed_access_attempts: 3,
        metadata_completeness: 86,
        last_audit: "2025-01-27",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 75,
        records_checked: 4473,
        duplicates_found: 13,
        compliance_status: "Non-Compliant",
        classified_datasets: 89,
        access_requests: 34,
        failed_access_attempts: 7,
        metadata_completeness: 90,
        last_audit: "2025-01-27",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 80,
        records_checked: 11751,
        duplicates_found: 50,
        compliance_status: "Compliant",
        classified_datasets: 73,
        access_requests: 20,
        failed_access_attempts: 4,
        metadata_completeness: 93,
        last_audit: "2025-01-27",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 78,
        records_checked: 24715,
        duplicates_found: 42,
        compliance_status: "Non-Compliant",
        classified_datasets: 68,
        access_requests: 33,
        failed_access_attempts: 7,
        metadata_completeness: 75,
        last_audit: "2025-01-27",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 88,
        records_checked: 11626,
        duplicates_found: 37,
        compliance_status: "Non-Compliant",
        classified_datasets: 53,
        access_requests: 31,
        failed_access_attempts: 2,
        metadata_completeness: 91,
        last_audit: "2025-01-27",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 77,
        records_checked: 4993,
        duplicates_found: 19,
        compliance_status: "Non-Compliant",
        classified_datasets: 74,
        access_requests: 31,
        failed_access_attempts: 6,
        metadata_completeness: 76,
        last_audit: "2025-01-27",
      },
    ],
  },
  {
    date: "2025-02-03",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 94,
        records_checked: 11044,
        duplicates_found: 16,
        compliance_status: "Non-Compliant",
        classified_datasets: 56,
        access_requests: 20,
        failed_access_attempts: 5,
        metadata_completeness: 85,
        last_audit: "2025-02-03",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 79,
        records_checked: 16027,
        duplicates_found: 28,
        compliance_status: "Compliant",
        classified_datasets: 67,
        access_requests: 20,
        failed_access_attempts: 5,
        metadata_completeness: 85,
        last_audit: "2025-02-03",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 83,
        records_checked: 16652,
        duplicates_found: 27,
        compliance_status: "Non-Compliant",
        classified_datasets: 69,
        access_requests: 54,
        failed_access_attempts: 2,
        metadata_completeness: 83,
        last_audit: "2025-02-03",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 77,
        records_checked: 20960,
        duplicates_found: 40,
        compliance_status: "Compliant",
        classified_datasets: 90,
        access_requests: 26,
        failed_access_attempts: 5,
        metadata_completeness: 73,
        last_audit: "2025-02-03",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 87,
        records_checked: 21744,
        duplicates_found: 38,
        compliance_status: "Compliant",
        classified_datasets: 80,
        access_requests: 42,
        failed_access_attempts: 6,
        metadata_completeness: 74,
        last_audit: "2025-02-03",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 84,
        records_checked: 10940,
        duplicates_found: 45,
        compliance_status: "Compliant",
        classified_datasets: 78,
        access_requests: 56,
        failed_access_attempts: 4,
        metadata_completeness: 73,
        last_audit: "2025-02-03",
      },
    ],
  },
  {
    date: "2025-02-10",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 76,
        records_checked: 13911,
        duplicates_found: 21,
        compliance_status: "Non-Compliant",
        classified_datasets: 65,
        access_requests: 38,
        failed_access_attempts: 7,
        metadata_completeness: 84,
        last_audit: "2025-02-10",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 93,
        records_checked: 14557,
        duplicates_found: 12,
        compliance_status: "Compliant",
        classified_datasets: 74,
        access_requests: 43,
        failed_access_attempts: 6,
        metadata_completeness: 76,
        last_audit: "2025-02-10",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 90,
        records_checked: 17049,
        duplicates_found: 34,
        compliance_status: "Non-Compliant",
        classified_datasets: 89,
        access_requests: 55,
        failed_access_attempts: 2,
        metadata_completeness: 97,
        last_audit: "2025-02-10",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 94,
        records_checked: 18994,
        duplicates_found: 47,
        compliance_status: "Compliant",
        classified_datasets: 78,
        access_requests: 44,
        failed_access_attempts: 5,
        metadata_completeness: 94,
        last_audit: "2025-02-10",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 78,
        records_checked: 8673,
        duplicates_found: 58,
        compliance_status: "Compliant",
        classified_datasets: 79,
        access_requests: 29,
        failed_access_attempts: 6,
        metadata_completeness: 89,
        last_audit: "2025-02-10",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 85,
        records_checked: 21675,
        duplicates_found: 41,
        compliance_status: "Compliant",
        classified_datasets: 58,
        access_requests: 36,
        failed_access_attempts: 1,
        metadata_completeness: 94,
        last_audit: "2025-02-10",
      },
    ],
  },
  {
    date: "2025-02-17",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 87,
        records_checked: 8202,
        duplicates_found: 36,
        compliance_status: "Compliant",
        classified_datasets: 80,
        access_requests: 28,
        failed_access_attempts: 4,
        metadata_completeness: 80,
        last_audit: "2025-02-17",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 78,
        records_checked: 24167,
        duplicates_found: 46,
        compliance_status: "Compliant",
        classified_datasets: 82,
        access_requests: 28,
        failed_access_attempts: 7,
        metadata_completeness: 88,
        last_audit: "2025-02-17",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 93,
        records_checked: 10165,
        duplicates_found: 34,
        compliance_status: "Non-Compliant",
        classified_datasets: 64,
        access_requests: 38,
        failed_access_attempts: 5,
        metadata_completeness: 77,
        last_audit: "2025-02-17",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 77,
        records_checked: 21236,
        duplicates_found: 19,
        compliance_status: "Non-Compliant",
        classified_datasets: 61,
        access_requests: 51,
        failed_access_attempts: 2,
        metadata_completeness: 82,
        last_audit: "2025-02-17",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 92,
        records_checked: 7645,
        duplicates_found: 12,
        compliance_status: "Compliant",
        classified_datasets: 54,
        access_requests: 25,
        failed_access_attempts: 3,
        metadata_completeness: 74,
        last_audit: "2025-02-17",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 77,
        records_checked: 4509,
        duplicates_found: 24,
        compliance_status: "Non-Compliant",
        classified_datasets: 50,
        access_requests: 23,
        failed_access_attempts: 1,
        metadata_completeness: 79,
        last_audit: "2025-02-17",
      },
    ],
  },
  {
    date: "2025-02-24",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 76,
        records_checked: 15477,
        duplicates_found: 17,
        compliance_status: "Compliant",
        classified_datasets: 62,
        access_requests: 21,
        failed_access_attempts: 2,
        metadata_completeness: 81,
        last_audit: "2025-02-24",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 92,
        records_checked: 16314,
        duplicates_found: 60,
        compliance_status: "Compliant",
        classified_datasets: 50,
        access_requests: 58,
        failed_access_attempts: 3,
        metadata_completeness: 77,
        last_audit: "2025-02-24",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 91,
        records_checked: 18495,
        duplicates_found: 25,
        compliance_status: "Compliant",
        classified_datasets: 75,
        access_requests: 46,
        failed_access_attempts: 4,
        metadata_completeness: 74,
        last_audit: "2025-02-24",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 91,
        records_checked: 21744,
        duplicates_found: 13,
        compliance_status: "Compliant",
        classified_datasets: 59,
        access_requests: 30,
        failed_access_attempts: 7,
        metadata_completeness: 82,
        last_audit: "2025-02-24",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 78,
        records_checked: 20014,
        duplicates_found: 14,
        compliance_status: "Compliant",
        classified_datasets: 68,
        access_requests: 55,
        failed_access_attempts: 6,
        metadata_completeness: 83,
        last_audit: "2025-02-24",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 75,
        records_checked: 9892,
        duplicates_found: 58,
        compliance_status: "Non-Compliant",
        classified_datasets: 50,
        access_requests: 48,
        failed_access_attempts: 4,
        metadata_completeness: 87,
        last_audit: "2025-02-24",
      },
    ],
  },
  {
    date: "2025-03-03",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 86,
        records_checked: 8867,
        duplicates_found: 15,
        compliance_status: "Compliant",
        classified_datasets: 79,
        access_requests: 30,
        failed_access_attempts: 4,
        metadata_completeness: 88,
        last_audit: "2025-03-03",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 88,
        records_checked: 6947,
        duplicates_found: 26,
        compliance_status: "Compliant",
        classified_datasets: 84,
        access_requests: 59,
        failed_access_attempts: 7,
        metadata_completeness: 93,
        last_audit: "2025-03-03",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 94,
        records_checked: 17283,
        duplicates_found: 21,
        compliance_status: "Compliant",
        classified_datasets: 78,
        access_requests: 41,
        failed_access_attempts: 3,
        metadata_completeness: 95,
        last_audit: "2025-03-03",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 79,
        records_checked: 21369,
        duplicates_found: 37,
        compliance_status: "Non-Compliant",
        classified_datasets: 55,
        access_requests: 47,
        failed_access_attempts: 3,
        metadata_completeness: 84,
        last_audit: "2025-03-03",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 86,
        records_checked: 23768,
        duplicates_found: 22,
        compliance_status: "Non-Compliant",
        classified_datasets: 57,
        access_requests: 26,
        failed_access_attempts: 6,
        metadata_completeness: 96,
        last_audit: "2025-03-03",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 82,
        records_checked: 9818,
        duplicates_found: 56,
        compliance_status: "Non-Compliant",
        classified_datasets: 58,
        access_requests: 21,
        failed_access_attempts: 5,
        metadata_completeness: 80,
        last_audit: "2025-03-03",
      },
    ],
  },
  {
    date: "2025-03-10",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 78,
        records_checked: 6790,
        duplicates_found: 54,
        compliance_status: "Non-Compliant",
        classified_datasets: 61,
        access_requests: 33,
        failed_access_attempts: 7,
        metadata_completeness: 81,
        last_audit: "2025-03-10",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 82,
        records_checked: 24473,
        duplicates_found: 18,
        compliance_status: "Non-Compliant",
        classified_datasets: 55,
        access_requests: 42,
        failed_access_attempts: 4,
        metadata_completeness: 79,
        last_audit: "2025-03-10",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 82,
        records_checked: 10680,
        duplicates_found: 44,
        compliance_status: "Non-Compliant",
        classified_datasets: 75,
        access_requests: 39,
        failed_access_attempts: 5,
        metadata_completeness: 86,
        last_audit: "2025-03-10",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 77,
        records_checked: 7445,
        duplicates_found: 40,
        compliance_status: "Non-Compliant",
        classified_datasets: 86,
        access_requests: 20,
        failed_access_attempts: 6,
        metadata_completeness: 80,
        last_audit: "2025-03-10",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 86,
        records_checked: 24784,
        duplicates_found: 32,
        compliance_status: "Compliant",
        classified_datasets: 54,
        access_requests: 46,
        failed_access_attempts: 6,
        metadata_completeness: 73,
        last_audit: "2025-03-10",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 80,
        records_checked: 6160,
        duplicates_found: 15,
        compliance_status: "Compliant",
        classified_datasets: 59,
        access_requests: 53,
        failed_access_attempts: 6,
        metadata_completeness: 76,
        last_audit: "2025-03-10",
      },
    ],
  },
  {
    date: "2025-03-17",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 86,
        records_checked: 7081,
        duplicates_found: 49,
        compliance_status: "Non-Compliant",
        classified_datasets: 88,
        access_requests: 28,
        failed_access_attempts: 6,
        metadata_completeness: 88,
        last_audit: "2025-03-17",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 93,
        records_checked: 12017,
        duplicates_found: 50,
        compliance_status: "Non-Compliant",
        classified_datasets: 70,
        access_requests: 44,
        failed_access_attempts: 5,
        metadata_completeness: 88,
        last_audit: "2025-03-17",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 83,
        records_checked: 22042,
        duplicates_found: 39,
        compliance_status: "Compliant",
        classified_datasets: 54,
        access_requests: 37,
        failed_access_attempts: 6,
        metadata_completeness: 80,
        last_audit: "2025-03-17",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 86,
        records_checked: 12295,
        duplicates_found: 22,
        compliance_status: "Compliant",
        classified_datasets: 74,
        access_requests: 60,
        failed_access_attempts: 5,
        metadata_completeness: 77,
        last_audit: "2025-03-17",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 84,
        records_checked: 18572,
        duplicates_found: 48,
        compliance_status: "Non-Compliant",
        classified_datasets: 69,
        access_requests: 30,
        failed_access_attempts: 2,
        metadata_completeness: 88,
        last_audit: "2025-03-17",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 84,
        records_checked: 21014,
        duplicates_found: 12,
        compliance_status: "Non-Compliant",
        classified_datasets: 77,
        access_requests: 60,
        failed_access_attempts: 3,
        metadata_completeness: 82,
        last_audit: "2025-03-17",
      },
    ],
  },
  {
    date: "2025-03-24",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 94,
        records_checked: 21502,
        duplicates_found: 46,
        compliance_status: "Non-Compliant",
        classified_datasets: 81,
        access_requests: 21,
        failed_access_attempts: 2,
        metadata_completeness: 87,
        last_audit: "2025-03-24",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 87,
        records_checked: 9280,
        duplicates_found: 11,
        compliance_status: "Non-Compliant",
        classified_datasets: 72,
        access_requests: 38,
        failed_access_attempts: 7,
        metadata_completeness: 75,
        last_audit: "2025-03-24",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 94,
        records_checked: 12486,
        duplicates_found: 33,
        compliance_status: "Compliant",
        classified_datasets: 84,
        access_requests: 56,
        failed_access_attempts: 7,
        metadata_completeness: 97,
        last_audit: "2025-03-24",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 82,
        records_checked: 9304,
        duplicates_found: 16,
        compliance_status: "Non-Compliant",
        classified_datasets: 89,
        access_requests: 51,
        failed_access_attempts: 1,
        metadata_completeness: 80,
        last_audit: "2025-03-24",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 83,
        records_checked: 11863,
        duplicates_found: 57,
        compliance_status: "Compliant",
        classified_datasets: 60,
        access_requests: 25,
        failed_access_attempts: 7,
        metadata_completeness: 96,
        last_audit: "2025-03-24",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 84,
        records_checked: 5255,
        duplicates_found: 41,
        compliance_status: "Compliant",
        classified_datasets: 69,
        access_requests: 46,
        failed_access_attempts: 5,
        metadata_completeness: 81,
        last_audit: "2025-03-24",
      },
    ],
  },
  {
    date: "2025-03-31",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 75,
        records_checked: 11003,
        duplicates_found: 50,
        compliance_status: "Compliant",
        classified_datasets: 50,
        access_requests: 39,
        failed_access_attempts: 7,
        metadata_completeness: 77,
        last_audit: "2025-03-31",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 90,
        records_checked: 17959,
        duplicates_found: 54,
        compliance_status: "Non-Compliant",
        classified_datasets: 74,
        access_requests: 30,
        failed_access_attempts: 1,
        metadata_completeness: 86,
        last_audit: "2025-03-31",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 95,
        records_checked: 14666,
        duplicates_found: 17,
        compliance_status: "Compliant",
        classified_datasets: 61,
        access_requests: 47,
        failed_access_attempts: 3,
        metadata_completeness: 83,
        last_audit: "2025-03-31",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 75,
        records_checked: 5385,
        duplicates_found: 12,
        compliance_status: "Compliant",
        classified_datasets: 53,
        access_requests: 40,
        failed_access_attempts: 5,
        metadata_completeness: 75,
        last_audit: "2025-03-31",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 94,
        records_checked: 6514,
        duplicates_found: 40,
        compliance_status: "Compliant",
        classified_datasets: 90,
        access_requests: 45,
        failed_access_attempts: 7,
        metadata_completeness: 76,
        last_audit: "2025-03-31",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 86,
        records_checked: 23934,
        duplicates_found: 39,
        compliance_status: "Non-Compliant",
        classified_datasets: 63,
        access_requests: 34,
        failed_access_attempts: 1,
        metadata_completeness: 74,
        last_audit: "2025-03-31",
      },
    ],
  },
  {
    date: "2025-04-07",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 79,
        records_checked: 23739,
        duplicates_found: 38,
        compliance_status: "Non-Compliant",
        classified_datasets: 85,
        access_requests: 50,
        failed_access_attempts: 5,
        metadata_completeness: 95,
        last_audit: "2025-04-07",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 83,
        records_checked: 15098,
        duplicates_found: 29,
        compliance_status: "Non-Compliant",
        classified_datasets: 70,
        access_requests: 59,
        failed_access_attempts: 2,
        metadata_completeness: 90,
        last_audit: "2025-04-07",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 85,
        records_checked: 15872,
        duplicates_found: 33,
        compliance_status: "Compliant",
        classified_datasets: 84,
        access_requests: 50,
        failed_access_attempts: 7,
        metadata_completeness: 80,
        last_audit: "2025-04-07",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 91,
        records_checked: 16702,
        duplicates_found: 12,
        compliance_status: "Compliant",
        classified_datasets: 88,
        access_requests: 25,
        failed_access_attempts: 3,
        metadata_completeness: 90,
        last_audit: "2025-04-07",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 93,
        records_checked: 24968,
        duplicates_found: 20,
        compliance_status: "Compliant",
        classified_datasets: 63,
        access_requests: 35,
        failed_access_attempts: 5,
        metadata_completeness: 90,
        last_audit: "2025-04-07",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 95,
        records_checked: 7612,
        duplicates_found: 13,
        compliance_status: "Compliant",
        classified_datasets: 85,
        access_requests: 25,
        failed_access_attempts: 5,
        metadata_completeness: 96,
        last_audit: "2025-04-07",
      },
    ],
  },
  {
    date: "2025-04-14",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 91,
        records_checked: 22590,
        duplicates_found: 34,
        compliance_status: "Non-Compliant",
        classified_datasets: 81,
        access_requests: 33,
        failed_access_attempts: 1,
        metadata_completeness: 92,
        last_audit: "2025-04-14",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 89,
        records_checked: 22626,
        duplicates_found: 55,
        compliance_status: "Non-Compliant",
        classified_datasets: 76,
        access_requests: 38,
        failed_access_attempts: 2,
        metadata_completeness: 82,
        last_audit: "2025-04-14",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 75,
        records_checked: 17463,
        duplicates_found: 10,
        compliance_status: "Compliant",
        classified_datasets: 74,
        access_requests: 55,
        failed_access_attempts: 1,
        metadata_completeness: 75,
        last_audit: "2025-04-14",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 86,
        records_checked: 13293,
        duplicates_found: 50,
        compliance_status: "Compliant",
        classified_datasets: 63,
        access_requests: 54,
        failed_access_attempts: 1,
        metadata_completeness: 88,
        last_audit: "2025-04-14",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 91,
        records_checked: 5564,
        duplicates_found: 14,
        compliance_status: "Non-Compliant",
        classified_datasets: 68,
        access_requests: 46,
        failed_access_attempts: 4,
        metadata_completeness: 88,
        last_audit: "2025-04-14",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 88,
        records_checked: 20412,
        duplicates_found: 31,
        compliance_status: "Compliant",
        classified_datasets: 74,
        access_requests: 53,
        failed_access_attempts: 6,
        metadata_completeness: 75,
        last_audit: "2025-04-14",
      },
    ],
  },
  {
    date: "2025-04-21",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 77,
        records_checked: 19056,
        duplicates_found: 49,
        compliance_status: "Compliant",
        classified_datasets: 90,
        access_requests: 49,
        failed_access_attempts: 2,
        metadata_completeness: 93,
        last_audit: "2025-04-21",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 93,
        records_checked: 22165,
        duplicates_found: 13,
        compliance_status: "Compliant",
        classified_datasets: 78,
        access_requests: 39,
        failed_access_attempts: 4,
        metadata_completeness: 84,
        last_audit: "2025-04-21",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 81,
        records_checked: 24077,
        duplicates_found: 30,
        compliance_status: "Non-Compliant",
        classified_datasets: 77,
        access_requests: 41,
        failed_access_attempts: 1,
        metadata_completeness: 83,
        last_audit: "2025-04-21",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 92,
        records_checked: 8099,
        duplicates_found: 25,
        compliance_status: "Non-Compliant",
        classified_datasets: 63,
        access_requests: 27,
        failed_access_attempts: 1,
        metadata_completeness: 77,
        last_audit: "2025-04-21",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 88,
        records_checked: 8475,
        duplicates_found: 42,
        compliance_status: "Non-Compliant",
        classified_datasets: 72,
        access_requests: 48,
        failed_access_attempts: 4,
        metadata_completeness: 91,
        last_audit: "2025-04-21",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 88,
        records_checked: 9679,
        duplicates_found: 46,
        compliance_status: "Non-Compliant",
        classified_datasets: 73,
        access_requests: 45,
        failed_access_attempts: 6,
        metadata_completeness: 79,
        last_audit: "2025-04-21",
      },
    ],
  },
  {
    date: "2025-04-28",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 84,
        records_checked: 5449,
        duplicates_found: 53,
        compliance_status: "Non-Compliant",
        classified_datasets: 85,
        access_requests: 30,
        failed_access_attempts: 1,
        metadata_completeness: 79,
        last_audit: "2025-04-28",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 92,
        records_checked: 23109,
        duplicates_found: 27,
        compliance_status: "Compliant",
        classified_datasets: 66,
        access_requests: 31,
        failed_access_attempts: 1,
        metadata_completeness: 81,
        last_audit: "2025-04-28",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 83,
        records_checked: 5989,
        duplicates_found: 35,
        compliance_status: "Compliant",
        classified_datasets: 54,
        access_requests: 60,
        failed_access_attempts: 1,
        metadata_completeness: 90,
        last_audit: "2025-04-28",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 91,
        records_checked: 15759,
        duplicates_found: 56,
        compliance_status: "Compliant",
        classified_datasets: 63,
        access_requests: 36,
        failed_access_attempts: 3,
        metadata_completeness: 96,
        last_audit: "2025-04-28",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 92,
        records_checked: 23701,
        duplicates_found: 10,
        compliance_status: "Compliant",
        classified_datasets: 60,
        access_requests: 58,
        failed_access_attempts: 1,
        metadata_completeness: 80,
        last_audit: "2025-04-28",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 84,
        records_checked: 15810,
        duplicates_found: 57,
        compliance_status: "Non-Compliant",
        classified_datasets: 59,
        access_requests: 52,
        failed_access_attempts: 6,
        metadata_completeness: 97,
        last_audit: "2025-04-28",
      },
    ],
  },
  {
    date: "2025-05-05",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 78,
        records_checked: 7680,
        duplicates_found: 17,
        compliance_status: "Compliant",
        classified_datasets: 69,
        access_requests: 31,
        failed_access_attempts: 4,
        metadata_completeness: 95,
        last_audit: "2025-05-05",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 91,
        records_checked: 11581,
        duplicates_found: 32,
        compliance_status: "Non-Compliant",
        classified_datasets: 83,
        access_requests: 59,
        failed_access_attempts: 3,
        metadata_completeness: 89,
        last_audit: "2025-05-05",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 93,
        records_checked: 15613,
        duplicates_found: 42,
        compliance_status: "Non-Compliant",
        classified_datasets: 62,
        access_requests: 37,
        failed_access_attempts: 1,
        metadata_completeness: 92,
        last_audit: "2025-05-05",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 89,
        records_checked: 12829,
        duplicates_found: 59,
        compliance_status: "Non-Compliant",
        classified_datasets: 80,
        access_requests: 40,
        failed_access_attempts: 3,
        metadata_completeness: 82,
        last_audit: "2025-05-05",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 92,
        records_checked: 19667,
        duplicates_found: 25,
        compliance_status: "Compliant",
        classified_datasets: 83,
        access_requests: 28,
        failed_access_attempts: 4,
        metadata_completeness: 84,
        last_audit: "2025-05-05",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 77,
        records_checked: 5780,
        duplicates_found: 20,
        compliance_status: "Compliant",
        classified_datasets: 86,
        access_requests: 56,
        failed_access_attempts: 5,
        metadata_completeness: 80,
        last_audit: "2025-05-05",
      },
    ],
  },
  {
    date: "2025-05-12",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 88,
        records_checked: 13333,
        duplicates_found: 28,
        compliance_status: "Non-Compliant",
        classified_datasets: 80,
        access_requests: 38,
        failed_access_attempts: 6,
        metadata_completeness: 80,
        last_audit: "2025-05-12",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 80,
        records_checked: 4580,
        duplicates_found: 47,
        compliance_status: "Compliant",
        classified_datasets: 50,
        access_requests: 25,
        failed_access_attempts: 2,
        metadata_completeness: 73,
        last_audit: "2025-05-12",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 87,
        records_checked: 21393,
        duplicates_found: 43,
        compliance_status: "Compliant",
        classified_datasets: 59,
        access_requests: 33,
        failed_access_attempts: 4,
        metadata_completeness: 93,
        last_audit: "2025-05-12",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 93,
        records_checked: 6203,
        duplicates_found: 51,
        compliance_status: "Non-Compliant",
        classified_datasets: 66,
        access_requests: 41,
        failed_access_attempts: 2,
        metadata_completeness: 82,
        last_audit: "2025-05-12",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 87,
        records_checked: 5975,
        duplicates_found: 30,
        compliance_status: "Compliant",
        classified_datasets: 85,
        access_requests: 30,
        failed_access_attempts: 2,
        metadata_completeness: 76,
        last_audit: "2025-05-12",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 92,
        records_checked: 16089,
        duplicates_found: 39,
        compliance_status: "Non-Compliant",
        classified_datasets: 57,
        access_requests: 40,
        failed_access_attempts: 1,
        metadata_completeness: 85,
        last_audit: "2025-05-12",
      },
    ],
  },
  {
    date: "2025-05-19",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 75,
        records_checked: 13446,
        duplicates_found: 48,
        compliance_status: "Non-Compliant",
        classified_datasets: 68,
        access_requests: 44,
        failed_access_attempts: 4,
        metadata_completeness: 76,
        last_audit: "2025-05-19",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 85,
        records_checked: 19804,
        duplicates_found: 14,
        compliance_status: "Compliant",
        classified_datasets: 56,
        access_requests: 20,
        failed_access_attempts: 2,
        metadata_completeness: 87,
        last_audit: "2025-05-19",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 79,
        records_checked: 17699,
        duplicates_found: 12,
        compliance_status: "Non-Compliant",
        classified_datasets: 80,
        access_requests: 45,
        failed_access_attempts: 2,
        metadata_completeness: 74,
        last_audit: "2025-05-19",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 88,
        records_checked: 8019,
        duplicates_found: 18,
        compliance_status: "Non-Compliant",
        classified_datasets: 69,
        access_requests: 30,
        failed_access_attempts: 1,
        metadata_completeness: 73,
        last_audit: "2025-05-19",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 88,
        records_checked: 6193,
        duplicates_found: 49,
        compliance_status: "Non-Compliant",
        classified_datasets: 89,
        access_requests: 43,
        failed_access_attempts: 1,
        metadata_completeness: 75,
        last_audit: "2025-05-19",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 79,
        records_checked: 4705,
        duplicates_found: 60,
        compliance_status: "Non-Compliant",
        classified_datasets: 75,
        access_requests: 44,
        failed_access_attempts: 1,
        metadata_completeness: 93,
        last_audit: "2025-05-19",
      },
    ],
  },
  {
    date: "2025-05-26",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 84,
        records_checked: 20063,
        duplicates_found: 26,
        compliance_status: "Compliant",
        classified_datasets: 88,
        access_requests: 48,
        failed_access_attempts: 4,
        metadata_completeness: 89,
        last_audit: "2025-05-26",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 91,
        records_checked: 18848,
        duplicates_found: 40,
        compliance_status: "Non-Compliant",
        classified_datasets: 56,
        access_requests: 58,
        failed_access_attempts: 7,
        metadata_completeness: 96,
        last_audit: "2025-05-26",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 75,
        records_checked: 20790,
        duplicates_found: 41,
        compliance_status: "Compliant",
        classified_datasets: 71,
        access_requests: 22,
        failed_access_attempts: 1,
        metadata_completeness: 73,
        last_audit: "2025-05-26",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 84,
        records_checked: 24071,
        duplicates_found: 47,
        compliance_status: "Compliant",
        classified_datasets: 64,
        access_requests: 29,
        failed_access_attempts: 5,
        metadata_completeness: 96,
        last_audit: "2025-05-26",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 82,
        records_checked: 13891,
        duplicates_found: 48,
        compliance_status: "Non-Compliant",
        classified_datasets: 56,
        access_requests: 52,
        failed_access_attempts: 4,
        metadata_completeness: 81,
        last_audit: "2025-05-26",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 79,
        records_checked: 13689,
        duplicates_found: 47,
        compliance_status: "Non-Compliant",
        classified_datasets: 60,
        access_requests: 49,
        failed_access_attempts: 2,
        metadata_completeness: 88,
        last_audit: "2025-05-26",
      },
    ],
  },
  {
    date: "2025-06-02",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 92,
        records_checked: 8350,
        duplicates_found: 15,
        compliance_status: "Compliant",
        classified_datasets: 67,
        access_requests: 23,
        failed_access_attempts: 7,
        metadata_completeness: 88,
        last_audit: "2025-06-02",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 79,
        records_checked: 14784,
        duplicates_found: 19,
        compliance_status: "Non-Compliant",
        classified_datasets: 67,
        access_requests: 32,
        failed_access_attempts: 6,
        metadata_completeness: 89,
        last_audit: "2025-06-02",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 77,
        records_checked: 19491,
        duplicates_found: 51,
        compliance_status: "Non-Compliant",
        classified_datasets: 63,
        access_requests: 55,
        failed_access_attempts: 4,
        metadata_completeness: 86,
        last_audit: "2025-06-02",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 86,
        records_checked: 6990,
        duplicates_found: 43,
        compliance_status: "Non-Compliant",
        classified_datasets: 69,
        access_requests: 27,
        failed_access_attempts: 3,
        metadata_completeness: 89,
        last_audit: "2025-06-02",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 76,
        records_checked: 23244,
        duplicates_found: 51,
        compliance_status: "Non-Compliant",
        classified_datasets: 78,
        access_requests: 30,
        failed_access_attempts: 6,
        metadata_completeness: 73,
        last_audit: "2025-06-02",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 95,
        records_checked: 20236,
        duplicates_found: 33,
        compliance_status: "Non-Compliant",
        classified_datasets: 61,
        access_requests: 40,
        failed_access_attempts: 6,
        metadata_completeness: 82,
        last_audit: "2025-06-02",
      },
    ],
  },
  {
    date: "2025-06-09",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 95,
        records_checked: 11305,
        duplicates_found: 11,
        compliance_status: "Compliant",
        classified_datasets: 84,
        access_requests: 25,
        failed_access_attempts: 3,
        metadata_completeness: 77,
        last_audit: "2025-06-09",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 85,
        records_checked: 21394,
        duplicates_found: 34,
        compliance_status: "Non-Compliant",
        classified_datasets: 65,
        access_requests: 41,
        failed_access_attempts: 6,
        metadata_completeness: 88,
        last_audit: "2025-06-09",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 76,
        records_checked: 13400,
        duplicates_found: 46,
        compliance_status: "Non-Compliant",
        classified_datasets: 61,
        access_requests: 54,
        failed_access_attempts: 2,
        metadata_completeness: 80,
        last_audit: "2025-06-09",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 86,
        records_checked: 5864,
        duplicates_found: 52,
        compliance_status: "Non-Compliant",
        classified_datasets: 65,
        access_requests: 24,
        failed_access_attempts: 1,
        metadata_completeness: 94,
        last_audit: "2025-06-09",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 87,
        records_checked: 21777,
        duplicates_found: 20,
        compliance_status: "Compliant",
        classified_datasets: 63,
        access_requests: 45,
        failed_access_attempts: 7,
        metadata_completeness: 78,
        last_audit: "2025-06-09",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 79,
        records_checked: 19869,
        duplicates_found: 23,
        compliance_status: "Compliant",
        classified_datasets: 86,
        access_requests: 51,
        failed_access_attempts: 2,
        metadata_completeness: 76,
        last_audit: "2025-06-09",
      },
    ],
  },
  {
    date: "2025-06-16",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 84,
        records_checked: 14040,
        duplicates_found: 47,
        compliance_status: "Non-Compliant",
        classified_datasets: 85,
        access_requests: 33,
        failed_access_attempts: 1,
        metadata_completeness: 94,
        last_audit: "2025-06-16",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 75,
        records_checked: 20821,
        duplicates_found: 38,
        compliance_status: "Non-Compliant",
        classified_datasets: 67,
        access_requests: 50,
        failed_access_attempts: 6,
        metadata_completeness: 76,
        last_audit: "2025-06-16",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 82,
        records_checked: 11994,
        duplicates_found: 25,
        compliance_status: "Non-Compliant",
        classified_datasets: 79,
        access_requests: 31,
        failed_access_attempts: 7,
        metadata_completeness: 80,
        last_audit: "2025-06-16",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 88,
        records_checked: 7847,
        duplicates_found: 34,
        compliance_status: "Non-Compliant",
        classified_datasets: 58,
        access_requests: 34,
        failed_access_attempts: 7,
        metadata_completeness: 88,
        last_audit: "2025-06-16",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 82,
        records_checked: 14604,
        duplicates_found: 54,
        compliance_status: "Non-Compliant",
        classified_datasets: 88,
        access_requests: 39,
        failed_access_attempts: 4,
        metadata_completeness: 84,
        last_audit: "2025-06-16",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 94,
        records_checked: 17974,
        duplicates_found: 42,
        compliance_status: "Compliant",
        classified_datasets: 60,
        access_requests: 58,
        failed_access_attempts: 1,
        metadata_completeness: 74,
        last_audit: "2025-06-16",
      },
    ],
  },
  {
    date: "2025-06-23",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 81,
        records_checked: 18851,
        duplicates_found: 15,
        compliance_status: "Non-Compliant",
        classified_datasets: 66,
        access_requests: 53,
        failed_access_attempts: 6,
        metadata_completeness: 74,
        last_audit: "2025-06-23",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 84,
        records_checked: 13137,
        duplicates_found: 17,
        compliance_status: "Compliant",
        classified_datasets: 88,
        access_requests: 51,
        failed_access_attempts: 5,
        metadata_completeness: 85,
        last_audit: "2025-06-23",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 79,
        records_checked: 8733,
        duplicates_found: 25,
        compliance_status: "Non-Compliant",
        classified_datasets: 62,
        access_requests: 40,
        failed_access_attempts: 6,
        metadata_completeness: 85,
        last_audit: "2025-06-23",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 92,
        records_checked: 9772,
        duplicates_found: 35,
        compliance_status: "Compliant",
        classified_datasets: 52,
        access_requests: 26,
        failed_access_attempts: 1,
        metadata_completeness: 79,
        last_audit: "2025-06-23",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 84,
        records_checked: 18261,
        duplicates_found: 54,
        compliance_status: "Compliant",
        classified_datasets: 88,
        access_requests: 42,
        failed_access_attempts: 3,
        metadata_completeness: 85,
        last_audit: "2025-06-23",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 86,
        records_checked: 12332,
        duplicates_found: 43,
        compliance_status: "Non-Compliant",
        classified_datasets: 70,
        access_requests: 43,
        failed_access_attempts: 4,
        metadata_completeness: 82,
        last_audit: "2025-06-23",
      },
    ],
  },
  {
    date: "2025-06-30",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 88,
        records_checked: 22451,
        duplicates_found: 44,
        compliance_status: "Non-Compliant",
        classified_datasets: 87,
        access_requests: 29,
        failed_access_attempts: 1,
        metadata_completeness: 94,
        last_audit: "2025-06-30",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 81,
        records_checked: 14747,
        duplicates_found: 41,
        compliance_status: "Compliant",
        classified_datasets: 88,
        access_requests: 52,
        failed_access_attempts: 3,
        metadata_completeness: 77,
        last_audit: "2025-06-30",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 88,
        records_checked: 21234,
        duplicates_found: 16,
        compliance_status: "Compliant",
        classified_datasets: 53,
        access_requests: 21,
        failed_access_attempts: 3,
        metadata_completeness: 94,
        last_audit: "2025-06-30",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 93,
        records_checked: 15272,
        duplicates_found: 40,
        compliance_status: "Non-Compliant",
        classified_datasets: 81,
        access_requests: 25,
        failed_access_attempts: 1,
        metadata_completeness: 78,
        last_audit: "2025-06-30",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 79,
        records_checked: 11888,
        duplicates_found: 60,
        compliance_status: "Compliant",
        classified_datasets: 68,
        access_requests: 22,
        failed_access_attempts: 3,
        metadata_completeness: 74,
        last_audit: "2025-06-30",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 87,
        records_checked: 7346,
        duplicates_found: 57,
        compliance_status: "Compliant",
        classified_datasets: 87,
        access_requests: 30,
        failed_access_attempts: 5,
        metadata_completeness: 95,
        last_audit: "2025-06-30",
      },
    ],
  },
  {
    date: "2025-07-07",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 91,
        records_checked: 14742,
        duplicates_found: 59,
        compliance_status: "Non-Compliant",
        classified_datasets: 81,
        access_requests: 33,
        failed_access_attempts: 6,
        metadata_completeness: 97,
        last_audit: "2025-07-07",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 90,
        records_checked: 5447,
        duplicates_found: 23,
        compliance_status: "Non-Compliant",
        classified_datasets: 84,
        access_requests: 34,
        failed_access_attempts: 5,
        metadata_completeness: 97,
        last_audit: "2025-07-07",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 86,
        records_checked: 20923,
        duplicates_found: 60,
        compliance_status: "Non-Compliant",
        classified_datasets: 73,
        access_requests: 30,
        failed_access_attempts: 3,
        metadata_completeness: 79,
        last_audit: "2025-07-07",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 94,
        records_checked: 17625,
        duplicates_found: 24,
        compliance_status: "Non-Compliant",
        classified_datasets: 90,
        access_requests: 26,
        failed_access_attempts: 5,
        metadata_completeness: 89,
        last_audit: "2025-07-07",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 92,
        records_checked: 22511,
        duplicates_found: 35,
        compliance_status: "Compliant",
        classified_datasets: 56,
        access_requests: 36,
        failed_access_attempts: 4,
        metadata_completeness: 83,
        last_audit: "2025-07-07",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 95,
        records_checked: 16870,
        duplicates_found: 58,
        compliance_status: "Compliant",
        classified_datasets: 56,
        access_requests: 23,
        failed_access_attempts: 5,
        metadata_completeness: 81,
        last_audit: "2025-07-07",
      },
    ],
  },
  {
    date: "2025-07-14",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 90,
        records_checked: 16273,
        duplicates_found: 57,
        compliance_status: "Compliant",
        classified_datasets: 69,
        access_requests: 43,
        failed_access_attempts: 1,
        metadata_completeness: 81,
        last_audit: "2025-07-14",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 78,
        records_checked: 24188,
        duplicates_found: 35,
        compliance_status: "Non-Compliant",
        classified_datasets: 90,
        access_requests: 48,
        failed_access_attempts: 4,
        metadata_completeness: 77,
        last_audit: "2025-07-14",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 90,
        records_checked: 10915,
        duplicates_found: 60,
        compliance_status: "Non-Compliant",
        classified_datasets: 56,
        access_requests: 41,
        failed_access_attempts: 5,
        metadata_completeness: 94,
        last_audit: "2025-07-14",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 90,
        records_checked: 9171,
        duplicates_found: 19,
        compliance_status: "Non-Compliant",
        classified_datasets: 56,
        access_requests: 60,
        failed_access_attempts: 6,
        metadata_completeness: 88,
        last_audit: "2025-07-14",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 80,
        records_checked: 14389,
        duplicates_found: 50,
        compliance_status: "Compliant",
        classified_datasets: 66,
        access_requests: 39,
        failed_access_attempts: 2,
        metadata_completeness: 94,
        last_audit: "2025-07-14",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 81,
        records_checked: 15448,
        duplicates_found: 21,
        compliance_status: "Non-Compliant",
        classified_datasets: 70,
        access_requests: 25,
        failed_access_attempts: 4,
        metadata_completeness: 96,
        last_audit: "2025-07-14",
      },
    ],
  },
  {
    date: "2025-07-21",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 93,
        records_checked: 6840,
        duplicates_found: 58,
        compliance_status: "Non-Compliant",
        classified_datasets: 88,
        access_requests: 20,
        failed_access_attempts: 1,
        metadata_completeness: 74,
        last_audit: "2025-07-21",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 90,
        records_checked: 24619,
        duplicates_found: 29,
        compliance_status: "Compliant",
        classified_datasets: 67,
        access_requests: 43,
        failed_access_attempts: 2,
        metadata_completeness: 88,
        last_audit: "2025-07-21",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 80,
        records_checked: 19839,
        duplicates_found: 20,
        compliance_status: "Non-Compliant",
        classified_datasets: 74,
        access_requests: 26,
        failed_access_attempts: 3,
        metadata_completeness: 77,
        last_audit: "2025-07-21",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 93,
        records_checked: 15742,
        duplicates_found: 12,
        compliance_status: "Non-Compliant",
        classified_datasets: 57,
        access_requests: 26,
        failed_access_attempts: 2,
        metadata_completeness: 88,
        last_audit: "2025-07-21",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 85,
        records_checked: 17347,
        duplicates_found: 17,
        compliance_status: "Non-Compliant",
        classified_datasets: 87,
        access_requests: 31,
        failed_access_attempts: 4,
        metadata_completeness: 87,
        last_audit: "2025-07-21",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 75,
        records_checked: 16963,
        duplicates_found: 52,
        compliance_status: "Compliant",
        classified_datasets: 85,
        access_requests: 34,
        failed_access_attempts: 4,
        metadata_completeness: 92,
        last_audit: "2025-07-21",
      },
    ],
  },
  {
    date: "2025-07-28",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 95,
        records_checked: 16242,
        duplicates_found: 17,
        compliance_status: "Non-Compliant",
        classified_datasets: 87,
        access_requests: 46,
        failed_access_attempts: 1,
        metadata_completeness: 74,
        last_audit: "2025-07-28",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 82,
        records_checked: 14614,
        duplicates_found: 40,
        compliance_status: "Compliant",
        classified_datasets: 81,
        access_requests: 31,
        failed_access_attempts: 5,
        metadata_completeness: 75,
        last_audit: "2025-07-28",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 82,
        records_checked: 16205,
        duplicates_found: 29,
        compliance_status: "Compliant",
        classified_datasets: 58,
        access_requests: 26,
        failed_access_attempts: 7,
        metadata_completeness: 93,
        last_audit: "2025-07-28",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 88,
        records_checked: 5727,
        duplicates_found: 14,
        compliance_status: "Non-Compliant",
        classified_datasets: 86,
        access_requests: 52,
        failed_access_attempts: 6,
        metadata_completeness: 77,
        last_audit: "2025-07-28",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 81,
        records_checked: 9597,
        duplicates_found: 60,
        compliance_status: "Compliant",
        classified_datasets: 64,
        access_requests: 45,
        failed_access_attempts: 5,
        metadata_completeness: 91,
        last_audit: "2025-07-28",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 82,
        records_checked: 6422,
        duplicates_found: 37,
        compliance_status: "Compliant",
        classified_datasets: 56,
        access_requests: 38,
        failed_access_attempts: 5,
        metadata_completeness: 85,
        last_audit: "2025-07-28",
      },
    ],
  },
  {
    date: "2025-08-04",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 91,
        records_checked: 7895,
        duplicates_found: 59,
        compliance_status: "Non-Compliant",
        classified_datasets: 79,
        access_requests: 43,
        failed_access_attempts: 2,
        metadata_completeness: 88,
        last_audit: "2025-08-04",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 95,
        records_checked: 16410,
        duplicates_found: 50,
        compliance_status: "Non-Compliant",
        classified_datasets: 81,
        access_requests: 40,
        failed_access_attempts: 1,
        metadata_completeness: 87,
        last_audit: "2025-08-04",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 77,
        records_checked: 11230,
        duplicates_found: 51,
        compliance_status: "Non-Compliant",
        classified_datasets: 83,
        access_requests: 20,
        failed_access_attempts: 2,
        metadata_completeness: 81,
        last_audit: "2025-08-04",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 83,
        records_checked: 14246,
        duplicates_found: 33,
        compliance_status: "Non-Compliant",
        classified_datasets: 68,
        access_requests: 60,
        failed_access_attempts: 3,
        metadata_completeness: 92,
        last_audit: "2025-08-04",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 91,
        records_checked: 19683,
        duplicates_found: 27,
        compliance_status: "Non-Compliant",
        classified_datasets: 88,
        access_requests: 21,
        failed_access_attempts: 2,
        metadata_completeness: 91,
        last_audit: "2025-08-04",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 95,
        records_checked: 13941,
        duplicates_found: 36,
        compliance_status: "Compliant",
        classified_datasets: 57,
        access_requests: 53,
        failed_access_attempts: 7,
        metadata_completeness: 82,
        last_audit: "2025-08-04",
      },
    ],
  },
  {
    date: "2025-08-11",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 91,
        records_checked: 4161,
        duplicates_found: 59,
        compliance_status: "Compliant",
        classified_datasets: 87,
        access_requests: 58,
        failed_access_attempts: 6,
        metadata_completeness: 87,
        last_audit: "2025-08-11",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 76,
        records_checked: 20979,
        duplicates_found: 55,
        compliance_status: "Compliant",
        classified_datasets: 68,
        access_requests: 29,
        failed_access_attempts: 2,
        metadata_completeness: 96,
        last_audit: "2025-08-11",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 92,
        records_checked: 10103,
        duplicates_found: 57,
        compliance_status: "Non-Compliant",
        classified_datasets: 52,
        access_requests: 26,
        failed_access_attempts: 4,
        metadata_completeness: 77,
        last_audit: "2025-08-11",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 80,
        records_checked: 10722,
        duplicates_found: 38,
        compliance_status: "Compliant",
        classified_datasets: 62,
        access_requests: 41,
        failed_access_attempts: 6,
        metadata_completeness: 81,
        last_audit: "2025-08-11",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 92,
        records_checked: 14644,
        duplicates_found: 19,
        compliance_status: "Non-Compliant",
        classified_datasets: 88,
        access_requests: 34,
        failed_access_attempts: 6,
        metadata_completeness: 90,
        last_audit: "2025-08-11",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 89,
        records_checked: 13132,
        duplicates_found: 14,
        compliance_status: "Non-Compliant",
        classified_datasets: 50,
        access_requests: 22,
        failed_access_attempts: 5,
        metadata_completeness: 75,
        last_audit: "2025-08-11",
      },
    ],
  },
  {
    date: "2025-08-18",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 79,
        records_checked: 12693,
        duplicates_found: 38,
        compliance_status: "Non-Compliant",
        classified_datasets: 76,
        access_requests: 54,
        failed_access_attempts: 7,
        metadata_completeness: 82,
        last_audit: "2025-08-18",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 79,
        records_checked: 22518,
        duplicates_found: 12,
        compliance_status: "Compliant",
        classified_datasets: 54,
        access_requests: 41,
        failed_access_attempts: 6,
        metadata_completeness: 76,
        last_audit: "2025-08-18",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 85,
        records_checked: 12694,
        duplicates_found: 26,
        compliance_status: "Compliant",
        classified_datasets: 86,
        access_requests: 50,
        failed_access_attempts: 7,
        metadata_completeness: 80,
        last_audit: "2025-08-18",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 84,
        records_checked: 4920,
        duplicates_found: 58,
        compliance_status: "Non-Compliant",
        classified_datasets: 77,
        access_requests: 28,
        failed_access_attempts: 5,
        metadata_completeness: 78,
        last_audit: "2025-08-18",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 84,
        records_checked: 20350,
        duplicates_found: 35,
        compliance_status: "Compliant",
        classified_datasets: 75,
        access_requests: 29,
        failed_access_attempts: 1,
        metadata_completeness: 96,
        last_audit: "2025-08-18",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 93,
        records_checked: 13581,
        duplicates_found: 28,
        compliance_status: "Compliant",
        classified_datasets: 61,
        access_requests: 38,
        failed_access_attempts: 5,
        metadata_completeness: 92,
        last_audit: "2025-08-18",
      },
    ],
  },
  {
    date: "2025-08-25",
    departments: [
      {
        department: "Finance",
        system: "ERP",
        data_quality_score: 86,
        records_checked: 5090,
        duplicates_found: 60,
        compliance_status: "Non-Compliant",
        classified_datasets: 55,
        access_requests: 25,
        failed_access_attempts: 4,
        metadata_completeness: 90,
        last_audit: "2025-08-25",
      },
      {
        department: "Sales and Marketing",
        system: "CRM",
        data_quality_score: 94,
        records_checked: 9707,
        duplicates_found: 52,
        compliance_status: "Compliant",
        classified_datasets: 71,
        access_requests: 52,
        failed_access_attempts: 4,
        metadata_completeness: 73,
        last_audit: "2025-08-25",
      },
      {
        department: "Editorial",
        system: "ContentDB",
        data_quality_score: 84,
        records_checked: 6441,
        duplicates_found: 39,
        compliance_status: "Compliant",
        classified_datasets: 79,
        access_requests: 25,
        failed_access_attempts: 1,
        metadata_completeness: 84,
        last_audit: "2025-08-25",
      },
      {
        department: "IT",
        system: "ITAssets",
        data_quality_score: 76,
        records_checked: 21276,
        duplicates_found: 28,
        compliance_status: "Compliant",
        classified_datasets: 59,
        access_requests: 27,
        failed_access_attempts: 6,
        metadata_completeness: 91,
        last_audit: "2025-08-25",
      },
      {
        department: "Production",
        system: "ManufacturingDB",
        data_quality_score: 89,
        records_checked: 21902,
        duplicates_found: 56,
        compliance_status: "Compliant",
        classified_datasets: 64,
        access_requests: 55,
        failed_access_attempts: 4,
        metadata_completeness: 78,
        last_audit: "2025-08-25",
      },
      {
        department: "Admin",
        system: "AdminPortal",
        data_quality_score: 78,
        records_checked: 10447,
        duplicates_found: 16,
        compliance_status: "Compliant",
        classified_datasets: 70,
        access_requests: 49,
        failed_access_attempts: 1,
        metadata_completeness: 96,
        last_audit: "2025-08-25",
      },
    ],
  },
];

export default reports;
