export const data = [
  {
    task_id: 1,
    task_name: "Content Upload",
    task_type: "Testing",
    assignee: "Alice Johnson",
    date_assigned: "2025-02-10",
    date_completed: null,
    expected_end_date: "2025-02-20",
    task_status: "On Hold",
  },
  {
    task_id: 2,
    task_name: "Bug Fixing",
    task_type: "Testing",
    assignee: "Fiona Adams",
    date_assigned: "2025-01-21",
    date_completed: null,
    expected_end_date: "2025-01-30",
    task_status: "In Progress",
  },
  {
    task_id: 3,
    task_name: "System Upgrade",
    task_type: "Testing",
    assignee: "Alice Johnson",
    date_assigned: "2025-07-12",
    date_completed: "2025-07-17",
    expected_end_date: "2025-07-20",
    task_status: "On Hold",
  },
  {
    task_id: 4,
    task_name: "UI Redesign",
    task_type: "Design",
    assignee: "Bob Smith",
    date_assigned: "2025-02-10",
    date_completed: null,
    expected_end_date: "2025-02-20",
    task_status: "Completed",
  },
  {
    task_id: 5,
    task_name: "Bug Fixing",
    task_type: "Testing",
    assignee: "Ethan Clark",
    date_assigned: "2025-06-02",
    date_completed: null,
    expected_end_date: "2025-06-07",
    task_status: "Pending",
  },
  {
    task_id: 6,
    task_name: "SEO Optimization",
    task_type: "Design",
    assignee: "Diana Rose",
    date_assigned: "2025-06-30",
    date_completed: "2025-07-04",
    expected_end_date: "2025-07-13",
    task_status: "Pending",
  },
  {
    task_id: 7,
    task_name: "System Upgrade",
    task_type: "Audit",
    assignee: "Charlie Green",
    date_assigned: "2025-03-10",
    date_completed: null,
    expected_end_date: "2025-03-25",
    task_status: "Completed",
  },
  {
    task_id: 8,
    task_name: "Security Audit",
    task_type: "Audit",
    assignee: "George White",
    date_assigned: "2025-06-01",
    date_completed: "2025-06-06",
    expected_end_date: "2025-06-13",
    task_status: "On Hold",
  },
  {
    task_id: 9,
    task_name: "Security Audit",
    task_type: "Deployment",
    assignee: "Fiona Adams",
    date_assigned: "2025-08-05",
    date_completed: null,
    expected_end_date: "2025-08-12",
    task_status: "Completed",
  },
  {
    task_id: 10,
    task_name: "Security Audit",
    task_type: "Testing",
    assignee: "Diana Rose",
    date_assigned: "2025-03-03",
    date_completed: "2025-03-07",
    expected_end_date: "2025-03-11",
    task_status: "In Progress",
  },
  {
    task_id: 11,
    task_name: "Performance Testing",
    task_type: "Deployment",
    assignee: "Hannah Brown",
    date_assigned: "2025-05-13",
    date_completed: null,
    expected_end_date: "2025-05-22",
    task_status: "Pending",
  },
  {
    task_id: 12,
    task_name: "Bug Fixing",
    task_type: "Design",
    assignee: "Bob Smith",
    date_assigned: "2025-07-25",
    date_completed: null,
    expected_end_date: "2025-08-01",
    task_status: "Completed",
  },
  {
    task_id: 13,
    task_name: "SEO Optimization",
    task_type: "Deployment",
    assignee: "Alice Johnson",
    date_assigned: "2025-02-16",
    date_completed: null,
    expected_end_date: "2025-02-23",
    task_status: "On Hold",
  },
  {
    task_id: 14,
    task_name: "Bug Fixing",
    task_type: "Testing",
    assignee: "Fiona Adams",
    date_assigned: "2025-02-21",
    date_completed: "2025-03-02",
    expected_end_date: "2025-02-27",
    task_status: "Pending",
  },
  {
    task_id: 15,
    task_name: "Code Review",
    task_type: "Testing",
    assignee: "Hannah Brown",
    date_assigned: "2025-06-09",
    date_completed: "2025-06-17",
    expected_end_date: "2025-06-23",
    task_status: "On Hold",
  },
  {
    task_id: 16,
    task_name: "Database Backup",
    task_type: "Development",
    assignee: "Ethan Clark",
    date_assigned: "2025-03-15",
    date_completed: "2025-03-16",
    expected_end_date: "2025-03-21",
    task_status: "In Progress",
  },
  {
    task_id: 17,
    task_name: "Performance Testing",
    task_type: "Development",
    assignee: "George White",
    date_assigned: "2025-03-04",
    date_completed: "2025-03-14",
    expected_end_date: "2025-03-09",
    task_status: "Pending",
  },
  {
    task_id: 18,
    task_name: "Code Review",
    task_type: "Design",
    assignee: "Hannah Brown",
    date_assigned: "2025-04-30",
    date_completed: "2025-05-08",
    expected_end_date: "2025-05-13",
    task_status: "Pending",
  },
  {
    task_id: 19,
    task_name: "System Upgrade",
    task_type: "Maintenance",
    assignee: "Alice Johnson",
    date_assigned: "2025-07-07",
    date_completed: "2025-07-13",
    expected_end_date: "2025-07-13",
    task_status: "Completed",
  },
  {
    task_id: 20,
    task_name: "System Upgrade",
    task_type: "Design",
    assignee: "Diana Rose",
    date_assigned: "2025-03-10",
    date_completed: "2025-03-18",
    expected_end_date: "2025-03-16",
    task_status: "In Progress",
  },
  {
    task_id: 21,
    task_name: "API Integration",
    task_type: "Development",
    assignee: "Alice Johnson",
    date_assigned: "2025-02-28",
    date_completed: null,
    expected_end_date: "2025-03-14",
    task_status: "Completed",
  },
  {
    task_id: 22,
    task_name: "System Upgrade",
    task_type: "Deployment",
    assignee: "Fiona Adams",
    date_assigned: "2025-08-09",
    date_completed: "2025-08-10",
    expected_end_date: "2025-08-12",
    task_status: "In Progress",
  },
  {
    task_id: 23,
    task_name: "UI Redesign",
    task_type: "Audit",
    assignee: "Bob Smith",
    date_assigned: "2025-01-04",
    date_completed: null,
    expected_end_date: "2025-01-10",
    task_status: "In Progress",
  },
  {
    task_id: 24,
    task_name: "Database Backup",
    task_type: "Testing",
    assignee: "Diana Rose",
    date_assigned: "2025-05-15",
    date_completed: "2025-05-18",
    expected_end_date: "2025-05-28",
    task_status: "In Progress",
  },
  {
    task_id: 25,
    task_name: "Database Backup",
    task_type: "Design",
    assignee: "Fiona Adams",
    date_assigned: "2025-04-11",
    date_completed: "2025-04-14",
    expected_end_date: "2025-04-16",
    task_status: "Pending",
  },
  {
    task_id: 26,
    task_name: "UI Redesign",
    task_type: "Design",
    assignee: "George White",
    date_assigned: "2025-07-07",
    date_completed: "2025-07-13",
    expected_end_date: "2025-07-22",
    task_status: "Pending",
  },
  {
    task_id: 27,
    task_name: "SEO Optimization",
    task_type: "Deployment",
    assignee: "Bob Smith",
    date_assigned: "2025-03-06",
    date_completed: null,
    expected_end_date: "2025-03-20",
    task_status: "On Hold",
  },
  {
    task_id: 28,
    task_name: "UI Redesign",
    task_type: "Audit",
    assignee: "Fiona Adams",
    date_assigned: "2025-01-22",
    date_completed: "2025-01-27",
    expected_end_date: "2025-01-28",
    task_status: "Completed",
  },
  {
    task_id: 29,
    task_name: "Security Audit",
    task_type: "Design",
    assignee: "Charlie Green",
    date_assigned: "2025-01-10",
    date_completed: null,
    expected_end_date: "2025-01-18",
    task_status: "On Hold",
  },
  {
    task_id: 30,
    task_name: "Database Backup",
    task_type: "Maintenance",
    assignee: "Bob Smith",
    date_assigned: "2025-01-08",
    date_completed: null,
    expected_end_date: "2025-01-16",
    task_status: "Pending",
  },
  {
    task_id: 31,
    task_name: "Database Backup",
    task_type: "Design",
    assignee: "Charlie Green",
    date_assigned: "2025-06-12",
    date_completed: "2025-06-22",
    expected_end_date: "2025-06-21",
    task_status: "In Progress",
  },
  {
    task_id: 32,
    task_name: "Code Review",
    task_type: "Development",
    assignee: "Ethan Clark",
    date_assigned: "2025-01-17",
    date_completed: "2025-01-22",
    expected_end_date: "2025-01-27",
    task_status: "Completed",
  },
  {
    task_id: 33,
    task_name: "Database Backup",
    task_type: "Deployment",
    assignee: "Bob Smith",
    date_assigned: "2025-02-22",
    date_completed: "2025-02-24",
    expected_end_date: "2025-03-06",
    task_status: "Pending",
  },
  {
    task_id: 34,
    task_name: "API Integration",
    task_type: "Maintenance",
    assignee: "Hannah Brown",
    date_assigned: "2025-02-06",
    date_completed: "2025-02-12",
    expected_end_date: "2025-02-17",
    task_status: "In Progress",
  },
  {
    task_id: 35,
    task_name: "UI Redesign",
    task_type: "Testing",
    assignee: "Hannah Brown",
    date_assigned: "2025-01-04",
    date_completed: null,
    expected_end_date: "2025-01-15",
    task_status: "In Progress",
  },
  {
    task_id: 36,
    task_name: "Content Upload",
    task_type: "Deployment",
    assignee: "George White",
    date_assigned: "2025-04-02",
    date_completed: null,
    expected_end_date: "2025-04-13",
    task_status: "On Hold",
  },
  {
    task_id: 37,
    task_name: "API Integration",
    task_type: "Testing",
    assignee: "Hannah Brown",
    date_assigned: "2025-05-06",
    date_completed: null,
    expected_end_date: "2025-05-14",
    task_status: "Pending",
  },
  {
    task_id: 38,
    task_name: "Performance Testing",
    task_type: "Development",
    assignee: "Diana Rose",
    date_assigned: "2025-06-03",
    date_completed: "2025-06-12",
    expected_end_date: "2025-06-14",
    task_status: "On Hold",
  },
  {
    task_id: 39,
    task_name: "Bug Fixing",
    task_type: "Audit",
    assignee: "George White",
    date_assigned: "2025-06-07",
    date_completed: null,
    expected_end_date: "2025-06-18",
    task_status: "Pending",
  },
  {
    task_id: 40,
    task_name: "UI Redesign",
    task_type: "Deployment",
    assignee: "Bob Smith",
    date_assigned: "2025-01-13",
    date_completed: "2025-01-18",
    expected_end_date: "2025-01-24",
    task_status: "On Hold",
  },
  {
    task_id: 41,
    task_name: "Database Backup",
    task_type: "Audit",
    assignee: "Bob Smith",
    date_assigned: "2025-04-30",
    date_completed: null,
    expected_end_date: "2025-05-08",
    task_status: "In Progress",
  },
  {
    task_id: 42,
    task_name: "Security Audit",
    task_type: "Development",
    assignee: "Ethan Clark",
    date_assigned: "2025-08-05",
    date_completed: null,
    expected_end_date: "2025-08-10",
    task_status: "On Hold",
  },
  {
    task_id: 43,
    task_name: "SEO Optimization",
    task_type: "Maintenance",
    assignee: "Fiona Adams",
    date_assigned: "2025-04-21",
    date_completed: null,
    expected_end_date: "2025-05-05",
    task_status: "On Hold",
  },
  {
    task_id: 44,
    task_name: "API Integration",
    task_type: "Testing",
    assignee: "Diana Rose",
    date_assigned: "2025-02-13",
    date_completed: "2025-02-21",
    expected_end_date: "2025-02-23",
    task_status: "On Hold",
  },
  {
    task_id: 45,
    task_name: "API Integration",
    task_type: "Maintenance",
    assignee: "George White",
    date_assigned: "2025-06-23",
    date_completed: null,
    expected_end_date: "2025-07-07",
    task_status: "Completed",
  },
  {
    task_id: 46,
    task_name: "API Integration",
    task_type: "Maintenance",
    assignee: "Fiona Adams",
    date_assigned: "2025-03-22",
    date_completed: null,
    expected_end_date: "2025-04-02",
    task_status: "On Hold",
  },
  {
    task_id: 47,
    task_name: "Security Audit",
    task_type: "Deployment",
    assignee: "Charlie Green",
    date_assigned: "2025-07-23",
    date_completed: null,
    expected_end_date: "2025-07-28",
    task_status: "Completed",
  },
  {
    task_id: 48,
    task_name: "Database Backup",
    task_type: "Design",
    assignee: "Charlie Green",
    date_assigned: "2025-01-17",
    date_completed: null,
    expected_end_date: "2025-01-30",
    task_status: "Pending",
  },
  {
    task_id: 49,
    task_name: "UI Redesign",
    task_type: "Deployment",
    assignee: "Bob Smith",
    date_assigned: "2025-01-10",
    date_completed: null,
    expected_end_date: "2025-01-20",
    task_status: "On Hold",
  },
  {
    task_id: 50,
    task_name: "API Integration",
    task_type: "Design",
    assignee: "Alice Johnson",
    date_assigned: "2025-04-03",
    date_completed: "2025-04-05",
    expected_end_date: "2025-04-13",
    task_status: "On Hold",
  },
  {
    task_id: 51,
    task_name: "Code Review",
    task_type: "Design",
    assignee: "Alice Johnson",
    date_assigned: "2025-04-21",
    date_completed: null,
    expected_end_date: "2025-04-28",
    task_status: "Completed",
  },
  {
    task_id: 52,
    task_name: "Content Upload",
    task_type: "Development",
    assignee: "Ethan Clark",
    date_assigned: "2025-07-14",
    date_completed: "2025-07-18",
    expected_end_date: "2025-07-23",
    task_status: "In Progress",
  },
  {
    task_id: 53,
    task_name: "Performance Testing",
    task_type: "Testing",
    assignee: "Fiona Adams",
    date_assigned: "2025-01-27",
    date_completed: null,
    expected_end_date: "2025-02-02",
    task_status: "Pending",
  },
  {
    task_id: 54,
    task_name: "Code Review",
    task_type: "Testing",
    assignee: "George White",
    date_assigned: "2025-07-27",
    date_completed: null,
    expected_end_date: "2025-08-09",
    task_status: "Completed",
  },
  {
    task_id: 55,
    task_name: "SEO Optimization",
    task_type: "Testing",
    assignee: "Hannah Brown",
    date_assigned: "2025-03-13",
    date_completed: "2025-03-15",
    expected_end_date: "2025-03-26",
    task_status: "Pending",
  },
  {
    task_id: 56,
    task_name: "API Integration",
    task_type: "Deployment",
    assignee: "Charlie Green",
    date_assigned: "2025-04-25",
    date_completed: null,
    expected_end_date: "2025-05-10",
    task_status: "In Progress",
  },
  {
    task_id: 57,
    task_name: "UI Redesign",
    task_type: "Design",
    assignee: "Fiona Adams",
    date_assigned: "2025-04-23",
    date_completed: "2025-05-02",
    expected_end_date: "2025-05-06",
    task_status: "Pending",
  },
  {
    task_id: 58,
    task_name: "Security Audit",
    task_type: "Development",
    assignee: "Hannah Brown",
    date_assigned: "2025-02-01",
    date_completed: "2025-02-11",
    expected_end_date: "2025-02-16",
    task_status: "Completed",
  },
  {
    task_id: 59,
    task_name: "SEO Optimization",
    task_type: "Design",
    assignee: "Hannah Brown",
    date_assigned: "2025-08-03",
    date_completed: null,
    expected_end_date: "2025-08-12",
    task_status: "In Progress",
  },
  {
    task_id: 60,
    task_name: "Content Upload",
    task_type: "Audit",
    assignee: "Ethan Clark",
    date_assigned: "2025-06-15",
    date_completed: "2025-06-17",
    expected_end_date: "2025-06-28",
    task_status: "Completed",
  },
  {
    task_id: 61,
    task_name: "Security Audit",
    task_type: "Testing",
    assignee: "Hannah Brown",
    date_assigned: "2025-07-16",
    date_completed: null,
    expected_end_date: "2025-07-21",
    task_status: "Pending",
  },
  {
    task_id: 62,
    task_name: "Performance Testing",
    task_type: "Design",
    assignee: "Ethan Clark",
    date_assigned: "2025-07-03",
    date_completed: "2025-07-11",
    expected_end_date: "2025-07-11",
    task_status: "Pending",
  },
  {
    task_id: 63,
    task_name: "Bug Fixing",
    task_type: "Audit",
    assignee: "Diana Rose",
    date_assigned: "2025-05-01",
    date_completed: null,
    expected_end_date: "2025-05-08",
    task_status: "Completed",
  },
  {
    task_id: 64,
    task_name: "Content Upload",
    task_type: "Deployment",
    assignee: "Ethan Clark",
    date_assigned: "2025-04-13",
    date_completed: "2025-04-21",
    expected_end_date: "2025-04-23",
    task_status: "On Hold",
  },
  {
    task_id: 65,
    task_name: "Content Upload",
    task_type: "Development",
    assignee: "Ethan Clark",
    date_assigned: "2025-02-17",
    date_completed: null,
    expected_end_date: "2025-02-23",
    task_status: "On Hold",
  },
  {
    task_id: 66,
    task_name: "Code Review",
    task_type: "Design",
    assignee: "Ethan Clark",
    date_assigned: "2025-06-29",
    date_completed: null,
    expected_end_date: "2025-07-14",
    task_status: "Pending",
  },
  {
    task_id: 67,
    task_name: "API Integration",
    task_type: "Testing",
    assignee: "Hannah Brown",
    date_assigned: "2025-07-18",
    date_completed: null,
    expected_end_date: "2025-08-02",
    task_status: "On Hold",
  },
  {
    task_id: 68,
    task_name: "Performance Testing",
    task_type: "Maintenance",
    assignee: "Bob Smith",
    date_assigned: "2025-02-01",
    date_completed: "2025-02-11",
    expected_end_date: "2025-02-07",
    task_status: "On Hold",
  },
  {
    task_id: 69,
    task_name: "SEO Optimization",
    task_type: "Development",
    assignee: "Diana Rose",
    date_assigned: "2025-02-01",
    date_completed: "2025-02-09",
    expected_end_date: "2025-02-15",
    task_status: "In Progress",
  },
  {
    task_id: 70,
    task_name: "Database Backup",
    task_type: "Audit",
    assignee: "Diana Rose",
    date_assigned: "2025-01-29",
    date_completed: null,
    expected_end_date: "2025-02-13",
    task_status: "Completed",
  },
  {
    task_id: 71,
    task_name: "API Integration",
    task_type: "Maintenance",
    assignee: "Bob Smith",
    date_assigned: "2025-02-02",
    date_completed: null,
    expected_end_date: "2025-02-09",
    task_status: "Pending",
  },
  {
    task_id: 72,
    task_name: "Code Review",
    task_type: "Design",
    assignee: "Bob Smith",
    date_assigned: "2025-01-03",
    date_completed: null,
    expected_end_date: "2025-01-12",
    task_status: "On Hold",
  },
  {
    task_id: 73,
    task_name: "Security Audit",
    task_type: "Testing",
    assignee: "Hannah Brown",
    date_assigned: "2025-03-28",
    date_completed: null,
    expected_end_date: "2025-04-12",
    task_status: "Completed",
  },
  {
    task_id: 74,
    task_name: "Code Review",
    task_type: "Deployment",
    assignee: "Ethan Clark",
    date_assigned: "2025-04-16",
    date_completed: null,
    expected_end_date: "2025-04-25",
    task_status: "Pending",
  },
  {
    task_id: 75,
    task_name: "Content Upload",
    task_type: "Development",
    assignee: "Charlie Green",
    date_assigned: "2025-03-28",
    date_completed: "2025-04-03",
    expected_end_date: "2025-04-10",
    task_status: "Pending",
  },
  {
    task_id: 76,
    task_name: "Security Audit",
    task_type: "Testing",
    assignee: "Diana Rose",
    date_assigned: "2025-03-04",
    date_completed: "2025-03-09",
    expected_end_date: "2025-03-10",
    task_status: "In Progress",
  },
  {
    task_id: 77,
    task_name: "API Integration",
    task_type: "Deployment",
    assignee: "George White",
    date_assigned: "2025-07-10",
    date_completed: "2025-07-13",
    expected_end_date: "2025-07-18",
    task_status: "Completed",
  },
  {
    task_id: 78,
    task_name: "Bug Fixing",
    task_type: "Deployment",
    assignee: "Bob Smith",
    date_assigned: "2025-01-23",
    date_completed: "2025-01-25",
    expected_end_date: "2025-02-05",
    task_status: "On Hold",
  },
  {
    task_id: 79,
    task_name: "Performance Testing",
    task_type: "Deployment",
    assignee: "George White",
    date_assigned: "2025-02-03",
    date_completed: "2025-02-07",
    expected_end_date: "2025-02-14",
    task_status: "Completed",
  },
  {
    task_id: 80,
    task_name: "API Integration",
    task_type: "Maintenance",
    assignee: "Hannah Brown",
    date_assigned: "2025-02-26",
    date_completed: null,
    expected_end_date: "2025-03-05",
    task_status: "Completed",
  },
  {
    task_id: 81,
    task_name: "Content Upload",
    task_type: "Deployment",
    assignee: "Alice Johnson",
    date_assigned: "2025-01-13",
    date_completed: "2025-01-20",
    expected_end_date: "2025-01-20",
    task_status: "In Progress",
  },
  {
    task_id: 82,
    task_name: "UI Redesign",
    task_type: "Design",
    assignee: "Bob Smith",
    date_assigned: "2025-04-22",
    date_completed: "2025-04-27",
    expected_end_date: "2025-05-07",
    task_status: "Completed",
  },
  {
    task_id: 83,
    task_name: "Security Audit",
    task_type: "Development",
    assignee: "Alice Johnson",
    date_assigned: "2025-07-03",
    date_completed: null,
    expected_end_date: "2025-07-17",
    task_status: "In Progress",
  },
  {
    task_id: 84,
    task_name: "UI Redesign",
    task_type: "Deployment",
    assignee: "Fiona Adams",
    date_assigned: "2025-06-13",
    date_completed: null,
    expected_end_date: "2025-06-21",
    task_status: "On Hold",
  },
  {
    task_id: 85,
    task_name: "Code Review",
    task_type: "Design",
    assignee: "Ethan Clark",
    date_assigned: "2025-02-05",
    date_completed: null,
    expected_end_date: "2025-02-17",
    task_status: "Completed",
  },
  {
    task_id: 86,
    task_name: "SEO Optimization",
    task_type: "Maintenance",
    assignee: "Alice Johnson",
    date_assigned: "2025-06-17",
    date_completed: "2025-06-18",
    expected_end_date: "2025-06-23",
    task_status: "Completed",
  },
  {
    task_id: 87,
    task_name: "Performance Testing",
    task_type: "Deployment",
    assignee: "George White",
    date_assigned: "2025-06-01",
    date_completed: "2025-06-11",
    expected_end_date: "2025-06-12",
    task_status: "In Progress",
  },
  {
    task_id: 88,
    task_name: "Database Backup",
    task_type: "Development",
    assignee: "Bob Smith",
    date_assigned: "2025-06-11",
    date_completed: null,
    expected_end_date: "2025-06-25",
    task_status: "Completed",
  },
  {
    task_id: 89,
    task_name: "Database Backup",
    task_type: "Testing",
    assignee: "Ethan Clark",
    date_assigned: "2025-02-24",
    date_completed: null,
    expected_end_date: "2025-03-04",
    task_status: "Completed",
  },
  {
    task_id: 90,
    task_name: "UI Redesign",
    task_type: "Deployment",
    assignee: "George White",
    date_assigned: "2025-03-31",
    date_completed: null,
    expected_end_date: "2025-04-07",
    task_status: "In Progress",
  },
  {
    task_id: 91,
    task_name: "Database Backup",
    task_type: "Design",
    assignee: "George White",
    date_assigned: "2025-08-03",
    date_completed: null,
    expected_end_date: "2025-08-12",
    task_status: "Completed",
  },
  {
    task_id: 92,
    task_name: "System Upgrade",
    task_type: "Maintenance",
    assignee: "George White",
    date_assigned: "2025-07-24",
    date_completed: null,
    expected_end_date: "2025-07-29",
    task_status: "Pending",
  },
  {
    task_id: 93,
    task_name: "Content Upload",
    task_type: "Testing",
    assignee: "Charlie Green",
    date_assigned: "2025-02-11",
    date_completed: "2025-02-16",
    expected_end_date: "2025-02-16",
    task_status: "Completed",
  },
  {
    task_id: 94,
    task_name: "System Upgrade",
    task_type: "Development",
    assignee: "Bob Smith",
    date_assigned: "2025-07-21",
    date_completed: "2025-07-28",
    expected_end_date: "2025-07-26",
    task_status: "Completed",
  },
  {
    task_id: 95,
    task_name: "Content Upload",
    task_type: "Design",
    assignee: "Hannah Brown",
    date_assigned: "2025-01-24",
    date_completed: "2025-01-27",
    expected_end_date: "2025-02-02",
    task_status: "On Hold",
  },
  {
    task_id: 96,
    task_name: "Code Review",
    task_type: "Development",
    assignee: "Charlie Green",
    date_assigned: "2025-07-01",
    date_completed: null,
    expected_end_date: "2025-07-14",
    task_status: "Pending",
  },
  {
    task_id: 97,
    task_name: "API Integration",
    task_type: "Maintenance",
    assignee: "George White",
    date_assigned: "2025-06-08",
    date_completed: null,
    expected_end_date: "2025-06-17",
    task_status: "On Hold",
  },
  {
    task_id: 98,
    task_name: "Performance Testing",
    task_type: "Development",
    assignee: "Ethan Clark",
    date_assigned: "2025-04-15",
    date_completed: null,
    expected_end_date: "2025-04-29",
    task_status: "Pending",
  },
  {
    task_id: 99,
    task_name: "Code Review",
    task_type: "Audit",
    assignee: "Diana Rose",
    date_assigned: "2025-07-04",
    date_completed: "2025-07-14",
    expected_end_date: "2025-07-15",
    task_status: "In Progress",
  },
  {
    task_id: 100,
    task_name: "Database Backup",
    task_type: "Maintenance",
    assignee: "Ethan Clark",
    date_assigned: "2025-01-25",
    date_completed: "2025-01-26",
    expected_end_date: "2025-01-30",
    task_status: "On Hold",
  },
  {
    task_id: 101,
    task_name: "System Upgrade",
    task_type: "Audit",
    assignee: "Hannah Brown",
    date_assigned: "2025-03-16",
    date_completed: null,
    expected_end_date: "2025-03-22",
    task_status: "Completed",
  },
  {
    task_id: 102,
    task_name: "Code Review",
    task_type: "Testing",
    assignee: "Diana Rose",
    date_assigned: "2025-04-21",
    date_completed: "2025-04-30",
    expected_end_date: "2025-05-06",
    task_status: "On Hold",
  },
  {
    task_id: 103,
    task_name: "System Upgrade",
    task_type: "Testing",
    assignee: "Diana Rose",
    date_assigned: "2025-01-08",
    date_completed: null,
    expected_end_date: "2025-01-20",
    task_status: "In Progress",
  },
  {
    task_id: 104,
    task_name: "API Integration",
    task_type: "Development",
    assignee: "Ethan Clark",
    date_assigned: "2025-08-12",
    date_completed: null,
    expected_end_date: "2025-08-12",
    task_status: "In Progress",
  },
  {
    task_id: 105,
    task_name: "Database Backup",
    task_type: "Testing",
    assignee: "Diana Rose",
    date_assigned: "2025-07-12",
    date_completed: "2025-07-21",
    expected_end_date: "2025-07-26",
    task_status: "Completed",
  },
  {
    task_id: 106,
    task_name: "SEO Optimization",
    task_type: "Testing",
    assignee: "Fiona Adams",
    date_assigned: "2025-05-08",
    date_completed: "2025-05-18",
    expected_end_date: "2025-05-20",
    task_status: "Pending",
  },
  {
    task_id: 107,
    task_name: "Bug Fixing",
    task_type: "Testing",
    assignee: "Ethan Clark",
    date_assigned: "2025-05-20",
    date_completed: "2025-05-29",
    expected_end_date: "2025-05-31",
    task_status: "Completed",
  },
  {
    task_id: 108,
    task_name: "API Integration",
    task_type: "Testing",
    assignee: "Hannah Brown",
    date_assigned: "2025-02-05",
    date_completed: null,
    expected_end_date: "2025-02-15",
    task_status: "Pending",
  },
  {
    task_id: 109,
    task_name: "Performance Testing",
    task_type: "Deployment",
    assignee: "Charlie Green",
    date_assigned: "2025-01-19",
    date_completed: null,
    expected_end_date: "2025-01-26",
    task_status: "Completed",
  },
  {
    task_id: 110,
    task_name: "Code Review",
    task_type: "Audit",
    assignee: "Ethan Clark",
    date_assigned: "2025-04-12",
    date_completed: "2025-04-21",
    expected_end_date: "2025-04-21",
    task_status: "In Progress",
  },
  {
    task_id: 111,
    task_name: "Security Audit",
    task_type: "Development",
    assignee: "Bob Smith",
    date_assigned: "2025-04-25",
    date_completed: "2025-04-28",
    expected_end_date: "2025-05-04",
    task_status: "Pending",
  },
  {
    task_id: 112,
    task_name: "Code Review",
    task_type: "Design",
    assignee: "Ethan Clark",
    date_assigned: "2025-01-29",
    date_completed: "2025-02-04",
    expected_end_date: "2025-02-11",
    task_status: "Pending",
  },
  {
    task_id: 113,
    task_name: "Code Review",
    task_type: "Development",
    assignee: "Bob Smith",
    date_assigned: "2025-05-20",
    date_completed: "2025-05-28",
    expected_end_date: "2025-05-26",
    task_status: "In Progress",
  },
  {
    task_id: 114,
    task_name: "System Upgrade",
    task_type: "Audit",
    assignee: "Fiona Adams",
    date_assigned: "2025-06-24",
    date_completed: "2025-06-26",
    expected_end_date: "2025-07-06",
    task_status: "In Progress",
  },
  {
    task_id: 115,
    task_name: "SEO Optimization",
    task_type: "Testing",
    assignee: "Diana Rose",
    date_assigned: "2025-03-16",
    date_completed: null,
    expected_end_date: "2025-03-30",
    task_status: "In Progress",
  },
  {
    task_id: 116,
    task_name: "Code Review",
    task_type: "Audit",
    assignee: "Diana Rose",
    date_assigned: "2025-08-11",
    date_completed: null,
    expected_end_date: "2025-08-12",
    task_status: "On Hold",
  },
  {
    task_id: 117,
    task_name: "Database Backup",
    task_type: "Testing",
    assignee: "Ethan Clark",
    date_assigned: "2025-01-01",
    date_completed: null,
    expected_end_date: "2025-01-14",
    task_status: "Pending",
  },
  {
    task_id: 118,
    task_name: "System Upgrade",
    task_type: "Maintenance",
    assignee: "Charlie Green",
    date_assigned: "2025-06-22",
    date_completed: "2025-06-28",
    expected_end_date: "2025-06-28",
    task_status: "In Progress",
  },
  {
    task_id: 119,
    task_name: "SEO Optimization",
    task_type: "Development",
    assignee: "Charlie Green",
    date_assigned: "2025-03-03",
    date_completed: "2025-03-08",
    expected_end_date: "2025-03-15",
    task_status: "Pending",
  },
  {
    task_id: 120,
    task_name: "SEO Optimization",
    task_type: "Deployment",
    assignee: "Ethan Clark",
    date_assigned: "2025-01-18",
    date_completed: "2025-01-23",
    expected_end_date: "2025-01-30",
    task_status: "On Hold",
  },
  {
    task_id: 121,
    task_name: "Security Audit",
    task_type: "Maintenance",
    assignee: "Charlie Green",
    date_assigned: "2025-03-29",
    date_completed: "2025-04-03",
    expected_end_date: "2025-04-07",
    task_status: "In Progress",
  },
  {
    task_id: 122,
    task_name: "Code Review",
    task_type: "Audit",
    assignee: "Hannah Brown",
    date_assigned: "2025-02-09",
    date_completed: null,
    expected_end_date: "2025-02-21",
    task_status: "On Hold",
  },
  {
    task_id: 123,
    task_name: "Performance Testing",
    task_type: "Deployment",
    assignee: "Ethan Clark",
    date_assigned: "2025-04-04",
    date_completed: "2025-04-09",
    expected_end_date: "2025-04-13",
    task_status: "On Hold",
  },
  {
    task_id: 124,
    task_name: "Code Review",
    task_type: "Development",
    assignee: "Hannah Brown",
    date_assigned: "2025-03-01",
    date_completed: null,
    expected_end_date: "2025-03-08",
    task_status: "On Hold",
  },
  {
    task_id: 125,
    task_name: "Code Review",
    task_type: "Design",
    assignee: "Charlie Green",
    date_assigned: "2025-07-10",
    date_completed: "2025-07-20",
    expected_end_date: "2025-07-16",
    task_status: "On Hold",
  },
  {
    task_id: 126,
    task_name: "Performance Testing",
    task_type: "Design",
    assignee: "George White",
    date_assigned: "2025-07-31",
    date_completed: null,
    expected_end_date: "2025-08-06",
    task_status: "Completed",
  },
  {
    task_id: 127,
    task_name: "Bug Fixing",
    task_type: "Development",
    assignee: "Bob Smith",
    date_assigned: "2025-03-02",
    date_completed: null,
    expected_end_date: "2025-03-12",
    task_status: "Pending",
  },
  {
    task_id: 128,
    task_name: "Security Audit",
    task_type: "Maintenance",
    assignee: "Bob Smith",
    date_assigned: "2025-03-10",
    date_completed: null,
    expected_end_date: "2025-03-22",
    task_status: "Completed",
  },
  {
    task_id: 129,
    task_name: "UI Redesign",
    task_type: "Maintenance",
    assignee: "George White",
    date_assigned: "2025-07-03",
    date_completed: null,
    expected_end_date: "2025-07-15",
    task_status: "On Hold",
  },
  {
    task_id: 130,
    task_name: "System Upgrade",
    task_type: "Development",
    assignee: "Fiona Adams",
    date_assigned: "2025-03-07",
    date_completed: "2025-03-15",
    expected_end_date: "2025-03-22",
    task_status: "In Progress",
  },
  {
    task_id: 131,
    task_name: "Security Audit",
    task_type: "Audit",
    assignee: "Hannah Brown",
    date_assigned: "2025-03-29",
    date_completed: null,
    expected_end_date: "2025-04-08",
    task_status: "Completed",
  },
  {
    task_id: 132,
    task_name: "API Integration",
    task_type: "Development",
    assignee: "Alice Johnson",
    date_assigned: "2025-04-06",
    date_completed: null,
    expected_end_date: "2025-04-11",
    task_status: "Pending",
  },
  {
    task_id: 133,
    task_name: "API Integration",
    task_type: "Testing",
    assignee: "Bob Smith",
    date_assigned: "2025-08-02",
    date_completed: "2025-08-10",
    expected_end_date: "2025-08-12",
    task_status: "Pending",
  },
  {
    task_id: 134,
    task_name: "UI Redesign",
    task_type: "Deployment",
    assignee: "Hannah Brown",
    date_assigned: "2025-03-20",
    date_completed: null,
    expected_end_date: "2025-03-28",
    task_status: "In Progress",
  },
  {
    task_id: 135,
    task_name: "Code Review",
    task_type: "Audit",
    assignee: "George White",
    date_assigned: "2025-04-19",
    date_completed: null,
    expected_end_date: "2025-04-25",
    task_status: "Completed",
  },
  {
    task_id: 136,
    task_name: "Performance Testing",
    task_type: "Maintenance",
    assignee: "Fiona Adams",
    date_assigned: "2025-04-01",
    date_completed: "2025-04-04",
    expected_end_date: "2025-04-16",
    task_status: "On Hold",
  },
  {
    task_id: 137,
    task_name: "Performance Testing",
    task_type: "Development",
    assignee: "Charlie Green",
    date_assigned: "2025-04-22",
    date_completed: "2025-04-25",
    expected_end_date: "2025-05-06",
    task_status: "Completed",
  },
  {
    task_id: 138,
    task_name: "Database Backup",
    task_type: "Maintenance",
    assignee: "Diana Rose",
    date_assigned: "2025-04-28",
    date_completed: null,
    expected_end_date: "2025-05-04",
    task_status: "Completed",
  },
  {
    task_id: 139,
    task_name: "Database Backup",
    task_type: "Deployment",
    assignee: "George White",
    date_assigned: "2025-07-25",
    date_completed: null,
    expected_end_date: "2025-08-08",
    task_status: "Completed",
  },
  {
    task_id: 140,
    task_name: "Code Review",
    task_type: "Development",
    assignee: "Bob Smith",
    date_assigned: "2025-03-15",
    date_completed: null,
    expected_end_date: "2025-03-25",
    task_status: "In Progress",
  },
  {
    task_id: 141,
    task_name: "UI Redesign",
    task_type: "Testing",
    assignee: "George White",
    date_assigned: "2025-05-18",
    date_completed: "2025-05-27",
    expected_end_date: "2025-06-01",
    task_status: "Completed",
  },
  {
    task_id: 142,
    task_name: "SEO Optimization",
    task_type: "Deployment",
    assignee: "Alice Johnson",
    date_assigned: "2025-05-01",
    date_completed: null,
    expected_end_date: "2025-05-08",
    task_status: "In Progress",
  },
  {
    task_id: 143,
    task_name: "Performance Testing",
    task_type: "Development",
    assignee: "Ethan Clark",
    date_assigned: "2025-04-05",
    date_completed: "2025-04-14",
    expected_end_date: "2025-04-16",
    task_status: "Completed",
  },
  {
    task_id: 144,
    task_name: "Code Review",
    task_type: "Testing",
    assignee: "Ethan Clark",
    date_assigned: "2025-04-29",
    date_completed: null,
    expected_end_date: "2025-05-12",
    task_status: "Completed",
  },
  {
    task_id: 145,
    task_name: "Code Review",
    task_type: "Testing",
    assignee: "Bob Smith",
    date_assigned: "2025-05-28",
    date_completed: null,
    expected_end_date: "2025-06-07",
    task_status: "In Progress",
  },
  {
    task_id: 146,
    task_name: "SEO Optimization",
    task_type: "Design",
    assignee: "Diana Rose",
    date_assigned: "2025-04-01",
    date_completed: "2025-04-06",
    expected_end_date: "2025-04-11",
    task_status: "On Hold",
  },
  {
    task_id: 147,
    task_name: "API Integration",
    task_type: "Deployment",
    assignee: "Diana Rose",
    date_assigned: "2025-04-26",
    date_completed: null,
    expected_end_date: "2025-05-08",
    task_status: "Completed",
  },
  {
    task_id: 148,
    task_name: "SEO Optimization",
    task_type: "Design",
    assignee: "Hannah Brown",
    date_assigned: "2025-02-01",
    date_completed: "2025-02-03",
    expected_end_date: "2025-02-13",
    task_status: "In Progress",
  },
  {
    task_id: 149,
    task_name: "SEO Optimization",
    task_type: "Audit",
    assignee: "Alice Johnson",
    date_assigned: "2025-04-12",
    date_completed: "2025-04-17",
    expected_end_date: "2025-04-27",
    task_status: "Completed",
  },
  {
    task_id: 150,
    task_name: "Database Backup",
    task_type: "Audit",
    assignee: "Diana Rose",
    date_assigned: "2025-01-24",
    date_completed: "2025-02-03",
    expected_end_date: "2025-02-06",
    task_status: "Pending",
  },
  {
    task_id: 151,
    task_name: "Security Audit",
    task_type: "Development",
    assignee: "Bob Smith",
    date_assigned: "2025-04-07",
    date_completed: "2025-04-16",
    expected_end_date: "2025-04-20",
    task_status: "Pending",
  },
  {
    task_id: 152,
    task_name: "SEO Optimization",
    task_type: "Design",
    assignee: "Charlie Green",
    date_assigned: "2025-01-31",
    date_completed: "2025-02-07",
    expected_end_date: "2025-02-13",
    task_status: "In Progress",
  },
  {
    task_id: 153,
    task_name: "System Upgrade",
    task_type: "Audit",
    assignee: "Ethan Clark",
    date_assigned: "2025-03-29",
    date_completed: "2025-04-04",
    expected_end_date: "2025-04-03",
    task_status: "Pending",
  },
  {
    task_id: 154,
    task_name: "Content Upload",
    task_type: "Testing",
    assignee: "George White",
    date_assigned: "2025-02-10",
    date_completed: "2025-02-11",
    expected_end_date: "2025-02-17",
    task_status: "In Progress",
  },
  {
    task_id: 155,
    task_name: "SEO Optimization",
    task_type: "Audit",
    assignee: "Charlie Green",
    date_assigned: "2025-04-17",
    date_completed: null,
    expected_end_date: "2025-04-24",
    task_status: "Pending",
  },
  {
    task_id: 156,
    task_name: "UI Redesign",
    task_type: "Audit",
    assignee: "Bob Smith",
    date_assigned: "2025-02-01",
    date_completed: null,
    expected_end_date: "2025-02-11",
    task_status: "In Progress",
  },
  {
    task_id: 157,
    task_name: "Security Audit",
    task_type: "Deployment",
    assignee: "Alice Johnson",
    date_assigned: "2025-05-24",
    date_completed: "2025-05-30",
    expected_end_date: "2025-06-02",
    task_status: "Completed",
  },
  {
    task_id: 158,
    task_name: "System Upgrade",
    task_type: "Design",
    assignee: "Bob Smith",
    date_assigned: "2025-02-04",
    date_completed: "2025-02-13",
    expected_end_date: "2025-02-10",
    task_status: "On Hold",
  },
  {
    task_id: 159,
    task_name: "API Integration",
    task_type: "Deployment",
    assignee: "Hannah Brown",
    date_assigned: "2025-02-08",
    date_completed: "2025-02-18",
    expected_end_date: "2025-02-19",
    task_status: "In Progress",
  },
  {
    task_id: 160,
    task_name: "API Integration",
    task_type: "Audit",
    assignee: "Fiona Adams",
    date_assigned: "2025-07-04",
    date_completed: null,
    expected_end_date: "2025-07-16",
    task_status: "In Progress",
  },
  {
    task_id: 161,
    task_name: "Bug Fixing",
    task_type: "Audit",
    assignee: "Alice Johnson",
    date_assigned: "2025-02-11",
    date_completed: null,
    expected_end_date: "2025-02-21",
    task_status: "Completed",
  },
  {
    task_id: 162,
    task_name: "UI Redesign",
    task_type: "Design",
    assignee: "Bob Smith",
    date_assigned: "2025-06-17",
    date_completed: "2025-06-24",
    expected_end_date: "2025-07-02",
    task_status: "On Hold",
  },
  {
    task_id: 163,
    task_name: "Database Backup",
    task_type: "Design",
    assignee: "George White",
    date_assigned: "2025-03-14",
    date_completed: "2025-03-21",
    expected_end_date: "2025-03-28",
    task_status: "In Progress",
  },
  {
    task_id: 164,
    task_name: "UI Redesign",
    task_type: "Audit",
    assignee: "Ethan Clark",
    date_assigned: "2025-07-18",
    date_completed: null,
    expected_end_date: "2025-07-28",
    task_status: "On Hold",
  },
  {
    task_id: 165,
    task_name: "Bug Fixing",
    task_type: "Deployment",
    assignee: "Fiona Adams",
    date_assigned: "2025-02-25",
    date_completed: null,
    expected_end_date: "2025-03-10",
    task_status: "In Progress",
  },
  {
    task_id: 166,
    task_name: "Code Review",
    task_type: "Audit",
    assignee: "George White",
    date_assigned: "2025-07-21",
    date_completed: "2025-07-31",
    expected_end_date: "2025-07-28",
    task_status: "On Hold",
  },
  {
    task_id: 167,
    task_name: "API Integration",
    task_type: "Maintenance",
    assignee: "Alice Johnson",
    date_assigned: "2025-08-06",
    date_completed: null,
    expected_end_date: "2025-08-12",
    task_status: "Completed",
  },
  {
    task_id: 168,
    task_name: "Performance Testing",
    task_type: "Testing",
    assignee: "Hannah Brown",
    date_assigned: "2025-07-23",
    date_completed: null,
    expected_end_date: "2025-08-02",
    task_status: "In Progress",
  },
  {
    task_id: 169,
    task_name: "Database Backup",
    task_type: "Design",
    assignee: "Bob Smith",
    date_assigned: "2025-06-21",
    date_completed: null,
    expected_end_date: "2025-07-03",
    task_status: "Pending",
  },
  {
    task_id: 170,
    task_name: "Content Upload",
    task_type: "Audit",
    assignee: "Charlie Green",
    date_assigned: "2025-02-03",
    date_completed: "2025-02-09",
    expected_end_date: "2025-02-11",
    task_status: "On Hold",
  },
  {
    task_id: 171,
    task_name: "System Upgrade",
    task_type: "Audit",
    assignee: "Fiona Adams",
    date_assigned: "2025-06-24",
    date_completed: null,
    expected_end_date: "2025-07-05",
    task_status: "In Progress",
  },
  {
    task_id: 172,
    task_name: "Security Audit",
    task_type: "Audit",
    assignee: "Ethan Clark",
    date_assigned: "2025-05-01",
    date_completed: null,
    expected_end_date: "2025-05-09",
    task_status: "On Hold",
  },
  {
    task_id: 173,
    task_name: "SEO Optimization",
    task_type: "Testing",
    assignee: "Diana Rose",
    date_assigned: "2025-06-20",
    date_completed: null,
    expected_end_date: "2025-07-03",
    task_status: "Completed",
  },
  {
    task_id: 174,
    task_name: "API Integration",
    task_type: "Design",
    assignee: "Hannah Brown",
    date_assigned: "2025-05-18",
    date_completed: null,
    expected_end_date: "2025-05-24",
    task_status: "Pending",
  },
  {
    task_id: 175,
    task_name: "Performance Testing",
    task_type: "Deployment",
    assignee: "Charlie Green",
    date_assigned: "2025-08-08",
    date_completed: null,
    expected_end_date: "2025-08-12",
    task_status: "Pending",
  },
  {
    task_id: 176,
    task_name: "Security Audit",
    task_type: "Audit",
    assignee: "Alice Johnson",
    date_assigned: "2025-04-12",
    date_completed: "2025-04-13",
    expected_end_date: "2025-04-18",
    task_status: "Completed",
  },
  {
    task_id: 177,
    task_name: "System Upgrade",
    task_type: "Testing",
    assignee: "Ethan Clark",
    date_assigned: "2025-08-01",
    date_completed: null,
    expected_end_date: "2025-08-09",
    task_status: "On Hold",
  },
  {
    task_id: 178,
    task_name: "Bug Fixing",
    task_type: "Audit",
    assignee: "George White",
    date_assigned: "2025-01-09",
    date_completed: null,
    expected_end_date: "2025-01-14",
    task_status: "In Progress",
  },
  {
    task_id: 179,
    task_name: "Code Review",
    task_type: "Deployment",
    assignee: "Hannah Brown",
    date_assigned: "2025-06-10",
    date_completed: null,
    expected_end_date: "2025-06-23",
    task_status: "In Progress",
  },
  {
    task_id: 180,
    task_name: "System Upgrade",
    task_type: "Development",
    assignee: "George White",
    date_assigned: "2025-04-30",
    date_completed: null,
    expected_end_date: "2025-05-09",
    task_status: "On Hold",
  },
  {
    task_id: 181,
    task_name: "API Integration",
    task_type: "Development",
    assignee: "Charlie Green",
    date_assigned: "2025-04-09",
    date_completed: "2025-04-14",
    expected_end_date: "2025-04-17",
    task_status: "Pending",
  },
  {
    task_id: 182,
    task_name: "UI Redesign",
    task_type: "Audit",
    assignee: "Bob Smith",
    date_assigned: "2025-03-14",
    date_completed: null,
    expected_end_date: "2025-03-21",
    task_status: "In Progress",
  },
  {
    task_id: 183,
    task_name: "Security Audit",
    task_type: "Design",
    assignee: "Alice Johnson",
    date_assigned: "2025-06-04",
    date_completed: "2025-06-12",
    expected_end_date: "2025-06-10",
    task_status: "Pending",
  },
  {
    task_id: 184,
    task_name: "Code Review",
    task_type: "Development",
    assignee: "Bob Smith",
    date_assigned: "2025-02-04",
    date_completed: "2025-02-12",
    expected_end_date: "2025-02-14",
    task_status: "On Hold",
  },
  {
    task_id: 185,
    task_name: "Security Audit",
    task_type: "Deployment",
    assignee: "Bob Smith",
    date_assigned: "2025-07-13",
    date_completed: "2025-07-14",
    expected_end_date: "2025-07-22",
    task_status: "On Hold",
  },
  {
    task_id: 186,
    task_name: "System Upgrade",
    task_type: "Development",
    assignee: "Hannah Brown",
    date_assigned: "2025-04-19",
    date_completed: null,
    expected_end_date: "2025-04-27",
    task_status: "In Progress",
  },
  {
    task_id: 187,
    task_name: "System Upgrade",
    task_type: "Design",
    assignee: "Charlie Green",
    date_assigned: "2025-01-13",
    date_completed: "2025-01-17",
    expected_end_date: "2025-01-28",
    task_status: "On Hold",
  },
  {
    task_id: 188,
    task_name: "Content Upload",
    task_type: "Development",
    assignee: "Ethan Clark",
    date_assigned: "2025-08-09",
    date_completed: null,
    expected_end_date: "2025-08-12",
    task_status: "Pending",
  },
  {
    task_id: 189,
    task_name: "Performance Testing",
    task_type: "Testing",
    assignee: "George White",
    date_assigned: "2025-04-26",
    date_completed: "2025-04-27",
    expected_end_date: "2025-05-04",
    task_status: "In Progress",
  },
  {
    task_id: 190,
    task_name: "Database Backup",
    task_type: "Audit",
    assignee: "Fiona Adams",
    date_assigned: "2025-03-07",
    date_completed: null,
    expected_end_date: "2025-03-12",
    task_status: "In Progress",
  },
  {
    task_id: 191,
    task_name: "Bug Fixing",
    task_type: "Design",
    assignee: "Ethan Clark",
    date_assigned: "2025-07-04",
    date_completed: "2025-07-09",
    expected_end_date: "2025-07-10",
    task_status: "On Hold",
  },
  {
    task_id: 192,
    task_name: "Security Audit",
    task_type: "Audit",
    assignee: "Hannah Brown",
    date_assigned: "2025-01-03",
    date_completed: "2025-01-06",
    expected_end_date: "2025-01-10",
    task_status: "Pending",
  },
  {
    task_id: 193,
    task_name: "Code Review",
    task_type: "Maintenance",
    assignee: "Charlie Green",
    date_assigned: "2025-06-25",
    date_completed: null,
    expected_end_date: "2025-07-01",
    task_status: "On Hold",
  },
  {
    task_id: 194,
    task_name: "Code Review",
    task_type: "Development",
    assignee: "Alice Johnson",
    date_assigned: "2025-04-24",
    date_completed: null,
    expected_end_date: "2025-04-29",
    task_status: "On Hold",
  },
  {
    task_id: 195,
    task_name: "Bug Fixing",
    task_type: "Audit",
    assignee: "Fiona Adams",
    date_assigned: "2025-01-06",
    date_completed: null,
    expected_end_date: "2025-01-13",
    task_status: "Pending",
  },
  {
    task_id: 196,
    task_name: "SEO Optimization",
    task_type: "Development",
    assignee: "Hannah Brown",
    date_assigned: "2025-04-06",
    date_completed: null,
    expected_end_date: "2025-04-20",
    task_status: "In Progress",
  },
  {
    task_id: 197,
    task_name: "Database Backup",
    task_type: "Deployment",
    assignee: "Charlie Green",
    date_assigned: "2025-05-25",
    date_completed: null,
    expected_end_date: "2025-06-09",
    task_status: "In Progress",
  },
  {
    task_id: 198,
    task_name: "Security Audit",
    task_type: "Development",
    assignee: "Charlie Green",
    date_assigned: "2025-02-08",
    date_completed: "2025-02-16",
    expected_end_date: "2025-02-15",
    task_status: "Completed",
  },
  {
    task_id: 199,
    task_name: "UI Redesign",
    task_type: "Deployment",
    assignee: "Diana Rose",
    date_assigned: "2025-04-07",
    date_completed: null,
    expected_end_date: "2025-04-16",
    task_status: "On Hold",
  },
  {
    task_id: 200,
    task_name: "SEO Optimization",
    task_type: "Testing",
    assignee: "Alice Johnson",
    date_assigned: "2025-05-05",
    date_completed: "2025-05-07",
    expected_end_date: "2025-05-17",
    task_status: "On Hold",
  },
];
