export const complianceTasks = [
  {
    taskId: "T001",
    department: "Finance",
    title: "Quarterly tax filing",
    description: "File quarterly PAYE and VAT returns",
    status: "Completed",
    assignedTo: "John Doe",
    startDate: "2025-01-01",
    dueDate: "2025-01-15",
    completionDate: "2025-01-12",
    riskId: "R001"
  },
  {
    taskId: "T002",
    department: "HR",
    title: "Employee contract review",
    description: "Review employment contracts for compliance with labor laws",
    status: "In Progress",
    assignedTo: "Sarah Nakitende",
    startDate: "2025-01-05",
    dueDate: "2025-01-20",
    completionDate: null,
    riskId: "R002"
  },
  {
    taskId: "T003",
    department: "IT",
    title: "Data backup audit",
    description: "Audit monthly data backup process",
    status: "Not Started",
    assignedTo: "Michael Owor",
    startDate: "2025-02-01",
    dueDate: "2025-02-10",
    completionDate: null,
    riskId: "R003"
  },
  {
    taskId: "T004",
    department: "Editorial",
    title: "Content copyright compliance",
    description: "Ensure all editorial content meets copyright standards",
    status: "Completed",
    assignedTo: "Grace Akello",
    startDate: "2025-02-03",
    dueDate: "2025-02-15",
    completionDate: "2025-02-12",
    riskId: "R004"
  },
  {
    taskId: "T005",
    department: "Legal",
    title: "Contract renewal review",
    description: "Review supplier contracts for compliance",
    status: "Completed",
    assignedTo: "Peter Mugisha",
    startDate: "2025-02-05",
    dueDate: "2025-02-20",
    completionDate: "2025-02-19",
    riskId: "R005"
  },
  {
    taskId: "T006",
    department: "Finance",
    title: "Annual financial audit prep",
    description: "Prepare financial statements for annual audit",
    status: "In Progress",
    assignedTo: "John Doe",
    startDate: "2025-03-01",
    dueDate: "2025-03-15",
    completionDate: null,
    riskId: "R001"
  },
  {
    taskId: "T007",
    department: "HR",
    title: "Workplace safety training",
    description: "Conduct compliance training for workplace safety",
    status: "Completed",
    assignedTo: "Sarah Nakitende",
    startDate: "2025-03-10",
    dueDate: "2025-03-20",
    completionDate: "2025-03-19",
    riskId: "R002"
  },
  {
    taskId: "T008",
    department: "IT",
    title: "Access control policy review",
    description: "Review and update IT access control policy",
    status: "Not Started",
    assignedTo: "Michael Owor",
    startDate: "2025-04-01",
    dueDate: "2025-04-10",
    completionDate: null,
    riskId: "R003"
  },
  {
    taskId: "T009",
    department: "Editorial",
    title: "Ethical reporting compliance",
    description: "Ensure all published news meets ethical reporting standards",
    status: "Completed",
    assignedTo: "Grace Akello",
    startDate: "2025-04-05",
    dueDate: "2025-04-20",
    completionDate: "2025-04-18",
    riskId: "R004"
  },
  {
    taskId: "T010",
    department: "Legal",
    title: "Data protection compliance",
    description: "Review company practices for GDPR compliance",
    status: "In Progress",
    assignedTo: "Peter Mugisha",
    startDate: "2025-05-01",
    dueDate: "2025-05-15",
    completionDate: null,
    riskId: "R005"
  },
 
  {
    taskId: "T011",
    department: "Finance",
    title: "Payroll compliance check",
    description: "Verify payroll tax deductions accuracy",
    status: "Completed",
    assignedTo: "John Doe",
    startDate: "2025-05-05",
    dueDate: "2025-05-10",
    completionDate: "2025-05-09",
    riskId: "R001"
  },
  {
    taskId: "T012",
    department: "HR",
    title: "Disciplinary procedures review",
    description: "Ensure procedures meet labor compliance laws",
    status: "Not Started",
    assignedTo: "Sarah Nakitende",
    startDate: "2025-05-10",
    dueDate: "2025-05-25",
    completionDate: null,
    riskId: "R002"
  },
  {
    taskId: "T013",
    department: "IT",
    title: "Software licensing audit",
    description: "Check compliance with software licensing agreements",
    status: "Completed",
    assignedTo: "Michael Owor",
    startDate: "2025-05-15",
    dueDate: "2025-05-30",
    completionDate: "2025-05-29",
    riskId: "R003"
  },
  {
    taskId: "T014",
    department: "Editorial",
    title: "Fact-checking compliance audit",
    description: "Audit editorial processes for fact-checking standards",
    status: "Completed",
    assignedTo: "Grace Akello",
    startDate: "2025-06-01",
    dueDate: "2025-06-15",
    completionDate: "2025-06-14",
    riskId: "R004"
  },
  {
    taskId: "T015",
    department: "Legal",
    title: "Trademark compliance review",
    description: "Verify company use of trademarks is compliant",
    status: "Not Started",
    assignedTo: "Peter Mugisha",
    startDate: "2025-06-05",
    dueDate: "2025-06-20",
    completionDate: null,
    riskId: "R005"
  },
  {
    taskId: "T016",
    department: "Finance",
    title: "Expense policy compliance",
    description: "Review staff claims against company expense policy",
    status: "In Progress",
    assignedTo: "John Doe",
    startDate: "2025-06-10",
    dueDate: "2025-06-25",
    completionDate: null,
    riskId: "R001"
  },
  {
    taskId: "T017",
    department: "HR",
    title: "Recruitment process compliance",
    description: "Ensure hiring processes align with labor law",
    status: "Completed",
    assignedTo: "Sarah Nakitende",
    startDate: "2025-07-01",
    dueDate: "2025-07-10",
    completionDate: "2025-07-09",
    riskId: "R002"
  },
  {
    taskId: "T018",
    department: "IT",
    title: "Penetration testing",
    description: "Perform penetration testing to ensure cybersecurity compliance",
    status: "In Progress",
    assignedTo: "Michael Owor",
    startDate: "2025-07-05",
    dueDate: "2025-07-20",
    completionDate: null,
    riskId: "R003"
  },
  {
    taskId: "T019",
    department: "Editorial",
    title: "Plagiarism audit",
    description: "Check editorial work for plagiarism compliance",
    status: "Completed",
    assignedTo: "Grace Akello",
    startDate: "2025-07-10",
    dueDate: "2025-07-25",
    completionDate: "2025-07-23",
    riskId: "R004"
  },
  {
    taskId: "T020",
    department: "Legal",
    title: "Litigation risk review",
    description: "Review ongoing litigation cases for compliance exposure",
    status: "Completed",
    assignedTo: "Peter Mugisha",
    startDate: "2025-07-15",
    dueDate: "2025-07-30",
    completionDate: "2025-07-28",
    riskId: "R005"
  },
  {
    taskId: "T021",
    department: "Finance",
    title: "Supplier payment compliance",
    description: "Check supplier payments against contracts",
    status: "Completed",
    assignedTo: "John Doe",
    startDate: "2025-08-01",
    dueDate: "2025-08-05",
    completionDate: "2025-08-04",
    riskId: "R001"
  },
  {
    taskId: "T022",
    department: "HR",
    title: "Equal opportunity audit",
    description: "Audit HR practices for equal opportunity compliance",
    status: "In Progress",
    assignedTo: "Sarah Nakitende",
    startDate: "2025-08-05",
    dueDate: "2025-08-15",
    completionDate: null,
    riskId: "R002"
  },
  {
    taskId: "T023",
    department: "IT",
    title: "Cloud compliance audit",
    description: "Ensure cloud systems meet compliance standards",
    status: "Completed",
    assignedTo: "Michael Owor",
    startDate: "2025-08-10",
    dueDate: "2025-08-20",
    completionDate: "2025-08-18",
    riskId: "R003"
  },
  {
    taskId: "T024",
    department: "Editorial",
    title: "Advertising standards compliance",
    description: "Review adverts for compliance with laws",
    status: "Not Started",
    assignedTo: "Grace Akello",
    startDate: "2025-08-15",
    dueDate: "2025-08-30",
    completionDate: null,
    riskId: "R004"
  },
  {
    taskId: "T025",
    department: "Legal",
    title: "Contract dispute resolution review",
    description: "Ensure dispute processes align with compliance standards",
    status: "Completed",
    assignedTo: "Peter Mugisha",
    startDate: "2025-08-20",
    dueDate: "2025-09-05",
    completionDate: "2025-09-03",
    riskId: "R005"
  },
  {
    taskId: "T026",
    department: "Finance",
    title: "Capital expenditure compliance",
    description: "Review capital expenditure for compliance with policies",
    status: "Not Started",
    assignedTo: "John Doe",
    startDate: "2025-09-01",
    dueDate: "2025-09-15",
    completionDate: null,
    riskId: "R001"
  },
  {
    taskId: "T027",
    department: "HR",
    title: "Leave policy compliance",
    description: "Check leave applications against company policy",
    status: "Completed",
    assignedTo: "Sarah Nakitende",
    startDate: "2025-09-05",
    dueDate: "2025-09-10",
    completionDate: "2025-09-09",
    riskId: "R002"
  },
  {
    taskId: "T028",
    department: "IT",
    title: "Incident response drill",
    description: "Conduct compliance testing for incident response plan",
    status: "Completed",
    assignedTo: "Michael Owor",
    startDate: "2025-09-10",
    dueDate: "2025-09-20",
    completionDate: "2025-09-19",
    riskId: "R003"
  },
  {
    taskId: "T029",
    department: "Editorial",
    title: "Sensitive content compliance",
    description: "Ensure reporting on sensitive issues meets compliance",
    status: "In Progress",
    assignedTo: "Grace Akello",
    startDate: "2025-09-15",
    dueDate: "2025-09-30",
    completionDate: null,
    riskId: "R004"
  },
  {
    taskId: "T030",
    department: "Legal",
    title: "Regulatory filing compliance",
    description: "Submit regulatory filings on time",
    status: "Completed",
    assignedTo: "Peter Mugisha",
    startDate: "2025-09-20",
    dueDate: "2025-09-30",
    completionDate: "2025-09-28",
    riskId: "R005"
  }
];
