export const dummyRiskData = [
  {
    "riskId": "R001",
    "department": "Finance & Accounting",
    "riskType": "Regulatory",
    "description": "Delayed tax filing penalties",
    "likelihood": 4,
    "impact": 3,
    "riskScore": 12,
    "status": "Open",
    "reviewDate": "2023-02-15",
    "nextReviewDate": "2023-05-15"
  },
  {
    "riskId": "R002",
    "department": "Editorial & Content",
    "riskType": "Operational",
    "description": "Content copyright infringement",
    "likelihood": 3,
    "impact": 4,
    "riskScore": 12,
    "status": "In Progress",
    "reviewDate": "2023-03-10",
    "nextReviewDate": "2023-06-10"
  },
  {
    "riskId": "R003",
    "department": "Sales & Marketing",
    "riskType": "Strategic",
    "description": "Low ad revenue due to competitor campaigns",
    "likelihood": 5,
    "impact": 4,
    "riskScore": 20,
    "status": "Open",
    "reviewDate": "2023-04-05",
    "nextReviewDate": "2023-07-05"
  },
  {
    "riskId": "R004",
    "department": "Operations & Production",
    "riskType": "Operational",
    "description": "Printing press breakdown",
    "likelihood": 4,
    "impact": 5,
    "riskScore": 20,
    "status": "Mitigated",
    "reviewDate": "2023-06-12",
    "nextReviewDate": "2023-09-12"
  },
  {
    "riskId": "R005",
    "department": "Executive Leadership",
    "riskType": "Strategic",
    "description": "Reputation damage from public scandal",
    "likelihood": 2,
    "impact": 5,
    "riskScore": 10,
    "status": "Open",
    "reviewDate": "2023-08-01",
    "nextReviewDate": "2023-11-01"
  },
  {
    "riskId": "R006",
    "department": "Legal",
    "riskType": "Regulatory",
    "description": "Non-compliance with data privacy laws",
    "likelihood": 3,
    "impact": 5,
    "riskScore": 15,
    "status": "In Progress",
    "reviewDate": "2023-09-20",
    "nextReviewDate": "2023-12-20"
  },
  {
    "riskId": "R007",
    "department": "HR",
    "riskType": "Operational",
    "description": "High staff turnover",
    "likelihood": 4,
    "impact": 3,
    "riskScore": 12,
    "status": "Open",
    "reviewDate": "2023-11-10",
    "nextReviewDate": "2024-02-10"
  },
  {
    "riskId": "R008",
    "department": "Risk Management",
    "riskType": "Strategic",
    "description": "Inadequate internal controls",
    "likelihood": 5,
    "impact": 4,
    "riskScore": 20,
    "status": "In Progress",
    "reviewDate": "2023-12-15",
    "nextReviewDate": "2024-03-15"
  },
  {
    "riskId": "R009",
    "department": "Finance & Accounting",
    "riskType": "Operational",
    "description": "Fraudulent financial reporting",
    "likelihood": 3,
    "impact": 5,
    "riskScore": 15,
    "status": "Mitigated",
    "reviewDate": "2024-01-22",
    "nextReviewDate": "2024-04-22"
  },
  {
    "riskId": "R010",
    "department": "Administrative & Support",
    "riskType": "Operational",
    "description": "Power outages affecting IT systems",
    "likelihood": 4,
    "impact": 4,
    "riskScore": 16,
    "status": "Open",
    "reviewDate": "2024-02-18",
    "nextReviewDate": "2024-05-18"
  },

  {
    "riskId": "R011",
    "department": "Operations & Production",
    "riskType": "Operational",
    "description": "Supply chain disruption",
    "likelihood": 3,
    "impact": 4,
    "riskScore": 12,
    "status": "Open",
    "reviewDate": "2024-03-12",
    "nextReviewDate": "2024-06-12"
  },
  {
    "riskId": "R012",
    "department": "Editorial & Content",
    "riskType": "Strategic",
    "description": "Fake news publishing incident",
    "likelihood": 2,
    "impact": 5,
    "riskScore": 10,
    "status": "In Progress",
    "reviewDate": "2024-04-01",
    "nextReviewDate": "2024-07-01"
  },
  {
    "riskId": "R013",
    "department": "Sales & Marketing",
    "riskType": "Strategic",
    "description": "Failed advertising campaigns",
    "likelihood": 4,
    "impact": 3,
    "riskScore": 12,
    "status": "Open",
    "reviewDate": "2024-05-20",
    "nextReviewDate": "2024-08-20"
  },
  {
    "riskId": "R014",
    "department": "Executive Leadership",
    "riskType": "Regulatory",
    "description": "Failure to meet board governance requirements",
    "likelihood": 2,
    "impact": 4,
    "riskScore": 8,
    "status": "Mitigated",
    "reviewDate": "2024-06-25",
    "nextReviewDate": "2024-09-25"
  },
  {
    "riskId": "R015",
    "department": "Legal",
    "riskType": "Regulatory",
    "description": "Ongoing litigation case",
    "likelihood": 3,
    "impact": 4,
    "riskScore": 12,
    "status": "Open",
    "reviewDate": "2024-07-15",
    "nextReviewDate": "2024-10-15"
  },
  {
    "riskId": "R016",
    "department": "HR",
    "riskType": "Operational",
    "description": "Inadequate training for staff",
    "likelihood": 4,
    "impact": 2,
    "riskScore": 8,
    "status": "Open",
    "reviewDate": "2024-08-02",
    "nextReviewDate": "2024-11-02"
  },
  {
    "riskId": "R017",
    "department": "Finance & Accounting",
    "riskType": "Operational",
    "description": "Payroll processing errors",
    "likelihood": 3,
    "impact": 3,
    "riskScore": 9,
    "status": "In Progress",
    "reviewDate": "2024-09-12",
    "nextReviewDate": "2024-12-12"
  },
  {
    "riskId": "R018",
    "department": "Risk Management",
    "riskType": "Strategic",
    "description": "Weak risk monitoring systems",
    "likelihood": 5,
    "impact": 3,
    "riskScore": 15,
    "status": "Open",
    "reviewDate": "2024-10-18",
    "nextReviewDate": "2025-01-18"
  },
  {
    "riskId": "R019",
    "department": "Operations & Production",
    "riskType": "Operational",
    "description": "Machine safety hazards",
    "likelihood": 2,
    "impact": 5,
    "riskScore": 10,
    "status": "Mitigated",
    "reviewDate": "2024-11-11",
    "nextReviewDate": "2025-02-11"
  },
  {
    "riskId": "R020",
    "department": "Sales & Marketing",
    "riskType": "Strategic",
    "description": "Low subscription renewals",
    "likelihood": 3,
    "impact": 3,
    "riskScore": 9,
    "status": "Open",
    "reviewDate": "2024-12-05",
    "nextReviewDate": "2025-03-05"
  },

  {
    "riskId": "R021",
    "department": "Administrative & Support",
    "riskType": "Operational",
    "description": "Fire hazard in records storage",
    "likelihood": 2,
    "impact": 5,
    "riskScore": 10,
    "status": "Open",
    "reviewDate": "2025-01-09",
    "nextReviewDate": "2025-04-09"
  },
  {
    "riskId": "R022",
    "department": "Editorial & Content",
    "riskType": "Operational",
    "description": "Failure in editorial workflow system",
    "likelihood": 4,
    "impact": 3,
    "riskScore": 12,
    "status": "In Progress",
    "reviewDate": "2025-02-15",
    "nextReviewDate": "2025-05-15"
  },
  {
    "riskId": "R023",
    "department": "Executive Leadership",
    "riskType": "Strategic",
    "description": "Failure in digital transformation strategy",
    "likelihood": 3,
    "impact": 4,
    "riskScore": 12,
    "status": "Open",
    "reviewDate": "2025-03-12",
    "nextReviewDate": "2025-06-12"
  },
  {
    "riskId": "R024",
    "department": "Legal",
    "riskType": "Regulatory",
    "description": "Breach of contract lawsuits",
    "likelihood": 2,
    "impact": 4,
    "riskScore": 8,
    "status": "Mitigated",
    "reviewDate": "2025-04-01",
    "nextReviewDate": "2025-07-01"
  },
  {
    "riskId": "R025",
    "department": "HR",
    "riskType": "Operational",
    "description": "Workplace harassment claims",
    "likelihood": 3,
    "impact": 4,
    "riskScore": 12,
    "status": "Open",
    "reviewDate": "2025-04-28",
    "nextReviewDate": "2025-07-28"
  },
  {
    "riskId": "R026",
    "department": "Finance & Accounting",
    "riskType": "Regulatory",
    "description": "AML compliance gaps",
    "likelihood": 4,
    "impact": 4,
    "riskScore": 16,
    "status": "In Progress",
    "reviewDate": "2025-05-18",
    "nextReviewDate": "2025-08-18"
  },
  {
    "riskId": "R027",
    "department": "Risk Management",
    "riskType": "Strategic",
    "description": "Unclear reporting structures",
    "likelihood": 3,
    "impact": 2,
    "riskScore": 6,
    "status": "Open",
    "reviewDate": "2025-06-09",
    "nextReviewDate": "2025-09-09"
  },
  {
    "riskId": "R028",
    "department": "Operations & Production",
    "riskType": "Operational",
    "description": "Equipment maintenance delays",
    "likelihood": 4,
    "impact": 3,
    "riskScore": 12,
    "status": "In Progress",
    "reviewDate": "2025-07-22",
    "nextReviewDate": "2025-10-22"
  },
  {
    "riskId": "R029",
    "department": "Sales & Marketing",
    "riskType": "Strategic",
    "description": "Negative brand perception",
    "likelihood": 2,
    "impact": 5,
    "riskScore": 10,
    "status": "Open",
    "reviewDate": "2025-08-14",
    "nextReviewDate": "2025-11-14"
  },
  {
    "riskId": "R030",
    "department": "Administrative & Support",
    "riskType": "Operational",
    "description": "Data loss from system crash",
    "likelihood": 5,
    "impact": 4,
    "riskScore": 20,
    "status": "Open",
    "reviewDate": "2025-09-01",
    "nextReviewDate": "2025-12-01"
  }
]
