const wide_kpis = [
  {
    date: "2025-01-01",
    administrative_support: {
      employee_headcount: 468,
      employee_turnover_percent: 5.6,
      training_hours_per_employee: 14.6,
      employee_engagement_percent: 84,
    },
    editorial: {
      top_content: [
        {
          title: "Market Trends in Uganda",
          views: 70855,
          channel: "Digital",
        },
        {
          title: "Weekend Editorial Feature",
          views: 128135,
          channel: "Digital",
        },
        {
          title: "Health & Lifestyle",
          views: 109176,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 4.7,
      digital_users: 557146,
      print_circulation: 261820,
      broadcast_viewers: 700165,
    },
    finance: {
      revenue: 264602272,
      operating_costs: 196874193,
      cash_flow_month_to_date: 29185142,
      cash_flow_quarter_to_date: 118485774,
      cash_flow_year_to_date: 357721402,
      profit_margin_percent: {
        Print: 15,
        TV: 19,
        Digital: 23,
      },
    },
    it: {
      website_uptime_percent: 99.6,
      broadcast_uptime_percent: 99.8,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 1,
      cybersecurity_incidents_resolved: 3,
      avg_ticket_resolution_hours: 4.9,
    },
    operations_production: {
      print_pages_per_hour: 7873,
      broadcast_segments_per_day: 157,
      distribution_on_time_percent: 95,
      printing_press_utilization_percent: 75,
      broadcast_equipment_utilization_percent: 81,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 6,
        TV: 7,
        Digital: 14,
      },
      CAC: 49,
      CLV: 416,
      market_share_percent: 36,
    },
  },
  {
    date: "2025-01-08",
    administrative_support: {
      employee_headcount: 455,
      employee_turnover_percent: 7.1,
      training_hours_per_employee: 12.0,
      employee_engagement_percent: 78,
    },
    editorial: {
      top_content: [
        {
          title: "New Education Policy",
          views: 117681,
          channel: "Print",
        },
        {
          title: "Weekend Editorial Feature",
          views: 89908,
          channel: "TV",
        },
        {
          title: "Sports Highlights",
          views: 63831,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 5.9,
      digital_users: 521064,
      print_circulation: 247032,
      broadcast_viewers: 682115,
    },
    finance: {
      revenue: 267097811,
      operating_costs: 170804938,
      cash_flow_month_to_date: 35221763,
      cash_flow_quarter_to_date: 97432157,
      cash_flow_year_to_date: 288042812,
      profit_margin_percent: {
        Print: 11,
        TV: 20,
        Digital: 26,
      },
    },
    it: {
      website_uptime_percent: 99.7,
      broadcast_uptime_percent: 99.4,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 0,
      cybersecurity_incidents_resolved: 2,
      avg_ticket_resolution_hours: 3.1,
    },
    operations_production: {
      print_pages_per_hour: 8366,
      broadcast_segments_per_day: 166,
      distribution_on_time_percent: 93,
      printing_press_utilization_percent: 72,
      broadcast_equipment_utilization_percent: 84,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 7,
        TV: 9,
        Digital: 18,
      },
      CAC: 51,
      CLV: 431,
      market_share_percent: 33,
    },
  },
  {
    date: "2025-01-15",
    administrative_support: {
      employee_headcount: 462,
      employee_turnover_percent: 6.6,
      training_hours_per_employee: 14.6,
      employee_engagement_percent: 78,
    },
    editorial: {
      top_content: [
        {
          title: "Market Trends in Uganda",
          views: 110298,
          channel: "Digital",
        },
        {
          title: "National Sports Roundup",
          views: 81926,
          channel: "Print",
        },
        {
          title: "International News Roundup",
          views: 110041,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 5.0,
      digital_users: 518503,
      print_circulation: 274772,
      broadcast_viewers: 741546,
    },
    finance: {
      revenue: 259456403,
      operating_costs: 191017897,
      cash_flow_month_to_date: 34489676,
      cash_flow_quarter_to_date: 110802460,
      cash_flow_year_to_date: 279249428,
      profit_margin_percent: {
        Print: 14,
        TV: 15,
        Digital: 22,
      },
    },
    it: {
      website_uptime_percent: 99.8,
      broadcast_uptime_percent: 99.4,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 0,
      cybersecurity_incidents_resolved: 3,
      avg_ticket_resolution_hours: 4.6,
    },
    operations_production: {
      print_pages_per_hour: 8219,
      broadcast_segments_per_day: 143,
      distribution_on_time_percent: 90,
      printing_press_utilization_percent: 73,
      broadcast_equipment_utilization_percent: 86,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 8,
        TV: 11,
        Digital: 19,
      },
      CAC: 59,
      CLV: 390,
      market_share_percent: 33,
    },
  },
  {
    date: "2025-01-22",
    administrative_support: {
      employee_headcount: 461,
      employee_turnover_percent: 6.6,
      training_hours_per_employee: 12.5,
      employee_engagement_percent: 76,
    },
    editorial: {
      top_content: [
        {
          title: "New Education Policy",
          views: 103519,
          channel: "Digital",
        },
        {
          title: "Weekend Editorial Feature",
          views: 115553,
          channel: "TV",
        },
        {
          title: "Health & Lifestyle",
          views: 114941,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 5.0,
      digital_users: 485609,
      print_circulation: 263061,
      broadcast_viewers: 685767,
    },
    finance: {
      revenue: 249845984,
      operating_costs: 197667692,
      cash_flow_month_to_date: 35521634,
      cash_flow_quarter_to_date: 95355356,
      cash_flow_year_to_date: 421957041,
      profit_margin_percent: {
        Print: 10,
        TV: 20,
        Digital: 20,
      },
    },
    it: {
      website_uptime_percent: 99.6,
      broadcast_uptime_percent: 99.7,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 1,
      cybersecurity_incidents_resolved: 0,
      avg_ticket_resolution_hours: 4.8,
    },
    operations_production: {
      print_pages_per_hour: 8287,
      broadcast_segments_per_day: 168,
      distribution_on_time_percent: 91,
      printing_press_utilization_percent: 75,
      broadcast_equipment_utilization_percent: 82,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 8,
        TV: 7,
        Digital: 16,
      },
      CAC: 58,
      CLV: 426,
      market_share_percent: 36,
    },
  },
  {
    date: "2025-01-29",
    administrative_support: {
      employee_headcount: 440,
      employee_turnover_percent: 6.8,
      training_hours_per_employee: 10.5,
      employee_engagement_percent: 76,
    },
    editorial: {
      top_content: [
        {
          title: "Market Trends in Uganda",
          views: 116335,
          channel: "Print",
        },
        {
          title: "Technology in Africa",
          views: 62440,
          channel: "TV",
        },
        {
          title: "Election Updates",
          views: 71097,
          channel: "Digital",
        },
      ],
      avg_content_production_hours: 5.5,
      digital_users: 593164,
      print_circulation: 249434,
      broadcast_viewers: 704777,
    },
    finance: {
      revenue: 261210294,
      operating_costs: 190137228,
      cash_flow_month_to_date: 36115721,
      cash_flow_quarter_to_date: 86267838,
      cash_flow_year_to_date: 454725879,
      profit_margin_percent: {
        Print: 13,
        TV: 17,
        Digital: 25,
      },
    },
    it: {
      website_uptime_percent: 99.6,
      broadcast_uptime_percent: 99.7,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 3,
      cybersecurity_incidents_resolved: 4,
      avg_ticket_resolution_hours: 4.2,
    },
    operations_production: {
      print_pages_per_hour: 8029,
      broadcast_segments_per_day: 160,
      distribution_on_time_percent: 90,
      printing_press_utilization_percent: 72,
      broadcast_equipment_utilization_percent: 86,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 5,
        TV: 10,
        Digital: 18,
      },
      CAC: 55,
      CLV: 423,
      market_share_percent: 35,
    },
  },
  {
    date: "2025-02-05",
    administrative_support: {
      employee_headcount: 447,
      employee_turnover_percent: 5.8,
      training_hours_per_employee: 14.9,
      employee_engagement_percent: 77,
    },
    editorial: {
      top_content: [
        {
          title: "Sports Weekly Recap",
          views: 123608,
          channel: "Print",
        },
        {
          title: "Weekend Editorial Feature",
          views: 129945,
          channel: "TV",
        },
        {
          title: "Education Reform",
          views: 74846,
          channel: "Print",
        },
      ],
      avg_content_production_hours: 4.6,
      digital_users: 509304,
      print_circulation: 275099,
      broadcast_viewers: 729100,
    },
    finance: {
      revenue: 246588520,
      operating_costs: 187100898,
      cash_flow_month_to_date: 30777743,
      cash_flow_quarter_to_date: 106462900,
      cash_flow_year_to_date: 428793626,
      profit_margin_percent: {
        Print: 12,
        TV: 17,
        Digital: 21,
      },
    },
    it: {
      website_uptime_percent: 99.9,
      broadcast_uptime_percent: 99.8,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 1,
      cybersecurity_incidents_resolved: 0,
      avg_ticket_resolution_hours: 5.0,
    },
    operations_production: {
      print_pages_per_hour: 8084,
      broadcast_segments_per_day: 163,
      distribution_on_time_percent: 94,
      printing_press_utilization_percent: 74,
      broadcast_equipment_utilization_percent: 80,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 8,
        TV: 9,
        Digital: 20,
      },
      CAC: 56,
      CLV: 444,
      market_share_percent: 35,
    },
  },
  {
    date: "2025-02-12",
    administrative_support: {
      employee_headcount: 443,
      employee_turnover_percent: 6.1,
      training_hours_per_employee: 14.8,
      employee_engagement_percent: 82,
    },
    editorial: {
      top_content: [
        {
          title: "Political Debate Highlights",
          views: 90408,
          channel: "Print",
        },
        {
          title: "Economic Policy Analysis",
          views: 92865,
          channel: "Print",
        },
        {
          title: "Education Reform",
          views: 117050,
          channel: "Print",
        },
      ],
      avg_content_production_hours: 5.0,
      digital_users: 585200,
      print_circulation: 267160,
      broadcast_viewers: 716147,
    },
    finance: {
      revenue: 274677524,
      operating_costs: 199167422,
      cash_flow_month_to_date: 33488534,
      cash_flow_quarter_to_date: 84618372,
      cash_flow_year_to_date: 250990139,
      profit_margin_percent: {
        Print: 13,
        TV: 19,
        Digital: 25,
      },
    },
    it: {
      website_uptime_percent: 99.9,
      broadcast_uptime_percent: 99.8,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 4,
      cybersecurity_incidents_resolved: 2,
      avg_ticket_resolution_hours: 3.2,
    },
    operations_production: {
      print_pages_per_hour: 8207,
      broadcast_segments_per_day: 161,
      distribution_on_time_percent: 93,
      printing_press_utilization_percent: 76,
      broadcast_equipment_utilization_percent: 81,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 5,
        TV: 7,
        Digital: 18,
      },
      CAC: 50,
      CLV: 435,
      market_share_percent: 35,
    },
  },
  {
    date: "2025-02-19",
    administrative_support: {
      employee_headcount: 463,
      employee_turnover_percent: 7.1,
      training_hours_per_employee: 13.6,
      employee_engagement_percent: 81,
    },
    editorial: {
      top_content: [
        {
          title: "Sports Weekly Recap",
          views: 123652,
          channel: "Print",
        },
        {
          title: "Technology in Africa",
          views: 121214,
          channel: "Print",
        },
        {
          title: "Education Reform",
          views: 65087,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 5.9,
      digital_users: 481052,
      print_circulation: 273080,
      broadcast_viewers: 715112,
    },
    finance: {
      revenue: 245662754,
      operating_costs: 186076268,
      cash_flow_month_to_date: 26218529,
      cash_flow_quarter_to_date: 109002127,
      cash_flow_year_to_date: 493842650,
      profit_margin_percent: {
        Print: 10,
        TV: 20,
        Digital: 23,
      },
    },
    it: {
      website_uptime_percent: 99.5,
      broadcast_uptime_percent: 99.8,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 4,
      cybersecurity_incidents_resolved: 0,
      avg_ticket_resolution_hours: 3.9,
    },
    operations_production: {
      print_pages_per_hour: 7850,
      broadcast_segments_per_day: 156,
      distribution_on_time_percent: 90,
      printing_press_utilization_percent: 78,
      broadcast_equipment_utilization_percent: 80,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 5,
        TV: 10,
        Digital: 15,
      },
      CAC: 56,
      CLV: 433,
      market_share_percent: 37,
    },
  },
  {
    date: "2025-02-26",
    administrative_support: {
      employee_headcount: 474,
      employee_turnover_percent: 6.1,
      training_hours_per_employee: 13.5,
      employee_engagement_percent: 85,
    },
    editorial: {
      top_content: [
        {
          title: "New Education Policy",
          views: 84574,
          channel: "TV",
        },
        {
          title: "Economic Policy Analysis",
          views: 69470,
          channel: "Digital",
        },
        {
          title: "Education Reform",
          views: 92895,
          channel: "Digital",
        },
      ],
      avg_content_production_hours: 5.0,
      digital_users: 583432,
      print_circulation: 243987,
      broadcast_viewers: 680342,
    },
    finance: {
      revenue: 261014008,
      operating_costs: 182477598,
      cash_flow_month_to_date: 30235555,
      cash_flow_quarter_to_date: 107347666,
      cash_flow_year_to_date: 427705738,
      profit_margin_percent: {
        Print: 13,
        TV: 16,
        Digital: 27,
      },
    },
    it: {
      website_uptime_percent: 99.7,
      broadcast_uptime_percent: 99.6,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 0,
      cybersecurity_incidents_resolved: 2,
      avg_ticket_resolution_hours: 3.3,
    },
    operations_production: {
      print_pages_per_hour: 7924,
      broadcast_segments_per_day: 143,
      distribution_on_time_percent: 94,
      printing_press_utilization_percent: 76,
      broadcast_equipment_utilization_percent: 81,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 7,
        TV: 12,
        Digital: 16,
      },
      CAC: 50,
      CLV: 417,
      market_share_percent: 35,
    },
  },
  {
    date: "2025-03-05",
    administrative_support: {
      employee_headcount: 459,
      employee_turnover_percent: 7.3,
      training_hours_per_employee: 13.2,
      employee_engagement_percent: 77,
    },
    editorial: {
      top_content: [
        {
          title: "Political Debate Highlights",
          views: 137094,
          channel: "Print",
        },
        {
          title: "Economic Policy Analysis",
          views: 61661,
          channel: "Print",
        },
        {
          title: "Education Reform",
          views: 98680,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 5.7,
      digital_users: 592507,
      print_circulation: 261677,
      broadcast_viewers: 725068,
    },
    finance: {
      revenue: 269132529,
      operating_costs: 173441464,
      cash_flow_month_to_date: 30712942,
      cash_flow_quarter_to_date: 113986864,
      cash_flow_year_to_date: 355089635,
      profit_margin_percent: {
        Print: 14,
        TV: 19,
        Digital: 22,
      },
    },
    it: {
      website_uptime_percent: 99.8,
      broadcast_uptime_percent: 99.8,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 3,
      cybersecurity_incidents_resolved: 2,
      avg_ticket_resolution_hours: 4.8,
    },
    operations_production: {
      print_pages_per_hour: 8390,
      broadcast_segments_per_day: 151,
      distribution_on_time_percent: 90,
      printing_press_utilization_percent: 75,
      broadcast_equipment_utilization_percent: 82,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 7,
        TV: 7,
        Digital: 17,
      },
      CAC: 52,
      CLV: 437,
      market_share_percent: 37,
    },
  },
  {
    date: "2025-03-12",
    administrative_support: {
      employee_headcount: 476,
      employee_turnover_percent: 6.1,
      training_hours_per_employee: 11.9,
      employee_engagement_percent: 81,
    },
    editorial: {
      top_content: [
        {
          title: "Market Trends in Uganda",
          views: 170398,
          channel: "Print",
        },
        {
          title: "National Sports Roundup",
          views: 131237,
          channel: "Digital",
        },
        {
          title: "Education Reform",
          views: 61215,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 4.6,
      digital_users: 589425,
      print_circulation: 277941,
      broadcast_viewers: 693176,
    },
    finance: {
      revenue: 246523099,
      operating_costs: 197745916,
      cash_flow_month_to_date: 27591612,
      cash_flow_quarter_to_date: 106445949,
      cash_flow_year_to_date: 240692496,
      profit_margin_percent: {
        Print: 10,
        TV: 20,
        Digital: 28,
      },
    },
    it: {
      website_uptime_percent: 99.6,
      broadcast_uptime_percent: 99.8,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 0,
      cybersecurity_incidents_resolved: 0,
      avg_ticket_resolution_hours: 4.1,
    },
    operations_production: {
      print_pages_per_hour: 8082,
      broadcast_segments_per_day: 153,
      distribution_on_time_percent: 90,
      printing_press_utilization_percent: 74,
      broadcast_equipment_utilization_percent: 82,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 4,
        TV: 12,
        Digital: 18,
      },
      CAC: 48,
      CLV: 382,
      market_share_percent: 33,
    },
  },
  {
    date: "2025-03-19",
    administrative_support: {
      employee_headcount: 480,
      employee_turnover_percent: 6.7,
      training_hours_per_employee: 13.5,
      employee_engagement_percent: 77,
    },
    editorial: {
      top_content: [
        {
          title: "Sports Weekly Recap",
          views: 146082,
          channel: "TV",
        },
        {
          title: "Weekend Editorial Feature",
          views: 89637,
          channel: "Digital",
        },
        {
          title: "Health & Lifestyle",
          views: 56216,
          channel: "Print",
        },
      ],
      avg_content_production_hours: 5.0,
      digital_users: 531053,
      print_circulation: 246154,
      broadcast_viewers: 694417,
    },
    finance: {
      revenue: 252894945,
      operating_costs: 178145620,
      cash_flow_month_to_date: 29036804,
      cash_flow_quarter_to_date: 84181574,
      cash_flow_year_to_date: 426396895,
      profit_margin_percent: {
        Print: 13,
        TV: 16,
        Digital: 22,
      },
    },
    it: {
      website_uptime_percent: 99.9,
      broadcast_uptime_percent: 99.5,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 4,
      cybersecurity_incidents_resolved: 1,
      avg_ticket_resolution_hours: 3.3,
    },
    operations_production: {
      print_pages_per_hour: 8380,
      broadcast_segments_per_day: 164,
      distribution_on_time_percent: 92,
      printing_press_utilization_percent: 75,
      broadcast_equipment_utilization_percent: 84,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 4,
        TV: 7,
        Digital: 15,
      },
      CAC: 49,
      CLV: 382,
      market_share_percent: 32,
    },
  },
  {
    date: "2025-03-26",
    administrative_support: {
      employee_headcount: 473,
      employee_turnover_percent: 6.3,
      training_hours_per_employee: 10.5,
      employee_engagement_percent: 79,
    },
    editorial: {
      top_content: [
        {
          title: "Political Debate Highlights",
          views: 107751,
          channel: "TV",
        },
        {
          title: "National Sports Roundup",
          views: 105744,
          channel: "Print",
        },
        {
          title: "Education Reform",
          views: 63672,
          channel: "Print",
        },
      ],
      avg_content_production_hours: 4.9,
      digital_users: 563243,
      print_circulation: 268606,
      broadcast_viewers: 716133,
    },
    finance: {
      revenue: 266269643,
      operating_costs: 186300934,
      cash_flow_month_to_date: 33115056,
      cash_flow_quarter_to_date: 118114374,
      cash_flow_year_to_date: 321312781,
      profit_margin_percent: {
        Print: 11,
        TV: 16,
        Digital: 27,
      },
    },
    it: {
      website_uptime_percent: 99.6,
      broadcast_uptime_percent: 99.8,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 0,
      cybersecurity_incidents_resolved: 2,
      avg_ticket_resolution_hours: 4.6,
    },
    operations_production: {
      print_pages_per_hour: 7819,
      broadcast_segments_per_day: 143,
      distribution_on_time_percent: 92,
      printing_press_utilization_percent: 75,
      broadcast_equipment_utilization_percent: 83,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 7,
        TV: 7,
        Digital: 20,
      },
      CAC: 54,
      CLV: 405,
      market_share_percent: 37,
    },
  },
  {
    date: "2025-04-02",
    administrative_support: {
      employee_headcount: 470,
      employee_turnover_percent: 5.7,
      training_hours_per_employee: 11.4,
      employee_engagement_percent: 78,
    },
    editorial: {
      top_content: [
        {
          title: "Sports Weekly Recap",
          views: 109355,
          channel: "Digital",
        },
        {
          title: "Technology in Africa",
          views: 147501,
          channel: "TV",
        },
        {
          title: "Election Updates",
          views: 119656,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 5.4,
      digital_users: 510283,
      print_circulation: 274043,
      broadcast_viewers: 723904,
    },
    finance: {
      revenue: 245354896,
      operating_costs: 175244084,
      cash_flow_month_to_date: 26828062,
      cash_flow_quarter_to_date: 106451378,
      cash_flow_year_to_date: 333855844,
      profit_margin_percent: {
        Print: 11,
        TV: 17,
        Digital: 27,
      },
    },
    it: {
      website_uptime_percent: 99.7,
      broadcast_uptime_percent: 99.6,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 1,
      cybersecurity_incidents_resolved: 1,
      avg_ticket_resolution_hours: 3.5,
    },
    operations_production: {
      print_pages_per_hour: 8107,
      broadcast_segments_per_day: 149,
      distribution_on_time_percent: 92,
      printing_press_utilization_percent: 73,
      broadcast_equipment_utilization_percent: 83,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 8,
        TV: 9,
        Digital: 14,
      },
      CAC: 49,
      CLV: 422,
      market_share_percent: 38,
    },
  },
  {
    date: "2025-04-09",
    administrative_support: {
      employee_headcount: 477,
      employee_turnover_percent: 7.2,
      training_hours_per_employee: 14.8,
      employee_engagement_percent: 79,
    },
    editorial: {
      top_content: [
        {
          title: "Political Debate Highlights",
          views: 96673,
          channel: "TV",
        },
        {
          title: "Regional Sports Highlights",
          views: 90756,
          channel: "TV",
        },
        {
          title: "Education Reform",
          views: 106182,
          channel: "Print",
        },
      ],
      avg_content_production_hours: 5.9,
      digital_users: 519793,
      print_circulation: 247996,
      broadcast_viewers: 749339,
    },
    finance: {
      revenue: 259161516,
      operating_costs: 185835051,
      cash_flow_month_to_date: 36415550,
      cash_flow_quarter_to_date: 84698436,
      cash_flow_year_to_date: 464462811,
      profit_margin_percent: {
        Print: 10,
        TV: 17,
        Digital: 22,
      },
    },
    it: {
      website_uptime_percent: 99.9,
      broadcast_uptime_percent: 99.7,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 3,
      cybersecurity_incidents_resolved: 0,
      avg_ticket_resolution_hours: 4.5,
    },
    operations_production: {
      print_pages_per_hour: 8483,
      broadcast_segments_per_day: 167,
      distribution_on_time_percent: 95,
      printing_press_utilization_percent: 78,
      broadcast_equipment_utilization_percent: 83,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 5,
        TV: 10,
        Digital: 16,
      },
      CAC: 52,
      CLV: 446,
      market_share_percent: 35,
    },
  },
  {
    date: "2025-04-16",
    administrative_support: {
      employee_headcount: 473,
      employee_turnover_percent: 7.4,
      training_hours_per_employee: 13.1,
      employee_engagement_percent: 80,
    },
    editorial: {
      top_content: [
        {
          title: "Sports Weekly Recap",
          views: 149338,
          channel: "TV",
        },
        {
          title: "National Sports Roundup",
          views: 118439,
          channel: "Print",
        },
        {
          title: "Health & Lifestyle",
          views: 76347,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 4.6,
      digital_users: 544957,
      print_circulation: 261026,
      broadcast_viewers: 737549,
    },
    finance: {
      revenue: 274366909,
      operating_costs: 193926838,
      cash_flow_month_to_date: 38336323,
      cash_flow_quarter_to_date: 94741924,
      cash_flow_year_to_date: 286711215,
      profit_margin_percent: {
        Print: 11,
        TV: 16,
        Digital: 28,
      },
    },
    it: {
      website_uptime_percent: 99.6,
      broadcast_uptime_percent: 99.4,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 3,
      cybersecurity_incidents_resolved: 1,
      avg_ticket_resolution_hours: 3.8,
    },
    operations_production: {
      print_pages_per_hour: 8007,
      broadcast_segments_per_day: 159,
      distribution_on_time_percent: 96,
      printing_press_utilization_percent: 78,
      broadcast_equipment_utilization_percent: 83,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 8,
        TV: 11,
        Digital: 15,
      },
      CAC: 56,
      CLV: 409,
      market_share_percent: 35,
    },
  },
  {
    date: "2025-04-23",
    administrative_support: {
      employee_headcount: 463,
      employee_turnover_percent: 6.9,
      training_hours_per_employee: 11.2,
      employee_engagement_percent: 76,
    },
    editorial: {
      top_content: [
        {
          title: "New Education Policy",
          views: 69942,
          channel: "Print",
        },
        {
          title: "Technology in Africa",
          views: 80305,
          channel: "Print",
        },
        {
          title: "Health & Lifestyle",
          views: 97796,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 4.6,
      digital_users: 561833,
      print_circulation: 265952,
      broadcast_viewers: 718762,
    },
    finance: {
      revenue: 278028459,
      operating_costs: 189452961,
      cash_flow_month_to_date: 29892445,
      cash_flow_quarter_to_date: 88572270,
      cash_flow_year_to_date: 345305642,
      profit_margin_percent: {
        Print: 12,
        TV: 15,
        Digital: 22,
      },
    },
    it: {
      website_uptime_percent: 99.7,
      broadcast_uptime_percent: 99.4,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 4,
      cybersecurity_incidents_resolved: 2,
      avg_ticket_resolution_hours: 4.3,
    },
    operations_production: {
      print_pages_per_hour: 8242,
      broadcast_segments_per_day: 163,
      distribution_on_time_percent: 90,
      printing_press_utilization_percent: 72,
      broadcast_equipment_utilization_percent: 81,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 4,
        TV: 11,
        Digital: 18,
      },
      CAC: 50,
      CLV: 391,
      market_share_percent: 37,
    },
  },
  {
    date: "2025-04-30",
    administrative_support: {
      employee_headcount: 480,
      employee_turnover_percent: 5.5,
      training_hours_per_employee: 13.1,
      employee_engagement_percent: 81,
    },
    editorial: {
      top_content: [
        {
          title: "Sports Weekly Recap",
          views: 177368,
          channel: "Digital",
        },
        {
          title: "Regional Sports Highlights",
          views: 88297,
          channel: "Print",
        },
        {
          title: "Election Updates",
          views: 73052,
          channel: "Print",
        },
      ],
      avg_content_production_hours: 4.6,
      digital_users: 505537,
      print_circulation: 255335,
      broadcast_viewers: 717929,
    },
    finance: {
      revenue: 253996183,
      operating_costs: 191854292,
      cash_flow_month_to_date: 36890297,
      cash_flow_quarter_to_date: 83207644,
      cash_flow_year_to_date: 274779125,
      profit_margin_percent: {
        Print: 15,
        TV: 15,
        Digital: 29,
      },
    },
    it: {
      website_uptime_percent: 99.9,
      broadcast_uptime_percent: 99.6,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 1,
      cybersecurity_incidents_resolved: 1,
      avg_ticket_resolution_hours: 4.0,
    },
    operations_production: {
      print_pages_per_hour: 8396,
      broadcast_segments_per_day: 157,
      distribution_on_time_percent: 96,
      printing_press_utilization_percent: 76,
      broadcast_equipment_utilization_percent: 83,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 4,
        TV: 8,
        Digital: 16,
      },
      CAC: 48,
      CLV: 381,
      market_share_percent: 38,
    },
  },
  {
    date: "2025-05-07",
    administrative_support: {
      employee_headcount: 476,
      employee_turnover_percent: 6.1,
      training_hours_per_employee: 13.5,
      employee_engagement_percent: 85,
    },
    editorial: {
      top_content: [
        {
          title: "Cultural Festival Coverage",
          views: 172569,
          channel: "Print",
        },
        {
          title: "Regional Sports Highlights",
          views: 118025,
          channel: "Digital",
        },
        {
          title: "Health & Lifestyle",
          views: 82708,
          channel: "Print",
        },
      ],
      avg_content_production_hours: 4.9,
      digital_users: 502210,
      print_circulation: 249489,
      broadcast_viewers: 708931,
    },
    finance: {
      revenue: 243990013,
      operating_costs: 199292270,
      cash_flow_month_to_date: 35215087,
      cash_flow_quarter_to_date: 110388788,
      cash_flow_year_to_date: 293011941,
      profit_margin_percent: {
        Print: 13,
        TV: 18,
        Digital: 28,
      },
    },
    it: {
      website_uptime_percent: 99.6,
      broadcast_uptime_percent: 99.8,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 2,
      cybersecurity_incidents_resolved: 1,
      avg_ticket_resolution_hours: 3.8,
    },
    operations_production: {
      print_pages_per_hour: 8159,
      broadcast_segments_per_day: 148,
      distribution_on_time_percent: 95,
      printing_press_utilization_percent: 72,
      broadcast_equipment_utilization_percent: 84,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 8,
        TV: 11,
        Digital: 20,
      },
      CAC: 57,
      CLV: 385,
      market_share_percent: 37,
    },
  },
  {
    date: "2025-05-14",
    administrative_support: {
      employee_headcount: 469,
      employee_turnover_percent: 7.3,
      training_hours_per_employee: 11.8,
      employee_engagement_percent: 84,
    },
    editorial: {
      top_content: [
        {
          title: "Cultural Festival Coverage",
          views: 105653,
          channel: "Print",
        },
        {
          title: "Regional Sports Highlights",
          views: 79187,
          channel: "Digital",
        },
        {
          title: "Health & Lifestyle",
          views: 67337,
          channel: "Digital",
        },
      ],
      avg_content_production_hours: 5.9,
      digital_users: 494649,
      print_circulation: 254536,
      broadcast_viewers: 686399,
    },
    finance: {
      revenue: 248115004,
      operating_costs: 172707072,
      cash_flow_month_to_date: 36118995,
      cash_flow_quarter_to_date: 104644987,
      cash_flow_year_to_date: 425345132,
      profit_margin_percent: {
        Print: 10,
        TV: 17,
        Digital: 26,
      },
    },
    it: {
      website_uptime_percent: 99.9,
      broadcast_uptime_percent: 99.3,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 2,
      cybersecurity_incidents_resolved: 2,
      avg_ticket_resolution_hours: 3.0,
    },
    operations_production: {
      print_pages_per_hour: 8053,
      broadcast_segments_per_day: 169,
      distribution_on_time_percent: 95,
      printing_press_utilization_percent: 76,
      broadcast_equipment_utilization_percent: 85,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 8,
        TV: 11,
        Digital: 19,
      },
      CAC: 54,
      CLV: 442,
      market_share_percent: 38,
    },
  },
  {
    date: "2025-05-21",
    administrative_support: {
      employee_headcount: 464,
      employee_turnover_percent: 7.2,
      training_hours_per_employee: 11.7,
      employee_engagement_percent: 85,
    },
    editorial: {
      top_content: [
        {
          title: "Cultural Festival Coverage",
          views: 163842,
          channel: "TV",
        },
        {
          title: "Regional Sports Highlights",
          views: 74542,
          channel: "Digital",
        },
        {
          title: "Sports Highlights",
          views: 97582,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 5.7,
      digital_users: 578085,
      print_circulation: 271413,
      broadcast_viewers: 737329,
    },
    finance: {
      revenue: 274571375,
      operating_costs: 172901089,
      cash_flow_month_to_date: 33727176,
      cash_flow_quarter_to_date: 98974891,
      cash_flow_year_to_date: 271066839,
      profit_margin_percent: {
        Print: 13,
        TV: 15,
        Digital: 30,
      },
    },
    it: {
      website_uptime_percent: 99.7,
      broadcast_uptime_percent: 99.6,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 0,
      cybersecurity_incidents_resolved: 4,
      avg_ticket_resolution_hours: 3.5,
    },
    operations_production: {
      print_pages_per_hour: 7948,
      broadcast_segments_per_day: 149,
      distribution_on_time_percent: 93,
      printing_press_utilization_percent: 75,
      broadcast_equipment_utilization_percent: 81,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 6,
        TV: 10,
        Digital: 17,
      },
      CAC: 49,
      CLV: 389,
      market_share_percent: 35,
    },
  },
  {
    date: "2025-05-28",
    administrative_support: {
      employee_headcount: 470,
      employee_turnover_percent: 6.8,
      training_hours_per_employee: 10.3,
      employee_engagement_percent: 83,
    },
    editorial: {
      top_content: [
        {
          title: "Political Debate Highlights",
          views: 164442,
          channel: "Digital",
        },
        {
          title: "National Sports Roundup",
          views: 60657,
          channel: "TV",
        },
        {
          title: "International News Roundup",
          views: 98300,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 4.9,
      digital_users: 559090,
      print_circulation: 249361,
      broadcast_viewers: 694688,
    },
    finance: {
      revenue: 274312565,
      operating_costs: 189277868,
      cash_flow_month_to_date: 36249288,
      cash_flow_quarter_to_date: 80694914,
      cash_flow_year_to_date: 467677081,
      profit_margin_percent: {
        Print: 15,
        TV: 19,
        Digital: 22,
      },
    },
    it: {
      website_uptime_percent: 99.6,
      broadcast_uptime_percent: 99.3,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 1,
      cybersecurity_incidents_resolved: 1,
      avg_ticket_resolution_hours: 4.7,
    },
    operations_production: {
      print_pages_per_hour: 7989,
      broadcast_segments_per_day: 162,
      distribution_on_time_percent: 94,
      printing_press_utilization_percent: 79,
      broadcast_equipment_utilization_percent: 82,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 4,
        TV: 7,
        Digital: 17,
      },
      CAC: 48,
      CLV: 410,
      market_share_percent: 37,
    },
  },
  {
    date: "2025-06-04",
    administrative_support: {
      employee_headcount: 472,
      employee_turnover_percent: 6.1,
      training_hours_per_employee: 10.8,
      employee_engagement_percent: 75,
    },
    editorial: {
      top_content: [
        {
          title: "Political Debate Highlights",
          views: 153912,
          channel: "Print",
        },
        {
          title: "Technology in Africa",
          views: 93137,
          channel: "Print",
        },
        {
          title: "Election Updates",
          views: 82009,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 4.8,
      digital_users: 484805,
      print_circulation: 243365,
      broadcast_viewers: 714450,
    },
    finance: {
      revenue: 265204738,
      operating_costs: 198050348,
      cash_flow_month_to_date: 30694201,
      cash_flow_quarter_to_date: 77063727,
      cash_flow_year_to_date: 295131725,
      profit_margin_percent: {
        Print: 14,
        TV: 17,
        Digital: 26,
      },
    },
    it: {
      website_uptime_percent: 99.8,
      broadcast_uptime_percent: 99.4,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 1,
      cybersecurity_incidents_resolved: 1,
      avg_ticket_resolution_hours: 4.4,
    },
    operations_production: {
      print_pages_per_hour: 8185,
      broadcast_segments_per_day: 163,
      distribution_on_time_percent: 95,
      printing_press_utilization_percent: 80,
      broadcast_equipment_utilization_percent: 85,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 7,
        TV: 7,
        Digital: 16,
      },
      CAC: 53,
      CLV: 411,
      market_share_percent: 36,
    },
  },
  {
    date: "2025-06-11",
    administrative_support: {
      employee_headcount: 458,
      employee_turnover_percent: 5.7,
      training_hours_per_employee: 14.4,
      employee_engagement_percent: 84,
    },
    editorial: {
      top_content: [
        {
          title: "Market Trends in Uganda",
          views: 168167,
          channel: "Print",
        },
        {
          title: "Regional Sports Highlights",
          views: 80663,
          channel: "Digital",
        },
        {
          title: "Education Reform",
          views: 95605,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 5.9,
      digital_users: 507734,
      print_circulation: 268286,
      broadcast_viewers: 716599,
    },
    finance: {
      revenue: 272983520,
      operating_costs: 198551566,
      cash_flow_month_to_date: 34386030,
      cash_flow_quarter_to_date: 99351752,
      cash_flow_year_to_date: 429189798,
      profit_margin_percent: {
        Print: 10,
        TV: 20,
        Digital: 25,
      },
    },
    it: {
      website_uptime_percent: 99.9,
      broadcast_uptime_percent: 99.3,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 2,
      cybersecurity_incidents_resolved: 4,
      avg_ticket_resolution_hours: 4.0,
    },
    operations_production: {
      print_pages_per_hour: 8405,
      broadcast_segments_per_day: 143,
      distribution_on_time_percent: 90,
      printing_press_utilization_percent: 75,
      broadcast_equipment_utilization_percent: 80,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 6,
        TV: 9,
        Digital: 20,
      },
      CAC: 55,
      CLV: 382,
      market_share_percent: 37,
    },
  },
  {
    date: "2025-06-18",
    administrative_support: {
      employee_headcount: 454,
      employee_turnover_percent: 5.8,
      training_hours_per_employee: 10.8,
      employee_engagement_percent: 76,
    },
    editorial: {
      top_content: [
        {
          title: "Cultural Festival Coverage",
          views: 144548,
          channel: "Print",
        },
        {
          title: "Weekend Editorial Feature",
          views: 106603,
          channel: "Digital",
        },
        {
          title: "International News Roundup",
          views: 51894,
          channel: "Print",
        },
      ],
      avg_content_production_hours: 4.8,
      digital_users: 514409,
      print_circulation: 248595,
      broadcast_viewers: 685971,
    },
    finance: {
      revenue: 279405573,
      operating_costs: 185835207,
      cash_flow_month_to_date: 38592653,
      cash_flow_quarter_to_date: 83959858,
      cash_flow_year_to_date: 344583143,
      profit_margin_percent: {
        Print: 11,
        TV: 19,
        Digital: 30,
      },
    },
    it: {
      website_uptime_percent: 99.7,
      broadcast_uptime_percent: 99.4,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 3,
      cybersecurity_incidents_resolved: 3,
      avg_ticket_resolution_hours: 4.1,
    },
    operations_production: {
      print_pages_per_hour: 8068,
      broadcast_segments_per_day: 156,
      distribution_on_time_percent: 90,
      printing_press_utilization_percent: 78,
      broadcast_equipment_utilization_percent: 83,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 4,
        TV: 9,
        Digital: 18,
      },
      CAC: 51,
      CLV: 386,
      market_share_percent: 34,
    },
  },
  {
    date: "2025-06-25",
    administrative_support: {
      employee_headcount: 479,
      employee_turnover_percent: 7.1,
      training_hours_per_employee: 14.9,
      employee_engagement_percent: 82,
    },
    editorial: {
      top_content: [
        {
          title: "Presidential Address Recap",
          views: 119521,
          channel: "Digital",
        },
        {
          title: "Technology in Africa",
          views: 133347,
          channel: "Digital",
        },
        {
          title: "Education Reform",
          views: 101717,
          channel: "Digital",
        },
      ],
      avg_content_production_hours: 5.8,
      digital_users: 546685,
      print_circulation: 250393,
      broadcast_viewers: 734556,
    },
    finance: {
      revenue: 240384863,
      operating_costs: 194531679,
      cash_flow_month_to_date: 34533403,
      cash_flow_quarter_to_date: 93153763,
      cash_flow_year_to_date: 490887318,
      profit_margin_percent: {
        Print: 11,
        TV: 18,
        Digital: 27,
      },
    },
    it: {
      website_uptime_percent: 99.8,
      broadcast_uptime_percent: 99.7,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 4,
      cybersecurity_incidents_resolved: 0,
      avg_ticket_resolution_hours: 4.2,
    },
    operations_production: {
      print_pages_per_hour: 7988,
      broadcast_segments_per_day: 168,
      distribution_on_time_percent: 92,
      printing_press_utilization_percent: 74,
      broadcast_equipment_utilization_percent: 80,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 7,
        TV: 9,
        Digital: 18,
      },
      CAC: 59,
      CLV: 404,
      market_share_percent: 37,
    },
  },
  {
    date: "2025-07-02",
    administrative_support: {
      employee_headcount: 448,
      employee_turnover_percent: 7.2,
      training_hours_per_employee: 14.3,
      employee_engagement_percent: 81,
    },
    editorial: {
      top_content: [
        {
          title: "Sports Weekly Recap",
          views: 121648,
          channel: "Digital",
        },
        {
          title: "Regional Sports Highlights",
          views: 124634,
          channel: "Digital",
        },
        {
          title: "Health & Lifestyle",
          views: 84255,
          channel: "Print",
        },
      ],
      avg_content_production_hours: 4.7,
      digital_users: 528774,
      print_circulation: 275388,
      broadcast_viewers: 714135,
    },
    finance: {
      revenue: 269196063,
      operating_costs: 178717216,
      cash_flow_month_to_date: 27514649,
      cash_flow_quarter_to_date: 98781903,
      cash_flow_year_to_date: 329321873,
      profit_margin_percent: {
        Print: 11,
        TV: 19,
        Digital: 23,
      },
    },
    it: {
      website_uptime_percent: 99.8,
      broadcast_uptime_percent: 99.4,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 2,
      cybersecurity_incidents_resolved: 2,
      avg_ticket_resolution_hours: 4.3,
    },
    operations_production: {
      print_pages_per_hour: 8486,
      broadcast_segments_per_day: 153,
      distribution_on_time_percent: 96,
      printing_press_utilization_percent: 78,
      broadcast_equipment_utilization_percent: 81,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 4,
        TV: 12,
        Digital: 18,
      },
      CAC: 60,
      CLV: 401,
      market_share_percent: 36,
    },
  },
  {
    date: "2025-07-09",
    administrative_support: {
      employee_headcount: 450,
      employee_turnover_percent: 7.2,
      training_hours_per_employee: 14.0,
      employee_engagement_percent: 75,
    },
    editorial: {
      top_content: [
        {
          title: "New Education Policy",
          views: 78130,
          channel: "Digital",
        },
        {
          title: "Technology in Africa",
          views: 69941,
          channel: "TV",
        },
        {
          title: "Sports Highlights",
          views: 118620,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 5.2,
      digital_users: 557844,
      print_circulation: 241729,
      broadcast_viewers: 699346,
    },
    finance: {
      revenue: 252338503,
      operating_costs: 193702355,
      cash_flow_month_to_date: 31483185,
      cash_flow_quarter_to_date: 101128033,
      cash_flow_year_to_date: 276747401,
      profit_margin_percent: {
        Print: 13,
        TV: 20,
        Digital: 29,
      },
    },
    it: {
      website_uptime_percent: 99.6,
      broadcast_uptime_percent: 99.5,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 1,
      cybersecurity_incidents_resolved: 3,
      avg_ticket_resolution_hours: 3.7,
    },
    operations_production: {
      print_pages_per_hour: 8142,
      broadcast_segments_per_day: 170,
      distribution_on_time_percent: 90,
      printing_press_utilization_percent: 73,
      broadcast_equipment_utilization_percent: 82,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 6,
        TV: 12,
        Digital: 14,
      },
      CAC: 53,
      CLV: 401,
      market_share_percent: 33,
    },
  },
  {
    date: "2025-07-16",
    administrative_support: {
      employee_headcount: 440,
      employee_turnover_percent: 6.6,
      training_hours_per_employee: 12.9,
      employee_engagement_percent: 77,
    },
    editorial: {
      top_content: [
        {
          title: "Cultural Festival Coverage",
          views: 144015,
          channel: "Print",
        },
        {
          title: "National Sports Roundup",
          views: 145458,
          channel: "Digital",
        },
        {
          title: "Education Reform",
          views: 82968,
          channel: "Digital",
        },
      ],
      avg_content_production_hours: 4.9,
      digital_users: 580554,
      print_circulation: 247445,
      broadcast_viewers: 680112,
    },
    finance: {
      revenue: 250854494,
      operating_costs: 171299655,
      cash_flow_month_to_date: 35805769,
      cash_flow_quarter_to_date: 118867920,
      cash_flow_year_to_date: 354378503,
      profit_margin_percent: {
        Print: 14,
        TV: 19,
        Digital: 20,
      },
    },
    it: {
      website_uptime_percent: 99.9,
      broadcast_uptime_percent: 99.5,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 2,
      cybersecurity_incidents_resolved: 0,
      avg_ticket_resolution_hours: 4.7,
    },
    operations_production: {
      print_pages_per_hour: 8191,
      broadcast_segments_per_day: 155,
      distribution_on_time_percent: 91,
      printing_press_utilization_percent: 72,
      broadcast_equipment_utilization_percent: 82,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 6,
        TV: 9,
        Digital: 19,
      },
      CAC: 48,
      CLV: 389,
      market_share_percent: 36,
    },
  },
  {
    date: "2025-07-23",
    administrative_support: {
      employee_headcount: 460,
      employee_turnover_percent: 6.4,
      training_hours_per_employee: 11.6,
      employee_engagement_percent: 80,
    },
    editorial: {
      top_content: [
        {
          title: "Cultural Festival Coverage",
          views: 103892,
          channel: "Print",
        },
        {
          title: "Economic Policy Analysis",
          views: 128151,
          channel: "Digital",
        },
        {
          title: "Sports Highlights",
          views: 106720,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 5.5,
      digital_users: 591029,
      print_circulation: 258140,
      broadcast_viewers: 692393,
    },
    finance: {
      revenue: 251630581,
      operating_costs: 180201041,
      cash_flow_month_to_date: 30436973,
      cash_flow_quarter_to_date: 82660761,
      cash_flow_year_to_date: 288396686,
      profit_margin_percent: {
        Print: 13,
        TV: 19,
        Digital: 24,
      },
    },
    it: {
      website_uptime_percent: 99.7,
      broadcast_uptime_percent: 99.8,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 3,
      cybersecurity_incidents_resolved: 2,
      avg_ticket_resolution_hours: 3.7,
    },
    operations_production: {
      print_pages_per_hour: 8056,
      broadcast_segments_per_day: 165,
      distribution_on_time_percent: 91,
      printing_press_utilization_percent: 78,
      broadcast_equipment_utilization_percent: 84,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 4,
        TV: 10,
        Digital: 18,
      },
      CAC: 51,
      CLV: 429,
      market_share_percent: 35,
    },
  },
  {
    date: "2025-07-30",
    administrative_support: {
      employee_headcount: 448,
      employee_turnover_percent: 6.6,
      training_hours_per_employee: 14.2,
      employee_engagement_percent: 78,
    },
    editorial: {
      top_content: [
        {
          title: "New Education Policy",
          views: 147640,
          channel: "TV",
        },
        {
          title: "Weekend Editorial Feature",
          views: 67579,
          channel: "TV",
        },
        {
          title: "Health & Lifestyle",
          views: 83256,
          channel: "Print",
        },
      ],
      avg_content_production_hours: 5.9,
      digital_users: 480098,
      print_circulation: 278217,
      broadcast_viewers: 688353,
    },
    finance: {
      revenue: 254614015,
      operating_costs: 191165655,
      cash_flow_month_to_date: 35075857,
      cash_flow_quarter_to_date: 78664823,
      cash_flow_year_to_date: 475782396,
      profit_margin_percent: {
        Print: 11,
        TV: 16,
        Digital: 20,
      },
    },
    it: {
      website_uptime_percent: 99.8,
      broadcast_uptime_percent: 99.3,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 3,
      cybersecurity_incidents_resolved: 2,
      avg_ticket_resolution_hours: 3.7,
    },
    operations_production: {
      print_pages_per_hour: 8320,
      broadcast_segments_per_day: 148,
      distribution_on_time_percent: 93,
      printing_press_utilization_percent: 79,
      broadcast_equipment_utilization_percent: 81,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 7,
        TV: 9,
        Digital: 14,
      },
      CAC: 55,
      CLV: 424,
      market_share_percent: 35,
    },
  },
  {
    date: "2025-08-06",
    administrative_support: {
      employee_headcount: 445,
      employee_turnover_percent: 5.6,
      training_hours_per_employee: 13.3,
      employee_engagement_percent: 76,
    },
    editorial: {
      top_content: [
        {
          title: "Political Debate Highlights",
          views: 166185,
          channel: "TV",
        },
        {
          title: "Weekend Editorial Feature",
          views: 65961,
          channel: "Digital",
        },
        {
          title: "Health & Lifestyle",
          views: 83877,
          channel: "Print",
        },
      ],
      avg_content_production_hours: 5.1,
      digital_users: 544352,
      print_circulation: 269749,
      broadcast_viewers: 681589,
    },
    finance: {
      revenue: 242629586,
      operating_costs: 191141685,
      cash_flow_month_to_date: 28868203,
      cash_flow_quarter_to_date: 95411497,
      cash_flow_year_to_date: 436826520,
      profit_margin_percent: {
        Print: 15,
        TV: 18,
        Digital: 23,
      },
    },
    it: {
      website_uptime_percent: 99.7,
      broadcast_uptime_percent: 99.6,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 2,
      cybersecurity_incidents_resolved: 0,
      avg_ticket_resolution_hours: 3.6,
    },
    operations_production: {
      print_pages_per_hour: 8490,
      broadcast_segments_per_day: 166,
      distribution_on_time_percent: 91,
      printing_press_utilization_percent: 72,
      broadcast_equipment_utilization_percent: 84,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 7,
        TV: 11,
        Digital: 16,
      },
      CAC: 48,
      CLV: 409,
      market_share_percent: 35,
    },
  },
  {
    date: "2025-08-13",
    administrative_support: {
      employee_headcount: 479,
      employee_turnover_percent: 6.3,
      training_hours_per_employee: 10.2,
      employee_engagement_percent: 78,
    },
    editorial: {
      top_content: [
        {
          title: "Market Trends in Uganda",
          views: 113226,
          channel: "Print",
        },
        {
          title: "Weekend Editorial Feature",
          views: 95886,
          channel: "TV",
        },
        {
          title: "Sports Highlights",
          views: 70947,
          channel: "Print",
        },
      ],
      avg_content_production_hours: 5.7,
      digital_users: 573836,
      print_circulation: 250205,
      broadcast_viewers: 709487,
    },
    finance: {
      revenue: 253054679,
      operating_costs: 173339272,
      cash_flow_month_to_date: 28093863,
      cash_flow_quarter_to_date: 75645998,
      cash_flow_year_to_date: 361086318,
      profit_margin_percent: {
        Print: 10,
        TV: 15,
        Digital: 28,
      },
    },
    it: {
      website_uptime_percent: 99.6,
      broadcast_uptime_percent: 99.4,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 3,
      cybersecurity_incidents_resolved: 4,
      avg_ticket_resolution_hours: 3.7,
    },
    operations_production: {
      print_pages_per_hour: 8207,
      broadcast_segments_per_day: 153,
      distribution_on_time_percent: 96,
      printing_press_utilization_percent: 80,
      broadcast_equipment_utilization_percent: 85,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 8,
        TV: 10,
        Digital: 19,
      },
      CAC: 48,
      CLV: 440,
      market_share_percent: 35,
    },
  },
  {
    date: "2025-08-20",
    administrative_support: {
      employee_headcount: 456,
      employee_turnover_percent: 7.3,
      training_hours_per_employee: 13.1,
      employee_engagement_percent: 80,
    },
    editorial: {
      top_content: [
        {
          title: "Sports Weekly Recap",
          views: 116436,
          channel: "Print",
        },
        {
          title: "Technology in Africa",
          views: 76658,
          channel: "Print",
        },
        {
          title: "Education Reform",
          views: 78723,
          channel: "TV",
        },
      ],
      avg_content_production_hours: 5.0,
      digital_users: 520590,
      print_circulation: 245812,
      broadcast_viewers: 711499,
    },
    finance: {
      revenue: 255931131,
      operating_costs: 172781216,
      cash_flow_month_to_date: 37465838,
      cash_flow_quarter_to_date: 86658823,
      cash_flow_year_to_date: 436327541,
      profit_margin_percent: {
        Print: 13,
        TV: 20,
        Digital: 21,
      },
    },
    it: {
      website_uptime_percent: 99.5,
      broadcast_uptime_percent: 99.5,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 1,
      cybersecurity_incidents_resolved: 2,
      avg_ticket_resolution_hours: 4.4,
    },
    operations_production: {
      print_pages_per_hour: 8280,
      broadcast_segments_per_day: 155,
      distribution_on_time_percent: 95,
      printing_press_utilization_percent: 78,
      broadcast_equipment_utilization_percent: 85,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 8,
        TV: 10,
        Digital: 20,
      },
      CAC: 49,
      CLV: 382,
      market_share_percent: 33,
    },
  },
  {
    date: "2025-08-27",
    administrative_support: {
      employee_headcount: 479,
      employee_turnover_percent: 7.1,
      training_hours_per_employee: 12.0,
      employee_engagement_percent: 77,
    },
    editorial: {
      top_content: [
        {
          title: "Political Debate Highlights",
          views: 129406,
          channel: "Digital",
        },
        {
          title: "Regional Sports Highlights",
          views: 128113,
          channel: "Print",
        },
        {
          title: "Health & Lifestyle",
          views: 66245,
          channel: "Print",
        },
      ],
      avg_content_production_hours: 5.6,
      digital_users: 480699,
      print_circulation: 241408,
      broadcast_viewers: 706975,
    },
    finance: {
      revenue: 242324262,
      operating_costs: 172497722,
      cash_flow_month_to_date: 30264067,
      cash_flow_quarter_to_date: 82335021,
      cash_flow_year_to_date: 250671666,
      profit_margin_percent: {
        Print: 15,
        TV: 15,
        Digital: 25,
      },
    },
    it: {
      website_uptime_percent: 99.8,
      broadcast_uptime_percent: 99.6,
      internal_systems_uptime_percent: 99.9,
      cybersecurity_incidents_detected: 4,
      cybersecurity_incidents_resolved: 0,
      avg_ticket_resolution_hours: 4.7,
    },
    operations_production: {
      print_pages_per_hour: 8186,
      broadcast_segments_per_day: 158,
      distribution_on_time_percent: 94,
      printing_press_utilization_percent: 72,
      broadcast_equipment_utilization_percent: 82,
    },
    sales_marketing: {
      ad_revenue_growth_percent: {
        Print: 4,
        TV: 9,
        Digital: 14,
      },
      CAC: 55,
      CLV: 445,
      market_share_percent: 33,
    },
  },
];

export default wide_kpis;
