const assessments = [
  {
    date: "2025-01-01",
    departments: [
      {
        department: "Finance",
        totalRisks: 28,
        mitigatedRisks: 17,
        mitigationEffectiveness: 61,
        topIneffectiveControls: ["Incident Response", "System Redundancy"],
        residualRiskScore: 45,
      },
      {
        department: "Operations",
        totalRisks: 20,
        mitigatedRisks: 20,
        mitigationEffectiveness: 100,
        topIneffectiveControls: ["Vendor Management", "Incident Response"],
        residualRiskScore: 25,
      },
      {
        department: "IT",
        totalRisks: 33,
        mitigatedRisks: 30,
        mitigationEffectiveness: 91,
        topIneffectiveControls: ["Vendor Management", "Incident Response"],
        residualRiskScore: 31,
      },
      {
        department: "HR",
        totalRisks: 22,
        mitigatedRisks: 18,
        mitigationEffectiveness: 82,
        topIneffectiveControls: ["Vendor Management", "Training Program"],
        residualRiskScore: 23,
      },
      {
        department: "Marketing",
        totalRisks: 25,
        mitigatedRisks: 23,
        mitigationEffectiveness: 92,
        topIneffectiveControls: ["Vendor Management", "System Redundancy"],
        residualRiskScore: 28,
      },
      {
        department: "Sales",
        totalRisks: 27,
        mitigatedRisks: 20,
        mitigationEffectiveness: 74,
        topIneffectiveControls: ["Access Controls", "Vendor Management"],
        residualRiskScore: 31,
      },
    ],
  },
  {
    date: "2025-01-08",
    departments: [
      {
        department: "Finance",
        totalRisks: 25,
        mitigatedRisks: 20,
        mitigationEffectiveness: 80,
        topIneffectiveControls: ["Access Controls", "Incident Response"],
        residualRiskScore: 47,
      },
      {
        department: "Operations",
        totalRisks: 20,
        mitigatedRisks: 17,
        mitigationEffectiveness: 85,
        topIneffectiveControls: ["Vendor Management", "Incident Response"],
        residualRiskScore: 40,
      },
      {
        department: "IT",
        totalRisks: 35,
        mitigatedRisks: 14,
        mitigationEffectiveness: 40,
        topIneffectiveControls: ["Incident Response", "Vendor Management"],
        residualRiskScore: 43,
      },
      {
        department: "HR",
        totalRisks: 26,
        mitigatedRisks: 16,
        mitigationEffectiveness: 62,
        topIneffectiveControls: ["Incident Response", "Access Controls"],
        residualRiskScore: 27,
      },
      {
        department: "Marketing",
        totalRisks: 26,
        mitigatedRisks: 11,
        mitigationEffectiveness: 42,
        topIneffectiveControls: ["Access Controls", "Vendor Management"],
        residualRiskScore: 37,
      },
      {
        department: "Sales",
        totalRisks: 32,
        mitigatedRisks: 15,
        mitigationEffectiveness: 47,
        topIneffectiveControls: ["Access Controls", "Training Program"],
        residualRiskScore: 31,
      },
    ],
  },
  {
    date: "2025-01-15",
    departments: [
      {
        department: "Finance",
        totalRisks: 38,
        mitigatedRisks: 30,
        mitigationEffectiveness: 79,
        topIneffectiveControls: ["Incident Response", "Training Program"],
        residualRiskScore: 47,
      },
      {
        department: "Operations",
        totalRisks: 29,
        mitigatedRisks: 25,
        mitigationEffectiveness: 86,
        topIneffectiveControls: ["System Redundancy", "Incident Response"],
        residualRiskScore: 48,
      },
      {
        department: "IT",
        totalRisks: 33,
        mitigatedRisks: 12,
        mitigationEffectiveness: 36,
        topIneffectiveControls: ["System Redundancy", "Incident Response"],
        residualRiskScore: 41,
      },
      {
        department: "HR",
        totalRisks: 37,
        mitigatedRisks: 30,
        mitigationEffectiveness: 81,
        topIneffectiveControls: ["Training Program", "Incident Response"],
        residualRiskScore: 35,
      },
      {
        department: "Marketing",
        totalRisks: 20,
        mitigatedRisks: 11,
        mitigationEffectiveness: 55,
        topIneffectiveControls: ["System Redundancy", "Vendor Management"],
        residualRiskScore: 25,
      },
      {
        department: "Sales",
        totalRisks: 34,
        mitigatedRisks: 15,
        mitigationEffectiveness: 44,
        topIneffectiveControls: ["System Redundancy", "Access Controls"],
        residualRiskScore: 43,
      },
    ],
  },
  {
    date: "2025-01-22",
    departments: [
      {
        department: "Finance",
        totalRisks: 21,
        mitigatedRisks: 10,
        mitigationEffectiveness: 48,
        topIneffectiveControls: ["Training Program", "Incident Response"],
        residualRiskScore: 33,
      },
      {
        department: "Operations",
        totalRisks: 29,
        mitigatedRisks: 22,
        mitigationEffectiveness: 76,
        topIneffectiveControls: ["Vendor Management", "System Redundancy"],
        residualRiskScore: 29,
      },
      {
        department: "IT",
        totalRisks: 20,
        mitigatedRisks: 19,
        mitigationEffectiveness: 95,
        topIneffectiveControls: ["Vendor Management", "System Redundancy"],
        residualRiskScore: 25,
      },
      {
        department: "HR",
        totalRisks: 37,
        mitigatedRisks: 26,
        mitigationEffectiveness: 70,
        topIneffectiveControls: ["Training Program", "Vendor Management"],
        residualRiskScore: 33,
      },
      {
        department: "Marketing",
        totalRisks: 31,
        mitigatedRisks: 28,
        mitigationEffectiveness: 90,
        topIneffectiveControls: ["Access Controls", "Training Program"],
        residualRiskScore: 20,
      },
      {
        department: "Sales",
        totalRisks: 28,
        mitigatedRisks: 18,
        mitigationEffectiveness: 64,
        topIneffectiveControls: ["Access Controls", "Training Program"],
        residualRiskScore: 24,
      },
    ],
  },
  {
    date: "2025-01-29",
    departments: [
      {
        department: "Finance",
        totalRisks: 25,
        mitigatedRisks: 12,
        mitigationEffectiveness: 48,
        topIneffectiveControls: ["Training Program", "Vendor Management"],
        residualRiskScore: 45,
      },
      {
        department: "Operations",
        totalRisks: 20,
        mitigatedRisks: 14,
        mitigationEffectiveness: 70,
        topIneffectiveControls: ["Access Controls", "Incident Response"],
        residualRiskScore: 25,
      },
      {
        department: "IT",
        totalRisks: 26,
        mitigatedRisks: 19,
        mitigationEffectiveness: 73,
        topIneffectiveControls: ["Vendor Management", "Access Controls"],
        residualRiskScore: 22,
      },
      {
        department: "HR",
        totalRisks: 23,
        mitigatedRisks: 18,
        mitigationEffectiveness: 78,
        topIneffectiveControls: ["System Redundancy", "Vendor Management"],
        residualRiskScore: 34,
      },
      {
        department: "Marketing",
        totalRisks: 25,
        mitigatedRisks: 14,
        mitigationEffectiveness: 56,
        topIneffectiveControls: ["Access Controls", "Training Program"],
        residualRiskScore: 44,
      },
      {
        department: "Sales",
        totalRisks: 27,
        mitigatedRisks: 11,
        mitigationEffectiveness: 41,
        topIneffectiveControls: ["Training Program", "System Redundancy"],
        residualRiskScore: 22,
      },
    ],
  },
  {
    date: "2025-02-05",
    departments: [
      {
        department: "Finance",
        totalRisks: 27,
        mitigatedRisks: 17,
        mitigationEffectiveness: 63,
        topIneffectiveControls: ["Training Program", "Access Controls"],
        residualRiskScore: 23,
      },
      {
        department: "Operations",
        totalRisks: 26,
        mitigatedRisks: 11,
        mitigationEffectiveness: 42,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 46,
      },
      {
        department: "IT",
        totalRisks: 26,
        mitigatedRisks: 26,
        mitigationEffectiveness: 100,
        topIneffectiveControls: ["Training Program", "Access Controls"],
        residualRiskScore: 34,
      },
      {
        department: "HR",
        totalRisks: 26,
        mitigatedRisks: 14,
        mitigationEffectiveness: 54,
        topIneffectiveControls: ["Vendor Management", "Training Program"],
        residualRiskScore: 20,
      },
      {
        department: "Marketing",
        totalRisks: 30,
        mitigatedRisks: 18,
        mitigationEffectiveness: 60,
        topIneffectiveControls: ["System Redundancy", "Vendor Management"],
        residualRiskScore: 22,
      },
      {
        department: "Sales",
        totalRisks: 31,
        mitigatedRisks: 13,
        mitigationEffectiveness: 42,
        topIneffectiveControls: ["Vendor Management", "Training Program"],
        residualRiskScore: 27,
      },
    ],
  },
  {
    date: "2025-02-12",
    departments: [
      {
        department: "Finance",
        totalRisks: 33,
        mitigatedRisks: 18,
        mitigationEffectiveness: 55,
        topIneffectiveControls: ["Incident Response", "Training Program"],
        residualRiskScore: 48,
      },
      {
        department: "Operations",
        totalRisks: 32,
        mitigatedRisks: 15,
        mitigationEffectiveness: 47,
        topIneffectiveControls: ["Incident Response", "Access Controls"],
        residualRiskScore: 33,
      },
      {
        department: "IT",
        totalRisks: 40,
        mitigatedRisks: 18,
        mitigationEffectiveness: 45,
        topIneffectiveControls: ["Incident Response", "Vendor Management"],
        residualRiskScore: 42,
      },
      {
        department: "HR",
        totalRisks: 25,
        mitigatedRisks: 18,
        mitigationEffectiveness: 72,
        topIneffectiveControls: ["Training Program", "Vendor Management"],
        residualRiskScore: 39,
      },
      {
        department: "Marketing",
        totalRisks: 23,
        mitigatedRisks: 18,
        mitigationEffectiveness: 78,
        topIneffectiveControls: ["Training Program", "System Redundancy"],
        residualRiskScore: 50,
      },
      {
        department: "Sales",
        totalRisks: 37,
        mitigatedRisks: 16,
        mitigationEffectiveness: 43,
        topIneffectiveControls: ["System Redundancy", "Incident Response"],
        residualRiskScore: 31,
      },
    ],
  },
  {
    date: "2025-02-19",
    departments: [
      {
        department: "Finance",
        totalRisks: 32,
        mitigatedRisks: 17,
        mitigationEffectiveness: 53,
        topIneffectiveControls: ["Training Program", "Vendor Management"],
        residualRiskScore: 42,
      },
      {
        department: "Operations",
        totalRisks: 36,
        mitigatedRisks: 31,
        mitigationEffectiveness: 86,
        topIneffectiveControls: ["Incident Response", "Vendor Management"],
        residualRiskScore: 34,
      },
      {
        department: "IT",
        totalRisks: 25,
        mitigatedRisks: 23,
        mitigationEffectiveness: 92,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 34,
      },
      {
        department: "HR",
        totalRisks: 35,
        mitigatedRisks: 20,
        mitigationEffectiveness: 57,
        topIneffectiveControls: ["Incident Response", "Training Program"],
        residualRiskScore: 23,
      },
      {
        department: "Marketing",
        totalRisks: 35,
        mitigatedRisks: 34,
        mitigationEffectiveness: 97,
        topIneffectiveControls: ["System Redundancy", "Access Controls"],
        residualRiskScore: 36,
      },
      {
        department: "Sales",
        totalRisks: 37,
        mitigatedRisks: 27,
        mitigationEffectiveness: 73,
        topIneffectiveControls: ["Training Program", "Vendor Management"],
        residualRiskScore: 37,
      },
    ],
  },
  {
    date: "2025-02-26",
    departments: [
      {
        department: "Finance",
        totalRisks: 34,
        mitigatedRisks: 32,
        mitigationEffectiveness: 94,
        topIneffectiveControls: ["System Redundancy", "Access Controls"],
        residualRiskScore: 45,
      },
      {
        department: "Operations",
        totalRisks: 35,
        mitigatedRisks: 16,
        mitigationEffectiveness: 46,
        topIneffectiveControls: ["Incident Response", "Access Controls"],
        residualRiskScore: 34,
      },
      {
        department: "IT",
        totalRisks: 28,
        mitigatedRisks: 13,
        mitigationEffectiveness: 46,
        topIneffectiveControls: ["Incident Response", "Training Program"],
        residualRiskScore: 46,
      },
      {
        department: "HR",
        totalRisks: 38,
        mitigatedRisks: 21,
        mitigationEffectiveness: 55,
        topIneffectiveControls: ["Access Controls", "Incident Response"],
        residualRiskScore: 29,
      },
      {
        department: "Marketing",
        totalRisks: 29,
        mitigatedRisks: 22,
        mitigationEffectiveness: 76,
        topIneffectiveControls: ["Vendor Management", "System Redundancy"],
        residualRiskScore: 50,
      },
      {
        department: "Sales",
        totalRisks: 27,
        mitigatedRisks: 19,
        mitigationEffectiveness: 70,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 46,
      },
    ],
  },
  {
    date: "2025-03-05",
    departments: [
      {
        department: "Finance",
        totalRisks: 27,
        mitigatedRisks: 19,
        mitigationEffectiveness: 70,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 36,
      },
      {
        department: "Operations",
        totalRisks: 22,
        mitigatedRisks: 18,
        mitigationEffectiveness: 82,
        topIneffectiveControls: ["Vendor Management", "Incident Response"],
        residualRiskScore: 36,
      },
      {
        department: "IT",
        totalRisks: 34,
        mitigatedRisks: 16,
        mitigationEffectiveness: 47,
        topIneffectiveControls: ["Access Controls", "Training Program"],
        residualRiskScore: 48,
      },
      {
        department: "HR",
        totalRisks: 38,
        mitigatedRisks: 15,
        mitigationEffectiveness: 39,
        topIneffectiveControls: ["Training Program", "Incident Response"],
        residualRiskScore: 47,
      },
      {
        department: "Marketing",
        totalRisks: 21,
        mitigatedRisks: 19,
        mitigationEffectiveness: 90,
        topIneffectiveControls: ["Vendor Management", "Access Controls"],
        residualRiskScore: 22,
      },
      {
        department: "Sales",
        totalRisks: 34,
        mitigatedRisks: 23,
        mitigationEffectiveness: 68,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 44,
      },
    ],
  },
  {
    date: "2025-03-12",
    departments: [
      {
        department: "Finance",
        totalRisks: 38,
        mitigatedRisks: 24,
        mitigationEffectiveness: 63,
        topIneffectiveControls: ["Vendor Management", "System Redundancy"],
        residualRiskScore: 40,
      },
      {
        department: "Operations",
        totalRisks: 36,
        mitigatedRisks: 15,
        mitigationEffectiveness: 42,
        topIneffectiveControls: ["Training Program", "Incident Response"],
        residualRiskScore: 38,
      },
      {
        department: "IT",
        totalRisks: 26,
        mitigatedRisks: 25,
        mitigationEffectiveness: 96,
        topIneffectiveControls: ["Vendor Management", "Training Program"],
        residualRiskScore: 34,
      },
      {
        department: "HR",
        totalRisks: 21,
        mitigatedRisks: 21,
        mitigationEffectiveness: 100,
        topIneffectiveControls: ["Incident Response", "System Redundancy"],
        residualRiskScore: 31,
      },
      {
        department: "Marketing",
        totalRisks: 24,
        mitigatedRisks: 18,
        mitigationEffectiveness: 75,
        topIneffectiveControls: ["Training Program", "System Redundancy"],
        residualRiskScore: 34,
      },
      {
        department: "Sales",
        totalRisks: 29,
        mitigatedRisks: 19,
        mitigationEffectiveness: 66,
        topIneffectiveControls: ["System Redundancy", "Incident Response"],
        residualRiskScore: 49,
      },
    ],
  },
  {
    date: "2025-03-19",
    departments: [
      {
        department: "Finance",
        totalRisks: 34,
        mitigatedRisks: 15,
        mitigationEffectiveness: 44,
        topIneffectiveControls: ["Vendor Management", "Incident Response"],
        residualRiskScore: 21,
      },
      {
        department: "Operations",
        totalRisks: 37,
        mitigatedRisks: 24,
        mitigationEffectiveness: 65,
        topIneffectiveControls: ["Incident Response", "System Redundancy"],
        residualRiskScore: 20,
      },
      {
        department: "IT",
        totalRisks: 32,
        mitigatedRisks: 13,
        mitigationEffectiveness: 41,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 40,
      },
      {
        department: "HR",
        totalRisks: 21,
        mitigatedRisks: 19,
        mitigationEffectiveness: 90,
        topIneffectiveControls: ["Incident Response", "Training Program"],
        residualRiskScore: 29,
      },
      {
        department: "Marketing",
        totalRisks: 27,
        mitigatedRisks: 22,
        mitigationEffectiveness: 81,
        topIneffectiveControls: ["Vendor Management", "Access Controls"],
        residualRiskScore: 27,
      },
      {
        department: "Sales",
        totalRisks: 29,
        mitigatedRisks: 11,
        mitigationEffectiveness: 38,
        topIneffectiveControls: ["System Redundancy", "Vendor Management"],
        residualRiskScore: 41,
      },
    ],
  },
  {
    date: "2025-03-26",
    departments: [
      {
        department: "Finance",
        totalRisks: 22,
        mitigatedRisks: 15,
        mitigationEffectiveness: 68,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 22,
      },
      {
        department: "Operations",
        totalRisks: 27,
        mitigatedRisks: 26,
        mitigationEffectiveness: 96,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 41,
      },
      {
        department: "IT",
        totalRisks: 24,
        mitigatedRisks: 24,
        mitigationEffectiveness: 100,
        topIneffectiveControls: ["Incident Response", "Training Program"],
        residualRiskScore: 29,
      },
      {
        department: "HR",
        totalRisks: 32,
        mitigatedRisks: 27,
        mitigationEffectiveness: 84,
        topIneffectiveControls: ["Training Program", "Vendor Management"],
        residualRiskScore: 23,
      },
      {
        department: "Marketing",
        totalRisks: 39,
        mitigatedRisks: 28,
        mitigationEffectiveness: 72,
        topIneffectiveControls: ["System Redundancy", "Vendor Management"],
        residualRiskScore: 48,
      },
      {
        department: "Sales",
        totalRisks: 27,
        mitigatedRisks: 24,
        mitigationEffectiveness: 89,
        topIneffectiveControls: ["Vendor Management", "Training Program"],
        residualRiskScore: 25,
      },
    ],
  },
  {
    date: "2025-04-02",
    departments: [
      {
        department: "Finance",
        totalRisks: 20,
        mitigatedRisks: 13,
        mitigationEffectiveness: 65,
        topIneffectiveControls: ["Access Controls", "Vendor Management"],
        residualRiskScore: 38,
      },
      {
        department: "Operations",
        totalRisks: 30,
        mitigatedRisks: 10,
        mitigationEffectiveness: 33,
        topIneffectiveControls: ["Training Program", "Access Controls"],
        residualRiskScore: 27,
      },
      {
        department: "IT",
        totalRisks: 32,
        mitigatedRisks: 15,
        mitigationEffectiveness: 47,
        topIneffectiveControls: ["Incident Response", "Vendor Management"],
        residualRiskScore: 42,
      },
      {
        department: "HR",
        totalRisks: 34,
        mitigatedRisks: 15,
        mitigationEffectiveness: 44,
        topIneffectiveControls: ["Access Controls", "Incident Response"],
        residualRiskScore: 38,
      },
      {
        department: "Marketing",
        totalRisks: 37,
        mitigatedRisks: 21,
        mitigationEffectiveness: 57,
        topIneffectiveControls: ["Access Controls", "Vendor Management"],
        residualRiskScore: 27,
      },
      {
        department: "Sales",
        totalRisks: 20,
        mitigatedRisks: 11,
        mitigationEffectiveness: 55,
        topIneffectiveControls: ["Vendor Management", "Incident Response"],
        residualRiskScore: 44,
      },
    ],
  },
  {
    date: "2025-04-09",
    departments: [
      {
        department: "Finance",
        totalRisks: 27,
        mitigatedRisks: 13,
        mitigationEffectiveness: 48,
        topIneffectiveControls: ["Incident Response", "System Redundancy"],
        residualRiskScore: 41,
      },
      {
        department: "Operations",
        totalRisks: 37,
        mitigatedRisks: 28,
        mitigationEffectiveness: 76,
        topIneffectiveControls: ["Incident Response", "Access Controls"],
        residualRiskScore: 38,
      },
      {
        department: "IT",
        totalRisks: 23,
        mitigatedRisks: 11,
        mitigationEffectiveness: 48,
        topIneffectiveControls: ["Access Controls", "Training Program"],
        residualRiskScore: 30,
      },
      {
        department: "HR",
        totalRisks: 40,
        mitigatedRisks: 37,
        mitigationEffectiveness: 92,
        topIneffectiveControls: ["Vendor Management", "Training Program"],
        residualRiskScore: 39,
      },
      {
        department: "Marketing",
        totalRisks: 30,
        mitigatedRisks: 19,
        mitigationEffectiveness: 63,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 23,
      },
      {
        department: "Sales",
        totalRisks: 28,
        mitigatedRisks: 19,
        mitigationEffectiveness: 68,
        topIneffectiveControls: ["Vendor Management", "System Redundancy"],
        residualRiskScore: 25,
      },
    ],
  },
  {
    date: "2025-04-16",
    departments: [
      {
        department: "Finance",
        totalRisks: 36,
        mitigatedRisks: 14,
        mitigationEffectiveness: 39,
        topIneffectiveControls: ["Incident Response", "Vendor Management"],
        residualRiskScore: 39,
      },
      {
        department: "Operations",
        totalRisks: 30,
        mitigatedRisks: 13,
        mitigationEffectiveness: 43,
        topIneffectiveControls: ["Incident Response", "Access Controls"],
        residualRiskScore: 31,
      },
      {
        department: "IT",
        totalRisks: 33,
        mitigatedRisks: 31,
        mitigationEffectiveness: 94,
        topIneffectiveControls: ["Incident Response", "Vendor Management"],
        residualRiskScore: 23,
      },
      {
        department: "HR",
        totalRisks: 20,
        mitigatedRisks: 12,
        mitigationEffectiveness: 60,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 37,
      },
      {
        department: "Marketing",
        totalRisks: 38,
        mitigatedRisks: 16,
        mitigationEffectiveness: 42,
        topIneffectiveControls: ["Training Program", "Vendor Management"],
        residualRiskScore: 32,
      },
      {
        department: "Sales",
        totalRisks: 33,
        mitigatedRisks: 17,
        mitigationEffectiveness: 52,
        topIneffectiveControls: ["Training Program", "Incident Response"],
        residualRiskScore: 20,
      },
    ],
  },
  {
    date: "2025-04-23",
    departments: [
      {
        department: "Finance",
        totalRisks: 34,
        mitigatedRisks: 20,
        mitigationEffectiveness: 59,
        topIneffectiveControls: ["Training Program", "System Redundancy"],
        residualRiskScore: 49,
      },
      {
        department: "Operations",
        totalRisks: 36,
        mitigatedRisks: 15,
        mitigationEffectiveness: 42,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 46,
      },
      {
        department: "IT",
        totalRisks: 25,
        mitigatedRisks: 24,
        mitigationEffectiveness: 96,
        topIneffectiveControls: ["Vendor Management", "System Redundancy"],
        residualRiskScore: 20,
      },
      {
        department: "HR",
        totalRisks: 31,
        mitigatedRisks: 13,
        mitigationEffectiveness: 42,
        topIneffectiveControls: ["Training Program", "Access Controls"],
        residualRiskScore: 20,
      },
      {
        department: "Marketing",
        totalRisks: 30,
        mitigatedRisks: 22,
        mitigationEffectiveness: 73,
        topIneffectiveControls: ["System Redundancy", "Access Controls"],
        residualRiskScore: 22,
      },
      {
        department: "Sales",
        totalRisks: 24,
        mitigatedRisks: 19,
        mitigationEffectiveness: 79,
        topIneffectiveControls: ["Access Controls", "Incident Response"],
        residualRiskScore: 23,
      },
    ],
  },
  {
    date: "2025-04-30",
    departments: [
      {
        department: "Finance",
        totalRisks: 35,
        mitigatedRisks: 31,
        mitigationEffectiveness: 89,
        topIneffectiveControls: ["System Redundancy", "Training Program"],
        residualRiskScore: 44,
      },
      {
        department: "Operations",
        totalRisks: 37,
        mitigatedRisks: 11,
        mitigationEffectiveness: 30,
        topIneffectiveControls: ["Vendor Management", "Incident Response"],
        residualRiskScore: 36,
      },
      {
        department: "IT",
        totalRisks: 39,
        mitigatedRisks: 33,
        mitigationEffectiveness: 85,
        topIneffectiveControls: ["Vendor Management", "System Redundancy"],
        residualRiskScore: 46,
      },
      {
        department: "HR",
        totalRisks: 33,
        mitigatedRisks: 18,
        mitigationEffectiveness: 55,
        topIneffectiveControls: ["Vendor Management", "Incident Response"],
        residualRiskScore: 40,
      },
      {
        department: "Marketing",
        totalRisks: 24,
        mitigatedRisks: 20,
        mitigationEffectiveness: 83,
        topIneffectiveControls: ["Vendor Management", "System Redundancy"],
        residualRiskScore: 43,
      },
      {
        department: "Sales",
        totalRisks: 34,
        mitigatedRisks: 33,
        mitigationEffectiveness: 97,
        topIneffectiveControls: ["Training Program", "Incident Response"],
        residualRiskScore: 21,
      },
    ],
  },
  {
    date: "2025-05-07",
    departments: [
      {
        department: "Finance",
        totalRisks: 37,
        mitigatedRisks: 12,
        mitigationEffectiveness: 32,
        topIneffectiveControls: ["Vendor Management", "System Redundancy"],
        residualRiskScore: 44,
      },
      {
        department: "Operations",
        totalRisks: 21,
        mitigatedRisks: 12,
        mitigationEffectiveness: 57,
        topIneffectiveControls: ["Vendor Management", "Training Program"],
        residualRiskScore: 26,
      },
      {
        department: "IT",
        totalRisks: 23,
        mitigatedRisks: 23,
        mitigationEffectiveness: 100,
        topIneffectiveControls: ["Access Controls", "Incident Response"],
        residualRiskScore: 48,
      },
      {
        department: "HR",
        totalRisks: 34,
        mitigatedRisks: 18,
        mitigationEffectiveness: 53,
        topIneffectiveControls: ["Incident Response", "Access Controls"],
        residualRiskScore: 31,
      },
      {
        department: "Marketing",
        totalRisks: 20,
        mitigatedRisks: 11,
        mitigationEffectiveness: 55,
        topIneffectiveControls: ["Vendor Management", "System Redundancy"],
        residualRiskScore: 33,
      },
      {
        department: "Sales",
        totalRisks: 21,
        mitigatedRisks: 15,
        mitigationEffectiveness: 71,
        topIneffectiveControls: ["Access Controls", "Incident Response"],
        residualRiskScore: 23,
      },
    ],
  },
  {
    date: "2025-05-14",
    departments: [
      {
        department: "Finance",
        totalRisks: 26,
        mitigatedRisks: 14,
        mitigationEffectiveness: 54,
        topIneffectiveControls: ["Training Program", "Incident Response"],
        residualRiskScore: 24,
      },
      {
        department: "Operations",
        totalRisks: 27,
        mitigatedRisks: 17,
        mitigationEffectiveness: 63,
        topIneffectiveControls: ["Training Program", "Incident Response"],
        residualRiskScore: 44,
      },
      {
        department: "IT",
        totalRisks: 27,
        mitigatedRisks: 13,
        mitigationEffectiveness: 48,
        topIneffectiveControls: ["Vendor Management", "Incident Response"],
        residualRiskScore: 38,
      },
      {
        department: "HR",
        totalRisks: 35,
        mitigatedRisks: 27,
        mitigationEffectiveness: 77,
        topIneffectiveControls: ["System Redundancy", "Training Program"],
        residualRiskScore: 39,
      },
      {
        department: "Marketing",
        totalRisks: 35,
        mitigatedRisks: 32,
        mitigationEffectiveness: 91,
        topIneffectiveControls: ["Access Controls", "Training Program"],
        residualRiskScore: 34,
      },
      {
        department: "Sales",
        totalRisks: 21,
        mitigatedRisks: 12,
        mitigationEffectiveness: 57,
        topIneffectiveControls: ["Vendor Management", "Training Program"],
        residualRiskScore: 37,
      },
    ],
  },
  {
    date: "2025-05-21",
    departments: [
      {
        department: "Finance",
        totalRisks: 25,
        mitigatedRisks: 12,
        mitigationEffectiveness: 48,
        topIneffectiveControls: ["Vendor Management", "Training Program"],
        residualRiskScore: 44,
      },
      {
        department: "Operations",
        totalRisks: 20,
        mitigatedRisks: 10,
        mitigationEffectiveness: 50,
        topIneffectiveControls: ["Access Controls", "Training Program"],
        residualRiskScore: 42,
      },
      {
        department: "IT",
        totalRisks: 34,
        mitigatedRisks: 33,
        mitigationEffectiveness: 97,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 20,
      },
      {
        department: "HR",
        totalRisks: 22,
        mitigatedRisks: 18,
        mitigationEffectiveness: 82,
        topIneffectiveControls: ["Vendor Management", "Access Controls"],
        residualRiskScore: 47,
      },
      {
        department: "Marketing",
        totalRisks: 32,
        mitigatedRisks: 31,
        mitigationEffectiveness: 97,
        topIneffectiveControls: ["Vendor Management", "Incident Response"],
        residualRiskScore: 45,
      },
      {
        department: "Sales",
        totalRisks: 25,
        mitigatedRisks: 18,
        mitigationEffectiveness: 72,
        topIneffectiveControls: ["Incident Response", "Training Program"],
        residualRiskScore: 39,
      },
    ],
  },
  {
    date: "2025-05-28",
    departments: [
      {
        department: "Finance",
        totalRisks: 36,
        mitigatedRisks: 15,
        mitigationEffectiveness: 42,
        topIneffectiveControls: ["System Redundancy", "Incident Response"],
        residualRiskScore: 36,
      },
      {
        department: "Operations",
        totalRisks: 26,
        mitigatedRisks: 15,
        mitigationEffectiveness: 58,
        topIneffectiveControls: ["Incident Response", "Vendor Management"],
        residualRiskScore: 33,
      },
      {
        department: "IT",
        totalRisks: 34,
        mitigatedRisks: 27,
        mitigationEffectiveness: 79,
        topIneffectiveControls: ["Access Controls", "Vendor Management"],
        residualRiskScore: 47,
      },
      {
        department: "HR",
        totalRisks: 34,
        mitigatedRisks: 21,
        mitigationEffectiveness: 62,
        topIneffectiveControls: ["Access Controls", "Training Program"],
        residualRiskScore: 25,
      },
      {
        department: "Marketing",
        totalRisks: 28,
        mitigatedRisks: 12,
        mitigationEffectiveness: 43,
        topIneffectiveControls: ["System Redundancy", "Incident Response"],
        residualRiskScore: 37,
      },
      {
        department: "Sales",
        totalRisks: 39,
        mitigatedRisks: 31,
        mitigationEffectiveness: 79,
        topIneffectiveControls: ["Incident Response", "Vendor Management"],
        residualRiskScore: 27,
      },
    ],
  },
  {
    date: "2025-06-04",
    departments: [
      {
        department: "Finance",
        totalRisks: 20,
        mitigatedRisks: 19,
        mitigationEffectiveness: 95,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 47,
      },
      {
        department: "Operations",
        totalRisks: 25,
        mitigatedRisks: 12,
        mitigationEffectiveness: 48,
        topIneffectiveControls: ["System Redundancy", "Vendor Management"],
        residualRiskScore: 21,
      },
      {
        department: "IT",
        totalRisks: 27,
        mitigatedRisks: 22,
        mitigationEffectiveness: 81,
        topIneffectiveControls: ["Training Program", "Incident Response"],
        residualRiskScore: 28,
      },
      {
        department: "HR",
        totalRisks: 34,
        mitigatedRisks: 29,
        mitigationEffectiveness: 85,
        topIneffectiveControls: ["Training Program", "System Redundancy"],
        residualRiskScore: 23,
      },
      {
        department: "Marketing",
        totalRisks: 39,
        mitigatedRisks: 13,
        mitigationEffectiveness: 33,
        topIneffectiveControls: ["Training Program", "Vendor Management"],
        residualRiskScore: 40,
      },
      {
        department: "Sales",
        totalRisks: 30,
        mitigatedRisks: 26,
        mitigationEffectiveness: 87,
        topIneffectiveControls: ["System Redundancy", "Vendor Management"],
        residualRiskScore: 24,
      },
    ],
  },
  {
    date: "2025-06-11",
    departments: [
      {
        department: "Finance",
        totalRisks: 35,
        mitigatedRisks: 10,
        mitigationEffectiveness: 29,
        topIneffectiveControls: ["Incident Response", "System Redundancy"],
        residualRiskScore: 30,
      },
      {
        department: "Operations",
        totalRisks: 35,
        mitigatedRisks: 21,
        mitigationEffectiveness: 60,
        topIneffectiveControls: ["System Redundancy", "Incident Response"],
        residualRiskScore: 22,
      },
      {
        department: "IT",
        totalRisks: 26,
        mitigatedRisks: 23,
        mitigationEffectiveness: 88,
        topIneffectiveControls: ["Vendor Management", "Access Controls"],
        residualRiskScore: 36,
      },
      {
        department: "HR",
        totalRisks: 28,
        mitigatedRisks: 27,
        mitigationEffectiveness: 96,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 37,
      },
      {
        department: "Marketing",
        totalRisks: 31,
        mitigatedRisks: 11,
        mitigationEffectiveness: 35,
        topIneffectiveControls: ["Vendor Management", "Training Program"],
        residualRiskScore: 46,
      },
      {
        department: "Sales",
        totalRisks: 26,
        mitigatedRisks: 12,
        mitigationEffectiveness: 46,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 36,
      },
    ],
  },
  {
    date: "2025-06-18",
    departments: [
      {
        department: "Finance",
        totalRisks: 27,
        mitigatedRisks: 21,
        mitigationEffectiveness: 78,
        topIneffectiveControls: ["Vendor Management", "System Redundancy"],
        residualRiskScore: 44,
      },
      {
        department: "Operations",
        totalRisks: 38,
        mitigatedRisks: 13,
        mitigationEffectiveness: 34,
        topIneffectiveControls: ["Incident Response", "System Redundancy"],
        residualRiskScore: 38,
      },
      {
        department: "IT",
        totalRisks: 21,
        mitigatedRisks: 12,
        mitigationEffectiveness: 57,
        topIneffectiveControls: ["Vendor Management", "Incident Response"],
        residualRiskScore: 21,
      },
      {
        department: "HR",
        totalRisks: 27,
        mitigatedRisks: 21,
        mitigationEffectiveness: 78,
        topIneffectiveControls: ["System Redundancy", "Training Program"],
        residualRiskScore: 21,
      },
      {
        department: "Marketing",
        totalRisks: 21,
        mitigatedRisks: 17,
        mitigationEffectiveness: 81,
        topIneffectiveControls: ["System Redundancy", "Access Controls"],
        residualRiskScore: 22,
      },
      {
        department: "Sales",
        totalRisks: 31,
        mitigatedRisks: 14,
        mitigationEffectiveness: 45,
        topIneffectiveControls: ["System Redundancy", "Access Controls"],
        residualRiskScore: 20,
      },
    ],
  },
  {
    date: "2025-06-25",
    departments: [
      {
        department: "Finance",
        totalRisks: 23,
        mitigatedRisks: 10,
        mitigationEffectiveness: 43,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 30,
      },
      {
        department: "Operations",
        totalRisks: 35,
        mitigatedRisks: 27,
        mitigationEffectiveness: 77,
        topIneffectiveControls: ["Incident Response", "Access Controls"],
        residualRiskScore: 48,
      },
      {
        department: "IT",
        totalRisks: 22,
        mitigatedRisks: 10,
        mitigationEffectiveness: 45,
        topIneffectiveControls: ["Incident Response", "Vendor Management"],
        residualRiskScore: 29,
      },
      {
        department: "HR",
        totalRisks: 38,
        mitigatedRisks: 10,
        mitigationEffectiveness: 26,
        topIneffectiveControls: ["Vendor Management", "Incident Response"],
        residualRiskScore: 50,
      },
      {
        department: "Marketing",
        totalRisks: 22,
        mitigatedRisks: 11,
        mitigationEffectiveness: 50,
        topIneffectiveControls: ["Incident Response", "System Redundancy"],
        residualRiskScore: 25,
      },
      {
        department: "Sales",
        totalRisks: 28,
        mitigatedRisks: 27,
        mitigationEffectiveness: 96,
        topIneffectiveControls: ["Vendor Management", "Incident Response"],
        residualRiskScore: 46,
      },
    ],
  },
  {
    date: "2025-07-02",
    departments: [
      {
        department: "Finance",
        totalRisks: 20,
        mitigatedRisks: 18,
        mitigationEffectiveness: 90,
        topIneffectiveControls: ["Vendor Management", "Access Controls"],
        residualRiskScore: 24,
      },
      {
        department: "Operations",
        totalRisks: 28,
        mitigatedRisks: 16,
        mitigationEffectiveness: 57,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 48,
      },
      {
        department: "IT",
        totalRisks: 39,
        mitigatedRisks: 28,
        mitigationEffectiveness: 72,
        topIneffectiveControls: ["Training Program", "Incident Response"],
        residualRiskScore: 44,
      },
      {
        department: "HR",
        totalRisks: 33,
        mitigatedRisks: 13,
        mitigationEffectiveness: 39,
        topIneffectiveControls: ["Incident Response", "Vendor Management"],
        residualRiskScore: 50,
      },
      {
        department: "Marketing",
        totalRisks: 31,
        mitigatedRisks: 28,
        mitigationEffectiveness: 90,
        topIneffectiveControls: ["System Redundancy", "Training Program"],
        residualRiskScore: 23,
      },
      {
        department: "Sales",
        totalRisks: 39,
        mitigatedRisks: 19,
        mitigationEffectiveness: 49,
        topIneffectiveControls: ["Vendor Management", "Training Program"],
        residualRiskScore: 49,
      },
    ],
  },
  {
    date: "2025-07-09",
    departments: [
      {
        department: "Finance",
        totalRisks: 20,
        mitigatedRisks: 12,
        mitigationEffectiveness: 60,
        topIneffectiveControls: ["Vendor Management", "System Redundancy"],
        residualRiskScore: 45,
      },
      {
        department: "Operations",
        totalRisks: 28,
        mitigatedRisks: 19,
        mitigationEffectiveness: 68,
        topIneffectiveControls: ["Training Program", "Vendor Management"],
        residualRiskScore: 40,
      },
      {
        department: "IT",
        totalRisks: 34,
        mitigatedRisks: 34,
        mitigationEffectiveness: 100,
        topIneffectiveControls: ["System Redundancy", "Access Controls"],
        residualRiskScore: 30,
      },
      {
        department: "HR",
        totalRisks: 32,
        mitigatedRisks: 18,
        mitigationEffectiveness: 56,
        topIneffectiveControls: ["Vendor Management", "Access Controls"],
        residualRiskScore: 35,
      },
      {
        department: "Marketing",
        totalRisks: 30,
        mitigatedRisks: 21,
        mitigationEffectiveness: 70,
        topIneffectiveControls: ["Incident Response", "Training Program"],
        residualRiskScore: 24,
      },
      {
        department: "Sales",
        totalRisks: 28,
        mitigatedRisks: 14,
        mitigationEffectiveness: 50,
        topIneffectiveControls: ["System Redundancy", "Incident Response"],
        residualRiskScore: 38,
      },
    ],
  },
  {
    date: "2025-07-16",
    departments: [
      {
        department: "Finance",
        totalRisks: 32,
        mitigatedRisks: 26,
        mitigationEffectiveness: 81,
        topIneffectiveControls: ["Vendor Management", "Training Program"],
        residualRiskScore: 43,
      },
      {
        department: "Operations",
        totalRisks: 33,
        mitigatedRisks: 33,
        mitigationEffectiveness: 100,
        topIneffectiveControls: ["Access Controls", "System Redundancy"],
        residualRiskScore: 46,
      },
      {
        department: "IT",
        totalRisks: 28,
        mitigatedRisks: 16,
        mitigationEffectiveness: 57,
        topIneffectiveControls: ["Vendor Management", "Training Program"],
        residualRiskScore: 46,
      },
      {
        department: "HR",
        totalRisks: 25,
        mitigatedRisks: 22,
        mitigationEffectiveness: 88,
        topIneffectiveControls: ["Training Program", "Access Controls"],
        residualRiskScore: 26,
      },
      {
        department: "Marketing",
        totalRisks: 38,
        mitigatedRisks: 30,
        mitigationEffectiveness: 79,
        topIneffectiveControls: ["System Redundancy", "Incident Response"],
        residualRiskScore: 50,
      },
      {
        department: "Sales",
        totalRisks: 21,
        mitigatedRisks: 16,
        mitigationEffectiveness: 76,
        topIneffectiveControls: ["Vendor Management", "Incident Response"],
        residualRiskScore: 29,
      },
    ],
  },
  {
    date: "2025-07-23",
    departments: [
      {
        department: "Finance",
        totalRisks: 27,
        mitigatedRisks: 27,
        mitigationEffectiveness: 100,
        topIneffectiveControls: ["Incident Response", "Vendor Management"],
        residualRiskScore: 25,
      },
      {
        department: "Operations",
        totalRisks: 25,
        mitigatedRisks: 16,
        mitigationEffectiveness: 64,
        topIneffectiveControls: ["Training Program", "System Redundancy"],
        residualRiskScore: 27,
      },
      {
        department: "IT",
        totalRisks: 26,
        mitigatedRisks: 12,
        mitigationEffectiveness: 46,
        topIneffectiveControls: ["Vendor Management", "System Redundancy"],
        residualRiskScore: 37,
      },
      {
        department: "HR",
        totalRisks: 40,
        mitigatedRisks: 27,
        mitigationEffectiveness: 68,
        topIneffectiveControls: ["Access Controls", "Vendor Management"],
        residualRiskScore: 30,
      },
      {
        department: "Marketing",
        totalRisks: 36,
        mitigatedRisks: 35,
        mitigationEffectiveness: 97,
        topIneffectiveControls: ["Incident Response", "Training Program"],
        residualRiskScore: 33,
      },
      {
        department: "Sales",
        totalRisks: 39,
        mitigatedRisks: 30,
        mitigationEffectiveness: 77,
        topIneffectiveControls: ["Incident Response", "Vendor Management"],
        residualRiskScore: 45,
      },
    ],
  },
  {
    date: "2025-07-30",
    departments: [
      {
        department: "Finance",
        totalRisks: 23,
        mitigatedRisks: 20,
        mitigationEffectiveness: 87,
        topIneffectiveControls: ["Incident Response", "Training Program"],
        residualRiskScore: 28,
      },
      {
        department: "Operations",
        totalRisks: 26,
        mitigatedRisks: 17,
        mitigationEffectiveness: 65,
        topIneffectiveControls: ["Access Controls", "Vendor Management"],
        residualRiskScore: 32,
      },
      {
        department: "IT",
        totalRisks: 40,
        mitigatedRisks: 25,
        mitigationEffectiveness: 62,
        topIneffectiveControls: ["Incident Response", "Training Program"],
        residualRiskScore: 36,
      },
      {
        department: "HR",
        totalRisks: 28,
        mitigatedRisks: 23,
        mitigationEffectiveness: 82,
        topIneffectiveControls: ["Vendor Management", "Incident Response"],
        residualRiskScore: 38,
      },
      {
        department: "Marketing",
        totalRisks: 33,
        mitigatedRisks: 13,
        mitigationEffectiveness: 39,
        topIneffectiveControls: ["Vendor Management", "System Redundancy"],
        residualRiskScore: 32,
      },
      {
        department: "Sales",
        totalRisks: 32,
        mitigatedRisks: 17,
        mitigationEffectiveness: 53,
        topIneffectiveControls: ["System Redundancy", "Training Program"],
        residualRiskScore: 20,
      },
    ],
  },
  {
    date: "2025-08-06",
    departments: [
      {
        department: "Finance",
        totalRisks: 33,
        mitigatedRisks: 30,
        mitigationEffectiveness: 91,
        topIneffectiveControls: ["Incident Response", "System Redundancy"],
        residualRiskScore: 26,
      },
      {
        department: "Operations",
        totalRisks: 25,
        mitigatedRisks: 13,
        mitigationEffectiveness: 52,
        topIneffectiveControls: ["Vendor Management", "Access Controls"],
        residualRiskScore: 26,
      },
      {
        department: "IT",
        totalRisks: 25,
        mitigatedRisks: 16,
        mitigationEffectiveness: 64,
        topIneffectiveControls: ["System Redundancy", "Incident Response"],
        residualRiskScore: 50,
      },
      {
        department: "HR",
        totalRisks: 40,
        mitigatedRisks: 26,
        mitigationEffectiveness: 65,
        topIneffectiveControls: ["Incident Response", "Training Program"],
        residualRiskScore: 48,
      },
      {
        department: "Marketing",
        totalRisks: 26,
        mitigatedRisks: 20,
        mitigationEffectiveness: 77,
        topIneffectiveControls: ["Incident Response", "Vendor Management"],
        residualRiskScore: 40,
      },
      {
        department: "Sales",
        totalRisks: 21,
        mitigatedRisks: 21,
        mitigationEffectiveness: 100,
        topIneffectiveControls: ["Vendor Management", "Training Program"],
        residualRiskScore: 45,
      },
    ],
  },
  {
    date: "2025-08-13",
    departments: [
      {
        department: "Finance",
        totalRisks: 26,
        mitigatedRisks: 21,
        mitigationEffectiveness: 81,
        topIneffectiveControls: ["Training Program", "Incident Response"],
        residualRiskScore: 46,
      },
      {
        department: "Operations",
        totalRisks: 38,
        mitigatedRisks: 26,
        mitigationEffectiveness: 68,
        topIneffectiveControls: ["Training Program", "System Redundancy"],
        residualRiskScore: 45,
      },
      {
        department: "IT",
        totalRisks: 20,
        mitigatedRisks: 13,
        mitigationEffectiveness: 65,
        topIneffectiveControls: ["Incident Response", "Training Program"],
        residualRiskScore: 40,
      },
      {
        department: "HR",
        totalRisks: 26,
        mitigatedRisks: 14,
        mitigationEffectiveness: 54,
        topIneffectiveControls: ["System Redundancy", "Vendor Management"],
        residualRiskScore: 28,
      },
      {
        department: "Marketing",
        totalRisks: 39,
        mitigatedRisks: 14,
        mitigationEffectiveness: 36,
        topIneffectiveControls: ["Incident Response", "System Redundancy"],
        residualRiskScore: 33,
      },
      {
        department: "Sales",
        totalRisks: 20,
        mitigatedRisks: 16,
        mitigationEffectiveness: 80,
        topIneffectiveControls: ["Incident Response", "System Redundancy"],
        residualRiskScore: 47,
      },
    ],
  },
  {
    date: "2025-08-20",
    departments: [
      {
        department: "Finance",
        totalRisks: 23,
        mitigatedRisks: 15,
        mitigationEffectiveness: 65,
        topIneffectiveControls: ["System Redundancy", "Incident Response"],
        residualRiskScore: 35,
      },
      {
        department: "Operations",
        totalRisks: 34,
        mitigatedRisks: 17,
        mitigationEffectiveness: 50,
        topIneffectiveControls: ["Training Program", "Vendor Management"],
        residualRiskScore: 44,
      },
      {
        department: "IT",
        totalRisks: 30,
        mitigatedRisks: 17,
        mitigationEffectiveness: 57,
        topIneffectiveControls: ["Training Program", "System Redundancy"],
        residualRiskScore: 47,
      },
      {
        department: "HR",
        totalRisks: 22,
        mitigatedRisks: 12,
        mitigationEffectiveness: 55,
        topIneffectiveControls: ["System Redundancy", "Training Program"],
        residualRiskScore: 34,
      },
      {
        department: "Marketing",
        totalRisks: 23,
        mitigatedRisks: 20,
        mitigationEffectiveness: 87,
        topIneffectiveControls: ["Training Program", "Incident Response"],
        residualRiskScore: 32,
      },
      {
        department: "Sales",
        totalRisks: 25,
        mitigatedRisks: 10,
        mitigationEffectiveness: 40,
        topIneffectiveControls: ["Incident Response", "Vendor Management"],
        residualRiskScore: 26,
      },
    ],
  },
  {
    date: "2025-08-27",
    departments: [
      {
        department: "Finance",
        totalRisks: 22,
        mitigatedRisks: 19,
        mitigationEffectiveness: 86,
        topIneffectiveControls: ["Training Program", "Incident Response"],
        residualRiskScore: 20,
      },
      {
        department: "Operations",
        totalRisks: 28,
        mitigatedRisks: 11,
        mitigationEffectiveness: 39,
        topIneffectiveControls: ["Access Controls", "Training Program"],
        residualRiskScore: 45,
      },
      {
        department: "IT",
        totalRisks: 22,
        mitigatedRisks: 20,
        mitigationEffectiveness: 91,
        topIneffectiveControls: ["Training Program", "Access Controls"],
        residualRiskScore: 27,
      },
      {
        department: "HR",
        totalRisks: 36,
        mitigatedRisks: 25,
        mitigationEffectiveness: 69,
        topIneffectiveControls: ["Training Program", "System Redundancy"],
        residualRiskScore: 26,
      },
      {
        department: "Marketing",
        totalRisks: 36,
        mitigatedRisks: 25,
        mitigationEffectiveness: 69,
        topIneffectiveControls: ["Incident Response", "System Redundancy"],
        residualRiskScore: 27,
      },
      {
        department: "Sales",
        totalRisks: 36,
        mitigatedRisks: 35,
        mitigationEffectiveness: 97,
        topIneffectiveControls: ["Training Program", "System Redundancy"],
        residualRiskScore: 34,
      },
    ],
  },
];

export default assessments;
