export const dummyTasks = [
  {
    task_id: "T001",
    task_type: "Procurement",
    request_date: "2025-08-11",
    completion_date: "2025-08-12",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "High",
    sla_due_date: "2025-08-14",
    sla_met: true,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 32,
    customer_satisfaction: 2,
  },
  {
    task_id: "T002",
    task_type: "Facility Maintenance",
    request_date: "2025-03-07",
    completion_date: "2025-03-12",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "Low",
    sla_due_date: "2025-03-12",
    sla_met: true,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 122,
    customer_satisfaction: 5,
  },
  {
    task_id: "T003",
    task_type: "Facility Maintenance",
    request_date: "2025-05-31",
    completion_date: null,
    status: "Pending",
    assigned_to: "Paul Ssemanda",
    priority: "High",
    sla_due_date: "2025-06-04",
    sla_met: null,
    error_flag: null,
    requestor_department: "Production",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T004",
    task_type: "Facility Maintenance",
    request_date: "2025-01-05",
    completion_date: "2025-01-10",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "High",
    sla_due_date: "2025-01-07",
    sla_met: false,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 125,
    customer_satisfaction: 1,
  },
  {
    task_id: "T005",
    task_type: "IT Support",
    request_date: "2025-02-02",
    completion_date: "2025-02-02",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "High",
    sla_due_date: "2025-02-05",
    sla_met: true,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 5,
    customer_satisfaction: 2,
  },
  {
    task_id: "T006",
    task_type: "Procurement",
    request_date: "2025-07-21",
    completion_date: "2025-07-24",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "Medium",
    sla_due_date: "2025-07-26",
    sla_met: true,
    error_flag: true,
    requestor_department: "Editorial",
    completion_time_hours: 73,
    customer_satisfaction: 5,
  },
  {
    task_id: "T007",
    task_type: "IT Support",
    request_date: "2025-08-15",
    completion_date: null,
    status: "In Progress",
    assigned_to: "David Mugisha",
    priority: "High",
    sla_due_date: "2025-08-19",
    sla_met: null,
    error_flag: null,
    requestor_department: "Sales",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T008",
    task_type: "IT Support",
    request_date: "2025-08-11",
    completion_date: "2025-08-14",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "Low",
    sla_due_date: "2025-08-14",
    sla_met: true,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 80,
    customer_satisfaction: 4,
  },
  {
    task_id: "T009",
    task_type: "HR Request",
    request_date: "2025-01-18",
    completion_date: "2025-01-21",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Low",
    sla_due_date: "2025-01-21",
    sla_met: true,
    error_flag: true,
    requestor_department: "Finance",
    completion_time_hours: 80,
    customer_satisfaction: 3,
  },
  {
    task_id: "T010",
    task_type: "Facility Maintenance",
    request_date: "2025-07-07",
    completion_date: "2025-07-10",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "Medium",
    sla_due_date: "2025-07-10",
    sla_met: true,
    error_flag: false,
    requestor_department: "Editorial",
    completion_time_hours: 78,
    customer_satisfaction: 5,
  },
  {
    task_id: "T011",
    task_type: "HR Request",
    request_date: "2025-07-17",
    completion_date: "2025-07-24",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "Low",
    sla_due_date: "2025-07-21",
    sla_met: false,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 175,
    customer_satisfaction: 1,
  },
  {
    task_id: "T012",
    task_type: "IT Support",
    request_date: "2025-03-25",
    completion_date: "2025-03-29",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "High",
    sla_due_date: "2025-03-27",
    sla_met: false,
    error_flag: true,
    requestor_department: "Editorial",
    completion_time_hours: 97,
    customer_satisfaction: 5,
  },
  {
    task_id: "T013",
    task_type: "IT Support",
    request_date: "2025-01-25",
    completion_date: "2025-01-26",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "Medium",
    sla_due_date: "2025-01-28",
    sla_met: true,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 29,
    customer_satisfaction: 5,
  },
  {
    task_id: "T014",
    task_type: "Facility Maintenance",
    request_date: "2025-08-30",
    completion_date: "2025-08-31",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "High",
    sla_due_date: "2025-09-01",
    sla_met: true,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 24,
    customer_satisfaction: 1,
  },
  {
    task_id: "T015",
    task_type: "Facility Maintenance",
    request_date: "2025-05-05",
    completion_date: "2025-05-05",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "High",
    sla_due_date: "2025-05-07",
    sla_met: true,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 4,
    customer_satisfaction: 2,
  },
  {
    task_id: "T016",
    task_type: "IT Support",
    request_date: "2025-07-18",
    completion_date: "2025-07-25",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "Low",
    sla_due_date: "2025-07-20",
    sla_met: false,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 172,
    customer_satisfaction: 3,
  },
  {
    task_id: "T017",
    task_type: "Procurement",
    request_date: "2025-01-31",
    completion_date: "2025-02-04",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-02-04",
    sla_met: true,
    error_flag: true,
    requestor_department: "Editorial",
    completion_time_hours: 99,
    customer_satisfaction: 4,
  },
  {
    task_id: "T018",
    task_type: "IT Support",
    request_date: "2025-02-14",
    completion_date: null,
    status: "Pending",
    assigned_to: "John Okello",
    priority: "High",
    sla_due_date: "2025-02-17",
    sla_met: null,
    error_flag: null,
    requestor_department: "Finance",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T019",
    task_type: "Procurement",
    request_date: "2025-06-11",
    completion_date: null,
    status: "In Progress",
    assigned_to: "David Mugisha",
    priority: "High",
    sla_due_date: "2025-06-14",
    sla_met: null,
    error_flag: null,
    requestor_department: "Marketing",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T020",
    task_type: "Procurement",
    request_date: "2025-05-20",
    completion_date: null,
    status: "Pending",
    assigned_to: "John Okello",
    priority: "High",
    sla_due_date: "2025-05-23",
    sla_met: null,
    error_flag: null,
    requestor_department: "Sales",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T021",
    task_type: "Facility Maintenance",
    request_date: "2025-08-13",
    completion_date: "2025-08-13",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-08-18",
    sla_met: true,
    error_flag: false,
    requestor_department: "Editorial",
    completion_time_hours: 0,
    customer_satisfaction: 5,
  },
  {
    task_id: "T022",
    task_type: "Facility Maintenance",
    request_date: "2025-04-11",
    completion_date: "2025-04-15",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Low",
    sla_due_date: "2025-04-15",
    sla_met: true,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 103,
    customer_satisfaction: 5,
  },
  {
    task_id: "T023",
    task_type: "Procurement",
    request_date: "2025-07-16",
    completion_date: null,
    status: "Pending",
    assigned_to: "Paul Ssemanda",
    priority: "Low",
    sla_due_date: "2025-07-18",
    sla_met: null,
    error_flag: null,
    requestor_department: "Sales",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T024",
    task_type: "Procurement",
    request_date: "2025-05-15",
    completion_date: "2025-05-17",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "Low",
    sla_due_date: "2025-05-17",
    sla_met: true,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 53,
    customer_satisfaction: 1,
  },
  {
    task_id: "T025",
    task_type: "HR Request",
    request_date: "2025-05-09",
    completion_date: "2025-05-16",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "Low",
    sla_due_date: "2025-05-13",
    sla_met: false,
    error_flag: false,
    requestor_department: "Production",
    completion_time_hours: 173,
    customer_satisfaction: 1,
  },
  {
    task_id: "T026",
    task_type: "Facility Maintenance",
    request_date: "2025-08-17",
    completion_date: "2025-08-17",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-08-22",
    sla_met: true,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 0,
    customer_satisfaction: 2,
  },
  {
    task_id: "T027",
    task_type: "Procurement",
    request_date: "2025-02-09",
    completion_date: null,
    status: "In Progress",
    assigned_to: "John Okello",
    priority: "Low",
    sla_due_date: "2025-02-13",
    sla_met: null,
    error_flag: null,
    requestor_department: "Finance",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T028",
    task_type: "HR Request",
    request_date: "2025-08-30",
    completion_date: "2025-08-31",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "Low",
    sla_due_date: "2025-09-02",
    sla_met: true,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 27,
    customer_satisfaction: 5,
  },
  {
    task_id: "T029",
    task_type: "Procurement",
    request_date: "2025-01-07",
    completion_date: "2025-01-14",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Low",
    sla_due_date: "2025-01-09",
    sla_met: false,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 174,
    customer_satisfaction: 5,
  },
  {
    task_id: "T030",
    task_type: "IT Support",
    request_date: "2025-05-20",
    completion_date: "2025-05-26",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "High",
    sla_due_date: "2025-05-23",
    sla_met: false,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 148,
    customer_satisfaction: 1,
  },
  {
    task_id: "T031",
    task_type: "Procurement",
    request_date: "2025-06-02",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Grace Nakato",
    priority: "Medium",
    sla_due_date: "2025-06-05",
    sla_met: null,
    error_flag: null,
    requestor_department: "Finance",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T032",
    task_type: "HR Request",
    request_date: "2025-02-13",
    completion_date: "2025-02-20",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-02-15",
    sla_met: false,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 168,
    customer_satisfaction: 3,
  },
  {
    task_id: "T033",
    task_type: "Procurement",
    request_date: "2025-03-12",
    completion_date: "2025-03-17",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Medium",
    sla_due_date: "2025-03-16",
    sla_met: false,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 128,
    customer_satisfaction: 2,
  },
  {
    task_id: "T034",
    task_type: "Facility Maintenance",
    request_date: "2025-08-30",
    completion_date: "2025-09-01",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "Low",
    sla_due_date: "2025-09-01",
    sla_met: true,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 52,
    customer_satisfaction: 4,
  },
  {
    task_id: "T035",
    task_type: "Procurement",
    request_date: "2025-08-01",
    completion_date: "2025-08-04",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Low",
    sla_due_date: "2025-08-03",
    sla_met: false,
    error_flag: false,
    requestor_department: "Marketing",
    completion_time_hours: 77,
    customer_satisfaction: 2,
  },
  {
    task_id: "T036",
    task_type: "IT Support",
    request_date: "2025-06-08",
    completion_date: "2025-06-13",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Low",
    sla_due_date: "2025-06-10",
    sla_met: false,
    error_flag: true,
    requestor_department: "Finance",
    completion_time_hours: 128,
    customer_satisfaction: 3,
  },
  {
    task_id: "T037",
    task_type: "IT Support",
    request_date: "2025-01-03",
    completion_date: null,
    status: "Pending",
    assigned_to: "David Mugisha",
    priority: "Medium",
    sla_due_date: "2025-01-05",
    sla_met: null,
    error_flag: null,
    requestor_department: "Production",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T038",
    task_type: "Facility Maintenance",
    request_date: "2025-08-01",
    completion_date: "2025-08-07",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "Low",
    sla_due_date: "2025-08-06",
    sla_met: false,
    error_flag: false,
    requestor_department: "Editorial",
    completion_time_hours: 152,
    customer_satisfaction: 2,
  },
  {
    task_id: "T039",
    task_type: "Procurement",
    request_date: "2025-05-16",
    completion_date: "2025-05-18",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-05-21",
    sla_met: true,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 53,
    customer_satisfaction: 2,
  },
  {
    task_id: "T040",
    task_type: "Facility Maintenance",
    request_date: "2025-08-06",
    completion_date: "2025-08-13",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-08-09",
    sla_met: false,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 169,
    customer_satisfaction: 2,
  },
  {
    task_id: "T041",
    task_type: "Facility Maintenance",
    request_date: "2025-02-08",
    completion_date: "2025-02-10",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "Medium",
    sla_due_date: "2025-02-10",
    sla_met: true,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 50,
    customer_satisfaction: 1,
  },
  {
    task_id: "T042",
    task_type: "IT Support",
    request_date: "2025-07-01",
    completion_date: "2025-07-06",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "Medium",
    sla_due_date: "2025-07-04",
    sla_met: false,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 126,
    customer_satisfaction: 5,
  },
  {
    task_id: "T043",
    task_type: "Facility Maintenance",
    request_date: "2025-05-07",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Paul Ssemanda",
    priority: "Medium",
    sla_due_date: "2025-05-09",
    sla_met: null,
    error_flag: null,
    requestor_department: "Sales",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T044",
    task_type: "Facility Maintenance",
    request_date: "2025-03-18",
    completion_date: "2025-03-20",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "Low",
    sla_due_date: "2025-03-23",
    sla_met: true,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 52,
    customer_satisfaction: 2,
  },
  {
    task_id: "T045",
    task_type: "Procurement",
    request_date: "2025-02-19",
    completion_date: "2025-02-25",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "Medium",
    sla_due_date: "2025-02-23",
    sla_met: false,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 149,
    customer_satisfaction: 1,
  },
  {
    task_id: "T046",
    task_type: "Procurement",
    request_date: "2025-01-24",
    completion_date: "2025-01-27",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "Medium",
    sla_due_date: "2025-01-28",
    sla_met: true,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 72,
    customer_satisfaction: 4,
  },
  {
    task_id: "T047",
    task_type: "Procurement",
    request_date: "2025-01-16",
    completion_date: "2025-01-18",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "High",
    sla_due_date: "2025-01-20",
    sla_met: true,
    error_flag: false,
    requestor_department: "Editorial",
    completion_time_hours: 56,
    customer_satisfaction: 1,
  },
  {
    task_id: "T048",
    task_type: "Procurement",
    request_date: "2025-07-13",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Sarah Kintu",
    priority: "Low",
    sla_due_date: "2025-07-16",
    sla_met: null,
    error_flag: null,
    requestor_department: "Sales",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T049",
    task_type: "IT Support",
    request_date: "2025-02-03",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Grace Nakato",
    priority: "Low",
    sla_due_date: "2025-02-08",
    sla_met: null,
    error_flag: null,
    requestor_department: "Finance",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T050",
    task_type: "Facility Maintenance",
    request_date: "2025-01-11",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Grace Nakato",
    priority: "High",
    sla_due_date: "2025-01-15",
    sla_met: null,
    error_flag: null,
    requestor_department: "Sales",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T051",
    task_type: "Facility Maintenance",
    request_date: "2025-01-02",
    completion_date: "2025-01-04",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Low",
    sla_due_date: "2025-01-05",
    sla_met: true,
    error_flag: false,
    requestor_department: "Editorial",
    completion_time_hours: 48,
    customer_satisfaction: 5,
  },
  {
    task_id: "T052",
    task_type: "HR Request",
    request_date: "2025-08-18",
    completion_date: "2025-08-18",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "High",
    sla_due_date: "2025-08-21",
    sla_met: true,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 0,
    customer_satisfaction: 4,
  },
  {
    task_id: "T053",
    task_type: "Facility Maintenance",
    request_date: "2025-08-04",
    completion_date: "2025-08-11",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "Medium",
    sla_due_date: "2025-08-07",
    sla_met: false,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 175,
    customer_satisfaction: 4,
  },
  {
    task_id: "T054",
    task_type: "Facility Maintenance",
    request_date: "2025-05-24",
    completion_date: "2025-05-30",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-05-29",
    sla_met: false,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 152,
    customer_satisfaction: 2,
  },
  {
    task_id: "T055",
    task_type: "IT Support",
    request_date: "2025-05-20",
    completion_date: "2025-05-25",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Low",
    sla_due_date: "2025-05-22",
    sla_met: false,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 123,
    customer_satisfaction: 5,
  },
  {
    task_id: "T056",
    task_type: "Facility Maintenance",
    request_date: "2025-08-02",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-08-05",
    sla_met: null,
    error_flag: null,
    requestor_department: "Finance",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T057",
    task_type: "Procurement",
    request_date: "2025-02-17",
    completion_date: "2025-02-20",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Low",
    sla_due_date: "2025-02-20",
    sla_met: true,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 72,
    customer_satisfaction: 1,
  },
  {
    task_id: "T058",
    task_type: "HR Request",
    request_date: "2025-03-22",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Grace Nakato",
    priority: "Medium",
    sla_due_date: "2025-03-27",
    sla_met: null,
    error_flag: null,
    requestor_department: "Marketing",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T059",
    task_type: "HR Request",
    request_date: "2025-07-20",
    completion_date: "2025-07-20",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-07-25",
    sla_met: true,
    error_flag: true,
    requestor_department: "Editorial",
    completion_time_hours: 2,
    customer_satisfaction: 5,
  },
  {
    task_id: "T060",
    task_type: "HR Request",
    request_date: "2025-05-17",
    completion_date: "2025-05-18",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Low",
    sla_due_date: "2025-05-21",
    sla_met: true,
    error_flag: false,
    requestor_department: "Editorial",
    completion_time_hours: 29,
    customer_satisfaction: 3,
  },
  {
    task_id: "T061",
    task_type: "Facility Maintenance",
    request_date: "2025-03-20",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Paul Ssemanda",
    priority: "High",
    sla_due_date: "2025-03-23",
    sla_met: null,
    error_flag: null,
    requestor_department: "Production",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T062",
    task_type: "HR Request",
    request_date: "2025-05-17",
    completion_date: "2025-05-22",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-05-20",
    sla_met: false,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 125,
    customer_satisfaction: 4,
  },
  {
    task_id: "T063",
    task_type: "IT Support",
    request_date: "2025-06-15",
    completion_date: "2025-06-19",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "High",
    sla_due_date: "2025-06-18",
    sla_met: false,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 102,
    customer_satisfaction: 2,
  },
  {
    task_id: "T064",
    task_type: "Procurement",
    request_date: "2025-04-14",
    completion_date: "2025-04-14",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Low",
    sla_due_date: "2025-04-16",
    sla_met: true,
    error_flag: true,
    requestor_department: "Editorial",
    completion_time_hours: 6,
    customer_satisfaction: 3,
  },
  {
    task_id: "T065",
    task_type: "Facility Maintenance",
    request_date: "2025-05-04",
    completion_date: "2025-05-09",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Low",
    sla_due_date: "2025-05-07",
    sla_met: false,
    error_flag: false,
    requestor_department: "Production",
    completion_time_hours: 124,
    customer_satisfaction: 1,
  },
  {
    task_id: "T066",
    task_type: "HR Request",
    request_date: "2025-01-29",
    completion_date: null,
    status: "In Progress",
    assigned_to: "John Okello",
    priority: "High",
    sla_due_date: "2025-02-01",
    sla_met: null,
    error_flag: null,
    requestor_department: "Sales",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T067",
    task_type: "IT Support",
    request_date: "2025-08-09",
    completion_date: null,
    status: "Pending",
    assigned_to: "Grace Nakato",
    priority: "Low",
    sla_due_date: "2025-08-12",
    sla_met: null,
    error_flag: null,
    requestor_department: "Marketing",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T068",
    task_type: "Facility Maintenance",
    request_date: "2025-04-10",
    completion_date: "2025-04-13",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "Medium",
    sla_due_date: "2025-04-14",
    sla_met: true,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 74,
    customer_satisfaction: 3,
  },
  {
    task_id: "T069",
    task_type: "Procurement",
    request_date: "2025-05-26",
    completion_date: "2025-05-30",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-05-29",
    sla_met: false,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 103,
    customer_satisfaction: 5,
  },
  {
    task_id: "T070",
    task_type: "HR Request",
    request_date: "2025-05-29",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Grace Nakato",
    priority: "High",
    sla_due_date: "2025-05-31",
    sla_met: null,
    error_flag: null,
    requestor_department: "Sales",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T071",
    task_type: "HR Request",
    request_date: "2025-08-07",
    completion_date: null,
    status: "Pending",
    assigned_to: "Grace Nakato",
    priority: "High",
    sla_due_date: "2025-08-12",
    sla_met: null,
    error_flag: null,
    requestor_department: "Editorial",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T072",
    task_type: "Facility Maintenance",
    request_date: "2025-04-21",
    completion_date: "2025-04-28",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "High",
    sla_due_date: "2025-04-23",
    sla_met: false,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 168,
    customer_satisfaction: 5,
  },
  {
    task_id: "T073",
    task_type: "IT Support",
    request_date: "2025-03-22",
    completion_date: "2025-03-28",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Medium",
    sla_due_date: "2025-03-27",
    sla_met: false,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 151,
    customer_satisfaction: 1,
  },
  {
    task_id: "T074",
    task_type: "IT Support",
    request_date: "2025-08-03",
    completion_date: null,
    status: "In Progress",
    assigned_to: "David Mugisha",
    priority: "Low",
    sla_due_date: "2025-08-05",
    sla_met: null,
    error_flag: null,
    requestor_department: "Marketing",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T075",
    task_type: "Facility Maintenance",
    request_date: "2025-02-26",
    completion_date: "2025-03-04",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "Low",
    sla_due_date: "2025-03-03",
    sla_met: false,
    error_flag: true,
    requestor_department: "Editorial",
    completion_time_hours: 147,
    customer_satisfaction: 2,
  },
  {
    task_id: "T076",
    task_type: "IT Support",
    request_date: "2025-07-30",
    completion_date: "2025-08-03",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "High",
    sla_due_date: "2025-08-04",
    sla_met: true,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 98,
    customer_satisfaction: 5,
  },
  {
    task_id: "T077",
    task_type: "HR Request",
    request_date: "2025-01-11",
    completion_date: null,
    status: "Pending",
    assigned_to: "David Mugisha",
    priority: "Medium",
    sla_due_date: "2025-01-13",
    sla_met: null,
    error_flag: null,
    requestor_department: "Marketing",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T078",
    task_type: "HR Request",
    request_date: "2025-01-12",
    completion_date: "2025-01-14",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "Medium",
    sla_due_date: "2025-01-17",
    sla_met: true,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 51,
    customer_satisfaction: 3,
  },
  {
    task_id: "T079",
    task_type: "Facility Maintenance",
    request_date: "2025-05-08",
    completion_date: null,
    status: "Pending",
    assigned_to: "Sarah Kintu",
    priority: "Medium",
    sla_due_date: "2025-05-11",
    sla_met: null,
    error_flag: null,
    requestor_department: "Editorial",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T080",
    task_type: "IT Support",
    request_date: "2025-08-05",
    completion_date: "2025-08-07",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "Low",
    sla_due_date: "2025-08-10",
    sla_met: true,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 53,
    customer_satisfaction: 5,
  },
  {
    task_id: "T081",
    task_type: "IT Support",
    request_date: "2025-01-13",
    completion_date: null,
    status: "Pending",
    assigned_to: "David Mugisha",
    priority: "Low",
    sla_due_date: "2025-01-18",
    sla_met: null,
    error_flag: null,
    requestor_department: "Editorial",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T082",
    task_type: "IT Support",
    request_date: "2025-01-29",
    completion_date: "2025-01-30",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "Low",
    sla_due_date: "2025-01-31",
    sla_met: true,
    error_flag: false,
    requestor_department: "Editorial",
    completion_time_hours: 28,
    customer_satisfaction: 1,
  },
  {
    task_id: "T083",
    task_type: "Procurement",
    request_date: "2025-03-12",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-03-15",
    sla_met: null,
    error_flag: null,
    requestor_department: "Sales",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T084",
    task_type: "HR Request",
    request_date: "2025-04-18",
    completion_date: null,
    status: "In Progress",
    assigned_to: "John Okello",
    priority: "High",
    sla_due_date: "2025-04-22",
    sla_met: null,
    error_flag: null,
    requestor_department: "Finance",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T085",
    task_type: "HR Request",
    request_date: "2025-05-19",
    completion_date: "2025-05-26",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "High",
    sla_due_date: "2025-05-22",
    sla_met: false,
    error_flag: false,
    requestor_department: "Production",
    completion_time_hours: 173,
    customer_satisfaction: 1,
  },
  {
    task_id: "T086",
    task_type: "HR Request",
    request_date: "2025-04-18",
    completion_date: "2025-04-22",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "Low",
    sla_due_date: "2025-04-20",
    sla_met: false,
    error_flag: true,
    requestor_department: "Editorial",
    completion_time_hours: 100,
    customer_satisfaction: 3,
  },
  {
    task_id: "T087",
    task_type: "IT Support",
    request_date: "2025-04-01",
    completion_date: "2025-04-08",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Medium",
    sla_due_date: "2025-04-06",
    sla_met: false,
    error_flag: false,
    requestor_department: "Marketing",
    completion_time_hours: 174,
    customer_satisfaction: 5,
  },
  {
    task_id: "T088",
    task_type: "HR Request",
    request_date: "2025-08-10",
    completion_date: "2025-08-11",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-08-15",
    sla_met: true,
    error_flag: false,
    requestor_department: "Production",
    completion_time_hours: 32,
    customer_satisfaction: 1,
  },
  {
    task_id: "T089",
    task_type: "IT Support",
    request_date: "2025-04-08",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Sarah Kintu",
    priority: "Medium",
    sla_due_date: "2025-04-13",
    sla_met: null,
    error_flag: null,
    requestor_department: "Production",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T090",
    task_type: "HR Request",
    request_date: "2025-05-07",
    completion_date: "2025-05-08",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "Low",
    sla_due_date: "2025-05-12",
    sla_met: true,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 30,
    customer_satisfaction: 4,
  },
  {
    task_id: "T091",
    task_type: "IT Support",
    request_date: "2025-03-07",
    completion_date: "2025-03-08",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "High",
    sla_due_date: "2025-03-11",
    sla_met: true,
    error_flag: false,
    requestor_department: "Marketing",
    completion_time_hours: 24,
    customer_satisfaction: 3,
  },
  {
    task_id: "T092",
    task_type: "Facility Maintenance",
    request_date: "2025-08-09",
    completion_date: "2025-08-09",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "Medium",
    sla_due_date: "2025-08-14",
    sla_met: true,
    error_flag: false,
    requestor_department: "Production",
    completion_time_hours: 4,
    customer_satisfaction: 5,
  },
  {
    task_id: "T093",
    task_type: "IT Support",
    request_date: "2025-07-26",
    completion_date: "2025-08-01",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "High",
    sla_due_date: "2025-07-31",
    sla_met: false,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 146,
    customer_satisfaction: 4,
  },
  {
    task_id: "T094",
    task_type: "Procurement",
    request_date: "2025-04-06",
    completion_date: null,
    status: "Pending",
    assigned_to: "Mary Nambasa",
    priority: "High",
    sla_due_date: "2025-04-09",
    sla_met: null,
    error_flag: null,
    requestor_department: "Sales",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T095",
    task_type: "IT Support",
    request_date: "2025-08-10",
    completion_date: "2025-08-12",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "Low",
    sla_due_date: "2025-08-14",
    sla_met: true,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 48,
    customer_satisfaction: 1,
  },
  {
    task_id: "T096",
    task_type: "Facility Maintenance",
    request_date: "2025-01-24",
    completion_date: "2025-01-28",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "High",
    sla_due_date: "2025-01-27",
    sla_met: false,
    error_flag: false,
    requestor_department: "Marketing",
    completion_time_hours: 102,
    customer_satisfaction: 1,
  },
  {
    task_id: "T097",
    task_type: "Facility Maintenance",
    request_date: "2025-03-07",
    completion_date: "2025-03-08",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Low",
    sla_due_date: "2025-03-11",
    sla_met: true,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 30,
    customer_satisfaction: 1,
  },
  {
    task_id: "T098",
    task_type: "HR Request",
    request_date: "2025-06-16",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Paul Ssemanda",
    priority: "High",
    sla_due_date: "2025-06-19",
    sla_met: null,
    error_flag: null,
    requestor_department: "Sales",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T099",
    task_type: "IT Support",
    request_date: "2025-02-12",
    completion_date: "2025-02-17",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "Medium",
    sla_due_date: "2025-02-17",
    sla_met: true,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 124,
    customer_satisfaction: 2,
  },
  {
    task_id: "T100",
    task_type: "HR Request",
    request_date: "2025-01-30",
    completion_date: null,
    status: "Pending",
    assigned_to: "John Okello",
    priority: "High",
    sla_due_date: "2025-02-01",
    sla_met: null,
    error_flag: null,
    requestor_department: "Production",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T101",
    task_type: "Facility Maintenance",
    request_date: "2025-02-15",
    completion_date: "2025-02-15",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "High",
    sla_due_date: "2025-02-20",
    sla_met: true,
    error_flag: false,
    requestor_department: "Marketing",
    completion_time_hours: 2,
    customer_satisfaction: 5,
  },
  {
    task_id: "T102",
    task_type: "Procurement",
    request_date: "2025-07-11",
    completion_date: "2025-07-15",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "Medium",
    sla_due_date: "2025-07-13",
    sla_met: false,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 103,
    customer_satisfaction: 3,
  },
  {
    task_id: "T103",
    task_type: "HR Request",
    request_date: "2025-08-25",
    completion_date: "2025-08-27",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "High",
    sla_due_date: "2025-08-27",
    sla_met: true,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 51,
    customer_satisfaction: 4,
  },
  {
    task_id: "T104",
    task_type: "Procurement",
    request_date: "2025-05-22",
    completion_date: null,
    status: "Pending",
    assigned_to: "Mary Nambasa",
    priority: "Low",
    sla_due_date: "2025-05-25",
    sla_met: null,
    error_flag: null,
    requestor_department: "Finance",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T105",
    task_type: "Facility Maintenance",
    request_date: "2025-05-04",
    completion_date: "2025-05-10",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-05-09",
    sla_met: false,
    error_flag: false,
    requestor_department: "Editorial",
    completion_time_hours: 148,
    customer_satisfaction: 5,
  },
  {
    task_id: "T106",
    task_type: "Facility Maintenance",
    request_date: "2025-05-05",
    completion_date: "2025-05-05",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-05-07",
    sla_met: true,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 5,
    customer_satisfaction: 3,
  },
  {
    task_id: "T107",
    task_type: "Procurement",
    request_date: "2025-05-11",
    completion_date: "2025-05-15",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "Medium",
    sla_due_date: "2025-05-15",
    sla_met: true,
    error_flag: false,
    requestor_department: "Editorial",
    completion_time_hours: 98,
    customer_satisfaction: 2,
  },
  {
    task_id: "T108",
    task_type: "Procurement",
    request_date: "2025-01-31",
    completion_date: "2025-02-06",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-02-03",
    sla_met: false,
    error_flag: false,
    requestor_department: "Marketing",
    completion_time_hours: 146,
    customer_satisfaction: 1,
  },
  {
    task_id: "T109",
    task_type: "Facility Maintenance",
    request_date: "2025-02-14",
    completion_date: null,
    status: "Pending",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-02-19",
    sla_met: null,
    error_flag: null,
    requestor_department: "Editorial",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T110",
    task_type: "Procurement",
    request_date: "2025-03-25",
    completion_date: "2025-03-30",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "Medium",
    sla_due_date: "2025-03-28",
    sla_met: false,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 127,
    customer_satisfaction: 2,
  },
  {
    task_id: "T111",
    task_type: "IT Support",
    request_date: "2025-04-20",
    completion_date: "2025-04-24",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Low",
    sla_due_date: "2025-04-24",
    sla_met: true,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 104,
    customer_satisfaction: 1,
  },
  {
    task_id: "T112",
    task_type: "Procurement",
    request_date: "2025-04-02",
    completion_date: "2025-04-02",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "Low",
    sla_due_date: "2025-04-07",
    sla_met: true,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 6,
    customer_satisfaction: 2,
  },
  {
    task_id: "T113",
    task_type: "Facility Maintenance",
    request_date: "2025-01-05",
    completion_date: "2025-01-12",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "High",
    sla_due_date: "2025-01-08",
    sla_met: false,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 170,
    customer_satisfaction: 4,
  },
  {
    task_id: "T114",
    task_type: "Procurement",
    request_date: "2025-01-30",
    completion_date: "2025-02-01",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "High",
    sla_due_date: "2025-02-03",
    sla_met: true,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 53,
    customer_satisfaction: 1,
  },
  {
    task_id: "T115",
    task_type: "Procurement",
    request_date: "2025-05-11",
    completion_date: "2025-05-15",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "High",
    sla_due_date: "2025-05-14",
    sla_met: false,
    error_flag: false,
    requestor_department: "Editorial",
    completion_time_hours: 96,
    customer_satisfaction: 1,
  },
  {
    task_id: "T116",
    task_type: "Procurement",
    request_date: "2025-06-20",
    completion_date: "2025-06-20",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "High",
    sla_due_date: "2025-06-25",
    sla_met: true,
    error_flag: true,
    requestor_department: "Finance",
    completion_time_hours: 1,
    customer_satisfaction: 2,
  },
  {
    task_id: "T117",
    task_type: "Procurement",
    request_date: "2025-07-16",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Sarah Kintu",
    priority: "Medium",
    sla_due_date: "2025-07-19",
    sla_met: null,
    error_flag: null,
    requestor_department: "Marketing",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T118",
    task_type: "HR Request",
    request_date: "2025-04-16",
    completion_date: "2025-04-20",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "High",
    sla_due_date: "2025-04-18",
    sla_met: false,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 101,
    customer_satisfaction: 4,
  },
  {
    task_id: "T119",
    task_type: "HR Request",
    request_date: "2025-02-08",
    completion_date: "2025-02-15",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "Medium",
    sla_due_date: "2025-02-13",
    sla_met: false,
    error_flag: true,
    requestor_department: "Finance",
    completion_time_hours: 168,
    customer_satisfaction: 5,
  },
  {
    task_id: "T120",
    task_type: "HR Request",
    request_date: "2025-08-06",
    completion_date: "2025-08-06",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "Low",
    sla_due_date: "2025-08-11",
    sla_met: true,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 2,
    customer_satisfaction: 1,
  },
  {
    task_id: "T121",
    task_type: "HR Request",
    request_date: "2025-04-19",
    completion_date: "2025-04-23",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "High",
    sla_due_date: "2025-04-23",
    sla_met: true,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 103,
    customer_satisfaction: 1,
  },
  {
    task_id: "T122",
    task_type: "HR Request",
    request_date: "2025-06-10",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-06-12",
    sla_met: null,
    error_flag: null,
    requestor_department: "Editorial",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T123",
    task_type: "IT Support",
    request_date: "2025-05-24",
    completion_date: "2025-05-31",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "High",
    sla_due_date: "2025-05-29",
    sla_met: false,
    error_flag: false,
    requestor_department: "Marketing",
    completion_time_hours: 168,
    customer_satisfaction: 2,
  },
  {
    task_id: "T124",
    task_type: "HR Request",
    request_date: "2025-06-09",
    completion_date: "2025-06-09",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "Medium",
    sla_due_date: "2025-06-12",
    sla_met: true,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 6,
    customer_satisfaction: 2,
  },
  {
    task_id: "T125",
    task_type: "Facility Maintenance",
    request_date: "2025-04-25",
    completion_date: "2025-04-27",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "High",
    sla_due_date: "2025-04-27",
    sla_met: true,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 54,
    customer_satisfaction: 5,
  },
  {
    task_id: "T126",
    task_type: "HR Request",
    request_date: "2025-02-04",
    completion_date: "2025-02-10",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "High",
    sla_due_date: "2025-02-06",
    sla_met: false,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 146,
    customer_satisfaction: 2,
  },
  {
    task_id: "T127",
    task_type: "HR Request",
    request_date: "2025-04-30",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Grace Nakato",
    priority: "Medium",
    sla_due_date: "2025-05-03",
    sla_met: null,
    error_flag: null,
    requestor_department: "Editorial",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T128",
    task_type: "Procurement",
    request_date: "2025-07-20",
    completion_date: "2025-07-27",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "Low",
    sla_due_date: "2025-07-22",
    sla_met: false,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 176,
    customer_satisfaction: 1,
  },
  {
    task_id: "T129",
    task_type: "Facility Maintenance",
    request_date: "2025-04-13",
    completion_date: null,
    status: "Pending",
    assigned_to: "John Okello",
    priority: "High",
    sla_due_date: "2025-04-15",
    sla_met: null,
    error_flag: null,
    requestor_department: "Production",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T130",
    task_type: "HR Request",
    request_date: "2025-08-28",
    completion_date: "2025-09-04",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-09-01",
    sla_met: false,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 176,
    customer_satisfaction: 1,
  },
  {
    task_id: "T131",
    task_type: "Facility Maintenance",
    request_date: "2025-04-21",
    completion_date: "2025-04-28",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "High",
    sla_due_date: "2025-04-23",
    sla_met: false,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 171,
    customer_satisfaction: 2,
  },
  {
    task_id: "T132",
    task_type: "HR Request",
    request_date: "2025-04-03",
    completion_date: "2025-04-06",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "High",
    sla_due_date: "2025-04-06",
    sla_met: true,
    error_flag: false,
    requestor_department: "Production",
    completion_time_hours: 73,
    customer_satisfaction: 1,
  },
  {
    task_id: "T133",
    task_type: "HR Request",
    request_date: "2025-03-19",
    completion_date: "2025-03-26",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "Medium",
    sla_due_date: "2025-03-23",
    sla_met: false,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 176,
    customer_satisfaction: 4,
  },
  {
    task_id: "T134",
    task_type: "Facility Maintenance",
    request_date: "2025-01-08",
    completion_date: "2025-01-08",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "Medium",
    sla_due_date: "2025-01-13",
    sla_met: true,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 2,
    customer_satisfaction: 2,
  },
  {
    task_id: "T135",
    task_type: "Facility Maintenance",
    request_date: "2025-01-01",
    completion_date: "2025-01-08",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "Medium",
    sla_due_date: "2025-01-04",
    sla_met: false,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 169,
    customer_satisfaction: 2,
  },
  {
    task_id: "T136",
    task_type: "IT Support",
    request_date: "2025-05-19",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Grace Nakato",
    priority: "High",
    sla_due_date: "2025-05-24",
    sla_met: null,
    error_flag: null,
    requestor_department: "Finance",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T137",
    task_type: "IT Support",
    request_date: "2025-06-12",
    completion_date: null,
    status: "Pending",
    assigned_to: "Grace Nakato",
    priority: "High",
    sla_due_date: "2025-06-14",
    sla_met: null,
    error_flag: null,
    requestor_department: "Sales",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T138",
    task_type: "IT Support",
    request_date: "2025-04-16",
    completion_date: "2025-04-16",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "Medium",
    sla_due_date: "2025-04-21",
    sla_met: true,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 4,
    customer_satisfaction: 3,
  },
  {
    task_id: "T139",
    task_type: "HR Request",
    request_date: "2025-06-11",
    completion_date: "2025-06-13",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-06-16",
    sla_met: true,
    error_flag: false,
    requestor_department: "Production",
    completion_time_hours: 52,
    customer_satisfaction: 1,
  },
  {
    task_id: "T140",
    task_type: "Facility Maintenance",
    request_date: "2025-06-01",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Sarah Kintu",
    priority: "Medium",
    sla_due_date: "2025-06-05",
    sla_met: null,
    error_flag: null,
    requestor_department: "Editorial",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T141",
    task_type: "Procurement",
    request_date: "2025-05-30",
    completion_date: "2025-06-06",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "High",
    sla_due_date: "2025-06-01",
    sla_met: false,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 174,
    customer_satisfaction: 4,
  },
  {
    task_id: "T142",
    task_type: "Facility Maintenance",
    request_date: "2025-08-09",
    completion_date: "2025-08-14",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "Medium",
    sla_due_date: "2025-08-13",
    sla_met: false,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 120,
    customer_satisfaction: 1,
  },
  {
    task_id: "T143",
    task_type: "Facility Maintenance",
    request_date: "2025-03-06",
    completion_date: "2025-03-09",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-03-08",
    sla_met: false,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 77,
    customer_satisfaction: 1,
  },
  {
    task_id: "T144",
    task_type: "IT Support",
    request_date: "2025-05-14",
    completion_date: "2025-05-15",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "Medium",
    sla_due_date: "2025-05-19",
    sla_met: true,
    error_flag: false,
    requestor_department: "Marketing",
    completion_time_hours: 31,
    customer_satisfaction: 3,
  },
  {
    task_id: "T145",
    task_type: "Procurement",
    request_date: "2025-04-25",
    completion_date: "2025-04-26",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "High",
    sla_due_date: "2025-04-29",
    sla_met: true,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 31,
    customer_satisfaction: 4,
  },
  {
    task_id: "T146",
    task_type: "Procurement",
    request_date: "2025-02-21",
    completion_date: null,
    status: "In Progress",
    assigned_to: "David Mugisha",
    priority: "Medium",
    sla_due_date: "2025-02-23",
    sla_met: null,
    error_flag: null,
    requestor_department: "Editorial",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T147",
    task_type: "Facility Maintenance",
    request_date: "2025-07-05",
    completion_date: "2025-07-07",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "Medium",
    sla_due_date: "2025-07-09",
    sla_met: true,
    error_flag: false,
    requestor_department: "Production",
    completion_time_hours: 56,
    customer_satisfaction: 5,
  },
  {
    task_id: "T148",
    task_type: "IT Support",
    request_date: "2025-05-24",
    completion_date: "2025-05-29",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "Medium",
    sla_due_date: "2025-05-27",
    sla_met: false,
    error_flag: false,
    requestor_department: "Editorial",
    completion_time_hours: 125,
    customer_satisfaction: 4,
  },
  {
    task_id: "T149",
    task_type: "IT Support",
    request_date: "2025-01-31",
    completion_date: "2025-02-01",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "High",
    sla_due_date: "2025-02-02",
    sla_met: true,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 29,
    customer_satisfaction: 2,
  },
  {
    task_id: "T150",
    task_type: "HR Request",
    request_date: "2025-08-19",
    completion_date: "2025-08-25",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "Medium",
    sla_due_date: "2025-08-21",
    sla_met: false,
    error_flag: true,
    requestor_department: "Finance",
    completion_time_hours: 150,
    customer_satisfaction: 2,
  },
  {
    task_id: "T151",
    task_type: "HR Request",
    request_date: "2025-07-22",
    completion_date: "2025-07-26",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "Low",
    sla_due_date: "2025-07-24",
    sla_met: false,
    error_flag: false,
    requestor_department: "Production",
    completion_time_hours: 101,
    customer_satisfaction: 2,
  },
  {
    task_id: "T152",
    task_type: "HR Request",
    request_date: "2025-06-16",
    completion_date: "2025-06-21",
    status: "Completed",
    assigned_to: "David Mugisha",
    priority: "Low",
    sla_due_date: "2025-06-19",
    sla_met: false,
    error_flag: false,
    requestor_department: "Production",
    completion_time_hours: 121,
    customer_satisfaction: 4,
  },
  {
    task_id: "T153",
    task_type: "IT Support",
    request_date: "2025-06-09",
    completion_date: "2025-06-14",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Medium",
    sla_due_date: "2025-06-13",
    sla_met: false,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 121,
    customer_satisfaction: 5,
  },
  {
    task_id: "T154",
    task_type: "Procurement",
    request_date: "2025-02-19",
    completion_date: null,
    status: "Pending",
    assigned_to: "Grace Nakato",
    priority: "Medium",
    sla_due_date: "2025-02-21",
    sla_met: null,
    error_flag: null,
    requestor_department: "Finance",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T155",
    task_type: "Facility Maintenance",
    request_date: "2025-03-12",
    completion_date: "2025-03-14",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "High",
    sla_due_date: "2025-03-14",
    sla_met: true,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 53,
    customer_satisfaction: 5,
  },
  {
    task_id: "T156",
    task_type: "Facility Maintenance",
    request_date: "2025-03-01",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Paul Ssemanda",
    priority: "Low",
    sla_due_date: "2025-03-06",
    sla_met: null,
    error_flag: null,
    requestor_department: "Production",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T157",
    task_type: "Procurement",
    request_date: "2025-06-13",
    completion_date: "2025-06-20",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "Medium",
    sla_due_date: "2025-06-17",
    sla_met: false,
    error_flag: false,
    requestor_department: "Marketing",
    completion_time_hours: 170,
    customer_satisfaction: 1,
  },
  {
    task_id: "T158",
    task_type: "HR Request",
    request_date: "2025-05-09",
    completion_date: "2025-05-09",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "High",
    sla_due_date: "2025-05-14",
    sla_met: true,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 8,
    customer_satisfaction: 3,
  },
  {
    task_id: "T159",
    task_type: "Procurement",
    request_date: "2025-01-23",
    completion_date: "2025-01-26",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Low",
    sla_due_date: "2025-01-25",
    sla_met: false,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 77,
    customer_satisfaction: 1,
  },
  {
    task_id: "T160",
    task_type: "Facility Maintenance",
    request_date: "2025-07-18",
    completion_date: null,
    status: "Pending",
    assigned_to: "John Okello",
    priority: "Medium",
    sla_due_date: "2025-07-23",
    sla_met: null,
    error_flag: null,
    requestor_department: "Production",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T161",
    task_type: "HR Request",
    request_date: "2025-04-27",
    completion_date: "2025-04-27",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "High",
    sla_due_date: "2025-05-01",
    sla_met: true,
    error_flag: true,
    requestor_department: "Editorial",
    completion_time_hours: 3,
    customer_satisfaction: 2,
  },
  {
    task_id: "T162",
    task_type: "Procurement",
    request_date: "2025-04-27",
    completion_date: "2025-05-03",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-04-29",
    sla_met: false,
    error_flag: false,
    requestor_department: "Production",
    completion_time_hours: 149,
    customer_satisfaction: 1,
  },
  {
    task_id: "T163",
    task_type: "Procurement",
    request_date: "2025-01-21",
    completion_date: "2025-01-23",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-01-26",
    sla_met: true,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 51,
    customer_satisfaction: 2,
  },
  {
    task_id: "T164",
    task_type: "IT Support",
    request_date: "2025-07-15",
    completion_date: "2025-07-22",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "High",
    sla_due_date: "2025-07-20",
    sla_met: false,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 171,
    customer_satisfaction: 2,
  },
  {
    task_id: "T165",
    task_type: "Facility Maintenance",
    request_date: "2025-04-06",
    completion_date: "2025-04-09",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Low",
    sla_due_date: "2025-04-08",
    sla_met: false,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 74,
    customer_satisfaction: 4,
  },
  {
    task_id: "T166",
    task_type: "HR Request",
    request_date: "2025-08-31",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Grace Nakato",
    priority: "Medium",
    sla_due_date: "2025-09-05",
    sla_met: null,
    error_flag: null,
    requestor_department: "Sales",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T167",
    task_type: "IT Support",
    request_date: "2025-08-30",
    completion_date: "2025-08-31",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "Medium",
    sla_due_date: "2025-09-01",
    sla_met: true,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 26,
    customer_satisfaction: 1,
  },
  {
    task_id: "T168",
    task_type: "HR Request",
    request_date: "2025-05-04",
    completion_date: "2025-05-08",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-05-06",
    sla_met: false,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 102,
    customer_satisfaction: 4,
  },
  {
    task_id: "T169",
    task_type: "Procurement",
    request_date: "2025-06-30",
    completion_date: "2025-06-30",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-07-04",
    sla_met: true,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 4,
    customer_satisfaction: 4,
  },
  {
    task_id: "T170",
    task_type: "Procurement",
    request_date: "2025-06-01",
    completion_date: "2025-06-03",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "Medium",
    sla_due_date: "2025-06-06",
    sla_met: true,
    error_flag: true,
    requestor_department: "Sales",
    completion_time_hours: 55,
    customer_satisfaction: 5,
  },
  {
    task_id: "T171",
    task_type: "HR Request",
    request_date: "2025-03-18",
    completion_date: "2025-03-22",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-03-22",
    sla_met: true,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 103,
    customer_satisfaction: 1,
  },
  {
    task_id: "T172",
    task_type: "HR Request",
    request_date: "2025-03-27",
    completion_date: "2025-03-31",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "Medium",
    sla_due_date: "2025-04-01",
    sla_met: true,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 102,
    customer_satisfaction: 5,
  },
  {
    task_id: "T173",
    task_type: "Facility Maintenance",
    request_date: "2025-05-01",
    completion_date: "2025-05-03",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "High",
    sla_due_date: "2025-05-04",
    sla_met: true,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 51,
    customer_satisfaction: 5,
  },
  {
    task_id: "T174",
    task_type: "Procurement",
    request_date: "2025-03-04",
    completion_date: "2025-03-05",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "High",
    sla_due_date: "2025-03-08",
    sla_met: true,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 32,
    customer_satisfaction: 3,
  },
  {
    task_id: "T175",
    task_type: "IT Support",
    request_date: "2025-05-30",
    completion_date: "2025-06-04",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Low",
    sla_due_date: "2025-06-04",
    sla_met: true,
    error_flag: true,
    requestor_department: "Production",
    completion_time_hours: 127,
    customer_satisfaction: 3,
  },
  {
    task_id: "T176",
    task_type: "Facility Maintenance",
    request_date: "2025-05-31",
    completion_date: "2025-06-07",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-06-05",
    sla_met: false,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 175,
    customer_satisfaction: 2,
  },
  {
    task_id: "T177",
    task_type: "HR Request",
    request_date: "2025-06-12",
    completion_date: "2025-06-19",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "Low",
    sla_due_date: "2025-06-17",
    sla_met: false,
    error_flag: false,
    requestor_department: "Editorial",
    completion_time_hours: 170,
    customer_satisfaction: 5,
  },
  {
    task_id: "T178",
    task_type: "Procurement",
    request_date: "2025-01-11",
    completion_date: null,
    status: "In Progress",
    assigned_to: "John Okello",
    priority: "Low",
    sla_due_date: "2025-01-15",
    sla_met: null,
    error_flag: null,
    requestor_department: "Finance",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T179",
    task_type: "HR Request",
    request_date: "2025-01-07",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-01-11",
    sla_met: null,
    error_flag: null,
    requestor_department: "Marketing",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T180",
    task_type: "Procurement",
    request_date: "2025-04-19",
    completion_date: "2025-04-24",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-04-21",
    sla_met: false,
    error_flag: false,
    requestor_department: "Marketing",
    completion_time_hours: 122,
    customer_satisfaction: 3,
  },
  {
    task_id: "T181",
    task_type: "HR Request",
    request_date: "2025-03-01",
    completion_date: "2025-03-01",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "High",
    sla_due_date: "2025-03-04",
    sla_met: true,
    error_flag: true,
    requestor_department: "Editorial",
    completion_time_hours: 3,
    customer_satisfaction: 3,
  },
  {
    task_id: "T182",
    task_type: "HR Request",
    request_date: "2025-02-12",
    completion_date: "2025-02-13",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Medium",
    sla_due_date: "2025-02-16",
    sla_met: true,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 29,
    customer_satisfaction: 1,
  },
  {
    task_id: "T183",
    task_type: "HR Request",
    request_date: "2025-03-13",
    completion_date: "2025-03-17",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "High",
    sla_due_date: "2025-03-17",
    sla_met: true,
    error_flag: false,
    requestor_department: "Marketing",
    completion_time_hours: 102,
    customer_satisfaction: 1,
  },
  {
    task_id: "T184",
    task_type: "IT Support",
    request_date: "2025-07-04",
    completion_date: null,
    status: "In Progress",
    assigned_to: "David Mugisha",
    priority: "Low",
    sla_due_date: "2025-07-06",
    sla_met: null,
    error_flag: null,
    requestor_department: "Finance",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T185",
    task_type: "HR Request",
    request_date: "2025-01-22",
    completion_date: "2025-01-28",
    status: "Completed",
    assigned_to: "Paul Ssemanda",
    priority: "Medium",
    sla_due_date: "2025-01-26",
    sla_met: false,
    error_flag: false,
    requestor_department: "Finance",
    completion_time_hours: 151,
    customer_satisfaction: 5,
  },
  {
    task_id: "T186",
    task_type: "Facility Maintenance",
    request_date: "2025-06-21",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-06-26",
    sla_met: null,
    error_flag: null,
    requestor_department: "Sales",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T187",
    task_type: "Procurement",
    request_date: "2025-01-07",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Mary Nambasa",
    priority: "Low",
    sla_due_date: "2025-01-09",
    sla_met: null,
    error_flag: null,
    requestor_department: "Production",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T188",
    task_type: "Procurement",
    request_date: "2025-01-09",
    completion_date: "2025-01-16",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "Low",
    sla_due_date: "2025-01-12",
    sla_met: false,
    error_flag: true,
    requestor_department: "Finance",
    completion_time_hours: 173,
    customer_satisfaction: 1,
  },
  {
    task_id: "T189",
    task_type: "Procurement",
    request_date: "2025-02-14",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Grace Nakato",
    priority: "Low",
    sla_due_date: "2025-02-16",
    sla_met: null,
    error_flag: null,
    requestor_department: "Finance",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T190",
    task_type: "Facility Maintenance",
    request_date: "2025-06-11",
    completion_date: "2025-06-14",
    status: "Completed",
    assigned_to: "Sarah Kintu",
    priority: "Medium",
    sla_due_date: "2025-06-13",
    sla_met: false,
    error_flag: true,
    requestor_department: "Editorial",
    completion_time_hours: 78,
    customer_satisfaction: 3,
  },
  {
    task_id: "T191",
    task_type: "HR Request",
    request_date: "2025-05-23",
    completion_date: null,
    status: "Pending",
    assigned_to: "Sarah Kintu",
    priority: "High",
    sla_due_date: "2025-05-25",
    sla_met: null,
    error_flag: null,
    requestor_department: "Production",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T192",
    task_type: "HR Request",
    request_date: "2025-06-18",
    completion_date: null,
    status: "In Progress",
    assigned_to: "Paul Ssemanda",
    priority: "Low",
    sla_due_date: "2025-06-22",
    sla_met: null,
    error_flag: null,
    requestor_department: "Marketing",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T193",
    task_type: "Facility Maintenance",
    request_date: "2025-08-23",
    completion_date: "2025-08-26",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "Low",
    sla_due_date: "2025-08-27",
    sla_met: true,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 74,
    customer_satisfaction: 5,
  },
  {
    task_id: "T194",
    task_type: "Procurement",
    request_date: "2025-02-28",
    completion_date: null,
    status: "In Progress",
    assigned_to: "John Okello",
    priority: "Medium",
    sla_due_date: "2025-03-05",
    sla_met: null,
    error_flag: null,
    requestor_department: "Production",
    completion_time_hours: null,
    customer_satisfaction: null,
  },
  {
    task_id: "T195",
    task_type: "Facility Maintenance",
    request_date: "2025-02-21",
    completion_date: "2025-02-27",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-02-26",
    sla_met: false,
    error_flag: false,
    requestor_department: "Editorial",
    completion_time_hours: 149,
    customer_satisfaction: 2,
  },
  {
    task_id: "T196",
    task_type: "IT Support",
    request_date: "2025-06-04",
    completion_date: "2025-06-06",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "Medium",
    sla_due_date: "2025-06-07",
    sla_met: true,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 50,
    customer_satisfaction: 1,
  },
  {
    task_id: "T197",
    task_type: "Facility Maintenance",
    request_date: "2025-04-20",
    completion_date: "2025-04-24",
    status: "Completed",
    assigned_to: "Grace Nakato",
    priority: "Low",
    sla_due_date: "2025-04-25",
    sla_met: true,
    error_flag: false,
    requestor_department: "Sales",
    completion_time_hours: 98,
    customer_satisfaction: 4,
  },
  {
    task_id: "T198",
    task_type: "HR Request",
    request_date: "2025-06-24",
    completion_date: "2025-06-27",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "High",
    sla_due_date: "2025-06-26",
    sla_met: false,
    error_flag: false,
    requestor_department: "Editorial",
    completion_time_hours: 73,
    customer_satisfaction: 1,
  },
  {
    task_id: "T199",
    task_type: "HR Request",
    request_date: "2025-07-24",
    completion_date: "2025-07-25",
    status: "Completed",
    assigned_to: "John Okello",
    priority: "High",
    sla_due_date: "2025-07-26",
    sla_met: true,
    error_flag: true,
    requestor_department: "Marketing",
    completion_time_hours: 25,
    customer_satisfaction: 1,
  },
  {
    task_id: "T200",
    task_type: "HR Request",
    request_date: "2025-06-25",
    completion_date: "2025-07-01",
    status: "Completed",
    assigned_to: "Mary Nambasa",
    priority: "Medium",
    sla_due_date: "2025-06-27",
    sla_met: false,
    error_flag: false,
    requestor_department: "Production",
    completion_time_hours: 152,
    customer_satisfaction: 2,
  },
];
