export const processThroughputDummy = [
  {
    request_id: "REQ001",
    request_date: "2025-01-08",
    process_type: "Procurement",
    department: "Administration",
    assignee: "John Doe",
    status: "Completed",
    start_time: "09:00",
    end_time: "11:30",
    duration_minutes: 150,
  },
  {
    request_id: "REQ002",
    request_date: "2025-01-15",
    process_type: "HR Onboarding",
    department: "HR",
    assignee: "Jane Smith",
    status: "In Progress",
    start_time: "10:00",
    end_time: null,
    duration_minutes: null,
  },
  {
    request_id: "REQ003",
    request_date: "2025-02-03",
    process_type: "Asset Requisition",
    department: "IT",
    assignee: "Peter Kato",
    status: "Completed",
    start_time: "08:30",
    end_time: "09:45",
    duration_minutes: 75,
  },
  {
    request_id: "REQ004",
    request_date: "2025-02-20",
    process_type: "Maintenance Request",
    department: "Operations",
    assignee: "Alice Nabwire",
    status: "Pending",
    start_time: "13:00",
    end_time: null,
    duration_minutes: null,
  },
  {
    request_id: "REQ005",
    request_date: "2025-03-10",
    process_type: "Travel Approval",
    department: "Sales",
    assignee: "Michael Ouma",
    status: "Completed",
    start_time: "14:00",
    end_time: "14:30",
    duration_minutes: 30,
  },
];
