const dummyAssets = [
  {
    assetId: "A001",
    name: "Dell Latitude 5420",
    type: "Hardware",
    category: "Laptop",
    model: "Latitude 5420",
    assignedTo: "John Doe",
    department: "Editorial",
    usage: "Content writing & editing",
    costUSD: 1200,
    purchaseDate: "2023-03-15",
    status: "Active"
  },
  {
    assetId: "A002",
    name: "HP LaserJet Pro M404dn",
    type: "Hardware",
    category: "Printer",
    model: "M404dn",
    assignedTo: "Shared",
    department: "Operations and Production",
    usage: "Document printing",
    costUSD: 450,
    purchaseDate: "2022-10-10",
    status: "Active"
  },
  {
    assetId: "A003",
    name: "Microsoft 365 Business Standard",
    type: "Software",
    category: "Productivity Suite",
    model: "Cloud License",
    assignedTo: "All Staff",
    department: "Company-wide",
    usage: "Emails, documents, spreadsheets",
    costUSD: 8000,
    purchaseDate: "2024-01-01",
    status: "Active"
  },
  {
    assetId: "A004",
    name: "Google Analytics 4",
    type: "Cloud Service",
    category: "Analytics",
    model: "GA4",
    assignedTo: "Analytics Team",
    department: "Sales and Marketing",
    usage: "Traffic and campaign tracking",
    costUSD: 0,
    purchaseDate: "2023-05-01",
    status: "Active"
  },
  {
    assetId: "A005",
    name: "AWS EC2 - Editorial Server",
    type: "Cloud Service",
    category: "Server",
    model: "t3.large",
    assignedTo: "Editorial",
    department: "IT",
    usage: "CMS hosting",
    costUSD: 350,
    purchaseDate: "2024-06-20",
    status: "Active"
  },
  {
    assetId: "A006",
    name: "Azure SQL Database - Finance",
    type: "Cloud Service",
    category: "Database",
    model: "Business Critical Tier",
    assignedTo: "Finance",
    department: "Finance",
    usage: "Financial reporting database",
    costUSD: 600,
    purchaseDate: "2024-02-10",
    status: "Active"
  },
  {
    assetId: "A007",
    name: "MacBook Pro 16”",
    type: "Hardware",
    category: "Laptop",
    model: "M1 Pro 2021",
    assignedTo: "Jane Smith",
    department: "Executives",
    usage: "Management & presentations",
    costUSD: 2400,
    purchaseDate: "2023-08-25",
    status: "Active"
  },
  {
    assetId: "A008",
    name: "Epson Projector EB-S41",
    type: "Hardware",
    category: "Projector",
    model: "EB-S41",
    assignedTo: "Shared",
    department: "HR",
    usage: "Training & presentations",
    costUSD: 650,
    purchaseDate: "2021-09-01",
    status: "Inactive"
  },
  {
    assetId: "A009",
    name: "Legal Case Management Software",
    type: "Software",
    category: "Case Management",
    model: "v3.5",
    assignedTo: "Legal Team",
    department: "Legal",
    usage: "Case documentation & tracking",
    costUSD: 1200,
    purchaseDate: "2023-04-14",
    status: "Active"
  },
  {
    assetId: "A010",
    name: "Canon EOS 90D Camera",
    type: "Hardware",
    category: "Camera",
    model: "EOS 90D",
    assignedTo: "Photography Team",
    department: "Editorial",
    usage: "News photography",
    costUSD: 1500,
    purchaseDate: "2023-11-30",
    status: "Active"
  },
  {
    assetId: "A011",
    name: "Lenovo ThinkPad T14",
    type: "Hardware",
    category: "Laptop",
    model: "T14 Gen 2",
    assignedTo: "IT Team",
    department: "IT",
    usage: "Infrastructure management",
    costUSD: 1300,
    purchaseDate: "2023-07-15",
    status: "Active"
  },
  {
    assetId: "A012",
    name: "Adobe Creative Cloud",
    type: "Software",
    category: "Design",
    model: "Creative Suite",
    assignedTo: "Editorial Designers",
    department: "Editorial",
    usage: "Graphic & video design",
    costUSD: 700,
    purchaseDate: "2023-02-20",
    status: "Active"
  },
  {
    assetId: "A013",
    name: "Slack Enterprise",
    type: "Software",
    category: "Collaboration",
    model: "v5",
    assignedTo: "All Staff",
    department: "Company-wide",
    usage: "Team communication",
    costUSD: 1200,
    purchaseDate: "2024-01-15",
    status: "Active"
  },
  {
    assetId: "A014",
    name: "Zoom Pro",
    type: "Software",
    category: "Communication",
    model: "v6",
    assignedTo: "Executives",
    department: "Executives",
    usage: "Video conferencing",
    costUSD: 500,
    purchaseDate: "2023-06-01",
    status: "Active"
  },
  {
    assetId: "A015",
    name: "AWS S3 Storage",
    type: "Cloud Service",
    category: "Storage",
    model: "Standard Tier",
    assignedTo: "Operations",
    department: "Operations and Production",
    usage: "File storage & backup",
    costUSD: 400,
    purchaseDate: "2023-09-12",
    status: "Active"
  },
  {
    assetId: "A016",
    name: "Google Workspace",
    type: "Software",
    category: "Productivity Suite",
    model: "Business Standard",
    assignedTo: "All Staff",
    department: "Company-wide",
    usage: "Docs, Sheets, Gmail",
    costUSD: 3000,
    purchaseDate: "2023-01-05",
    status: "Active"
  },
  {
    assetId: "A017",
    name: "Cisco Catalyst Switch",
    type: "Hardware",
    category: "Networking",
    model: "Catalyst 9300",
    assignedTo: "IT Team",
    department: "IT",
    usage: "Office networking",
    costUSD: 2000,
    purchaseDate: "2022-11-20",
    status: "Active"
  },
  {
    assetId: "A018",
    name: "HP ProDesk 600 G6",
    type: "Hardware",
    category: "Desktop",
    model: "ProDesk 600",
    assignedTo: "Finance Staff",
    department: "Finance",
    usage: "Accounting & reporting",
    costUSD: 900,
    purchaseDate: "2023-03-01",
    status: "Active"
  },
  {
    assetId: "A019",
    name: "Tableau Desktop",
    type: "Software",
    category: "Analytics",
    model: "2024.1",
    assignedTo: "Sales & Marketing Team",
    department: "Sales and Marketing",
    usage: "Sales dashboards",
    costUSD: 800,
    purchaseDate: "2023-08-15",
    status: "Active"
  },
  {
    assetId: "A020",
    name: "Fujifilm X-T4",
    type: "Hardware",
    category: "Camera",
    model: "X-T4",
    assignedTo: "Photography Team",
    department: "Editorial",
    usage: "News & feature photography",
    costUSD: 1800,
    purchaseDate: "2023-05-22",
    status: "Active"
  },
  {
    assetId: "A021",
    name: "VMware vSphere",
    type: "Software",
    category: "Virtualization",
    model: "v7.0",
    assignedTo: "IT Team",
    department: "IT",
    usage: "Server virtualization",
    costUSD: 2500,
    purchaseDate: "2023-09-05",
    status: "Active"
  },
  {
    assetId: "A022",
    name: "iPad Pro 12.9”",
    type: "Hardware",
    category: "Tablet",
    model: "iPad Pro 2021",
    assignedTo: "Executives",
    department: "Executives",
    usage: "Presentations & notes",
    costUSD: 1100,
    purchaseDate: "2023-04-18",
    status: "Active"
  },
  {
    assetId: "A023",
    name: "Brother HL-L2350DW",
    type: "Hardware",
    category: "Printer",
    model: "HL-L2350DW",
    assignedTo: "Admin Team",
    department: "Admin and Support",
    usage: "Office printing",
    costUSD: 200,
    purchaseDate: "2022-08-30",
    status: "Active"
  },
  {
    assetId: "A024",
    name: "AWS RDS - CMS DB",
    type: "Cloud Service",
    category: "Database",
    model: "db.t3.medium",
    assignedTo: "Editorial Team",
    department: "IT",
    usage: "CMS database",
    costUSD: 300,
    purchaseDate: "2024-01-10",
    status: "Active"
  },
  {
    assetId: "A025",
    name: "Slack Channel Archive",
    type: "Software",
    category: "Collaboration",
    model: "v2",
    assignedTo: "All Staff",
    department: "Company-wide",
    usage: "Team communication backup",
    costUSD: 200,
    purchaseDate: "2023-01-20",
    status: "Active"
  },
  {
    assetId: "A026",
    name: "Canon PIXMA MG3620",
    type: "Hardware",
    category: "Printer",
    model: "PIXMA MG3620",
    assignedTo: "Marketing Staff",
    department: "Sales and Marketing",
    usage: "Campaign printing",
    costUSD: 150,
    purchaseDate: "2023-06-01",
    status: "Active"
  },
  {
    assetId: "A027",
    name: "Zoom Webinar",
    type: "Software",
    category: "Communication",
    model: "v6",
    assignedTo: "Marketing Team",
    department: "Sales and Marketing",
    usage: "Customer webinars",
    costUSD: 400,
    purchaseDate: "2023-07-15",
    status: "Active"
  },
  {
    assetId: "A028",
    name: "Mac Mini M1",
    type: "Hardware",
    category: "Desktop",
    model: "Mac Mini 2021",
    assignedTo: "IT Staff",
    department: "IT",
    usage: "Server testing",
    costUSD: 700,
    purchaseDate: "2023-03-10",
    status: "Active"
  },
  {
    assetId: "A029",
    name: "Google Cloud Storage",
    type: "Cloud Service",
    category: "Storage",
    model: "Standard",
    assignedTo: "Operations",
    department: "Operations and Production",
    usage: "File backups",
    costUSD: 350,
    purchaseDate: "2023-05-20",
    status: "Active"
  },
  {
    assetId: "A030",
    name: "HP EliteDisplay E243",
    type: "Hardware",
    category: "Monitor",
    model: "E243",
    assignedTo: "Finance Staff",
    department: "Finance",
    usage: "Accounting & reporting",
    costUSD: 250,
    purchaseDate: "2023-02-05",
    status: "Active"
  }
];

export default dummyAssets;
