export const audits = [
  {
    auditId: "A001",
    auditName: "Quarterly Financial Audit Q1 2025",
    department: "Finance",
    startDate: "2025-01-05",
    endDate: "2025-01-20",
    actualEndDate: "2025-01-18",
    auditor: "Grace Namaganda",
    status: "Completed",
    findingsCount: 5,
    repeatFindingsCount: 1,
    riskLevel: "Medium",
    category: "Financial"
  },
  {
    auditId: "A002",
    auditName: "IT Security Audit 2025",
    department: "IT",
    startDate: "2025-02-01",
    endDate: "2025-02-15",
    actualEndDate: "2025-02-16",
    auditor: "Alice Mwangi",
    status: "Completed",
    findingsCount: 8,
    repeatFindingsCount: 2,
    riskLevel: "High",
    category: "IT"
  },
  {
    auditId: "A003",
    auditName: "Operational Process Audit",
    department: "Operations",
    startDate: "2025-03-01",
    endDate: "2025-03-20",
    actualEndDate: null,
    auditor: "Paul Nsubuga",
    status: "In Progress",
    findingsCount: 0,
    repeatFindingsCount: 0,
    riskLevel: "Low",
    category: "Operational"
  },
  {
    auditId: "A004",
    auditName: "HR Compliance Audit",
    department: "HR",
    startDate: "2024-11-10",
    endDate: "2024-11-25",
    actualEndDate: "2024-11-24",
    auditor: "John Okello",
    status: "Completed",
    findingsCount: 3,
    repeatFindingsCount: 0,
    riskLevel: "Low",
    category: "HR"
  },
  {
    auditId: "A005",
    auditName: "Editorial Content Audit",
    department: "Editorial",
    startDate: "2025-01-15",
    endDate: "2025-01-30",
    actualEndDate: null,
    auditor: "Charles Etukuri",
    status: "Planned",
    findingsCount: 0,
    repeatFindingsCount: 0,
    riskLevel: "Medium",
    category: "Regulatory"
  },
  {
    auditId: "A006",
    auditName: "Quarterly Financial Audit Q4 2024",
    department: "Finance",
    startDate: "2024-10-01",
    endDate: "2024-10-15",
    actualEndDate: "2024-10-14",
    auditor: "Grace Namaganda",
    status: "Completed",
    findingsCount: 6,
    repeatFindingsCount: 2,
    riskLevel: "Medium",
    category: "Financial"
  },
  {
    auditId: "A007",
    auditName: "Procurement Audit",
    department: "Procurement",
    startDate: "2024-08-05",
    endDate: "2024-08-20",
    actualEndDate: "2024-08-19",
    auditor: "David Ouma",
    status: "Completed",
    findingsCount: 4,
    repeatFindingsCount: 1,
    riskLevel: "Low",
    category: "Operational"
  },
  {
    auditId: "A008",
    auditName: "IT Disaster Recovery Audit",
    department: "IT",
    startDate: "2024-06-10",
    endDate: "2024-06-25",
    actualEndDate: "2024-06-26",
    auditor: "Sandra Mbabazi",
    status: "Completed",
    findingsCount: 7,
    repeatFindingsCount: 3,
    riskLevel: "High",
    category: "IT"
  },
  {
    auditId: "A009",
    auditName: "Legal Compliance Audit",
    department: "Legal",
    startDate: "2025-03-10",
    endDate: "2025-03-25",
    actualEndDate: null,
    auditor: "Janet Kintu",
    status: "Planned",
    findingsCount: 0,
    repeatFindingsCount: 0,
    riskLevel: "Medium",
    category: "Legal"
  },
  {
    auditId: "A010",
    auditName: "Operations Safety Audit",
    department: "Operations",
    startDate: "2024-09-01",
    endDate: "2024-09-15",
    actualEndDate: "2024-09-14",
    auditor: "Paul Nsubuga",
    status: "Completed",
    findingsCount: 5,
    repeatFindingsCount: 1,
    riskLevel: "Medium",
    category: "Operational"
  },
  {
    auditId: "A011",
    auditName: "Quarterly Financial Audit Q2 2025",
    department: "Finance",
    startDate: "2025-04-01",
    endDate: "2025-04-15",
    actualEndDate: null,
    auditor: "Grace Namaganda",
    status: "Planned",
    findingsCount: 0,
    repeatFindingsCount: 0,
    riskLevel: "Medium",
    category: "Financial"
  },
  {
    auditId: "A012",
    auditName: "HR Recruitment Process Audit",
    department: "HR",
    startDate: "2025-02-10",
    endDate: "2025-02-25",
    actualEndDate: null,
    auditor: "James Kato",
    status: "In Progress",
    findingsCount: 0,
    repeatFindingsCount: 0,
    riskLevel: "Low",
    category: "HR"
  },
  {
    auditId: "A013",
    auditName: "Editorial Licensing Audit",
    department: "Editorial",
    startDate: "2024-12-05",
    endDate: "2024-12-20",
    actualEndDate: "2024-12-19",
    auditor: "Charles Etukuri",
    status: "Completed",
    findingsCount: 2,
    repeatFindingsCount: 0,
    riskLevel: "Low",
    category: "Regulatory"
  },
  {
    auditId: "A014",
    auditName: "IT Security Patch Audit",
    department: "IT",
    startDate: "2025-03-01",
    endDate: "2025-03-15",
    actualEndDate: null,
    auditor: "Alice Mwangi",
    status: "Planned",
    findingsCount: 0,
    repeatFindingsCount: 0,
    riskLevel: "High",
    category: "IT"
  },
  {
    auditId: "A015",
    auditName: "Finance Payroll Audit",
    department: "Finance",
    startDate: "2024-07-10",
    endDate: "2024-07-25",
    actualEndDate: "2024-07-24",
    auditor: "Naomi Kyaligonza",
    status: "Completed",
    findingsCount: 3,
    repeatFindingsCount: 0,
    riskLevel: "Low",
    category: "Financial"
  },
  {
    auditId: "A016",
    auditName: "Operations Equipment Audit",
    department: "Operations",
    startDate: "2025-01-20",
    endDate: "2025-02-05",
    actualEndDate: null,
    auditor: "Robert Ochieng",
    status: "Planned",
    findingsCount: 0,
    repeatFindingsCount: 0,
    riskLevel: "Medium",
    category: "Operational"
  },
  {
    auditId: "A017",
    auditName: "Legal Contract Audit",
    department: "Legal",
    startDate: "2024-08-15",
    endDate: "2024-08-30",
    actualEndDate: "2024-08-29",
    auditor: "Samuel Owor",
    status: "Completed",
    findingsCount: 6,
    repeatFindingsCount: 1,
    riskLevel: "Medium",
    category: "Legal"
  },
  {
    auditId: "A018",
    auditName: "HR Policy Audit",
    department: "HR",
    startDate: "2025-03-01",
    endDate: "2025-03-15",
    actualEndDate: null,
    auditor: "Lydia Nabukenya",
    status: "Planned",
    findingsCount: 0,
    repeatFindingsCount: 0,
    riskLevel: "Low",
    category: "HR"
  },
  {
    auditId: "A019",
    auditName: "IT Backup Audit",
    department: "IT",
    startDate: "2024-09-01",
    endDate: "2024-09-15",
    actualEndDate: "2024-09-14",
    auditor: "Angela Mirembe",
    status: "Completed",
    findingsCount: 4,
    repeatFindingsCount: 0,
    riskLevel: "Medium",
    category: "IT"
  },
  {
    auditId: "A020",
    auditName: "Procurement Compliance Audit",
    department: "Procurement",
    startDate: "2025-02-05",
    endDate: "2025-02-20",
    actualEndDate: null,
    auditor: "Esther Kyomuhangi",
    status: "In Progress",
    findingsCount: 0,
    repeatFindingsCount: 0,
    riskLevel: "Medium",
    category: "Operational"
  },
  {
    auditId: "A021",
    auditName: "Editorial Content Accuracy Audit",
    department: "Editorial",
    startDate: "2025-01-15",
    endDate: "2025-01-30",
    actualEndDate: null,
    auditor: "Charles Etukuri",
    status: "Planned",
    findingsCount: 0,
    repeatFindingsCount: 0,
    riskLevel: "Medium",
    category: "Regulatory"
  },
  {
    auditId: "A022",
    auditName: "Finance Expense Audit",
    department: "Finance",
    startDate: "2024-06-05",
    endDate: "2024-06-20",
    actualEndDate: "2024-06-19",
    auditor: "Grace Namaganda",
    status: "Completed",
    findingsCount: 5,
    repeatFindingsCount: 1,
    riskLevel: "Medium",
    category: "Financial"
  },
  {
    auditId: "A023",
    auditName: "IT Security Awareness Audit",
    department: "IT",
    startDate: "2025-03-10",
    endDate: "2025-03-25",
    actualEndDate: null,
    auditor: "Alice Mwangi",
    status: "Planned",
    findingsCount: 0,
    repeatFindingsCount: 0,
    riskLevel: "High",
    category: "IT"
  },
  {
    auditId: "A024",
    auditName: "HR Attendance Audit",
    department: "HR",
    startDate: "2024-12-01",
    endDate: "2024-12-15",
    actualEndDate: "2024-12-14",
    auditor: "James Kato",
    status: "Completed",
    findingsCount: 2,
    repeatFindingsCount: 0,
    riskLevel: "Low",
    category: "HR"
  },
  {
    auditId: "A025",
    auditName: "Operations Logistics Audit",
    department: "Operations",
    startDate: "2025-02-01",
    endDate: "2025-02-15",
    actualEndDate: null,
    auditor: "Paul Nsubuga",
    status: "In Progress",
    findingsCount: 0,
    repeatFindingsCount: 0,
    riskLevel: "Medium",
    category: "Operational"
  },
  {
    auditId: "A026",
    auditName: "Finance Tax Compliance Audit",
    department: "Finance",
    startDate: "2024-11-05",
    endDate: "2024-11-20",
    actualEndDate: "2024-11-19",
    auditor: "Naomi Kyaligonza",
    status: "Completed",
    findingsCount: 4,
    repeatFindingsCount: 0,
    riskLevel: "Low",
    category: "Financial"
  },
  {
    auditId: "A027",
    auditName: "Legal Licensing Audit",
    department: "Legal",
    startDate: "2025-01-10",
    endDate: "2025-01-25",
    actualEndDate: null,
    auditor: "Peter Mugisha",
    status: "Planned",
    findingsCount: 0,
    repeatFindingsCount: 0,
    riskLevel: "Medium",
    category: "Legal"
  },
  {
    auditId: "A028",
    auditName: "Editorial Copyright Audit",
    department: "Editorial",
    startDate: "2024-10-01",
    endDate: "2024-10-15",
    actualEndDate: "2024-10-14",
    auditor: "Charles Etukuri",
    status: "Completed",
    findingsCount: 3,
    repeatFindingsCount: 0,
    riskLevel: "Low",
    category: "Regulatory"
  },
  {
    auditId: "A029",
    auditName: "IT Server Maintenance Audit",
    department: "IT",
    startDate: "2025-02-15",
    endDate: "2025-03-01",
    actualEndDate: null,
    auditor: "Sandra Mbabazi",
    status: "In Progress",
    findingsCount: 0,
    repeatFindingsCount: 0,
    riskLevel: "Medium",
    category: "IT"
  },
  {
    auditId: "A030",
    auditName: "Operations Compliance Audit",
    department: "Operations",
    startDate: "2024-07-10",
    endDate: "2024-07-25",
    actualEndDate: "2024-07-24",
    auditor: "Robert Ochieng",
    status: "Completed",
    findingsCount: 4,
    repeatFindingsCount: 1,
    riskLevel: "Medium",
    category: "Operational"
  }
];
