const machines = [
  {
    date: "2025-05-29",
    machine: "generator",
    operator: "sarah",
    distance_km: 65.0,
    fuel_consumed_l: 37.6,
    fuel_cost_usd: 45.81,
    avg_speed_kmh: 62.1,
    location: "kampala, ug",
  },
  {
    date: "2025-08-07",
    machine: "satellite_uplink_van",
    operator: "mike",
    distance_km: 221.8,
    fuel_consumed_l: 36.0,
    fuel_cost_usd: 57.57,
    avg_speed_kmh: 57.7,
    location: "mbarara, ug",
  },
  {
    date: "2025-01-09",
    machine: "news_van",
    operator: "sarah",
    distance_km: 201.3,
    fuel_consumed_l: 8.7,
    fuel_cost_usd: 104.13,
    avg_speed_kmh: 47.2,
    location: "jinja, ug",
  },
  {
    date: "2025-05-04",
    machine: "generator",
    operator: "sarah",
    distance_km: 229.7,
    fuel_consumed_l: 28.2,
    fuel_cost_usd: 93.78,
    avg_speed_kmh: 47.0,
    location: "gulu, ug",
  },
  {
    date: "2025-05-02",
    machine: "generator",
    operator: "sarah",
    distance_km: 21.5,
    fuel_consumed_l: 24.4,
    fuel_cost_usd: 93.75,
    avg_speed_kmh: 68.7,
    location: "mbarara, ug",
  },
  {
    date: "2025-07-24",
    machine: "production_car",
    operator: "sarah",
    distance_km: 49.0,
    fuel_consumed_l: 13.2,
    fuel_cost_usd: 64.51,
    avg_speed_kmh: 65.3,
    location: "gulu, ug",
  },
  {
    date: "2025-06-19",
    machine: "satellite_uplink_van",
    operator: "alice",
    distance_km: 91.2,
    fuel_consumed_l: 28.8,
    fuel_cost_usd: 35.64,
    avg_speed_kmh: 23.1,
    location: "gulu, ug",
  },
  {
    date: "2025-04-03",
    machine: "news_van",
    operator: "david",
    distance_km: 217.1,
    fuel_consumed_l: 15.7,
    fuel_cost_usd: 81.32,
    avg_speed_kmh: 73.2,
    location: "kampala, ug",
  },
  {
    date: "2025-05-12",
    machine: "generator",
    operator: "david",
    distance_km: 180.4,
    fuel_consumed_l: 20.4,
    fuel_cost_usd: 65.93,
    avg_speed_kmh: 75.1,
    location: "entebbe, ug",
  },
  {
    date: "2025-03-11",
    machine: "generator",
    operator: "alice",
    distance_km: 176.7,
    fuel_consumed_l: 17.6,
    fuel_cost_usd: 80.99,
    avg_speed_kmh: 39.9,
    location: "mbarara, ug",
  },
  {
    date: "2025-02-01",
    machine: "generator",
    operator: "alice",
    distance_km: 36.3,
    fuel_consumed_l: 26.8,
    fuel_cost_usd: 36.03,
    avg_speed_kmh: 80.1,
    location: "jinja, ug",
  },
  {
    date: "2025-07-19",
    machine: "news_van",
    operator: "john",
    distance_km: 179.9,
    fuel_consumed_l: 22.3,
    fuel_cost_usd: 48.04,
    avg_speed_kmh: 85.5,
    location: "entebbe, ug",
  },
  {
    date: "2025-08-06",
    machine: "generator",
    operator: "mike",
    distance_km: 161.5,
    fuel_consumed_l: 9.9,
    fuel_cost_usd: 109.94,
    avg_speed_kmh: 38.2,
    location: "kampala, ug",
  },
  {
    date: "2025-06-25",
    machine: "news_van",
    operator: "john",
    distance_km: 79.8,
    fuel_consumed_l: 25.8,
    fuel_cost_usd: 28.66,
    avg_speed_kmh: 63.8,
    location: "mbarara, ug",
  },
  {
    date: "2025-04-19",
    machine: "generator",
    operator: "sarah",
    distance_km: 171.8,
    fuel_consumed_l: 17.2,
    fuel_cost_usd: 10.95,
    avg_speed_kmh: 39.1,
    location: "entebbe, ug",
  },
  {
    date: "2025-02-10",
    machine: "news_van",
    operator: "john",
    distance_km: 143.2,
    fuel_consumed_l: 37.6,
    fuel_cost_usd: 62.31,
    avg_speed_kmh: 82.2,
    location: "mbarara, ug",
  },
  {
    date: "2025-03-23",
    machine: "news_van",
    operator: "sarah",
    distance_km: 216.4,
    fuel_consumed_l: 32.0,
    fuel_cost_usd: 55.64,
    avg_speed_kmh: 56.2,
    location: "entebbe, ug",
  },
  {
    date: "2025-04-04",
    machine: "production_car",
    operator: "david",
    distance_km: 65.6,
    fuel_consumed_l: 28.1,
    fuel_cost_usd: 34.19,
    avg_speed_kmh: 37.6,
    location: "kampala, ug",
  },
  {
    date: "2025-03-15",
    machine: "satellite_uplink_van",
    operator: "alice",
    distance_km: 170.2,
    fuel_consumed_l: 14.1,
    fuel_cost_usd: 63.57,
    avg_speed_kmh: 40.6,
    location: "gulu, ug",
  },
  {
    date: "2025-05-20",
    machine: "production_car",
    operator: "sarah",
    distance_km: 181.1,
    fuel_consumed_l: 25.6,
    fuel_cost_usd: 85.82,
    avg_speed_kmh: 74.5,
    location: "mbarara, ug",
  },
  {
    date: "2025-02-24",
    machine: "production_car",
    operator: "david",
    distance_km: 40.0,
    fuel_consumed_l: 15.1,
    fuel_cost_usd: 61.78,
    avg_speed_kmh: 53.7,
    location: "jinja, ug",
  },
  {
    date: "2025-03-09",
    machine: "camera_truck",
    operator: "david",
    distance_km: 51.7,
    fuel_consumed_l: 16.4,
    fuel_cost_usd: 86.34,
    avg_speed_kmh: 72.0,
    location: "gulu, ug",
  },
  {
    date: "2025-05-16",
    machine: "camera_truck",
    operator: "david",
    distance_km: 83.4,
    fuel_consumed_l: 7.9,
    fuel_cost_usd: 17.98,
    avg_speed_kmh: 24.7,
    location: "jinja, ug",
  },
  {
    date: "2025-03-29",
    machine: "camera_truck",
    operator: "david",
    distance_km: 160.0,
    fuel_consumed_l: 33.3,
    fuel_cost_usd: 103.45,
    avg_speed_kmh: 41.3,
    location: "gulu, ug",
  },
  {
    date: "2025-06-07",
    machine: "camera_truck",
    operator: "david",
    distance_km: 61.6,
    fuel_consumed_l: 21.9,
    fuel_cost_usd: 55.36,
    avg_speed_kmh: 22.7,
    location: "jinja, ug",
  },
  {
    date: "2025-07-24",
    machine: "news_van",
    operator: "david",
    distance_km: 66.7,
    fuel_consumed_l: 14.5,
    fuel_cost_usd: 26.26,
    avg_speed_kmh: 30.1,
    location: "gulu, ug",
  },
  {
    date: "2025-06-03",
    machine: "news_van",
    operator: "david",
    distance_km: 224.3,
    fuel_consumed_l: 8.6,
    fuel_cost_usd: 56.84,
    avg_speed_kmh: 67.5,
    location: "entebbe, ug",
  },
  {
    date: "2025-01-21",
    machine: "camera_truck",
    operator: "sarah",
    distance_km: 47.8,
    fuel_consumed_l: 28.7,
    fuel_cost_usd: 27.33,
    avg_speed_kmh: 73.0,
    location: "gulu, ug",
  },
  {
    date: "2025-04-03",
    machine: "generator",
    operator: "john",
    distance_km: 138.2,
    fuel_consumed_l: 25.6,
    fuel_cost_usd: 73.53,
    avg_speed_kmh: 40.7,
    location: "gulu, ug",
  },
  {
    date: "2025-05-25",
    machine: "news_van",
    operator: "john",
    distance_km: 183.7,
    fuel_consumed_l: 14.7,
    fuel_cost_usd: 12.08,
    avg_speed_kmh: 76.8,
    location: "kampala, ug",
  },
  {
    date: "2025-03-12",
    machine: "production_car",
    operator: "john",
    distance_km: 72.3,
    fuel_consumed_l: 7.0,
    fuel_cost_usd: 105.07,
    avg_speed_kmh: 23.0,
    location: "gulu, ug",
  },
  {
    date: "2025-01-26",
    machine: "news_van",
    operator: "sarah",
    distance_km: 152.5,
    fuel_consumed_l: 28.0,
    fuel_cost_usd: 42.49,
    avg_speed_kmh: 59.9,
    location: "gulu, ug",
  },
  {
    date: "2025-02-03",
    machine: "satellite_uplink_van",
    operator: "sarah",
    distance_km: 80.6,
    fuel_consumed_l: 13.4,
    fuel_cost_usd: 93.78,
    avg_speed_kmh: 69.9,
    location: "jinja, ug",
  },
  {
    date: "2025-08-23",
    machine: "news_van",
    operator: "john",
    distance_km: 78.6,
    fuel_consumed_l: 24.9,
    fuel_cost_usd: 100.83,
    avg_speed_kmh: 52.8,
    location: "kampala, ug",
  },
  {
    date: "2025-06-15",
    machine: "generator",
    operator: "alice",
    distance_km: 112.8,
    fuel_consumed_l: 11.1,
    fuel_cost_usd: 87.99,
    avg_speed_kmh: 56.7,
    location: "gulu, ug",
  },
  {
    date: "2025-06-06",
    machine: "production_car",
    operator: "sarah",
    distance_km: 171.8,
    fuel_consumed_l: 28.8,
    fuel_cost_usd: 22.47,
    avg_speed_kmh: 20.3,
    location: "mbarara, ug",
  },
  {
    date: "2025-03-22",
    machine: "satellite_uplink_van",
    operator: "david",
    distance_km: 70.4,
    fuel_consumed_l: 37.2,
    fuel_cost_usd: 50.61,
    avg_speed_kmh: 35.8,
    location: "entebbe, ug",
  },
  {
    date: "2025-07-08",
    machine: "camera_truck",
    operator: "david",
    distance_km: 54.0,
    fuel_consumed_l: 16.0,
    fuel_cost_usd: 60.16,
    avg_speed_kmh: 21.0,
    location: "gulu, ug",
  },
  {
    date: "2025-07-10",
    machine: "generator",
    operator: "sarah",
    distance_km: 34.7,
    fuel_consumed_l: 36.6,
    fuel_cost_usd: 17.06,
    avg_speed_kmh: 83.1,
    location: "kampala, ug",
  },
  {
    date: "2025-02-06",
    machine: "news_van",
    operator: "sarah",
    distance_km: 198.8,
    fuel_consumed_l: 9.1,
    fuel_cost_usd: 70.06,
    avg_speed_kmh: 89.0,
    location: "jinja, ug",
  },
  {
    date: "2025-07-26",
    machine: "satellite_uplink_van",
    operator: "mike",
    distance_km: 161.1,
    fuel_consumed_l: 5.2,
    fuel_cost_usd: 36.29,
    avg_speed_kmh: 76.7,
    location: "kampala, ug",
  },
  {
    date: "2025-08-03",
    machine: "production_car",
    operator: "alice",
    distance_km: 209.7,
    fuel_consumed_l: 32.9,
    fuel_cost_usd: 40.57,
    avg_speed_kmh: 54.5,
    location: "mbarara, ug",
  },
  {
    date: "2025-08-02",
    machine: "news_van",
    operator: "mike",
    distance_km: 102.4,
    fuel_consumed_l: 10.6,
    fuel_cost_usd: 35.07,
    avg_speed_kmh: 32.8,
    location: "entebbe, ug",
  },
  {
    date: "2025-03-04",
    machine: "production_car",
    operator: "mike",
    distance_km: 231.0,
    fuel_consumed_l: 25.0,
    fuel_cost_usd: 24.91,
    avg_speed_kmh: 51.3,
    location: "entebbe, ug",
  },
  {
    date: "2025-06-22",
    machine: "camera_truck",
    operator: "john",
    distance_km: 226.8,
    fuel_consumed_l: 14.3,
    fuel_cost_usd: 76.63,
    avg_speed_kmh: 43.9,
    location: "jinja, ug",
  },
  {
    date: "2025-05-16",
    machine: "satellite_uplink_van",
    operator: "john",
    distance_km: 205.9,
    fuel_consumed_l: 16.2,
    fuel_cost_usd: 59.06,
    avg_speed_kmh: 60.1,
    location: "gulu, ug",
  },
  {
    date: "2025-04-04",
    machine: "generator",
    operator: "sarah",
    distance_km: 141.8,
    fuel_consumed_l: 13.7,
    fuel_cost_usd: 13.83,
    avg_speed_kmh: 79.6,
    location: "mbarara, ug",
  },
  {
    date: "2025-07-07",
    machine: "production_car",
    operator: "alice",
    distance_km: 80.9,
    fuel_consumed_l: 34.4,
    fuel_cost_usd: 88.1,
    avg_speed_kmh: 29.4,
    location: "jinja, ug",
  },
  {
    date: "2025-03-25",
    machine: "camera_truck",
    operator: "alice",
    distance_km: 64.3,
    fuel_consumed_l: 13.7,
    fuel_cost_usd: 36.0,
    avg_speed_kmh: 26.4,
    location: "entebbe, ug",
  },
  {
    date: "2025-03-20",
    machine: "satellite_uplink_van",
    operator: "alice",
    distance_km: 27.7,
    fuel_consumed_l: 14.2,
    fuel_cost_usd: 116.66,
    avg_speed_kmh: 48.8,
    location: "entebbe, ug",
  },
  {
    date: "2025-02-12",
    machine: "production_car",
    operator: "john",
    distance_km: 23.5,
    fuel_consumed_l: 15.2,
    fuel_cost_usd: 62.14,
    avg_speed_kmh: 29.8,
    location: "jinja, ug",
  },
  {
    date: "2025-06-08",
    machine: "generator",
    operator: "sarah",
    distance_km: 105.1,
    fuel_consumed_l: 32.5,
    fuel_cost_usd: 77.37,
    avg_speed_kmh: 21.0,
    location: "mbarara, ug",
  },
  {
    date: "2025-08-24",
    machine: "news_van",
    operator: "mike",
    distance_km: 61.1,
    fuel_consumed_l: 39.7,
    fuel_cost_usd: 18.22,
    avg_speed_kmh: 48.1,
    location: "kampala, ug",
  },
  {
    date: "2025-02-05",
    machine: "production_car",
    operator: "david",
    distance_km: 202.7,
    fuel_consumed_l: 27.9,
    fuel_cost_usd: 61.4,
    avg_speed_kmh: 78.7,
    location: "kampala, ug",
  },
  {
    date: "2025-08-11",
    machine: "camera_truck",
    operator: "david",
    distance_km: 31.2,
    fuel_consumed_l: 31.7,
    fuel_cost_usd: 33.58,
    avg_speed_kmh: 76.8,
    location: "mbarara, ug",
  },
  {
    date: "2025-06-04",
    machine: "production_car",
    operator: "john",
    distance_km: 35.7,
    fuel_consumed_l: 32.2,
    fuel_cost_usd: 116.97,
    avg_speed_kmh: 52.6,
    location: "mbarara, ug",
  },
  {
    date: "2025-03-13",
    machine: "news_van",
    operator: "david",
    distance_km: 54.4,
    fuel_consumed_l: 37.6,
    fuel_cost_usd: 20.99,
    avg_speed_kmh: 22.9,
    location: "kampala, ug",
  },
  {
    date: "2025-02-13",
    machine: "production_car",
    operator: "sarah",
    distance_km: 216.4,
    fuel_consumed_l: 9.6,
    fuel_cost_usd: 75.78,
    avg_speed_kmh: 27.1,
    location: "gulu, ug",
  },
  {
    date: "2025-02-06",
    machine: "camera_truck",
    operator: "david",
    distance_km: 233.6,
    fuel_consumed_l: 33.9,
    fuel_cost_usd: 70.23,
    avg_speed_kmh: 49.9,
    location: "kampala, ug",
  },
  {
    date: "2025-07-31",
    machine: "satellite_uplink_van",
    operator: "alice",
    distance_km: 177.0,
    fuel_consumed_l: 18.1,
    fuel_cost_usd: 89.2,
    avg_speed_kmh: 44.0,
    location: "kampala, ug",
  },
  {
    date: "2025-05-06",
    machine: "satellite_uplink_van",
    operator: "john",
    distance_km: 103.0,
    fuel_consumed_l: 9.2,
    fuel_cost_usd: 88.54,
    avg_speed_kmh: 34.2,
    location: "gulu, ug",
  },
  {
    date: "2025-03-06",
    machine: "news_van",
    operator: "john",
    distance_km: 123.7,
    fuel_consumed_l: 7.2,
    fuel_cost_usd: 106.36,
    avg_speed_kmh: 79.9,
    location: "jinja, ug",
  },
  {
    date: "2025-06-29",
    machine: "satellite_uplink_van",
    operator: "john",
    distance_km: 190.4,
    fuel_consumed_l: 24.1,
    fuel_cost_usd: 82.89,
    avg_speed_kmh: 30.2,
    location: "mbarara, ug",
  },
  {
    date: "2025-08-22",
    machine: "production_car",
    operator: "john",
    distance_km: 85.9,
    fuel_consumed_l: 31.0,
    fuel_cost_usd: 115.81,
    avg_speed_kmh: 65.4,
    location: "gulu, ug",
  },
  {
    date: "2025-01-24",
    machine: "generator",
    operator: "john",
    distance_km: 203.0,
    fuel_consumed_l: 36.2,
    fuel_cost_usd: 86.1,
    avg_speed_kmh: 78.6,
    location: "entebbe, ug",
  },
  {
    date: "2025-03-19",
    machine: "news_van",
    operator: "mike",
    distance_km: 91.8,
    fuel_consumed_l: 24.0,
    fuel_cost_usd: 52.8,
    avg_speed_kmh: 50.3,
    location: "jinja, ug",
  },
  {
    date: "2025-08-19",
    machine: "generator",
    operator: "sarah",
    distance_km: 30.9,
    fuel_consumed_l: 22.1,
    fuel_cost_usd: 66.19,
    avg_speed_kmh: 58.3,
    location: "gulu, ug",
  },
  {
    date: "2025-05-06",
    machine: "generator",
    operator: "sarah",
    distance_km: 38.2,
    fuel_consumed_l: 7.8,
    fuel_cost_usd: 24.88,
    avg_speed_kmh: 21.0,
    location: "entebbe, ug",
  },
  {
    date: "2025-08-18",
    machine: "news_van",
    operator: "mike",
    distance_km: 89.5,
    fuel_consumed_l: 12.0,
    fuel_cost_usd: 118.8,
    avg_speed_kmh: 36.2,
    location: "mbarara, ug",
  },
  {
    date: "2025-02-15",
    machine: "satellite_uplink_van",
    operator: "john",
    distance_km: 124.4,
    fuel_consumed_l: 30.2,
    fuel_cost_usd: 98.06,
    avg_speed_kmh: 76.3,
    location: "entebbe, ug",
  },
  {
    date: "2025-08-14",
    machine: "news_van",
    operator: "mike",
    distance_km: 143.4,
    fuel_consumed_l: 17.8,
    fuel_cost_usd: 90.11,
    avg_speed_kmh: 36.1,
    location: "jinja, ug",
  },
  {
    date: "2025-02-12",
    machine: "satellite_uplink_van",
    operator: "sarah",
    distance_km: 68.4,
    fuel_consumed_l: 31.4,
    fuel_cost_usd: 59.26,
    avg_speed_kmh: 61.6,
    location: "entebbe, ug",
  },
  {
    date: "2025-01-10",
    machine: "satellite_uplink_van",
    operator: "sarah",
    distance_km: 71.1,
    fuel_consumed_l: 31.7,
    fuel_cost_usd: 55.4,
    avg_speed_kmh: 71.9,
    location: "mbarara, ug",
  },
  {
    date: "2025-07-23",
    machine: "generator",
    operator: "alice",
    distance_km: 209.5,
    fuel_consumed_l: 28.5,
    fuel_cost_usd: 116.16,
    avg_speed_kmh: 60.1,
    location: "kampala, ug",
  },
  {
    date: "2025-01-08",
    machine: "camera_truck",
    operator: "sarah",
    distance_km: 90.3,
    fuel_consumed_l: 28.6,
    fuel_cost_usd: 114.88,
    avg_speed_kmh: 76.8,
    location: "entebbe, ug",
  },
  {
    date: "2025-07-19",
    machine: "generator",
    operator: "john",
    distance_km: 69.0,
    fuel_consumed_l: 22.4,
    fuel_cost_usd: 87.43,
    avg_speed_kmh: 39.9,
    location: "jinja, ug",
  },
  {
    date: "2025-04-17",
    machine: "generator",
    operator: "david",
    distance_km: 233.5,
    fuel_consumed_l: 29.3,
    fuel_cost_usd: 82.15,
    avg_speed_kmh: 68.5,
    location: "gulu, ug",
  },
  {
    date: "2025-03-19",
    machine: "news_van",
    operator: "alice",
    distance_km: 204.8,
    fuel_consumed_l: 6.3,
    fuel_cost_usd: 53.42,
    avg_speed_kmh: 36.0,
    location: "jinja, ug",
  },
  {
    date: "2025-05-08",
    machine: "camera_truck",
    operator: "john",
    distance_km: 62.6,
    fuel_consumed_l: 10.0,
    fuel_cost_usd: 119.76,
    avg_speed_kmh: 38.6,
    location: "gulu, ug",
  },
  {
    date: "2025-08-30",
    machine: "camera_truck",
    operator: "john",
    distance_km: 228.0,
    fuel_consumed_l: 22.2,
    fuel_cost_usd: 108.35,
    avg_speed_kmh: 67.3,
    location: "kampala, ug",
  },
  {
    date: "2025-05-22",
    machine: "generator",
    operator: "sarah",
    distance_km: 27.5,
    fuel_consumed_l: 11.6,
    fuel_cost_usd: 33.53,
    avg_speed_kmh: 68.4,
    location: "kampala, ug",
  },
  {
    date: "2025-06-14",
    machine: "camera_truck",
    operator: "alice",
    distance_km: 171.9,
    fuel_consumed_l: 28.4,
    fuel_cost_usd: 117.47,
    avg_speed_kmh: 41.1,
    location: "kampala, ug",
  },
  {
    date: "2025-04-26",
    machine: "camera_truck",
    operator: "alice",
    distance_km: 231.8,
    fuel_consumed_l: 7.9,
    fuel_cost_usd: 79.46,
    avg_speed_kmh: 80.3,
    location: "kampala, ug",
  },
  {
    date: "2025-03-10",
    machine: "satellite_uplink_van",
    operator: "john",
    distance_km: 118.8,
    fuel_consumed_l: 17.6,
    fuel_cost_usd: 34.36,
    avg_speed_kmh: 84.8,
    location: "jinja, ug",
  },
  {
    date: "2025-04-12",
    machine: "camera_truck",
    operator: "david",
    distance_km: 72.7,
    fuel_consumed_l: 36.8,
    fuel_cost_usd: 19.14,
    avg_speed_kmh: 20.9,
    location: "entebbe, ug",
  },
  {
    date: "2025-03-04",
    machine: "satellite_uplink_van",
    operator: "david",
    distance_km: 43.5,
    fuel_consumed_l: 22.6,
    fuel_cost_usd: 36.3,
    avg_speed_kmh: 54.9,
    location: "mbarara, ug",
  },
  {
    date: "2025-08-20",
    machine: "camera_truck",
    operator: "david",
    distance_km: 56.1,
    fuel_consumed_l: 25.3,
    fuel_cost_usd: 89.56,
    avg_speed_kmh: 56.3,
    location: "jinja, ug",
  },
  {
    date: "2025-01-24",
    machine: "generator",
    operator: "david",
    distance_km: 86.0,
    fuel_consumed_l: 37.4,
    fuel_cost_usd: 15.82,
    avg_speed_kmh: 48.1,
    location: "entebbe, ug",
  },
  {
    date: "2025-08-29",
    machine: "news_van",
    operator: "john",
    distance_km: 42.0,
    fuel_consumed_l: 10.3,
    fuel_cost_usd: 52.55,
    avg_speed_kmh: 81.3,
    location: "mbarara, ug",
  },
  {
    date: "2025-01-01",
    machine: "production_car",
    operator: "john",
    distance_km: 109.0,
    fuel_consumed_l: 8.5,
    fuel_cost_usd: 50.29,
    avg_speed_kmh: 75.3,
    location: "kampala, ug",
  },
  {
    date: "2025-07-21",
    machine: "camera_truck",
    operator: "david",
    distance_km: 221.2,
    fuel_consumed_l: 16.8,
    fuel_cost_usd: 30.33,
    avg_speed_kmh: 86.7,
    location: "mbarara, ug",
  },
  {
    date: "2025-07-31",
    machine: "satellite_uplink_van",
    operator: "alice",
    distance_km: 21.5,
    fuel_consumed_l: 33.0,
    fuel_cost_usd: 62.83,
    avg_speed_kmh: 33.7,
    location: "mbarara, ug",
  },
  {
    date: "2025-05-05",
    machine: "generator",
    operator: "sarah",
    distance_km: 115.2,
    fuel_consumed_l: 32.1,
    fuel_cost_usd: 104.55,
    avg_speed_kmh: 21.1,
    location: "jinja, ug",
  },
  {
    date: "2025-05-16",
    machine: "camera_truck",
    operator: "david",
    distance_km: 201.3,
    fuel_consumed_l: 17.4,
    fuel_cost_usd: 109.19,
    avg_speed_kmh: 68.0,
    location: "mbarara, ug",
  },
  {
    date: "2025-02-10",
    machine: "production_car",
    operator: "alice",
    distance_km: 48.0,
    fuel_consumed_l: 11.3,
    fuel_cost_usd: 59.25,
    avg_speed_kmh: 82.5,
    location: "entebbe, ug",
  },
  {
    date: "2025-06-04",
    machine: "production_car",
    operator: "alice",
    distance_km: 93.6,
    fuel_consumed_l: 36.9,
    fuel_cost_usd: 118.69,
    avg_speed_kmh: 58.2,
    location: "jinja, ug",
  },
  {
    date: "2025-06-18",
    machine: "news_van",
    operator: "david",
    distance_km: 81.3,
    fuel_consumed_l: 32.0,
    fuel_cost_usd: 33.04,
    avg_speed_kmh: 33.7,
    location: "jinja, ug",
  },
  {
    date: "2025-01-03",
    machine: "satellite_uplink_van",
    operator: "alice",
    distance_km: 171.4,
    fuel_consumed_l: 14.3,
    fuel_cost_usd: 33.16,
    avg_speed_kmh: 44.7,
    location: "entebbe, ug",
  },
  {
    date: "2025-05-02",
    machine: "generator",
    operator: "david",
    distance_km: 124.6,
    fuel_consumed_l: 20.2,
    fuel_cost_usd: 18.08,
    avg_speed_kmh: 54.6,
    location: "mbarara, ug",
  },
  {
    date: "2025-01-03",
    machine: "news_van",
    operator: "john",
    distance_km: 87.8,
    fuel_consumed_l: 28.2,
    fuel_cost_usd: 89.49,
    avg_speed_kmh: 58.3,
    location: "mbarara, ug",
  },
  {
    date: "2025-03-13",
    machine: "camera_truck",
    operator: "sarah",
    distance_km: 192.9,
    fuel_consumed_l: 16.7,
    fuel_cost_usd: 107.39,
    avg_speed_kmh: 79.7,
    location: "gulu, ug",
  },
  {
    date: "2025-02-07",
    machine: "news_van",
    operator: "mike",
    distance_km: 78.8,
    fuel_consumed_l: 23.4,
    fuel_cost_usd: 73.88,
    avg_speed_kmh: 42.8,
    location: "entebbe, ug",
  },
  {
    date: "2025-02-19",
    machine: "generator",
    operator: "david",
    distance_km: 64.9,
    fuel_consumed_l: 32.9,
    fuel_cost_usd: 58.77,
    avg_speed_kmh: 78.4,
    location: "mbarara, ug",
  },
  {
    date: "2025-07-13",
    machine: "camera_truck",
    operator: "alice",
    distance_km: 142.8,
    fuel_consumed_l: 15.4,
    fuel_cost_usd: 48.74,
    avg_speed_kmh: 88.1,
    location: "kampala, ug",
  },
  {
    date: "2025-01-16",
    machine: "satellite_uplink_van",
    operator: "john",
    distance_km: 90.1,
    fuel_consumed_l: 22.5,
    fuel_cost_usd: 66.92,
    avg_speed_kmh: 36.9,
    location: "kampala, ug",
  },
  {
    date: "2025-07-08",
    machine: "generator",
    operator: "alice",
    distance_km: 166.1,
    fuel_consumed_l: 23.6,
    fuel_cost_usd: 92.86,
    avg_speed_kmh: 45.3,
    location: "kampala, ug",
  },
  {
    date: "2025-05-29",
    machine: "satellite_uplink_van",
    operator: "david",
    distance_km: 41.5,
    fuel_consumed_l: 29.5,
    fuel_cost_usd: 99.83,
    avg_speed_kmh: 67.7,
    location: "jinja, ug",
  },
  {
    date: "2025-06-25",
    machine: "camera_truck",
    operator: "mike",
    distance_km: 215.5,
    fuel_consumed_l: 32.5,
    fuel_cost_usd: 82.09,
    avg_speed_kmh: 73.3,
    location: "gulu, ug",
  },
  {
    date: "2025-03-02",
    machine: "satellite_uplink_van",
    operator: "david",
    distance_km: 98.8,
    fuel_consumed_l: 15.1,
    fuel_cost_usd: 104.88,
    avg_speed_kmh: 48.6,
    location: "jinja, ug",
  },
  {
    date: "2025-02-01",
    machine: "satellite_uplink_van",
    operator: "sarah",
    distance_km: 118.5,
    fuel_consumed_l: 20.2,
    fuel_cost_usd: 103.2,
    avg_speed_kmh: 71.5,
    location: "jinja, ug",
  },
  {
    date: "2025-01-11",
    machine: "generator",
    operator: "john",
    distance_km: 89.6,
    fuel_consumed_l: 23.5,
    fuel_cost_usd: 49.6,
    avg_speed_kmh: 22.9,
    location: "kampala, ug",
  },
  {
    date: "2025-08-10",
    machine: "generator",
    operator: "alice",
    distance_km: 171.9,
    fuel_consumed_l: 36.3,
    fuel_cost_usd: 89.08,
    avg_speed_kmh: 35.8,
    location: "kampala, ug",
  },
  {
    date: "2025-06-01",
    machine: "satellite_uplink_van",
    operator: "david",
    distance_km: 239.0,
    fuel_consumed_l: 8.5,
    fuel_cost_usd: 46.51,
    avg_speed_kmh: 82.6,
    location: "kampala, ug",
  },
  {
    date: "2025-01-08",
    machine: "satellite_uplink_van",
    operator: "david",
    distance_km: 237.4,
    fuel_consumed_l: 21.1,
    fuel_cost_usd: 58.43,
    avg_speed_kmh: 29.5,
    location: "gulu, ug",
  },
  {
    date: "2025-08-28",
    machine: "generator",
    operator: "david",
    distance_km: 137.4,
    fuel_consumed_l: 28.4,
    fuel_cost_usd: 97.91,
    avg_speed_kmh: 27.7,
    location: "jinja, ug",
  },
  {
    date: "2025-06-28",
    machine: "production_car",
    operator: "mike",
    distance_km: 204.4,
    fuel_consumed_l: 10.0,
    fuel_cost_usd: 45.32,
    avg_speed_kmh: 69.3,
    location: "jinja, ug",
  },
  {
    date: "2025-01-02",
    machine: "camera_truck",
    operator: "alice",
    distance_km: 232.1,
    fuel_consumed_l: 30.0,
    fuel_cost_usd: 46.49,
    avg_speed_kmh: 82.1,
    location: "gulu, ug",
  },
  {
    date: "2025-07-04",
    machine: "production_car",
    operator: "alice",
    distance_km: 151.6,
    fuel_consumed_l: 19.6,
    fuel_cost_usd: 32.99,
    avg_speed_kmh: 75.2,
    location: "gulu, ug",
  },
  {
    date: "2025-02-03",
    machine: "production_car",
    operator: "john",
    distance_km: 66.7,
    fuel_consumed_l: 19.5,
    fuel_cost_usd: 107.39,
    avg_speed_kmh: 50.2,
    location: "jinja, ug",
  },
  {
    date: "2025-01-31",
    machine: "camera_truck",
    operator: "alice",
    distance_km: 117.1,
    fuel_consumed_l: 21.3,
    fuel_cost_usd: 88.06,
    avg_speed_kmh: 48.7,
    location: "kampala, ug",
  },
  {
    date: "2025-04-11",
    machine: "production_car",
    operator: "david",
    distance_km: 169.4,
    fuel_consumed_l: 36.5,
    fuel_cost_usd: 119.1,
    avg_speed_kmh: 68.0,
    location: "gulu, ug",
  },
  {
    date: "2025-06-04",
    machine: "camera_truck",
    operator: "mike",
    distance_km: 183.6,
    fuel_consumed_l: 9.9,
    fuel_cost_usd: 92.67,
    avg_speed_kmh: 40.3,
    location: "kampala, ug",
  },
  {
    date: "2025-01-26",
    machine: "camera_truck",
    operator: "alice",
    distance_km: 39.8,
    fuel_consumed_l: 34.6,
    fuel_cost_usd: 62.61,
    avg_speed_kmh: 60.6,
    location: "gulu, ug",
  },
  {
    date: "2025-04-14",
    machine: "production_car",
    operator: "mike",
    distance_km: 226.2,
    fuel_consumed_l: 35.8,
    fuel_cost_usd: 34.52,
    avg_speed_kmh: 51.0,
    location: "jinja, ug",
  },
  {
    date: "2025-08-12",
    machine: "generator",
    operator: "alice",
    distance_km: 128.5,
    fuel_consumed_l: 14.5,
    fuel_cost_usd: 109.95,
    avg_speed_kmh: 25.8,
    location: "entebbe, ug",
  },
  {
    date: "2025-06-20",
    machine: "satellite_uplink_van",
    operator: "john",
    distance_km: 40.8,
    fuel_consumed_l: 20.8,
    fuel_cost_usd: 11.53,
    avg_speed_kmh: 85.7,
    location: "mbarara, ug",
  },
  {
    date: "2025-06-14",
    machine: "satellite_uplink_van",
    operator: "sarah",
    distance_km: 170.8,
    fuel_consumed_l: 22.6,
    fuel_cost_usd: 36.94,
    avg_speed_kmh: 37.4,
    location: "jinja, ug",
  },
  {
    date: "2025-03-07",
    machine: "generator",
    operator: "sarah",
    distance_km: 241.5,
    fuel_consumed_l: 5.1,
    fuel_cost_usd: 37.98,
    avg_speed_kmh: 89.9,
    location: "kampala, ug",
  },
  {
    date: "2025-03-12",
    machine: "satellite_uplink_van",
    operator: "alice",
    distance_km: 191.1,
    fuel_consumed_l: 15.5,
    fuel_cost_usd: 27.27,
    avg_speed_kmh: 40.9,
    location: "entebbe, ug",
  },
  {
    date: "2025-01-20",
    machine: "generator",
    operator: "mike",
    distance_km: 234.0,
    fuel_consumed_l: 33.3,
    fuel_cost_usd: 24.84,
    avg_speed_kmh: 33.7,
    location: "gulu, ug",
  },
  {
    date: "2025-07-31",
    machine: "camera_truck",
    operator: "john",
    distance_km: 57.9,
    fuel_consumed_l: 13.1,
    fuel_cost_usd: 85.06,
    avg_speed_kmh: 38.1,
    location: "gulu, ug",
  },
  {
    date: "2025-02-07",
    machine: "generator",
    operator: "mike",
    distance_km: 110.5,
    fuel_consumed_l: 32.2,
    fuel_cost_usd: 22.58,
    avg_speed_kmh: 38.3,
    location: "mbarara, ug",
  },
  {
    date: "2025-04-24",
    machine: "satellite_uplink_van",
    operator: "mike",
    distance_km: 55.4,
    fuel_consumed_l: 35.0,
    fuel_cost_usd: 43.57,
    avg_speed_kmh: 68.0,
    location: "jinja, ug",
  },
  {
    date: "2025-05-14",
    machine: "camera_truck",
    operator: "mike",
    distance_km: 242.9,
    fuel_consumed_l: 21.4,
    fuel_cost_usd: 57.1,
    avg_speed_kmh: 22.2,
    location: "entebbe, ug",
  },
  {
    date: "2025-07-17",
    machine: "satellite_uplink_van",
    operator: "mike",
    distance_km: 197.4,
    fuel_consumed_l: 18.2,
    fuel_cost_usd: 101.04,
    avg_speed_kmh: 85.2,
    location: "mbarara, ug",
  },
  {
    date: "2025-03-16",
    machine: "satellite_uplink_van",
    operator: "alice",
    distance_km: 142.6,
    fuel_consumed_l: 10.9,
    fuel_cost_usd: 90.77,
    avg_speed_kmh: 76.8,
    location: "mbarara, ug",
  },
  {
    date: "2025-03-12",
    machine: "news_van",
    operator: "alice",
    distance_km: 98.3,
    fuel_consumed_l: 34.6,
    fuel_cost_usd: 113.91,
    avg_speed_kmh: 38.1,
    location: "gulu, ug",
  },
  {
    date: "2025-01-24",
    machine: "production_car",
    operator: "mike",
    distance_km: 75.8,
    fuel_consumed_l: 7.5,
    fuel_cost_usd: 25.18,
    avg_speed_kmh: 73.7,
    location: "jinja, ug",
  },
  {
    date: "2025-07-30",
    machine: "camera_truck",
    operator: "alice",
    distance_km: 91.7,
    fuel_consumed_l: 32.5,
    fuel_cost_usd: 71.65,
    avg_speed_kmh: 54.0,
    location: "mbarara, ug",
  },
  {
    date: "2025-04-12",
    machine: "camera_truck",
    operator: "john",
    distance_km: 70.6,
    fuel_consumed_l: 5.9,
    fuel_cost_usd: 23.32,
    avg_speed_kmh: 38.8,
    location: "gulu, ug",
  },
  {
    date: "2025-07-21",
    machine: "camera_truck",
    operator: "mike",
    distance_km: 149.3,
    fuel_consumed_l: 7.0,
    fuel_cost_usd: 30.21,
    avg_speed_kmh: 44.4,
    location: "entebbe, ug",
  },
  {
    date: "2025-01-01",
    machine: "news_van",
    operator: "john",
    distance_km: 233.1,
    fuel_consumed_l: 19.5,
    fuel_cost_usd: 39.48,
    avg_speed_kmh: 33.9,
    location: "gulu, ug",
  },
  {
    date: "2025-06-02",
    machine: "camera_truck",
    operator: "alice",
    distance_km: 203.3,
    fuel_consumed_l: 32.3,
    fuel_cost_usd: 71.0,
    avg_speed_kmh: 83.3,
    location: "gulu, ug",
  },
  {
    date: "2025-03-01",
    machine: "satellite_uplink_van",
    operator: "david",
    distance_km: 111.9,
    fuel_consumed_l: 39.9,
    fuel_cost_usd: 86.59,
    avg_speed_kmh: 73.6,
    location: "jinja, ug",
  },
  {
    date: "2025-04-25",
    machine: "production_car",
    operator: "alice",
    distance_km: 93.5,
    fuel_consumed_l: 8.0,
    fuel_cost_usd: 95.79,
    avg_speed_kmh: 52.8,
    location: "entebbe, ug",
  },
  {
    date: "2025-04-27",
    machine: "production_car",
    operator: "john",
    distance_km: 58.2,
    fuel_consumed_l: 38.1,
    fuel_cost_usd: 89.96,
    avg_speed_kmh: 67.9,
    location: "kampala, ug",
  },
  {
    date: "2025-03-10",
    machine: "satellite_uplink_van",
    operator: "sarah",
    distance_km: 48.9,
    fuel_consumed_l: 10.8,
    fuel_cost_usd: 104.03,
    avg_speed_kmh: 22.3,
    location: "gulu, ug",
  },
  {
    date: "2025-08-29",
    machine: "production_car",
    operator: "david",
    distance_km: 177.2,
    fuel_consumed_l: 13.9,
    fuel_cost_usd: 18.8,
    avg_speed_kmh: 68.2,
    location: "jinja, ug",
  },
  {
    date: "2025-08-30",
    machine: "production_car",
    operator: "david",
    distance_km: 226.2,
    fuel_consumed_l: 28.1,
    fuel_cost_usd: 25.02,
    avg_speed_kmh: 25.8,
    location: "gulu, ug",
  },
  {
    date: "2025-06-29",
    machine: "news_van",
    operator: "john",
    distance_km: 227.7,
    fuel_consumed_l: 9.3,
    fuel_cost_usd: 89.02,
    avg_speed_kmh: 72.9,
    location: "kampala, ug",
  },
];

export default machines;
